### ISSUE TITLE
Part Builder not showing patterns on server

### ISSUE THREAD

**Issue by groggeri** [SlimeKnights/TinkersConstruct#4870] opened 2022-05-18 10:25 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.18

### Describe your issue

The Parts Builder, when given a blank, unused pattern does not show the option to select a pattern when being used on a server. It does however work on single player. 

I have already tried restarting the server to see if that resolved the issue, it did not. I have tested this on a local host server with just tinkers installed on it and it works normally. Tested again with Tinkers & Optifine installed which is part of the main server and it worked as well.

In total there are 86 mods installed, but it does seem to be working normally 
![image](https://user-images.githubusercontent.com/81985297/169009874-32141b75-edfa-4692-af2c-ba37cfa29a09.png)

### Other mods

Optifine 1.18.2_HD_U_H7

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment] 2022-05-18 10:26
have you tried putting a material in the material slot?

Also, don't use optifine, it breaks things. Test without optifine.

I ask because this mod has been running on ForgeCraft for awhile with no reports of patterns not working, something on your side is conflicting. Hopefully one of the above, if not you will have to try to narrow down mods while on a server to find the cause.

**Comment by groggeri** [comment] 2022-05-18 10:57
> have you tried putting a material in the material slot?
> 
> Also, don't use optifine, it breaks things. Test without optifine.
> 
> I ask because this mod has been running on ForgeCraft for awhile with no reports of patterns not working, something on your side is conflicting. Hopefully one of the above, if not you will have to try to narrow down mods while on a server to find the cause.

I have tried putting materials in the material slot and it still does not work. When testing in a single player world, the patterns for the parts still show up without materials. 

I have also tested it without optifine, as stated in my original post and it is working normally both with and without optifine. 

I fear I may have to spend the time and go mod by mod to figure out what is causing the issue.

**Comment by KnightMiner** [comment] 2022-05-18 11:12
As a tip when reporting issues: if it happens without optifine, report the issue without optifine. I don't care that you normally use optifine, I care if this bug only happens with optifine.

And yeah, might not be a better way to find the bug, its not happening on our server. You possibly have broken recipes, check if they show in JEI. If they do, no reason the buttons shouldn't show.

**Comment by groggeri** [comment] 2022-06-11 11:40
It took me a while with working full time and generally just having a life but I did manage to get through adding my mods 1 by 1 to determine which one created this issue with the parts builder. 

The result of which is that none of them seem to have created the issue. The issue only reared its head when ALL of the mods were added at once. I'm fully clueless as to why or what would cause this. 

The other tool benches are working, they just don't show the finished recipe in the box. And as for the broken recipes, I'm unsure of what you mean by this. I've attached an image of looking at the recipe for "Wooden Pick Head" 
![image](https://user-images.githubusercontent.com/81985297/173186347-775dce8b-054f-4863-af33-e67439b581f9.png)

**Comment by KnightMiner** [comment] 2022-06-13 02:17
That recipe in the screenshot is clearly broken, as the pattern it is showing is blank. There is nothing in the code which would cause it to show as blank, and it works fine on several servers I have played on. Unless you can give me a better answer than "it only happens when I add all the mods" I cannot help, I need a minimal mod list to even test in a dev environment.

**Comment by Cobyt3** [comment] 2022-06-26 13:37
Hi, so I am having the same Issue. In normal Singleplayer, the recipies show and work just fine in the part builder. But as soon as I join a Server (or a LAN world), the part builder is empty, just like in the first Screenshot from @groggeri 
![image](https://user-images.githubusercontent.com/108224706/175816744-4b8442f3-7e02-4946-9d3c-d978c35a2636.png)

@KnightMiner wanted a Modlist, and since I have the same Problem, maybe my [Modlist ](https://pastebin.com/8aME37Us)can help. 

Thank you for your Time!

**Comment by KnightMiner** [comment] 2022-06-26 17:48
Can you narrow down the mod list? I cannot test a list of 100+ mods in dev. I can test a list of 5. Ultimately as the ones experiencing the bug I need you to find the minimal list.

**Comment by Cobyt3** [comment] 2022-06-27 06:55
Hi, I tried to narrow down the mods like you said, and I am left with these 5 Mods:

- Ore Excavation
- Oreberries Replanted
- Solar Flux Reborn
- Simply Light
- Sophisticated Backpacks

My guess is the Oreberries Replanted Mod since they had an Issue with JEI as seen in [this GitHub Issue](https://github.com/Mrbysco/OreBerries-Replanted/issues/3), which also applies to my game and matches the Mod version I have installed. And because of that, I think the Issue is (or was) on their side, not on yours.

When I'm back from work I'm going to test if thats true and give another reply here, so this Issue can get closed :D

**Comment by Cobyt3** [comment] 2022-06-27 13:18
So I tried loading up the game without said Oreberries Replanted Mod, and now it works perfectly fine. 

Either removing or updating the Oreberries Mod should fix the Problem. Thanks for your Help though!

**Comment by groggeri** [comment] 2022-06-28 08:09
> So I tried loading up the game without said Oreberries Replanted Mod, and now it works perfectly fine.
> 
> Either removing or updating the Oreberries Mod should fix the Problem. Thanks for your Help though!

The issue that I have here, even with the mods you've given, is that none of them are in the mod pack that I'm using. 

I've got a couple of days off this weekend so I'm going to try and see if I can sort through the mods and try and break it down to a list of 5. 

I've also had a brief look through your whole modlist and we do have some of the same mods. So when I get opportunity I'm gonna compare and get a full list of what mods we both have and maybe see if any of them cause the issue.

**Comment by groggeri** [comment] 2022-07-11 21:15
Finally found myself an opportunity to go through both mod lists and compare. 

AppleSkin	
Chimes
Clumps
Falling Leaves
Macaw's Doors
Macaw's Fences and Walls
Quark
Tinker's Construct
Xero's Minimap
Xero's World Map


and the dependencies 
Architectury API
AutoRegLib
Cloth Config v4 API
Configured
Curios API
Mantle

**Comment by KnightMiner** [comment] 2022-09-04 05:26
That is still too many mods, and I highly doubt most of those are relevant. e.g. why would a door mod affect this?

**Comment by KnightMiner** [comment] 2023-01-17 02:08
I am going to close this as I have never seen this issue myself on multiple test servers, and have not received other reports of this issue.

Give me a **minimal** mod list to reproduce this issue if you want me to look into it further. By minimal, I mean less than 10. I highly doubt it takes 20 mods to reproduce your issue.

**Closed as completed by KnightMiner** 2023-01-17 02:08 UTC
Labels: Bug, Needs Update, Not enough information, 1.18
