### ISSUE TITLE
java.lang.IllegalStateException: vanilla model 'net.minecraft.client.renderer.block.model.ModelBlock@3d85a101' can't have non-vanilla parent

### ISSUE THREAD

**Issue by wormzjl** [SlimeKnights/TinkersConstruct#3576] opened 2018-07-14 07:45 UTC
Sometimes happens on player login, can be resolved by removing all TiC blocks in the area
https://gist.github.com/wormzjl/ca7906c8324b2b6fd882e47a1c36cf7b

**Comment by bonii-xx** [comment] 2018-07-14 17:01
You can also disable the table rendering in the config. You have an item with a broken model in the table. Either that or projectred/codechickenlib screw with the models. Do you know which item it was?

**Comment by wormzjl** [comment] 2018-07-14 17:05
Unfortunately no, and strangely it only crashes players that are logged in close to the object, not crashing other approaching players.
I'll keep an eye on it next time it happens

**Comment by bonii-xx** [comment] 2018-07-15 11:35
Please do. I suspect it might have to do with clientside mods though (optifine, etc)

**Comment by KnightMiner** [comment] 2018-07-20 20:53
Does it happen on a normal forge server?

**Comment by bonii-xx** [comment] 2018-07-22 07:07
Does it happen without project red, who seem to modify the renedring?

**Comment by wormzjl** [comment] 2018-07-25 21:06
Yes I had such report once when I removed sponge.
For project red, I fear that I'm unable to do the test since it's a live server.

**Comment by Peach774** [comment] 2018-07-27 03:15
Got the same issue when moving from the nether to the overworld. No clue whats causing this since I do not have ProjectRed

**Comment by bakkoting** [comment] 2018-08-02 17:17
I'm seeing the same thing. Here's a [crash log](https://gist.github.com/bakkoting/9f49fc04605e6c9dbcf1513171d41e4d).

This is a local copy of Modern Skyblock 3, running through MultiMC on Mac OS. It does not include Project Red, so that's not the problem. It seems to happen very consistently when logging in to my instance.

Since this is a local copy I'm happy to mess around with settings if there's things you'd like me to try. Or just send you a copy of my instance data, if that helps.

Setting `B:renderInventoryInWorld=false` and/or `B:renderInventoryNullLayer=false` does not fix it. Also, I'm very early game; I think the only things I've had in the table at any point were cobble, wood, and tool parts. Likely had cobble in there last, though since I can't log in it's hard to check.

**Comment by bakkoting** [comment] 2018-08-07 03:38
@KnightMiner Removing `moarTinkers` seems to make it go away. (Updating that mod from 0.5.4 to 0.6.0 did not.)

**Comment by Peach774** [comment] 2018-08-07 04:49
Maybe it’s caused by addons in general? I don’t have moartinkers, but I have constructs armory. Maybe it has to do with the way the implement their casting molds or something with the casting mold code?

**Comment by KnightMiner** [comment] 2018-08-18 03:01
Doubt it, I have seen this crash in other mods that use the Forge retexture method.

**Comment by Mugiwaxar** [comment] 2018-08-29 22:01
Same issues for me here
Happen since I added the mod Wireless Redstone CBE
The game crash when I'm near the table

**Comment by KnightMiner** [comment] 2018-08-29 22:29
Does it happen without FoamFix? I'm pretty sure I've narrowed this down to that mod

**Comment by pPkMnh4to8994h** [comment] 2018-10-16 15:59
same issue.
[https://gist.github.com/pPkMnh4to8994h/3133bcf0c66a5fc58b2dfd754d166055](url)

**Comment by KnightMiner** [comment] 2018-10-16 17:33
Great, can you try what I said above and test without FoamFix?

**Comment by pPkMnh4to8994h** [comment] 2018-10-17 14:16
ye, without foamfix it seems to be working, but fps drops harshly, i barely can login in the world :(

**Comment by KnightMiner** [comment] 2018-10-17 17:36
Thanks for the confirmation, this tells me I know the cause. Unfortunately it's not an easy fix on our side. It's an easy fix on Forges side but I still need to work on justifying it.

**Comment by KnightMiner** [comment] 2018-10-19 01:00
Alright, test this again with Forge build 2772 or later and FoamFix if you'd like

**Comment by pPkMnh4to8994h** [comment] 2018-10-19 13:13
can't really tell if it's fixed since the bug is kinda "floating". if i will play a few days without this crash, maybe we can consider it as "fixed"...

**Comment by KnightMiner** [comment] 2019-01-02 02:03
Closing this as fixed, as I know the specific cause I traced was related to that PR I linked

**Closed by KnightMiner** 2019-01-02 02:03 UTC
