### ISSUE TITLE
1.10.2 Crashing upon trying to break casting basin / table

### ISSUE THREAD

**Issue by BlueAvian** [SlimeKnights/TinkersConstruct#2308] opened 2016-08-09 22:13 UTC
While updating to the new alpha, I was confused why I ended up crashing in my world. Figuring it was probably due to any number of variables, I tested in a few test worlds stripping down mods to Forge + TiC & Mantle, and only happens with the casting basin / table and no other blocks.

http://pastebin.com/kByB2uAj

**Comment by ArukaAlter** [comment] 2016-08-09 22:22
Update Forge.

**Comment by KnightMiner** [comment] 2016-08-09 22:22
Duplicate of #2279. Forge's fault. Update Forge to build 2046 or later to fix it.

**Closed** 2016-08-10 06:35 UTC
Labels: duplicate
