### ISSUE TITLE
Tinkers construct keeps crashing on minecraft launcher

### ISSUE THREAD

**Issue by Flansmodandtinkersdontwork** [SlimeKnights/TinkersConstruct#4542] opened 2021-06-19 21:04 UTC
Whenever i press Play on the minecraft launcher and the game launches, the game crashes

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo
Exit Code: -1

https://pastebin.com/LSuKUAhD

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by ShinyPorygon** [comment] 2021-06-19 21:09
Duplicate of #4441 not tinkers fault. Try an older version of Lua craft.

**Closed as completed by ShinyPorygon** 2021-06-19 21:09 UTC
Labels: Duplicate, 1.12
