### ISSUE TITLE
Crash when placing tool in tool forge.

### ISSUE THREAD

**Issue by Moobien** [SlimeKnights/TinkersConstruct#3373] opened 2018-02-10 01:15 UTC
Hey guys, using TC version TConstruct-1.12-2.7.4.34 and Mantle version Mantle-1.12-1.3.1.21

Today my game crashes whenever I place a tool into the tool forge.  here are some logs for you to see what could be causing it.

https://gist.github.com/Moobien/03241ef0bebce69893c12c7820c211e8
https://gist.github.com/Moobien/4d95127d34ff2b8c081455729ffa42ad

**Comment by Moobien** [comment] 2018-02-10 01:16
EDIT: no crash when adding parts to it when trying to MAKE a new tool, but crash when adding existing tool for repairs/upgrades.

**Comment by KnightMiner** [comment] 2018-02-10 01:17
Duplicate of #3372.

**Closed by KnightMiner** 2018-02-10 01:17 UTC
