### ISSUE TITLE
Errors in minecraft 1.12.2 version

### ISSUE THREAD

**Issue by pjindras** [SlimeKnights/TinkersConstruct#3850] opened 2019-05-09 20:37 UTC
Hello, i have these errors in my log, how can i fix it or is it something bad?

```
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model conarm:parts/armor_plate.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model conarm:parts/armor_trim.tmat#inventory
[21:55:18] [Client thread/ERROR] [conarm]: Could not load multimodel conarm:armor/boots.conarm#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model conarm:parts/boots_core.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model conarm:parts/chest_core.tmat#inventory
[21:55:18] [Client thread/ERROR] [conarm]: Could not load multimodel conarm:armor/chestplate.conarm#inventory
[21:55:18] [Client thread/ERROR] [conarm]: Could not load multimodel conarm:armor/helmet.conarm#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model conarm:parts/helmet_core.tmat#inventory
[21:55:18] [Client thread/ERROR] [conarm]: Could not load multimodel conarm:armor/leggings.conarm#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model conarm:parts/leggings_core.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model conarm:parts/polishing_kit.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model plustic:parts/battery_cell.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel plustic:tools/katana.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel plustic:tools/laser_gun.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model plustic:parts/laser_medium.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model plustic:parts/pipe_piece.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/arrow.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/arrow_head.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/arrow_shaft.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/axe_head.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/battlesign.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/binding.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/bolt.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:parts/bolt_core.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/bow_limb.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/bow_string.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/broad_axe_head.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/broadsword.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/cleaver.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/cross_guard.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/crossbow.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/excavator.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/excavator_head.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/fletching.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/frypan.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/hammer.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/hammer_head.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/hand_guard.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/hatchet.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/kama.tcon#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/kama_head.tmat#inventory
[21:55:18] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/knife_blade.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/large_plate.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/large_sword_blade.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/longbow.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/longsword.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/lumberaxe.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/mattock.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:moms_spaghetti.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/pan_head.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/pick_head.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/pickaxe.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/rapier.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/scythe.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/scythe_head.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/shard.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/sharpening_kit.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/shortbow.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/shovel.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/shovel_head.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/shuriken.tcon#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/sign_head.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/sword_blade.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/tool_rod.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/tough_binding.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/tough_tool_rod.tmat#inventory
[21:55:19] [Client thread/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/wide_guard.tmat#inventory
```

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2 - 14.23.5.2837
* Mantle: Mantle-1.12-1.3.3.49.jar
* Tinkers Construct: TConstruct-1.12.2-2.12.0.135.jar

Thanks :))

**Comment by Reinay97** [comment] 2019-05-28 08:35
do you solved this issue? i have the same problem :(

**Comment by Carnaxus** [comment] 2019-06-02 09:13
Does the mod itself still work normally?

**Comment by Khioni** [comment] 2019-07-07 17:42
Seems to work just fine for me, nothing odd, **but I get that same kind of spam.**

**Comment by KnightMiner** [comment] 2019-07-07 18:15
Yeah, this does not break anything, Forge changed something about model loading and now the log errors in a spot where the error was previously ignored. Not an issue, but have not had time to look into how to remove those errors.

This is a duplicate of #3651, surprised it went this long before I noticed this issue.

**Closed by KnightMiner** 2019-07-07 18:15 UTC

**Comment by ChromaPIE** [comment] 2023-11-20 03:56
No it "breaks" things.
It freezes the game when trying to click open stencil tables, tool forges and tool stations https://mclo.gs/7JDV4pZ
Game recovers from the freeze when the errors stops, so apparently it's loading those models, causing the freeze.

But weird enough that i dont think its a thing for E2E-Extended modpack, the freeze only happens to my own sink pack to mess around in.

If anyone's still tracking this issue reply and i'll send my modlist or maybe more info
