### ISSUE TITLE
[1.12.2] Bow arrow animation is not correct

### ISSUE THREAD

**Issue by TheSnowyChickens** [SlimeKnights/TinkersConstruct#3193] opened 2017-10-10 19:34 UTC
Hello,
in the following picture you can see an skeleton and the arrow.
My shot was in the direction to the skeleton, but the arrow don't go the correct way. (Yes, I killed the skeleton with this 1 arrow)
I use a short bow (Steel bowlimb 2x / string bow string)

![2017-10-10_21 19 16](https://user-images.githubusercontent.com/29357962/31406483-c9a09274-ae01-11e7-9921-b8c7217d33be.png)

MC : 1.12.2
Forge 2512
TIC : 2.7.3.30
Mantle : 1.3.1.21
Optifine : C7 (pre.) (the bug happends with and without Optifine)
And many more, but no animation mods or kind of this.

**Comment by bonii-xx** [comment] 2017-10-11 06:39
Try reproducing without any other mods except TiC and Mantle (and JEI). This usually happens when the data is incorrectly transferred from the server to the client (even in singleplayer). There was a vanilla bug that caused this, but TiC doesn't use the vanilla code because of that, so I doubt it's due to the 1.12.2 update.

**Comment by KnightMiner** [comment] 2019-01-02 02:37
Closing for lack of response

**Closed by KnightMiner** 2019-01-02 02:37 UTC
Labels: Needs Confirmation
