### ISSUE TITLE
1.12 not working properly 

### ISSUE THREAD

**Issue by chickenbouillon** [SlimeKnights/TinkersConstruct#3069] opened 2017-07-31 21:03 UTC
I cannot access any templates through the stencil table. Missing book two and three and I cannot craft them either. Nor did I receive any guides when making the tool station, etc. The first guide book also has text coming off its pages that I cannot read. Please help

**Comment by KnightMiner** [comment] 2017-07-31 21:18
Duplicate of #2987 and #3008, a.k.a remove Optifine as it breaks our text, and it used to break our textures until a recent Optifine build.

The other books have been removed since the beginning of 1.8.

**Closed by KnightMiner** 2017-07-31 21:18 UTC
Labels: duplicate, invalid

**Comment by chickenbouillon** [comment] 2017-08-01 18:27
Thank you!
