### ISSUE TITLE
[1.16.5]Crash when using foundry controller

### ISSUE THREAD

**Issue by TruxRoyal** [SlimeKnights/TinkersConstruct#4527] opened 2021-06-11 09:12 UTC
**Issue description:**

When using the Foundry Controller, a crash occurs that ruins your world.
I have been experimenting and it is with any object that can be melted, from ores, magma cream, diamond, etc. In addition to trying in different worlds.

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/VuDmG8bJ

**Versions:**

Minecraft: 1.16.5
Forge: 36.10
Mantle: 1.6.103
Tinkers Construct: 3.0.4.171

**Can it be reproduced with just Tinkers Construct? If not, list the other mods required to reproduce the issue.
list of the mod :**

- Forge-1.16.5-36.1.0-client.jar                     
- TConstruct-1.16.5-3.0.4.171.jar                  
- forge-1.16.5-36.1.0-universal.jar                
- Mantle-1.16.5-1.6.103.jar

**Comment by TheLynk** [comment] 2021-06-11 11:17
I tested the same mods config and even put your resource pack and your games language and also your java settings my games do not crash

**Comment by KnightMiner** [comment] 2021-06-11 11:18
Duplicate of #4497, your foundry structure is invalid, but there was a bug that still allowed it to build. Likely you have the controller on the bottom layer and the second later is incomplete.

I honestly forgot that the fix has not been released yet, but you should be able to recover your world in the next alpha

**Closed as completed by KnightMiner** 2021-06-11 11:18 UTC
Labels: Bug, Duplicate, 1.16
