### ISSUE TITLE
Crash after putting the Traveler Armor on the armor stand

### ISSUE THREAD

**Issue by Ray-K-Newman** [SlimeKnights/TinkersConstruct#4755] opened 2022-02-15 11:40 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.76

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.0.34

### Describe your issue

After placing a Traveler armor on the armor stand Minecraft crashed. Since then the player can no longer log into the server.
The command to replace the armor stand with a stone block did not work.
What can I do to fix the error.
[crash-2022-02-15_12.19.28-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8068654/crash-2022-02-15_12.19.28-client.txt)

### Reproduced with only Tinkers' Construct?

Yes

### Other mods required

No

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [x] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [x] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-15 11:43
Well, considering that you have optifine (which you confirmed you didn't in the check boxes) but also confirmed that you didn't read the checkboxes. I'd advise you to read through them again and try without optifine.

Oh and update tinkers because you're ever so slightly behind but that won't fix this issue.

**Comment by KnightMiner** [comment] 2022-02-15 14:13
Duplicate of #4734, making the reporter a liar. All I ask is a little honestly when you report bugs, is that too hard to do? Tee one thing you were honest about is that you are using optifine. Optifine is not supported as its a garbage mod.

If you don't understand why this being a duplicate makes you a liar @Ray-K-Newman, try actually reading the checkboxes you checked.

**Closed as completed by KnightMiner** 2022-02-15 14:13 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18

**Comment by Ray-K-Newman** [comment] 2022-02-15 19:55
> Duplicate of #4734, making the reporter a liar. All I ask is a little honestly when you report bugs, is that too hard to do? Tee one thing you were honest about is that you are using optifine. Optifine is not supported as its a garbage mod.
> 
> If you don't understand why this being a duplicate makes you a liar @Ray-K-Newman, try actually reading the checkboxes you checked.

Sorry, but the first checkbox is for me (a not good english speaker) confusing. For me the checkbox means that I should check if I use optifine and "yes" i use it. I guess I misunderstood that, sorry for that, but that doesn't make me a liar.
@ShinyPorygon thanks for your help.

**Comment by KnightMiner** [comment] 2022-02-15 20:09
I am not talking about the first checkbox, you correctly checked that. I am talking about the other 3. If you really searched existing issues and pinned issues, you would have seen this is a duplicate of a pinned issue. If you don't understand what the checkbox means, you leave it unchecked because you did not do it.

**Comment by Ray-K-Newman** [comment] 2022-02-16 21:47
One last question: Where can I find a list of compatible shaders or are there none?

**Comment by KnightMiner** [comment] 2022-02-17 04:17
Vanilla shaders. aka any shader that is added through a resource pack, and not via optifine. No idea where you will find such a list, but I am sure someone has made it. I honestly don't care much for shaders so I have never invested time in finding which ones work.
