### ISSUE TITLE
switching active tool while drawing shortbow results in super fast running

### ISSUE THREAD

**Issue by esotericist** [SlimeKnights/TinkersConstruct#5070] opened 2023-01-25 03:17 UTC
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.18.2-1.9.43

### Tinkers' Construct Version

1.18.2-3.6.2.92

### Describe your issue

if you switch away from the shortbow while drawing it (whether you use numeric row, or mousewheel) the movement speed offset from the fast_use_item modifier stays active until you draw the shortbow again and release it without changing tools.

[video exhibiting behavior](https://youtu.be/-RNyE82QjlU).

### Other mods

reproduced with just forge, mantle, tconstruct, json things (1.18.2-9.7.0.209) and tinkers things (1.18.2-1.0.2).

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment] 2023-01-25 03:31
For the record, short bows are from an addon, not the base mod. In this case though, this issue is caused by a modifier added by Tinkers' Construct so the issue belongs here.

**Comment by esotericist** [comment] 2023-01-25 03:41
yeah, i had to search a bit to be sure of that before i landed on posting it here.

**Comment by KnightMiner** [comment] 2023-01-30 02:01
Pushed a fix, though unfortunately the way the fix had to be coded means an update is required in Tinkers' Things as well. Will wait to close until the fix is on both sides

**Comment by KnightMiner** [comment] 2023-02-14 17:53
Fixed in 3.6.3.111.

**Closed as completed by KnightMiner** 2023-02-14 17:53 UTC
Labels: Bug, Resolved, Confirmed, 1.18
