### ISSUE TITLE
Unable to pour glass

### ISSUE THREAD

**Issue by vedrit** [SlimeKnights/TinkersConstruct#3401] opened 2018-02-28 04:28 UTC
Using v1.12.2-2.9.0.55 in the Direwolf20 pack v1.18
When you add glass to the smelter and it melts down, it will not pour into either the casting basin or casting table.
When you right-click on the faucet, it will pour a little out. If you rick-click repeatedly to fill either the basin or table, there will be no recipe listed and no progress. The controller shows fluid has been removed, but if you switch to a different fluid, the molten glass will reset.

**Comment by TheQuadShot** [comment] 2018-03-13 01:56
I just DL'd Direwolf's pack and it works fine I was able to pour clear glass(casting bin) and clear pane(casting table).

MC 1.8.0
Forge 13.23.1.2801
TConstruct-1.12.2-2.9.0.55
Mantle-1.12-1.3.1.21

**Comment by davidsielert** [comment] 2018-03-13 04:58
Definitely not working here:
TConstruct-1.12.2-2.9.1.65
Forge -14.23.2.2618

**Comment by KnightMiner** [comment] 2018-03-13 05:11
Can you try creating a new world and see if the issue persists? I'm pretty sure I have the cause of this tracked down, but it's unfortunately not an easy fix.

**Comment by triasinformatica-gabe** [comment] 2018-07-29 12:19
Just came across the same issue on our new server after upgrading several mods. The exact issue as described by @vedrit.

Running with:
- Forge 14.23.4.2739
- TConstruct 1.12.2-2.10.1.87
- Mantle 1.3.2.24

A few of my findings:
1. I created a single player world to make a minimum example for testing and/or making a screen capture of the issue. In the SP world I did not have the issue present itself.
2. I logged back into our MP server; issue still present. Then I restarted the MP server; issue resolved and I was able to create the Clear Glass recipe as per normal.

I'm not sure what caused the issue in the first place. The difference between the SP smeltery and the MP one is the size. My MP smeltery is 5x5x10 on the inside, while the SP test smeltery was 2x2x2 for testing purposes. Not sure if that could be of any influence.

Something I've been doing quite a few times whilst constructing the smeltery is breaking part of it down again to get some cobble that fell down the shaft, breaking the smeltery and then fixing it up again. To check if that might have been the cause I've broken the smeltery again, then I smelted down some sand and poured it into a tank. Works just fine; so that's not it.

Hope this could be of some help.

-- Frikkle

**Comment by bonii-xx** [comment] 2018-08-04 11:55
It's probably something that messes with the recipes server side, and hence also out of our hands. Closing this since it's pretty old and not base-tic relevant.

Also, keep your eyes open, there was some mod that added an alloy recipe that killed glass in smelteries.

**Closed by bonii-xx** 2018-08-04 11:55 UTC
Labels: Not enough information
