### ISSUE TITLE
Tool Forge Dupe Bug

### ISSUE THREAD

**Issue by focamacho** [SlimeKnights/TinkersConstruct#3997] opened 2019-12-16 21:52 UTC
**Issue description:**
1 - Two players open a Tool Forge
2 - Put a Item in
3 - A player starts renaming the item, and the other collects the result
4 - Infinite items

Video: https://www.youtube.com/watch?v=8zfr79fSanQ
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.157

**Can it be reproduced with *just* Tinkers Construct?** Yes

**Comment by SweetSugarSugar** [comment] 2019-12-17 18:53
Is it a normal vanilla Forge server?

**Comment by focamacho** [comment] 2019-12-17 18:59
In the video is a sponge server
But I tested the bug with only tinkers and mantle installed on a LAN server, and the bug happened too

**Comment by PiggiesGoSqueal** [comment] 2020-05-11 18:40
I checked the updates of Tinkers' Construct for the versions after 2.12.0.157 of the mod. No mentions of fixing this. I'm stunned it hasn't been fixed considering how crucial duplication bugs are for allowing people to use the mod on their servers.

**Comment by KnightMiner** [comment] 2020-05-11 23:03
Duplication bugs like this are incredibly convoluted in the cause and incredible hard to debug. Honestly, with how many dupe bugs vanilla has, a single dupe bug in a mod is not as huge of a problem as you think. Its really a problem on the server if you cannot trust your players not to abuse dupe bugs. Not saying they are not important to fix, but its not as simple as flipping a switch to stop it.

**Comment by focamacho** [comment] 2020-05-11 23:28
> I checked the updates of Tinkers' Construct for the versions after 2.12.0.157 of the mod. No mentions of fixing this. I'm stunned it hasn't been fixed considering how crucial duplication bugs are for allowing people to use the mod on their servers.

@pinkpig3777
I did an easy fix myself to prevent two players from opening the same tool forge. Feel free to use it.
https://www.curseforge.com/minecraft/mc-mods/dupefix-project

**Comment by bonii-xx** [comment] 2020-05-12 07:45
But we want two players to be able to use the same tool forge. It'd be really weird if that wasn't possible.

**Comment by focamacho** [comment] 2020-05-12 15:31
It is just a fix for public servers, not a real good fix for the mod.

**Comment by KnightMiner** [comment] 2021-06-15 17:17
This should be fixed on 1.16. I am not comfortable trying to fix this on 1.12 as we have basically dropped support for it, so going to close this issue.

**Closed as completed by KnightMiner** 2021-06-15 17:17 UTC
Labels: Bug, Won't Fix, 1.12, Update
