### ISSUE TITLE
White Tools (Incompatibility with TexFix and FoamFix)

### ISSUE THREAD

**Issue by Tschipp** [SlimeKnights/TinkersConstruct#4127] opened 2020-06-06 15:09 UTC
**Issue description:**
Tools from regular Tinker's Construct are white

**Versions:** 
* Minecraft: 1.12.2
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2838

**Can it be reproduced with *just* Tinkers Construct? Remove any mods besides Mantle and Tinkers Construct to test.**
Both FoamFix and TexFix are required to reproduce the bug.
My versions are:
foamfix-0.10.10-1.12.2
TexFix V-1.12-4.0

![image](https://user-images.githubusercontent.com/11649893/83944450-ea731400-a803-11ea-85a2-4a5eb5652917.png)

Please tell me if you need further information. This could very well also be a bug on their end.

**Comment by KnightMiner** [comment] 2020-06-06 16:11
Duplicate of #3696. It's the fault of FoamFox and TexFix, they both know about the issue and for some reason refuse to cooperate and fix it. The TexFix mod description has more information.

**Closed as completed by KnightMiner** 2020-06-06 16:11 UTC
Labels: Duplicate, Performance Enhancers/Optifine

**Comment by Tschipp** [comment] 2020-06-06 18:07
Sorry, didn't see it was a dupe.
