### ISSUE TITLE
Description: Exception in server tick loop

### ISSUE THREAD

**Issue by bokuwaTel** [SlimeKnights/TinkersConstruct#3959] opened 2019-10-06 00:01 UTC
**Issue description:**
Within 2-5 minutes of creating a new world, after walking around a bit, the game CTDs with a server tick loop exception citing "No OpenGL context found in current thread" as the error.

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/6SnrBzYt

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Unsure, though it is worth mentioning here that I'm running TiC as part of a modpack of my own design. I haven't updated the mod list on Technic in a while, but here's the pack's page:
https://www.technicpack.net/modpack/ilionikoi-adventures.1300749

The mods are also listed in the crash report I linked in this post via pastebin.

**Comment by bokuwaTel** [comment] 2019-10-06 00:38
Issue resolved, I found out I've been running an outdated version of TiC for the past 6+ months. Tested with newest version, tested it out, no crash after exploring for more than 12 minutes.

**Comment by bokuwaTel** [comment] 2019-10-08 07:49
Issue re-opened due to reproduction of crash on latest version of TiC.

**Comment by KnightMiner** [comment] 2019-10-08 12:08
What makes you think this is a Tinkers Construct issue? Nothing in the crash points to Tinkers.

**Comment by bokuwaTel** [comment] 2019-10-08 13:58
Nothing except the big block that says it was an issue with TiC. The one with tildes and ERROR in it. The one that explicitly mentions it as an OpenGL issue with TiC.

**Comment by bokuwaTel** [comment] 2019-10-08 17:57
I'm going to mention that through troubleshooting I've figured out this is most likely a compatibility issue between OptiFine and TiC, the OpenGL rendering causes a server-side crash the first time the internal server on a world attempts to load TiC inventory rendering for Minecraft chests, which then onward render as a textureless block on TiC inventories. Nowhere else. It's either a compat issue with OF or with Quark in that regard, and yes, it is a TiC issue. The crash report quite literally mentions OpenGL rendering with TiC as the cause of the error, I can even provide a copy/paste of the exact spot where it mentions it. It's an indented block of text preceded by ~Error. Disabling inventory renders for TiC fixes the issue, but it still should be looked into. Thanks.

**Comment by KnightMiner** [comment] 2019-10-12 01:53
@bokuwaTel: you are very much misreading the crash report, I assume your comment is referencing the following:

```
 GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
    Pulsar/tconstruct loaded Pulses:
```

That information is debug information which is returned in every crash. Since this is a serverside crash, you of course have no OpenGL. Since this is a crash in a pack with Tinkers Construct, it lists what Tinkers Construct pulses are loaded. There is no statement there that the two are related nor that removing TiC fixes it. In fact, by your logic this is just as soon a AE2 issue as that shows up first after the GL info error.

----

For now, I am going to close this issue. If you can reproduce this issue in a pack with just Tinkers Construct and the minimal required mods (which is not 100 mods), then I can look into this, but the current crash report has nothing linking to our code thus nothing I can fix.

**Closed by KnightMiner** 2019-10-12 01:53 UTC

**Comment by bokuwaTel** [comment] 2019-10-15 01:33
Well now that you're all done just degrading people, invalidating their thoughts and feelings, and refusing to actually help anyone with issues, I'd like to mention I actually found the cause of the issue. I had to dig through the actual modpack logs to find it, since the crash report legitimately offers nothing as for finding the cause.
No, it wasn't a TiC issue, but that's still not a reason to be a belittling prick and just make fun of people. This was a frustrating thing I'd spent a month trying to figure out, I'd only put out two issue reports on mods that were *seemingly* related to the issue and never once did I claim to have comprehensive knowledge of the Java language. At no point did anyone in response to this thread have any right to be as insultingly rude as you all were. At no point in your life did you gain that right, nor will you ever have it. Try actually trying to troubleshoot an issue instead of just belittling people. I'm sorry your egos are too large for life, but that's not my problem. The only shitfest is in the fact all of you behaved in a very insolent manner. I don't know what it is with anyone who studies a language for two years, but it seems to me like you come out of it being just plain assholes.

**Comment by bokuwaTel** [comment] 2019-10-15 01:38
This thread was started by someone who clearly needed help with an issue, and rather than actually attempting to help it seems like for the most part most of you have just been acting like twelve year olds rather than adults. I was trying to make sense of something because all I got from people who understand this language better than I do personally were insults and condescending demeanor. It's uncalled for. Just because I was wrong, and I was and am very apologetic as well as I am willing to take responsibility for that, doesn't mean nobody should try to help me at least understand it until a week+ later. You don't know what's going on in my life and it's pretty messed up to just immediately jump in with some condescending tone like you're high and fucking mighty. Get over yourselves and seek mental help. That is all.

**Comment by bokuwaTel** [comment] 2019-10-15 01:41
And if someone decides to be a dumbass and reply saying I was wasting time, beating around the bush and insulting people rather than offering help is the only waste of time here. Don't @ me with your narcissistic bullshit. 😊

**Comment by Planet-Earth** [comment] 2021-01-01 03:39
@bokuwaTel 

You said you figured it out, but you didn't post what the issue was or how you resolved it.

I have been having a similar issue, and have also been having trouble resolving it.

Could you share with me how you resolved your issue, please?
