### ISSUE TITLE
Server java.lang.NullPointerException

### ISSUE THREAD

**Issue by Vexxen1** [SlimeKnights/TinkersConstruct#4277] opened 2021-03-22 02:52 UTC
**Issue description:**
I have been making a server, and i cant figure out how too fix this problom.
**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/tvtV1s1B
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Im not sure, but these are the mods i used. 
AdFinders-1.12.2-2.3.17.0-build.0559
AdLods-1.12.2-1.0.8.0-build.0504
AdPother-1.12.2-1.2.13.0-build.0563
ae2stuff-0.7.0.4-mc1.12.2
animania-1.12.2-base-2.0.3.28
animania-1.12.2-extra-1.0.2.28
animania-1.12.2-farm-1.0.2.28
antiqueatlas-1.12.2-4.6.3
AppleSkin-mc1.12-1.0.14
appliedenergistics2-rv6-stable-7
armoryexpansion-1.4.2
astralsorcery-1.12.2-1.10.27
AutoRegLib-1.3-32
Baubles-1.12-1.5.2
bdlib-1.14.3.12-mc1.12.2
bettercaves-1.12.2-2.0.4
BiblioCraft[v2.4.5][MC1.12.2]
biolib-1.1.2
BiomesOPlenty-1.12.2-7.0.1.2441-universal
BloodMagic-1.12.2-2.4.3-105
bloodtinker-1.0.5
CB-DTCompat-1.4.0-MC1.12.2
Chameleon-1.12-4.1.3
chiselsandbits-14.33
ClimaticBiomes-2.16.3-MC1.12.2
Clumps-3.1.2
comforts-1.12.2-1.4.1.3
conarm-1.12.2-1.2.5.10
Controlling-3.0.10
CraftableHorseArmour-1.3.0-1.12
CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
dcintegration-1.1.16-1.12
DummyCoreUnofficial-2.4.112.5
DynamicTrees-1.12.2-0.9.22
DynamicTreesBOP-1.12.2-1.4.4
DynamicTreesIC2-1.12.2-1.2.1
DynamicTreesPHC-1.12.2-2.0.5
DynamicTreesQuark-1.12.2-1.0.6
DynamicTreesTC-1.12.2-1.4.2
DynamicTreesThaumcraftAddons-1.12.2-1.1.3
DynamicTreesTinkersConstruct-1.12.2-1.2.6
engineers_doors-1.12.2-0.9.1
FastFurnace-1.12.2-1.3.1
FastWorkbench-1.12.2-1.7.3
ForgeEndertech-1.12.2-4.5.5.0-build.0561
FTBBackups-1.1.0.1
Guide-API-1.12-2.1.8-63
guns-0.15.3-1.12.2
iceandfire-1.9.1-1.12.2
ImmersiveEngineering-0.12-98
immersivepetroleum-1.12.2-1.1.9
ImprovedBackpacks-1.12.2-1.5.0.0
industrialcraft-2-2.8.170-ex112
infilter-2.0.0
jei_1.12.2-4.16.1.301
JEROreIntegration-1.12.2-1.1.0
JustEnoughResources-1.12.2-0.9.2.60
llibrary-1.7.20-1.12.2
malisiscore-1.12.2-6.5.1
malisisdoors-1.12.2-7.3.0
Mantle-1.12-1.3.3.55
mcw-bridges-1.0.4-mc1.12.2
moartinkers-0.6.0
Morpheus-1.12.2-3.5.106
NaturesCompass-1.12.2-1.8.5
Neat 1.4-17
Netherending-Ores-1.12.2-1.4.2
obfuscate-0.4.2-1.12.2
oeintegration-2.3.4
omlib-1.12.2-3.1.4-249
OpenComputers-MC1.12.2-1.7.5.192
openmodularturrets-1.12.2-3.1.12-378
OpenSecurity-1.12.2-1.0-71
OreExcavation-1.4.150
Pam's HarvestCraft 1.12.2zg
Placebo-1.12.2-1.6.0
pollutantpump-1.12.2-1.3.0
Psi-r1.1-78.2
Quark-r1.6-179
rustic-1.1.7
SereneSeasons-1.12.2-1.2.18-universal
stg-1.12.2-1.2.3
StorageDrawers-1.12.2-5.4.2
Tails-1.12-1.10.0
TConstruct-1.12.2-2.13.0.183
Thaumcraft-1.12.2-6.1.BETA26
thaumicbases-3.3.500.6r
thaumictinkerer-1.12.2-5.0-620a0c5
tinkers_reforged-1.5.2
tinkersjei-1.2
tinkersoc-0.6
TinkerSurvival-1.12.2-1.2.2.1
TMechworks-1.12.2-1.0.0
tumbleweed-1.12-0.4.7
Voice+Chat+Reloaded-1.2.5

**Comment by SweetSugarSugar** [comment] 2021-03-23 18:23
You might need more RAM?

**Comment by KnightMiner** [comment] 2021-03-24 15:44
I would not say needing more RAM is a fair assessment. This seems like a case of your favorite 3 mod interaction crash bug.

* Tinkers Construct does a recipe scan during post init to automatically add recipes for items crafted from other items
* IndustrialCraft apparently has a custom ingredient trying to determine if things are fluid containers. Somehow they are passing in a null capability
* Astral Sorcery does not expect `hasCapability` to receive a null parameter

Unfortunately, I cannot tell you why the capability being passed from Industrial Craft to Astral Sorcery is null since IndustrialCraft's code is not visible. I suggest cross posting this crash to Industrial Craft and linking it here. I also suggest before you cross post, get a crash report with fewer mods, just the three I mentioned should let you reproduce it.

However, as a warning TiC is basically done with 1.12 development. I'll mark this for an issue that can probably be worked around if we make another 1.12 release, but I really doubt that will happen. Its been a year since our last 1.12 build, efforts are focused on getting something ready for 1.16.

**Comment by KnightMiner** [comment] 2022-01-31 19:15
Closing as 1.16 received a beta making 1.12 end of support. If anyone picks up 1.12 in the future, we could work around this [with a try catch block here](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/smeltery/TinkerSmeltery.java#L823), but that is a super hacky fix for a bug that is not ours.

**Closed as completed by KnightMiner** 2022-01-31 19:15 UTC
Labels: Bug, Can't Fix, Mod interaction, 1.12
