### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by dpeter99** [SlimeKnights/TinkersConstruct#2784] opened 2017-02-27 17:27 UTC
`A TileEntity type slimeknights.tconstruct.smeltery.tileentity.TileCastingBasin has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22) ~[ee.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:128) ~[dr.class:?]
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:100) ~[FluidStack.class:?]
	at net.minecraftforge.fluids.FluidTank.writeToNBT(FluidTank.java:77) ~[FluidTank.class:?]
	at slimeknights.tconstruct.smeltery.tileentity.TileCasting.func_189515_b(TileCasting.java:271) ~[TileCasting.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[17:20:09] [Server thread/DEBUG] [FML/]: The world 1b047b13 (world) may have leaked: seen 8470 times.

From Direwolf20 mod pack (latest stable)`

**Comment by KnightMiner** [comment] 2017-08-07 17:19
Closing as a duplicate of #2994, since that issue provides more information.

**Closed by KnightMiner** 2017-08-07 17:19 UTC
