### ISSUE TITLE
Crafting Station with Nonuple Compressed Cobble from Additional Compression Mod

### ISSUE THREAD

**Issue by remclave** [SlimeKnights/TinkersConstruct#3762] opened 2019-02-11 22:22 UTC
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):** NO CRASH

**Versions:** 
* Minecraft: 1.12.2
* Forge: 2811
* Mantle: 1.3.3.42
* Tinkers Construct: 2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

CRAFTING STATION (TCon):
![2019-02-11_16 06 30](https://user-images.githubusercontent.com/31051239/52597239-ffaa7f00-2e17-11e9-9d1b-df863140f6c6.png)

Item in Crafting Station is the Nonuple Compressed Cobblestone from the Additional Compression mod version 3.1

CRAFTING TABLE (MC):
![2019-02-11_16 06 40](https://user-images.githubusercontent.com/31051239/52597277-1ea91100-2e18-11e9-8d0e-241603697be5.png)

Server does have NoMoreRecipeConflit version 0.13 for 1.12.2 MC.

**Comment by KnightMiner** [comment] 2019-02-12 03:40
Typically this is caused by a broken recipe that matches no ingredients. They typically still show in the vanilla table, but there is a chance one of your mods fixes that behavior. Try with just the two mods and see what results you get.

**Comment by RCXcrafter** [comment] 2019-02-16 16:34
I can confirm that additional compression causes this issue by adding empty recipes, I'll fix this on my end.

**Comment by remclave** [comment] 2019-02-18 17:03
Thank you @RCXcrafter for your response. I look forward to resolution.

**Comment by bonii-xx** [comment] 2019-02-19 18:48
Closing this since there's nothing to do for us ;)

**Closed by bonii-xx** 2019-02-19 18:48 UTC
Labels: 3rd party mod interaction
