### ISSUE TITLE
Battlesign Bugs

### ISSUE THREAD

**Issue by Mike-U5** [SlimeKnights/TinkersConstruct#3790] opened 2019-03-16 11:04 UTC
**1) Infinite Blocking** If your Battlesign breaks while you are actively blocking, it will continue to work as a normal shield until you switch away from it. 
The guard animation won't display and you can walk around at normal speed but it still blocks all damage coming from the front. You can even attack enemies while blocking if the battlesign was in your offhand when it broke. 

**2) Durability Loss Inconsistency** Another bug exists with Battlesigns: They will always lose 1 durability when blocking **melee** hits.
It should actually lose durability equal to the amount of damage blocked + 1. (If the attack deals 4 or more damage)
It does lose the correct amount of durability if you deflect an arrow though.
_If this gets fixed, perhaps consider upping the durability of Battlesigns a little bit to compensate._

**3) Stiff Trait** The Stiff trait reduces damage further when blocking. But... doesn't blocking already reduce damage to 0? So what does this trait do exactly?

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2815
* Mantle: 1.3.3.42
* Tinkers Construct: 2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
No mods used besides Tinker's Construct and Mantle.

**Comment by bonii-xx** [comment] 2019-03-16 17:23
>3) Stiff Trait The Stiff trait reduces damage further when blocking. But... doesn't blocking already reduce damage to 0? So what does this trait do exactly?

Battlesigns reduce the damage by 70%, unless vanilla or another mod broke things again.

**Comment by Mike-U5** [comment] 2019-03-16 21:52
I'm only using Tinker's Construct and Mantle, so yeah that's a vanilla change.  
The vanilla shield blocks 100% melee damage now. 
If that's the case, maybe make Battlesigns block 95% damage.

**Comment by Z-Tunic** [comment] 2019-04-20 07:46
Battlesigns appear to still reduce damage by 70% if you took damage while blocking unless they worked differently. You can fully block some hits from the front but you can still take damage if you get attacked from behind, touching a cactus, etc.

Stiff Trait does increase this damage reduction further. Here's a test vs a damage source that deals 5.0 damage. Stiff apparently stacks per hand but only once.

No Stiff while guarding: 16.5/20.0 Health | 3.5 damage taken, 1.5 reduced
1x Stiff while guarding: 17.2/20.0 Health | 2.8 damage taken, 2.2 reduced
2x Stiff while guarding: 17.9/20.0 Health | 2.1 damage taken, 2.9 reduced
5x Stiff while guarding: 17.9/20.0 Health | 2.1 damage taken, 2.9 reduced

Unsure if it's suppose to be like. I do recall running into the Infinite Blocking glitch before and thought it was a mod conflict but I guess not if it occurs with only Tinkers Construct & Mantle.

**Comment by KnightMiner** [comment] 2019-09-21 22:18
Did some testing, first bug is actually MC-86252, as in it sorta happens with vanilla shields. Essentially, vanilla relies on the fact that you are holding right click to update the shield stack being used for blocking, so if the stack loses blocking ability or you are pointing at an inventory it still thinks it can block. Luckily we can clear the active hand when the tool breaks, but not much we can do about the related vanilla bugs.

Durability bug appears to be caused by the fact that vanilla is actually handling the majority of our blocking logic, but does not damage our shield as its not marked as a shield. This can be fixed by marking it as a shield using the forge method, but then it breaks the above fix as vanilla does not pass a player when damaging the tool.

**Comment by KnightMiner** [comment] 2022-01-31 19:39
Closing as 1.16 got a beta release making 1.12 end of support. I mentioned most of these are hard to fix due to how vanilla handles most of our blocking logic. Forge has some PRs in 1.16-1.18 that should give us more control, so hopefully these no longer happen then.

**Closed by KnightMiner** 2022-01-31 19:39 UTC
Labels: Bug, 1.12
