### ISSUE TITLE
game crash if the player puts any of the armor on

### ISSUE THREAD

**Issue by iHas-Brain** [SlimeKnights/TinkersConstruct#4788] opened 2022-02-28 20:49 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.88

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

when trying to put on any armor that tinkers' construct adds, the game crashes. it's because of optifine

### Reproduced with only Tinkers' Construct?

No

### Other mods required

optifine

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment] 2022-02-28 20:59
Congratulations, you are the 15th duplicate of #4734. Your prize is shame for lying about checking the pinned issues. If you do not know how to check the pinned issues, don't lie and check the box. If you do know how to check the pinned issues, you would have seen this is a duplicate.

The fix is to stop using optifine. They have know about this issue for a month and have done nothing. I even posted a comment saying they don't care about their users on their issue tracker and they did not respond, making me guess they never read it.

**Closed as completed by KnightMiner** 2022-02-28 20:59 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
