### ISSUE TITLE
Strange Crossmod behavior with Chisel and Tinker's Construct

### ISSUE THREAD

**Issue by Serifina** [SlimeKnights/TinkersConstruct#3106] opened 2017-08-17 04:03 UTC
Minecraft: 1.12
Forge: 2443
Chisel: 1.12-0.0.13.15
Tinker's Construct: 1.12-2.7.2.19

Chisel blocks do not render in the casting basin at all. The One Probe also does not see them in the Casting Basin at the same time, but they can be removed as per normal. Which would just be an odd render issue, except.

Cobalt, poured into the casting basin (as from a smeltery), is defaulting to the Caution chisel block of Cobalt, instead of the normal block of cobalt. As soon as it finishes cooling, it vanishes. It's still there, but cannot be seen. Right clicking the basin removes the block as per normal.

I'm reporting this on both Chisel and Tinker's Construct githubs.

**Comment by KnightMiner** [comment] 2017-08-17 04:17
Duplicate of #2884. Do note that The One Probe not showing blocks affects any block, it does not currently show output items, just inputs IIRC.

**Closed by KnightMiner** 2017-08-17 04:17 UTC
