### ISSUE TITLE
Textures missing for items (TConstruct-1.12-2.7.1.9.jar)

### ISSUE THREAD

**Issue by SelfCombusted** [SlimeKnights/TinkersConstruct#3034] opened 2017-07-23 16:43 UTC
![minecraft 07 23 2017 - 17 18 03 01](https://user-images.githubusercontent.com/30390904/28501176-3d61f4f4-6fce-11e7-9526-0715b080f648.png)
Textures missing for many items,
using jei if helps

**Comment by KnightMiner** [comment] 2017-07-23 17:13
Search before you post please, duplicate of #3008. Optifine is on a new version again and has broken new features, upvote the post on their tracker.

**Closed by KnightMiner** 2017-07-23 17:13 UTC
