### ISSUE TITLE
Cobalt Chainmail Chest Piece Crashes game when worn

### ISSUE THREAD

**Issue by biker37889** [SlimeKnights/TinkersConstruct#4839] opened 2022-04-24 00:50 UTC
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

I was playing in my tinker's survival world and i made a plate chestplate, put it on and my game crashed, minecraft said it was the chestplate, went into a creative world, put it on and the game crashed and try reloading the worlds, it does load but the game crashes pretty much immediately, I also tried on the other gear in the plate armor set and the other armor sets and they all crashed too

### Other mods

These are all the mods I have installed: I don't think they should affect the armor but just in case:
Framedblocks 4.2.0
Just Enough Resources 0.13.1.138
Enhanced Mob Spawners 1.8.15
Excavation 1.18-1.7.1
Journeymap 5.8.0beta17
Just Enough Items 9.2.1.69

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment] 2022-04-24 00:52
Duplicate of #4734 
Remove optifine.

**Closed as completed by ShinyPorygon** 2022-04-24 00:52 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
