### ISSUE TITLE
[1.10.2] v2.60 JEi can't see items in chest adjacent to Crating tables

### ISSUE THREAD

**Issue by sbacchini** [SlimeKnights/TinkersConstruct#2627] opened 2016-12-05 20:26 UTC
After I updated to the latest version, JEI's Auto fill wouldn't work if the items were in a chest adjacent to a Crafting Table, only if the items were in my inventory, I went back to 2.5.6b and everything  worked again.

**Comment by KnightMiner** [comment] 2016-12-05 21:07
Of course there were regressions of the fix for #2570. Unfortunately a more full fix would require a much more complex solution, so it might take a bit.

**Comment by choekstr** [comment] 2016-12-31 21:39
Seems like both the packs I am playing just updated to 2.6.x and now I am affected by this bug.  As this is my primary method of crafting prior to RS/AE2 I am particularly crushed by this recent...development.

Hat in hand and respectfully asking: Is there any progress on this issue?  I'm dying over here without my wonderful tinkers crafting table and connected inventory crafting!

**Comment by KnightMiner** [comment] 2016-12-31 23:18
I've talked with mezz about the issue, and unfortunately a fix that won't bring back #2570 requires changes in Forge, specifically MinecraftForge/MinecraftForge#3516.

**Comment by MindCaged** [comment] 2017-01-03 12:20
Frankly, I'd be happy with a temporary config option to reenable it, and I'd just be careful what blocks I placed next to it, as if I understand #2570 correctly it only causes a problem if you place an invalid inventory next to the tinkers crafting table. I would like to just reenable the functionality and take my chances just so I could have the functionality. Like choekstr said, the tinkers crafting table was one of my main crafting gotos before RS/AE2. I think I have a few other possible options I'd have to check into, but I don't think they're fully compatible with JEI as in you can click the + button, but they won't highlight missing items in red. So you've got to do the thing where you click in the recipe and then check which items weren't placed in the grid because they were missing. I think EzStorage 2 is one of these, I have to recheck into it as I haven't touched it in a while.

**Comment by MasterRanger** [comment] 2017-01-16 13:32
https://youtu.be/zaRL16WDAmw  This bug is a bummer.  My server-mates and I were absolutely ecstatic when we could put an iron chest next to a crafting station.  Now, it doesn't work with anything.

**Comment by VT-14** [comment] 2017-02-03 17:48
I'm with MindCaged.  Being able to craft with JEI using items from the adjacent inventory is well worth the risk of a handful of uncooperative inventories.  Could the more common ones be 'fixed' by the Crafting Station Blacklist added in 8c4e430?

Alternatively, could there be a whitelist or have it hardcoded to at least work with the vanilla chest/doublechest?

**Comment by choekstr** [comment] 2017-02-03 18:04
Shutting down every connected inventory seems like a drastic measure indeed because of a rare potential for the uncooperative inventory (Petal Apothecary) to be placed next to it.  I would also relish having a config option to allow this again or even a blacklist for the offending inventories that crash.  Just adding in my vote as well.

**Comment by cloudpersona** [comment] 2017-02-25 00:13
Does anyone know which version of tinker's still had this working? Because I want this functionality back.

**Comment by borg286** [comment] 2017-03-22 02:39
sbacchini said that 2.5.6b worked, but when I tried Beyond(v1.2.1 and 1.1.0) rolling TCon to this version it broke. Extra utilities 2 tried calling out to TCon to initialize some bow stats and it failed. 
I've filed [this bug](https://forum.feed-the-beast.com/threads/jei-tinkers-crafting-station-not-reading-attached-inv.222565/) against Beyond so future hacky workarounds should probably not clog up this bug tracker here. Just Thumb up some comment here and post workarounds elsewhere.

Please reconsider rolling back your Petal Apothecary fix, as it hurts more than it helps.

**Comment by borg286** [comment] 2017-03-22 03:33
Reverting this change fixes it https://github.com/KnightMiner/TinkersConstruct/commit/eb641958416580129c96c18693aa008c328d899f
I just tested it. Checking to see if the original Petal problem repros.

**Comment by borg286** [comment] 2017-03-22 03:40
The petal problem crashed my computer hard. I advise waiting for a proper fix from KnightMiner, and not my hack. This will be my last post. My apologies for intruding with my amateur hacks.

**Comment by VT-14** [comment] 2017-11-11 15:47
Any update on this?  The mentioned Forge change was closed due to inactivity about a month ago.

**Comment by bonii-xx** [comment] 2017-11-21 16:24
@KnightMiner what do you judge the effort to reimplement the old, broken variant and add a workaround for the original problem? Worst case we'll have to use sided access.

**Comment by KnightMiner** [comment] 2017-11-21 16:31
It would be easy to add back the old behavior, espeically since we have the blacklist for cases like the original issue now. Since there is currently no way to handle a two way sided check as far as I know, we could try only allowing the slots to be used if you can both insert and extract or something.

**Comment by bonii-xx** [comment] 2017-11-21 17:40
Yeah.. let's add it back. With sided access, so it's compatible with anything. It's useful, but not THAT useful.

**Comment by jusitnboggs** [comment] 2017-12-31 01:49
So is this even going to get fixed? I'm kinda lost lol

**Comment by choekstr** [comment] 2017-12-31 02:26
It's fixed in 1.12.2 versions and OMG it is heaven!  SOOO happy it is back and life is good again.  I even went well into mid-game before going after an AE2 system since I didn't have to hold every crafting material in my inventory.

Thanks so much @bonii-xx for pushing this through.  Such a wonderful thing...

**Comment by jusitnboggs** [comment] 2017-12-31 05:51
ok well what about older versions?

**Comment by VT-14** [comment] 2017-12-31 05:58
The changelog on Curseforge for the last 1.10 release (1.10.2-2.6.5) stated "This will be the last release for 1.10.2." at the top, so I highly doubt this will officially be retroactively applied to 1.10.

On a different note, I would also like to express my gratitude at this feature being re-implemented.  I look forward to using it and the new content next time I play.

**Comment by KnightMiner** [comment] 2017-12-31 06:03
I thought I already marked this issue resolved. Anyways, this has been released, so closing.

**Closed by KnightMiner** 2017-12-31 06:03 UTC
Labels: bug, Resolved
