### ISSUE TITLE
Server crashing on startup

### ISSUE THREAD

**Issue by Remi4001** [SlimeKnights/TinkersConstruct#3819] opened 2019-04-11 01:22 UTC
**Issue description:**
When I launch my server with a custom modpack it crashes during startup but it only does that since I uptated Astral Sorcery to 1.10.13
**If crashed, link to crash report (use a site such as pastebin):**
[crash-2019-04-10_19.36.25-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3066510/crash-2019-04-10_19.36.25-server.txt)

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2824
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** Astral Sorcery version 1.10.13

**Comment by KnightMiner** [comment] 2019-04-11 01:27
Can you reproduce this with just Tinkers Construct and Astral Sorcery? If so, a clean crash report would be appreciated.

In any case, from the crash it appears to be an astral sorcery bug, looks like one of their access transformers broke, one used by one of their ingredients.

**Comment by Remi4001** [comment] 2019-04-11 01:36
[crash-2019-04-10_21.12.00-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3066540/crash-2019-04-10_21.12.00-client.txt)
I've got this crash report with only Astral Sorcery (and baubles which is a dependency) and TC. Hope you'll find something useful.

**Comment by Remi4001** [comment] 2019-04-11 01:38
And I already created an issue for Astral Sorcery there: https://github.com/HellFirePvP/AstralSorcery/issues/1063

**Comment by KnightMiner** [comment] 2019-09-21 19:53
Fixed in Astral Sorcery

**Closed by KnightMiner** 2019-09-21 19:53 UTC
Labels: 3rd party mod interaction
