### ISSUE TITLE
Blank Pickaxe fill

### ISSUE THREAD

**Issue by Pocketzabu** [SlimeKnights/TinkersConstruct#4290] opened 2021-04-03 06:56 UTC
**Issue description:**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.16.5-1.6.79
* Tinkers Construct: 3.0.2.73

When making a pickaxe withing the tool station, I shift-right clicked my pickaxe out of the table. All empty slots of my inventory filled with pure white blank pickaxes with 1 durability and no repair material.

**Comment by KnightMiner** [comment] 2021-04-03 20:43
Cannot reproduce. Crafting a pickaxe and adding a modifier both work fine with shift click. Please post a screenshot of the recipe you are doing, and fill out the rest of the issue template you ignored.

This may also have been fixed with #4282.

**Comment by KnightMiner** [comment] 2021-04-03 21:25
In addition to the extra information, try again in 3.0.2.76. If the other bug fix fixed this, that will tell.

**Comment by KnightMiner** [comment] 2021-04-09 05:35
Going to close this, assuming it was fixed in 3.0.2.76

**Closed as completed by KnightMiner** 2021-04-09 05:35 UTC
Labels: Bug, Not enough information, 1.16
