### ISSUE TITLE
Model Bake Broken (MC 1.9, Forge 12.16.0.1865, Mantle 0.9.4, TC 2.2.2)

### ISSUE THREAD

**Issue by JonnyBrando** [SlimeKnights/TinkersConstruct#2036] opened 2016-04-23 14:30 UTC
So, back to the drawing board again.

I tried stock builds on F1865, and they didn't work. I found (with your Git Releases page) that 2.2.2 is 45 commits behind, so I built my own in #2034.

Same problem with official 2.2.2 and the latest GIT build.

Both copies work fine in 1.9 F1865 server, just problem with client.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
  MalisisCorePlugin (malisiscore-1.9-3.0.5.jar)
  MMFMLCorePlugin (MultiMine-1.9.jar)
  BetterFoliageLoader (BetterFoliage-MC1.9-2.0.9.jar)
  MalisisSwitchesPlugin (malisisswitches-1.9-2.0.0.jar)
  DLFMLCorePlugin (DynamicLights-1.9.jar)
  SCFMLCorePlugin (StalkerCreepers-1.9.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 4/23/16 9:27 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.ToolModel.bake(ToolModel.java:74)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:756)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:323)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.ToolModel.bake(ToolModel.java:74)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:756)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:323)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 714179584 bytes (681 MB) / 1557389312 bytes (1485 MB) up to 4268163072 bytes (4070 MB)
	Mod Pack: 1.9-SNAPSHOT-r47D63A1-b7-2016-04-19_22-30-16
	LiteLoader Mods: 1 loaded mod(s)
          - Presence Footsteps version u9 for 1.9
	LaunchWrapper: 34 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.mods.betterfoliage.loader.BetterFoliageTransformer
          - Transformer: $wrapper.atomicstryker.dynamiclights.common.DLTransformer
          - Transformer: $wrapper.invtweaks.forge.asm.ContainerTransformer
          - Transformer: $wrapper.atomicstryker.multimine.common.fmlmagic.MMTransformer
          - Transformer: $wrapper.atomicstryker.stalkercreepers.common.SCTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: $wrapper.net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
          - Transformer: $wrapper.net.malisis.core.util.chunkblock.ChunkBlockTransformer
          - Transformer: $wrapper.net.malisis.core.renderer.transformer.MalisisRendererTransformer
          - Transformer: $wrapper.net.malisis.core.renderer.icon.asm.TextureMapTransformer
          - Transformer: $wrapper.net.malisis.switches.asm.MalisisSwitchesTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms350m -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:+AggressiveOpts -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1865 Optifine OptiFine_1.9_HD_U_B2_pre 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJA	Forge{12.16.0.1865} [Minecraft Forge] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJA	Baubles{1.2.0.1} [Baubles] (Baubles-1.9-1.2.0.1.jar) 
	UCHIJA	BetterAchievements{0.2.2} [Better Achievements] (BetterAchievements-1.9-0.2.2.jar) 
	UCHIJA	BetterFoliage{2.0.9} [Better Foliage] (BetterFoliage-MC1.9-2.0.9.jar) 
	UCHIJA	BiomesOPlenty{4.0.2.2012} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2012-universal.jar) 
	UCHIJA	Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar) 
	UCHIJA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.13.jar) 
	UCHIJA	DynamicLights{1.4.1} [Dynamic Lights] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.9.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.9.jar) 
	UCHIJA	graves{1.9-b8-universal} [Graves Mod] (graves-1.9-b8-universal.jar) 
	UCHIJA	LunatriusCore{1.1.2.34} [LunatriusCore] (LunatriusCore-1.9-1.1.2.34-universal.jar) 
	UCHIJA	InGameInfoXML{2.8.1.82} [InGame Info XML] (InGameInfoXML-1.9-2.8.1.82-universal.jar) 
	UCHIJA	inventorysorter{0.7.10+29} [Simple Inventory sorting] (inventorysorter-1.9-0.7.10+29.jar) 
	UCHIJA	inventorytweaks{1.61-dev-45-29e0ed5} [Inventory Tweaks] (InventoryTweaks-1.61-dev-45.jar) 
	UCHIJA	JEI{3.2.10.185} [Just Enough Items] (jei_1.9-3.2.10.185.jar) 
	UCHIJA	journeymap{1.9-5.1.6b2} [JourneyMap] (journeymap-1.9-5.1.6b2-unlimited.jar) 
	UCHIJA	malisiscore{1.9-3.0.5} [MalisisCore] (malisiscore-1.9-3.0.5.jar) 
	UCHIJA	malisisblocks{1.9-3.0.0} [Malisis Blocks] (malisisblocks-1.9-3.0.0.jar) 
	UCHIJA	malisisdoors{1.9-4.0.1} [MalisisDoors] (malisisdoors-1.9-4.0.1.jar) 
	UCHIJA	malisisswitches{1.9-2.0.0} [Malisis Switches] (malisisswitches-1.9-2.0.0.jar) 
	UCHIJA	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIJA	RadixCore{1.9-2.1.0} [RadixCore] (RadixCore-1.9-2.1.0-BETA-universal.jar) 
	UCHIJA	MCA{1.9-5.1.2} [Minecraft Comes Alive] (MCA-1.9-5.1.2-BETA-universal.jar) 
	UCHIJA	AS_MultiMine{1.5.2} [Multi Mine] (MultiMine-1.9.jar) 
	UCHIJA	parachutemod{1.4.1} [Parachute Mod] (parachutemod-ng-1.9-1.4.1-395.jar) 
	UCHIJA	progressiveautomation{1.6.38} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.38.jar) 
	UCHIJA	Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.9-1.5.0.jar) 
	UCHIJA	AS_Ruins{15.8} [Ruins Spawning System] (Ruins-1.9.jar) 
	UCHIJA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.jar) 
	UCHIJA	StorageDrawers{1.9-3.1.6} [Storage Drawers] (StorageDrawers-1.9-3.1.6.jar) 
	UCHIJA	tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
	UCHIJA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.9-3.0.5.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
MMFMLCorePlugin (MultiMine-1.9.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
BetterFoliageLoader (BetterFoliage-MC1.9-2.0.9.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
MalisisSwitchesPlugin (malisisswitches-1.9-2.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
DLFMLCorePlugin (DynamicLights-1.9.jar)
  atomicstryker.dynamiclights.common.DLTransformer
SCFMLCorePlugin (StalkerCreepers-1.9.jar)
  atomicstryker.stalkercreepers.common.SCTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.91' Renderer: 'Quadro M1000M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.9-forge1.9-12.16.0.1865-1.9
	LWJGL: 2.9.4
	OpenGL: Quadro M1000M/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.91, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ChromaHills128x-1.9_v0.1.zip, ChromaHillsMods-128x1.9_v1.0.zip, PF.Resources.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.9_HD_U_B2_pre
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: 'Sildurs Enhanced Default v1.0.1.zip
	OpenGlVersion: 4.5.0 NVIDIA 361.91
	OpenGlRenderer: Quadro M1000M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by bonii-xx** [comment] 2016-04-23 14:35
Ok, I need you to test if it also happens without Optifine, and if it does, if it also happens with only TiC and Mantle, no other mods.

And yes, we obviously can't support custom builds.

**Comment by JonnyBrando** [comment] 2016-04-23 16:11
Tested without OF, and it loads up just fine (with the RPs).
Tested with OF B1, and it appears to work as well (with the RPs). Looks like the texture map is larger (8192x8192)
Tested with OF B2 PRE, and it crashes. Looks like the texture map is smaller (2048x1024)

[crash-2016-04-23_12.01.08-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/233032/crash-2016-04-23_12.01.08-client.txt)

[fml-client-of_b2-crash.txt](https://github.com/SlimeKnights/TinkersConstruct/files/233029/fml-client-of_b2-crash.txt)
[shadersmod-of_b2-crash.txt](https://github.com/SlimeKnights/TinkersConstruct/files/233035/shadersmod-of_b2-crash.txt)

[fml-client-of_b1-works.txt](https://github.com/SlimeKnights/TinkersConstruct/files/233031/fml-client-of_b1-works.txt)
[shadersmod-of_b1-works.txt](https://github.com/SlimeKnights/TinkersConstruct/files/233036/shadersmod-of_b1-works.txt)

[fml-client-no_of-works.txt](https://github.com/SlimeKnights/TinkersConstruct/files/233030/fml-client-no_of-works.txt)

**Comment by bonii-xx** [comment] 2016-04-23 16:30
Well, there you have it, Optifine screwing things up, as always.

Judging by that one stacktrace in the crash it looks like BetterFoliage also has some Optifine integration that causes a crash. Might want to remove Betterfoliage and see if B2 works with that.

**Comment by sp614x** [comment] 2016-04-23 21:48
Forge #1863 + Mantle 0.9.4 + TC 2.2.2 + OptiFine B2_pre are working fine: http://i.imgur.com/pftscIB.png.
Adding BetterFoliage 2.0.9 causes TC to crash.
Only BetterFoliage 2.0.9 + OptiFine B2_pre also crashes: http://pastebin.com/raw/Q79npS7z

**Comment by JonnyBrando** [comment] 2016-04-23 22:16
Same version of BF 2.0.9 here as well.

If I remove Tinkers & Mantle I can play MC just fine with OF B2_pre / BetterFoliage 2.0.9 / Forge 1865.

I get the same error, but, it doesn't crash and still works. The texturemap stays 8192x8192. With tinkers, the texturemap size changes, and it completely crashes.


Yes, strange, I had it run once as well.

Changed resource packs because my daughter was on a MP Server, and it crashed.


Tried without RPs, still crashes now.

I typically use ChromaHills and PresenseFootsteps (I don't really care about PF) for RPs.

Running with OF B1 for now, and all is good.

**Comment by octarine-noise** [comment] 2016-04-25 05:59
The problem is entirely BetterFoliage. I'll push out a fix shortly.

**Comment by bonii-xx** [comment] 2016-04-25 08:10
https://github.com/octarine-noise/BetterFoliage/issues/59

**Comment by sp614x** [comment] 2016-04-25 18:41
Fixed in Better Foliage 2.0.10.

**Closed** 2016-04-25 20:19 UTC
Labels: OptiFine
