### ISSUE TITLE
Crash on 1.11.2, wont load up to the menu

### ISSUE THREAD

**Issue by RedBullSlurpie** [SlimeKnights/TinkersConstruct#2899] opened 2017-05-08 21:53 UTC
Here is the crash log, upon removing tinkers construct it seemed to work and launch fine with no issues. When TC is installed, it crashes during loading. Here is the crash report and some other info.

Crash report- https://pastebin.com/kypa7FGU
Forge Version- 1.11.2 - 13.20.0.2296
MC Version- 1.11.2

**Comment by KnightMiner** [comment] 2017-05-09 01:46
Dupe of #2881, pretty sure it is build Craft's fault.

**Closed by KnightMiner** 2017-05-09 01:46 UTC
