### ISSUE TITLE
liquid experience from openblock rendered incorrectly

### ISSUE THREAD

**Issue by Biviho** [SlimeKnights/TinkersConstruct#4207] opened 2020-10-18 01:10 UTC
**Issue description:**
liquid experience from openblock is not rendered correctly inside tanks from tinker, basically only the top of the fluid has a texture, other sides are transparent.
tested both in an heavy environment modpack (280 mods) and in a light environment modpack with just tinker, open block and ender io for comparison about the side rendering.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
tinkers construct
OpenBlocks
EnderIO (for reference)

**Comment by KnightMiner** [comment] 2020-10-18 01:16
Screenshots? Screenshots are always needed for any rendering bug.

**Comment by Biviho** [comment] 2020-10-18 02:42
yup, you are right, sorry, i wasn't thinking about it.

-first image in low mod environment, i have used ender io for reference with another mod that render fluid's sides
-in high mod environment is the same


![test1](https://user-images.githubusercontent.com/57569917/96357410-c30a4d00-10fb-11eb-90c7-6f9a444f1eb9.jpg)


while doing the screenshots i also tested the thinker tank and this is the result:

-first image in low mod environment (Edit:the faucet is actually pouring in the channel, it's totally not visible)
-second image in high mod environment, the same, but posted cause is more visible

![test2](https://user-images.githubusercontent.com/57569917/96357457-517ece80-10fc-11eb-8e03-2884dfd05bf4.jpg)
![test3](https://user-images.githubusercontent.com/57569917/96357458-5479bf00-10fc-11eb-9fc1-e7b9722b95f5.jpg)



Edit2: now that i think of it, this should probably be tested with more mods that provide tanks and pipe that render the fluid on the side to assure it is a tinker visual bug and not a bug from openBlocks, i will search some mods and test more in the next days

**Comment by KnightMiner** [comment] 2020-10-18 04:29
If I had to guess, open blocks has no flowing texture for their fluid, which is wrong. As I recall, we use the flowing texture on the sides of cubes 

You don't see the issue in other mods because they use the still texture. Compare molten iron in tanks from both mods.

**Comment by Biviho** [comment] 2020-10-18 09:39
i will then test it more and redirect the issue to open blocks, sorry for assuming it was on tinkers end, i remember on an older build it was causing some crash on rendering, i guess it was cause of an other problem.

just out of curiosity, would it be possible to add an override for fluids in the config to be rendered with the non flowing texture for compatibility?

**Comment by Biviho** [comment] 2020-10-18 11:22
Update: this is interesting

while testing with other mods i tried buildcraft and this is the result

![testbc](https://user-images.githubusercontent.com/57569917/96365825-9843e700-1143-11eb-8a28-9e51624b10bf.jpg)

i guess Buildcraft add some sort of fix for fluids that don't render correctly.
it would be nice to add the same fix if this is the case and is possible, for compatibility out of the box (and to avoid having to add buildcraft to an already chonky modpack)

**Comment by KnightMiner** [comment] 2020-10-18 14:22
This issue is likely caused by a mod doing something wrong, it's not significant enough for us to make another 1.12 release. No idea why adding Build craft would fix it, unless you are now using build craft liquid XP instead of open blocks, or the texture is missing because open blocks depends on build craft for it for some odd reason.

In short: no, this is not something we can trivially fix, and 1.12 is basically end of life.

**Comment by Biviho** [comment] 2020-10-18 15:09
as you already said it's probably on openblocks end to add flowing texture.

i just found the buildcraft behaviour interesting, that's why i posted here.

btw i have found that a mod called "WHAT" actually apply a fix for fluids, and with that all fluids that where previously rendered incorrectly are now not perfect, but at least are rendered, so if someone else have the same problem on 1.12 hopefully can find this issue thread and fix it for himself

**Comment by KnightMiner** [comment] 2021-06-15 17:11
Going to close this as there is no fix I'd be willing to make on 1.12 that does not risk breaking more. If you see the issue on 1.16 at all feel free to open a new issue.

**Closed as completed by KnightMiner** 2021-06-15 17:11 UTC
Labels: Mod interaction, 1.12, Update
