### ISSUE TITLE
1.12 aluminum brass issue

### ISSUE THREAD

**Issue by wickeddeamon** [SlimeKnights/TinkersConstruct#3059] opened 2017-07-28 13:55 UTC
i can create the alloy of aluminum brass(copper plus aluminum) but i cant make ingot or other cast with that alloy as substitute of gold. I dont know if is a bug or something else.

**Comment by KnightMiner** [comment] 2017-07-28 14:00
Duplicate of #3020.

**Closed by KnightMiner** 2017-07-28 14:00 UTC
