### ISSUE TITLE
Icons worder are wrong

### ISSUE THREAD

**Issue by castilio20** [SlimeKnights/TinkersConstruct#4325] opened 2021-04-08 14:23 UTC
**Issue description:**
the order of the icons are wrong
**If crashed, link to crash report (use a site such as pastebin):**
none
* Minecraft:1.16.5
* Forge: 1.16.5-forge-36.1.0
* Mantle: Mantle-1.16.5-1.6.79
* Tinkers Construct: TConstruct-1.16.5-3.0.2.78
![Screenshot_17](https://user-images.githubusercontent.com/76228548/114043505-34b98d00-983b-11eb-86c9-5119525437b5.png)

**Comment by PrincessOfEvil** [comment] 2021-04-08 14:24
Duplicate of #4311. Fixed in dev.

**Closed as completed by PrincessOfEvil** 2021-04-08 14:24 UTC
Labels: Bug, Duplicate, Resolved, 1.16, Confirmed
