### ISSUE TITLE
1.12 Stencil  Table missing patterns

### ISSUE THREAD

**Issue by heroboy04** [SlimeKnights/TinkersConstruct#3041] opened 2017-07-25 13:18 UTC
i'll leave it to the picture: 
![2017-07-25_06 15 32](https://user-images.githubusercontent.com/5399053/28573878-026efffc-7101-11e7-9db2-a6182e7898ae.png)

**Comment by KnightMiner** [comment] 2017-07-25 13:19
Duplicate of #3008, update Optifine.

**Closed by KnightMiner** 2017-07-25 13:19 UTC
