### ISSUE TITLE
Loading icons in JEI

### ISSUE THREAD

**Issue by Lalus03** [SlimeKnights/TinkersConstruct#4209] opened 2020-10-23 12:12 UTC
**Issue description: i created new world and when i wanted to check tinkers things in JEI, when i opened page with tinkers things i got crashed everytime even when i downloaded tinker's construct jei**

**If crashed, link to crash report (use a site such as pastebin):**https://pastebin.pl/view/68f02d3f

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.5.2854
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment] 2020-10-23 15:13
According to that crash, Weapon lib is to blame. As stated in the issue template, reproduce with fewer mods if you want us to be able to fix this. I expect without weapon lib your crash will stop, and without Tinkers your crash will still happen

**Comment by KnightMiner** [comment] 2021-01-26 04:10
Closing for lack of reply, looks like another mods fault

**Closed as completed by KnightMiner** 2021-01-26 04:10 UTC
Labels: Mod interaction
