### ISSUE TITLE
Can't create Mighty Smelting & Part Builder bug

### ISSUE THREAD

**Issue by Joetheknigh406** [SlimeKnights/TinkersConstruct#4612] opened 2021-08-29 11:16 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

I know that in Puny Smelting, and in various sources on the internet, it says that I need to pour molten seared stone onto Puny Smelting to create Mighty Smelting. However, the game will not let me pour it onto the book. I put the book in both the casting table and casting basin, but no luck. is it because I'm using a melter, and not a proper smeltery?

Less imprtantly (for me), he part builder will occasionally get bugged and refuse to actually give me the tool part, and I'll be forced to save and quit, and rejoin my world. only then will the issue fix itself. Tbh, this one is just inconvenient for me, so I don't mind it much.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment] 2021-08-29 12:41
First, go install JEI and look at the recipe for mighty smelting. Your mistake should be clear. We also show that recipe in the book puny smelting, so there is no excuse for not knowing the recipe (you have the wrong recipe by the way, you want a regular book unless your modpack changes it).

Second, one issue per report. It is a pain to deal with multiple issues in one ticket. Going to close this issue as the first one is not a bug, but you are free to open a new report with the second issue. If you do, you need to provide more info than "sometimes does not work" or I can do nothing.

**Closed as completed by KnightMiner** 2021-08-29 12:41 UTC
Labels: Question, 1.16

**Comment by Joetheknigh406** [comment] 2021-08-29 22:21
I'm such an idiot. It just says "A book", not "THIS book!" I'll be honest, I don't know how kept interpreting everything as "pour molten seared stone on Puny Smelting." My bad haha!
