### ISSUE TITLE
[1.12.2] [NPE: Updating screen events] Placing tool in workstation

### ISSUE THREAD

**Issue by ApexModder** [SlimeKnights/TinkersConstruct#3453] opened 2018-04-09 08:36 UTC
When playing with Minecraft with the following set of mods, Placing a Tinkers tool in the workstation to add modifiers crashes the game with a NPE: Updating screen events

**Minecraft Version**: _1.12.2_
**Forge Version**: _14.23.2.2653_
**Optifine**: _Yes_ - **Version**: _1.12.2 HD U D1_
**Tinkers Version**: _2.9.1.65_
Other versions can be grabbed from logs

_[Mod List](https://paste.md-5.net/suniwoqega.md)
[crash-2018-04-09_07.52.35-client.txt](https://paste.md-5.net/rerafajuta.vhdl)
[Full Game Log](https://paste.md-5.net/jufuwayidi.vhdl)_

**Comment by TheQuadShot** [comment] 2018-04-09 08:58
I could be wrong, but I think the problem is tinkertoolleveling, since Tic doesn't allow tool upgrades on anything but the tool station/forge.

**Comment by ApexModder** [comment] 2018-04-09 12:07
@TheQuadShot Sadly that was not the case 😞 removed TinkersToolLeveling from mods folder launched and this error still happened

**Comment by KnightMiner** [comment] 2018-04-09 12:10
Duplicate of #3372, TAIGA issue that I'm pretty sure is fixed.

**Closed by KnightMiner** 2018-04-09 12:10 UTC
