### ISSUE TITLE
"Error: java.lang.NullPointerException: Updating screen events" when adding reinforcement upgrades to pickaxe

### ISSUE THREAD

**Issue by KCtops100** [SlimeKnights/TinkersConstruct#3527] opened 2018-06-05 14:13 UTC
Hello,

I am playing a custom made modpack that includes tinkers construct.  When adding a reinforcement modifier to a tool, the game freezes and then shortly crashes.  The crash report is attached.
[crash-2018-06-05_10.09.37-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2072689/crash-2018-06-05_10.09.37-client.txt)

If there is any more information that I can provide, please let me know.

**Comment by KnightMiner** [comment] 2018-06-05 14:23
Duplicate of #3372, TAIGA's fault.

**Closed by KnightMiner** 2018-06-05 14:23 UTC

**Comment by KCtops100** [comment] 2018-06-05 15:58
Thank you for the reply
