### ISSUE TITLE
Crash to desktop when puting any tc tool into tool station/forge

### ISSUE THREAD

**Issue by zzBuilderzz** [SlimeKnights/TinkersConstruct#3388] opened 2018-02-19 22:23 UTC
Every time I put a tool into a tool station or forge I get an instant crash regardless if I pulled it out of creative or built it from the tools component parts. This is affecting me across multiple mod packs including my own private one. I am using the latest versions of all mods. All mods that add or affect Tinker's Construct that I am currently are as follows: Tinker's addons, Tinker tool leveling, PlusTic, Taiga, Tinker i/o.

**Comment by bba3075** [comment] 2018-02-20 01:37
It's Taiga. I( was having the same problem and fixed it by removing taiga.

**Comment by zzBuilderzz** [comment] 2018-02-20 01:38
ahh thank you

**Comment by KnightMiner** [comment] 2018-02-20 03:50
Duplicate of #3372.

**Closed by KnightMiner** 2018-02-20 03:50 UTC
