### ISSUE TITLE
{1.16.5] Molten Invar doesn't show in JEI on Servers

### ISSUE THREAD

**Issue by MuteTiefling** [SlimeKnights/TinkersConstruct#4556] opened 2021-06-28 23:49 UTC
**Issue description:**
Molten Invar doesn't show in JEI on Servers

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.31
* Mantle: Mantle-1.16.5-1.6.109
* Tinkers Construct: TConstruct-1.16.5-3.0.4.197

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Doesn't appear to be

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Reproducible with only Tinkers, Mantle and JEI. As near as I can tell, Tinker's Invar is the only fluid not showing in JEI.

**Comment by KnightMiner** [comment] 2021-06-29 00:55
Molten invar only shows if there is an invar ingot in the pack. Does the native recipe show up in JEI? Does molten bronze work? Invar is no different from bronze in logic

**Comment by MuteTiefling** [comment] 2021-06-29 01:21
hah, good point. I'll re-test with thermal. 

The issue is occuring in Enigmatica 6 as a whole, however, which does have Invar from Thermal. And it only seems to be an issue when running on a server. It's visible in single player without issue. I just goofed my testing by excluding Thermal from the final test.

**Comment by MuteTiefling** [comment] 2021-06-29 03:10
Yep, same issue. Added the following:

- cofh_core-1.16.4-1.2.1
- thermal_expansion-1.16.4-1.2.0
- thermal_foundation-1.16.4-1.2.0
- thermal_innovation-1.16.4-1.2.0
- thermal_locomotion-1.16.4-1.2.0

Molten Invar doesn't show in JEI when logged into a server. Works fine in SP.

**Comment by MuteTiefling** [comment] 2021-06-29 03:12
And yes, Bronze is showing fine on the server. Both types.

**Comment by KnightMiner** [comment] 2021-06-29 03:35
There is literally no difference between the two, nothing I can change about one that is not true about the other except the name. Which means something screwy is happening with tags in your pack. Can you reproduce with just Tinkers and Thermal?

Also, for debug, try using the mantle tag dump commands to view the contents of `forge:ingots/bronze` and `forge:ingots/invar`

**Comment by MuteTiefling** [comment] 2021-06-29 09:39
That is with just tinkers and thermal.

I kinda need jei to see the issue, but the mod list is only the mods I've listed here. Thermal, tinkers, jei, and required libraries.

**Comment by MuteTiefling** [comment] 2021-06-29 09:45
To clarify, molten invar does exist and does work, it's simply not showing in jei.

**Comment by MuteTiefling** [comment] 2021-06-29 10:31
Mantle Dump: [mantle_data_dump.zip](https://github.com/SlimeKnights/TinkersConstruct/files/6732612/mantle_data_dump.zip)

Mod list again, for the record: 
![image](https://user-images.githubusercontent.com/9543430/123781299-12676680-d8a2-11eb-87cd-17f1ee88d091.png)

JEI search for invar on a server: 
![image](https://user-images.githubusercontent.com/9543430/123781737-96215300-d8a2-11eb-931a-355bd5fc7d20.png)

Bronze: 
![image](https://user-images.githubusercontent.com/9543430/123781800-a5a09c00-d8a2-11eb-8a03-a65d0fcd2643.png)

Now this is interesting, because Bronze was here last night. I had two. Regular Molten Bronze and Tinker's Bronze. Now I only have Tinker's Bronze.

I can make Invar in the smeltery:
![image](https://user-images.githubusercontent.com/9543430/123782202-1051d780-d8a3-11eb-9b26-fdbe19ff94f8.png)

And also Bronze:
![image](https://user-images.githubusercontent.com/9543430/123782644-8bb38900-d8a3-11eb-903c-bdaf0ec54d76.png)

Latest log: 
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/6732684/latest.log)

Debug Log
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/6732687/debug.log)

**Comment by KnightMiner** [comment] 2021-08-04 22:05
@MuteTiefling the Enigmatica6 issue was marked as fixed, did you manage to fix this or did it resolve itself automatically?

**Comment by MuteTiefling** [comment] 2021-08-04 23:27
Not sure. @NillerMedDild, did this thing just decide to start working?

**Comment by NielsPilgaard** [comment] 2021-08-05 04:37
It was resolved by a recent Tinkers update, not sure which one though :)

**Comment by KnightMiner** [comment] 2021-08-05 06:06
That code has not changed in the last 4 months, so unless JEI tool part syncing broke it somehow that seems odd. However, since you can no longer reproduce this I will close this issue.

Possible you had a bug with tag loading in your pack and that was fixed solving this issue, that would be my best guess.

**Closed as completed by KnightMiner** 2021-08-05 06:06 UTC
Labels: Bug, Not enough information, 1.16

**Comment by Jwguy** [comment] 2022-06-12 01:57
This seems to still be occurring in 1.16.5 with TConstruct 3.3.4.335. Both Bronze and Invar are missing from JEI as of their most latest version for 1.16.5, v7.7.1.152.

Safe to say, it looks like it is back.

**Comment by KnightMiner** [comment] 2022-06-12 02:00
Its not back. I never got information that verified this happened in the first place. I need a minimal mod list that reproduces this, should have less than 10 mods. Even then, doubt there is anything I can do, this bug is related to tags which changed twice since 1.16.5, I have zero desire to rewrite tag code in 1.16.5 that will have no impact on modern versions.
