### ISSUE TITLE
The Stencel table in the update 1.12-2.7.1.9 can't craft stencils at all  

### ISSUE THREAD

**Issue by PosingCarton** [SlimeKnights/TinkersConstruct#3028] opened 2017-07-22 04:23 UTC
![tinkers 1 12](https://user-images.githubusercontent.com/30362698/28488238-8a3aa05a-6e6b-11e7-93c8-16b7f1f47ec8.png)

**Comment by KnightMiner** [comment] 2017-07-22 04:29
Cannot reproduce. Does this still happen after you remove Optifine? If so try and pinpoint the specific mod that is conflicting.

**Comment by PosingCarton** [comment] 2017-07-22 04:42
it was optifine any recomandations on other mods similar to optifine

**Comment by KnightMiner** [comment] 2017-07-22 05:06
FoamFix can help reduce RAM usage, and I have heard BetterFPS can increase performance. If I am correct, this is a duplicate of #3008 and the buttons actually are working, the output is just invisible. You might find large plates still work and the rest still give a tooltip.

**Closed by KnightMiner** 2017-07-22 05:06 UTC
Labels: Can't reproduce
