### ISSUE TITLE
Stencil Table doesnt produce an outcome

### ISSUE THREAD

**Issue by Rams59** [SlimeKnights/TinkersConstruct#3800] opened 2019-03-27 11:03 UTC
**Hey i tried to make a bigge Modpack for my own and it works quite fine. Just when i put Patterns into the stencil Table nad try to make a Pattern i dont get any output. It stays empty. ATe there any mods which work in that cause this Problem? I tried to run it simply with Forge and Mantle and it works than.**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions: 2.**
* Minecraft: 1.12.2
* Forge: 14.23.5.2823
* Mantle: 1.3.3.42
* Tinkers Construct: 2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

**Comment by KnightMiner** [comment] 2019-03-27 12:57
I am going to assume this is a duplicate of #3796. Update nuclearcraft.

**Closed by KnightMiner** 2019-03-27 12:57 UTC
