### ISSUE TITLE
Bug/crash with servers, TIC and wings mod shows particle as the main reason of crashing

### ISSUE THREAD

**Issue by SirAron111** [SlimeKnights/TinkersConstruct#3921] opened 2019-08-07 15:06 UTC
Bug/crash with servers, TIC and wings mod shows particle as the main reason of crashing
I made a post about this in the wings mod since I thought maybe it’s due to the wings not properly loading files as it always stops at that mod but the crash / error report itself always shows something related to tinkers construct some kind of particle problem.

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/ymux3ma1
https://pastebin.com/21t46DUn
https://pastebin.com/MXm76WCV
https://pastebin.com/GPuTviCX
https://pastebin.com/FVzvEy6v
https://pastebin.com/FB3D2XN3

**Versions:**
* Minecraft: 1.12.2
* Forge 14.23.5.2838
* Mantle: Mantle-1.12-1.3.3.55.jar
* Tinkers Construct: TConstruct-1.12.2-2.12.0.157.jar

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
https://github.com/pau101/Wings/issues/39
The rest of the mod list can be found on the here https://www.curseforge.com/minecraft/modpacks/dimension-zero at the very bottom Crash happens in the beta version.
But it also happens with just tinkers and wings.

**Comment by KnightMiner** [comment] 2019-08-07 16:02
Your first two crashes are different from your last two. The first two appear to be a duplicate of #3783, which we assume is a dynamic surrounds bug. Does this issue happen without dynamic surrounds? Please give a crash report with a minimal mod list to verify.

The last two look like a foamfix crash, unrelated to this issue and not caused by Tinkers construct

**Comment by SirAron111** [comment] 2019-08-07 21:27
Will add more information if i can.. i am not that god at reading the reports and i just conected this line at slimeknights.tconstruct.shared.client.ParticleEffect.func_180434_a(ParticleEffect.java:74) to this mod

**Closed** 2019-08-08 22:59 UTC
Labels: Not enough information
