### ISSUE TITLE
problem at open inventory

### ISSUE THREAD

**Issue by krakel** [SlimeKnights/TinkersConstruct#1657] opened 2015-06-17 11:13 UTC
We got the following error at open the inventure. 
```
[13:01:17] [Client thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$InitGuiEvent$Post@3d941130:
java.lang.NullPointerException
	at tconstruct.client.tabs.InventoryTabKnapsack.shouldAddToList(InventoryTabKnapsack.java:23) ~[InventoryTabKnapsack.class:?]
	at tconstruct.client.tabs.TabRegistry.updateTabValues(TabRegistry.java:64) ~[TabRegistry.class:?]
	at tconstruct.client.tabs.TabRegistry.guiPostInit(TabRegistry.java:43) ~[TabRegistry.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_TabRegistry_guiPostInit_Post.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:257) [bdw.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1895) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_76]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```
tested with 
```
	forge-1.7.10-10.13.3.1408-1.7.10.jar
	CodeChickenCore{1.0.7.46} 
	notenoughitems-1.7.10-1.0.5.110.jar
	mantle-1.7.10-0.3.2.jar
	neiaddons-mc1710-1.12.9.32.jar
	NEIIntegration-MC1.7.10-1.0.9.jar
	tconstruct-1.7.10-1.8.5.jar
```

**Comment by krakel** [comment] 2015-06-17 11:56
I forgot, its only happens on client server connection located on different machines. Its seems like a race conditions.

**Comment by soupmeister** [comment] 2015-06-21 15:30
I'm getting the same issue on version 1.4.1.  No problem on SSP but crashes often on SMP.

**Comment by devryb** [comment] 2015-06-21 22:40
I am experiencing this same crash with 1.8.5 however it only happens on our hub server which is vanilla.  Our modded servers don't have this issue.
This was not an issue in previous versions, we would really appreciate if vanilla support could be fixed!

**Comment by SamMan55** [comment] 2015-06-24 13:50
I as well experience this crash those have do used the newest java maybe. Because In till I updated java that minecraft used so I could used the hardcore ender expansion mode. It work well.

**Comment by bonii-xx** [comment] 2015-06-24 18:20
That would indeed be curious, but good to know nontheless. Can you post your java versions?

**Comment by SamMan55** [comment] 2015-06-25 15:55
Java 8 , 1.8.0_45, the newest update.

**Comment by covers1624** [comment] 2015-06-26 03:03
I do believe that this could be a sync issue, i fixed a bug a while ago that syncs the Tcon inventory tab to the client on join, so it may be assuming that the inventory exists but it does not .

**Comment by SamMan55** [comment] 2015-06-26 05:46
how would I go about fixing it then?

**Comment by bugged2much** [comment] 2015-07-25 23:01
i have this same issue , and my java is 7

**Comment by bonii-xx** [comment] 2015-07-26 08:17
The issue is fixed in the alpha version.

**Closed by bonii-xx** 2015-07-26 08:17 UTC
