### ISSUE TITLE
[1.10.2] Interaction with Extra Utilities 2 Demon Ingots

### ISSUE THREAD

**Issue by inkblot0** [SlimeKnights/TinkersConstruct#2740] opened 2017-01-25 05:00 UTC
Using Extra Utilities version 1.10.2-1.2.0 with Mantle version 1.10.2-1.1.4 and Tinkers Construct version 1.10.2-2.6.2 in a clean version, I added a Demon Ingot to the smeltery for a Demonic Pickaxe Head. Upon damaging the tool down, I proceeded to place the full demonic ingot pickaxe into the tool forge with a demon ingot to repair it with nothing happening. Doing the same in a vanilla anvil accomplishes nothing as well. While proceeding,  I checked in the Materials and You book to see that the material was in the book but invisible on the material select screen (as are copper, lead and silver.) Testing with a full Iron pickaxe confirmed that repairs are possible in the tool forge.
Extra Utilities issue # 1264

**Comment by Flabort** [comment] 2017-01-25 09:28
Duplicate of #2735, please go to the Extra Utilities devs.

**Closed** 2017-01-25 11:59 UTC
Labels: duplicate
