### ISSUE TITLE
Registry Object not present: tconstruct:nahuatl_fence

### ISSUE THREAD

**Issue by Craft94land** [SlimeKnights/TinkersConstruct#5027] opened 2022-11-25 09:39 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.85

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

when i start minecraft after a long period of loading a crash appears and it says a Registry Object is not present: tconstruct:nahuatl_fence and i dont know how to fix it

### Crash Report

https://pastebin.com/X0f4F5Re

### Other mods

appleskin
architectury
baubley heart canisters
bookshelf
chickenchunks
cloth config
clumps
codechickenlib
configured
cucumber
curios forge
enchantmentdiscription
fastfurnace
fastleafdecay
fastload
fastsuite
fastworkbench
gamemenumodoption
gamemenuremovegfarb
healthoverlay
mantle
mousetweaks
mysticaladaptations
mysticalaggradditions
mysticalagriculture
optifine_1.18.2_HD_U_H7
placebo
prefab
reiplugincompatibilities
roughlyenoughitems
roughlyenoughprofressions
simplemagnets
simplestoragenetwork
sophisticatedbackpacks
sophisticatedcore
sophisticatedstorage
supermartijn642configlib
supermartijn642corelib
tcintegrations
tconstruct
tinker_rapier
tinker reforged
tinkers levelling addon

### Tried reproducing with just Tinkers?

Yes But it worked without any other mods

### Performance Enchancers

Optifine

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment] 2022-11-25 09:51
If it did work without any other mods try and find the mod causing it. And never ever report any bugs with optifine, use rubidium and oculus for shaders or performance instead.

**Comment by KnightMiner** [comment] 2022-11-25 16:20
Registry object not present is a fake crash. The real error happened earlier, which is hopefully in your full game log, so if you share the latest.log from the same run that crashed I may be able to tell you which mod is to blame.

**Comment by KnightMiner** [comment] 2022-12-26 04:45
I am going to close this as a duplicate of #5042. Normally I keep the older issue, but in this case the person on the newer issue has been more responsive.

In general, this type of error *shouldn't* be possible, and is due to something being broken in forge internals. I unfortunately do not have enough details to know if this is a forge bug or a bug caused by bad mixins, so I have a hard time determining how to handle this issue.

**Closed as completed by KnightMiner** 2022-12-26 04:45 UTC
Labels: Bug, Duplicate, Not enough information, 1.18
