### ISSUE TITLE
Game crashed when using Tinker's weapons

### ISSUE THREAD

**Issue by Leon5Ray** [SlimeKnights/TinkersConstruct#3874] opened 2019-06-10 13:20 UTC
**Issue description:**
I was fighting a boss in AoA3 with Tinkers weapons and the game just crashed.I have asked the author of AoA3.He read the crash report and told me it was Tinkers Construct.
**If crashed, link to crash report (use a site such as pastebin):**
[crash-2019-06-09_15.57.36-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3272153/crash-2019-06-09_15.57.36-server.txt)

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
I don't know.But I installed TinkerToolLeveling 1.1.0.

**Comment by KnightMiner** [comment] 2019-06-26 04:27
Duplicate of #3781.

**Closed by KnightMiner** 2019-06-26 04:27 UTC
