### ISSUE TITLE
[1.12] Render Crash Breaking Smeltery

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#3074] opened 2017-08-03 02:22 UTC
Getting a crash breaking the smeltery with a hammer.

Log: https://pastebin.com/tvGXL1vw

**Comment by bonii-xx** [comment] 2017-08-03 06:16
Curious. I wonder if vanilla is causing race conditions with itself now... Does this happen every time or only sometimes?

**Comment by MokahTGS** [comment] 2017-08-03 16:29
Not sure about with just tinkers.   It s a big mod pack

**Comment by KnightMiner** [comment] 2017-08-06 03:33
I cannot reproduce this in dev, so we are going to need more information to determine the issue. Try reproducing this with minimal mods, there is a good chance one of your core mods is causing the issue as the line number in the crash does not match with the vanilla method.

**Comment by KnightMiner** [comment] 2017-10-22 20:40
Closing for lack of a response. Reproduce with minimal mods for a reopen, or find the conflicting mod.

**Closed by KnightMiner** 2017-10-22 20:40 UTC
Labels: 3rd party mod interaction
