### ISSUE TITLE
Seed 107038380838084 crashes the game

### ISSUE THREAD

**Issue by SoniEx2** [SlimeKnights/TinkersConstruct#2664] opened 2016-12-20 00:05 UTC
Creating a new world with seed 107038380838084 with just TiCon installed then heading south from spawn seems to freeze the game (server-side). It eventually spawns LOTS AND LOTS AND LOTS of slime islands. Then it crashes.

![Halt...](https://vgy.me/bpPH3P.png)
![And catch fire!](https://vgy.me/dcj1is.png)

I was so looking forward to playing on this seed, but then it crashed. :/

**Comment by bookerthegeek** [comment] 2016-12-20 00:22
That is a glitched seed and a vanilla bug, you can solve this by turning slime island spawning off

**Comment by SoniEx2** [comment] 2016-12-20 00:23
Vanilla doesn't crash the game.

**Comment by KnightMiner** [comment] 2016-12-20 00:23
Thats the thing about Minecraft's randomizer, whether a terrain feature appears is based on a randomizer, and that randomizer's results is entirely based on the seed. That means in theroy it is possible for all "should island be here" checks to be true. I assume you got the seed from [this  Reddit post](https://www.reddit.com/r/Minecraft/comments/3ris4i/i_created_yes_created_a_seed_that_generates_a/)? It really messes with the randomiser to make the mineshafts more common, no doubt islands will be more common.

As for what we can do about it, I am not entirely sure. I can confirm the issue happens, but whether it is fixable or likely on other seeds is a little beyond my skills to determine.

**Comment by SoniEx2** [comment] 2016-12-20 00:27
I'm guessing it's just endlessly generating islands.

Just make island generation lazy/make it so island generation only populates existing chunks, without generating new ones.

**Comment by bookerthegeek** [comment] 2016-12-20 00:30
Never said vanilla crashed,  I said it was a glitched seed.

It causes the radom features of the world (In this case slime islands) to spawn infinitely on the east/west axis. 

In sure other mods that add random world generation will also crash you.

**Comment by bookerthegeek** [comment] 2016-12-20 00:31
@SoniEx2 great idea.  When should we expect your PR with the code for that?

**Comment by SoniEx2** [comment] 2016-12-20 00:32
@bookerthegeek Why should you? I'm only reporting the issue.

**Comment by bookerthegeek** [comment] 2016-12-20 00:58
... nevermind.

**Comment by BrainStone** [comment] 2016-12-20 01:27
@SoniEx2 Could you provide the crashlog?

**Comment by SoniEx2** [comment] 2016-12-20 01:38
@BrainStone Not that it contains any useful information: http://sebsauvage.net/paste/?13fa10affb0d8576#kLutLwawaIgDOcjeIaJjbDuSWEd6KprFsagHUFxnfoQ=

Good luck tracing that back to TiCon without a debugger.

**Comment by SoniEx2** [comment] 2016-12-20 02:00
Interesting, when using the DW20 pack, slime islands are the only thing that makes the seed crash, and disabling them makes the game playable.

Now I just need a way to get slime island stuff without slime islands...

**Comment by bonii-xx** [comment] 2017-01-09 15:36
Closing this since it's the fault of the Random Number Generator

**Closed by bonii-xx** 2017-01-09 15:36 UTC

**Comment by SoniEx2** [comment] 2017-01-09 15:40
Can you at least blacklist the seed?

**Comment by bonii-xx** [comment] 2017-01-09 15:46
Not really worth it, chances of somebody getting the same seed are basically nonexistant, and there's probably many seeds that'd cause this.

**Comment by SoniEx2** [comment] 2017-01-09 15:47
Only 2, actually.
