### ISSUE TITLE
[1.12] Rendering issues with patterns with Optifine

### ISSUE THREAD

**Issue by TygreWolf** [SlimeKnights/TinkersConstruct#3060] opened 2017-07-28 14:55 UTC
Opening stencil table only displays (mostly) blank patterns.  Creating a pattern works, but provides an invisible texture.  This is definitely a visual integration issue with Optifine, but unsure who should own it.  Rendering looks fine when Optifine is disabled.

Forge 14.21.1.2424
TConstruct 1.12.2.7.1.9
Optifine 1.12 HD U C4

Sample log output: 
```
[10:39:55] [main/INFO]: [OptiFine] Custom loader: TextureAtlasSprite{name='tconstruct:items/pattern_tough_tool_rod', frameCount=0, rotated=false, x=0, y=0, height=1, width=1, u0=0.0, u1=0.0, v0=0.0, v1=0.0}
[10:39:55] [main/INFO]: [OptiFine] Scaled too small texture: tconstruct:items/pattern_tough_tool_rod, 1 -> 16
```

![2017-07-28_10 40 54](https://user-images.githubusercontent.com/8293997/28722431-c0ae112e-7381-11e7-907b-830076880058.png)

**Comment by KnightMiner** [comment] 2017-07-28 15:47
This is a duplicate of #3008. If it is only caused when Optifine is loaded, always assume it's Optifine's fault, updating Optifine will fix it in this case.

**Closed by KnightMiner** 2017-07-28 15:47 UTC
