### ISSUE TITLE
All but one stencil is uncraftable

### ISSUE THREAD

**Issue by Draglann** [SlimeKnights/TinkersConstruct#3093] opened 2017-08-10 21:05 UTC
I've created a personal modpack for myself, but the stencil table is broken.
Picture: 
![2017-08-10_13 58 49](https://user-images.githubusercontent.com/30911358/29191896-1e75e4ce-7dd4-11e7-8063-aa1224a92f7b.png)
As you can see, I've selected one of the blank patterns and nothing shows up.

Version: 1.12-forge1.12-14.21.1.2387
Mod list:

AppleSkin-mc1.12-1.0.7
BrandonsCore-1.12-2.3.2.129-universal
ChanceCubes-1.12-3.0.1.199
ChestTransporter-1.12-2.8.7
CodeChickenLib-1.12-3.1.1.288-universal
cucumber[1.12]-1.0.0
Draconic-Evolution-1.12-2.3.3.261-universal
extrautils2-1.12-1.5.1
gravestone-1.8.3
ironchest-1.12-7.0.31.818
jei_1.12-4.7.5.85
Mantle-1.12-1.3.1.18
mysticalagriculture[1.12]-1.6.2
OptiFine_1.12_HD_U_C4
Pam's HarvestCraft 1.12c
RedstoneFlux-1.12-2.0.1.2-universal
replaymod-1.12-2.0.0
SBM-WoodenShears-1.12-0.0.1b7
TConstruct-1.12-2.7.2.15
zerocore-1.12-0.1.0.9

**Comment by KnightMiner** [comment] 2017-08-10 21:09
Duplicate of #3008

**Closed by KnightMiner** 2017-08-10 21:09 UTC
