### ISSUE TITLE
Crafting Station & Item Interface

### ISSUE THREAD

**Issue by thejims** [SlimeKnights/TinkersConstruct#2503] opened 2016-10-19 03:18 UTC
Client side inventory goes crazy when opening a crafting station that is next to an Actually Additions Item Interface ( which is in turn synced to a storage drawer controller so it shows many items )

Clientside logs when opening the crafting station:
http://pastebin.com/RFcNTCRU

Images of looking at it and opening it showing effects on client side:
http://imgur.com/HjXevRN
http://imgur.com/OjyjehK

Inventory refreshes itself when relogging onto server

**Comment by bonii-xx** [comment] 2016-10-28 14:27
The item interface is probably changing its internal size, messing up things. I wouldn't put a crafting station next to it.

**Comment by garantiertnicht** [comment] 2016-11-25 18:26
There also seens a Dupe Bug with it: Use an odd item, click with this item on the item you want to dupe in the crafting station, the item in your hand changes to the item to dupe. Now click with that item in another slot. Close the Working station, go to the storage, and put the items together. You succssfuly cloned an item. I'll also put an issue at the Actually Additions repro

**Comment by Ellpeck** [comment] 2016-11-25 18:49
How should I fix this, @bonii-xx? Is there even fixing that can be done? :v
It does change its internal size, but only when new inventories are attached to or detached from it, so I don't that's necessarily bad, is it?

**Comment by bonii-xx** [comment] 2016-11-25 18:57
I don't think it's fixable without special casing both, since you aren't in control of the UI there. Easiest solution would probably be if we're blacklisting it.

**Comment by garantiertnicht** [comment] 2016-11-25 18:59
@Ellpeck My setup is the same science a couple of days, there was even a server restart in between, so the size changing seems not to affect it.

**Comment by Ellpeck** [comment] 2016-11-25 19:00
Huh, I guess. Little bit of a crappy solution though :v
What exactly is the problem here? I'm presuming you're pre-defining the amount of slots in the Crafting Station once opening the container, and then it changes resulting in exceptions? 
Isn't there a way to re-init the side GUI once the container changes? Maybe via the neighborChanged() method? I don't know how your setup works, but that's the first thing I thought of.

**Comment by Ellpeck** [comment] 2016-11-25 19:01
Although, I just realized, I might not actually be marking the Item Interface dirty or anything once it changes :v

**Comment by garantiertnicht** [comment] 2016-11-26 11:07
Ok, after a bit of testing on my side: The resize seems to happen without problems. But, if you shift-click a block into your Item system when there's a small amount of that item in the system already, it gets voided.

To Reproduce:
* Make an Actually Addition Laser Network.
* Grab one Stack of any odd item.
* Place one of the items in the Actually Additions Network.
* Shift-Click the Items from one of the Crafting Station Slots into your system. They get voided.

**Comment by bonii-xx** [comment] 2016-11-26 14:13
I don't really have the time to look into this currently, and since it's a very specific situation it's also not very high priority. Maybe we can find a small quick fix for the next release.

**Comment by dshadowwolf** [comment] 2016-12-10 03:51
Seeing a related issue, will attach screenshots when I have some. I keep forgetting to take them when I run into these issues. Basically... Inventory from the chests/Item Laser network overflow and take over the "user inventory" section of the GUI, then remain until another non-player inventory is opened. I do not know if this can be used for item dupe, will test.

 Solution, for now, appaears to be to not place an Item Interface next to a Crafting Station.

**Comment by KnightMiner** [comment] 2019-03-28 22:57
I'm going to close this issue as the blacklist should be sufficient to prevent this behavior.

**Closed by KnightMiner** 2019-03-28 22:57 UTC
Labels: 3rd party mod interaction
