### ISSUE TITLE
Nether tick crash

### ISSUE THREAD

**Issue by SamuraiShogun1102** [SlimeKnights/TinkersConstruct#4033] opened 2020-02-02 17:48 UTC
**Issue description:**

[crash-2020-02-02_09.39.39-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/4144825/crash-2020-02-02_09.39.39-client.txt)

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.13.0.171

It could be reproduced with only tinker's construct as well with other mods if you enter the nether and keep spamming the left click on mobs with a tinker's sword.

**Comment by KnightMiner** [comment] 2020-02-02 20:15
Duplicate of #3783. For more information, there is a crash with custom particles which none of the devs have managed to reproduce so far. Need more time to look into it mostly, which is hard as we are also trying to work on later version updates.

**Closed as completed by KnightMiner** 2020-02-02 20:15 UTC
Labels: Duplicate
