### ISSUE TITLE
game crashes when I open my inventory while wearing the plate helmet.

### ISSUE THREAD

**Issue by Spl1tSpark** [SlimeKnights/TinkersConstruct#4782] opened 2022-02-24 20:35 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

Mantle-1.18.1-1.8.31

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.1.46

### Describe your issue

I finally got enough cobalt to make my very own cobalt plate helmet! I crafted it, and then as soon as I clicked it into my helmet slot, my screen froze, cursor began to spin, and then it unfroze saying "saving world" then boom, desktop. no "Minecraft has crashed, error code ###" just the desktop. I can reload Minecraft and play my world just fine until I open my inventory, then it crashes. 

### Reproduced with only Tinkers' Construct?

No

### Other mods required

optifine 1.18.1 HD U H4

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-24 20:37
Duplicate of #4734 . Actually read through the pinned issues like you said you did. Remove optifine

**Closed as completed by ShinyPorygon** 2022-02-24 20:37 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18

**Comment by Spl1tSpark** [comment] 2022-02-24 20:40
> Duplicate of #4734 . Actually read through the pinned issues like you said you did. Remove optifine

i searched for helmet and armor but nothing like it came up. ill try it tho

**Comment by ShinyPorygon** [comment] 2022-02-24 20:40
Look at the 2nd and 3rd pinned issue.

**Comment by Spl1tSpark** [comment] 2022-02-24 20:43
oh geez i didnt even see that. sorry to bother you all
