### ISSUE TITLE
Currently my tinkers is crashing the pack in 1.16.5 and im wondering how to fix it

### ISSUE THREAD

**Issue by EeriShimi** [SlimeKnights/TinkersConstruct#4633] opened 2021-10-05 17:30 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

ok so basically tinkers is crashing and i want to know whats happening because its crashing my pack currently
[crash-2021-10-05_18.16.53-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/7287981/crash-2021-10-05_18.16.53-client.txt)

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment] 2021-10-05 17:33
Duplicate of #4631. Is it too much to ask that you take 5 seconds to look at the pinned issues?

**Closed as completed by KnightMiner** 2021-10-05 17:33 UTC
Labels: Duplicate, 1.16
