### ISSUE TITLE
Seared drain output fails if smeltery is deconstructed while the drain is outputting

### ISSUE THREAD

**Issue by luckyu19** [SlimeKnights/TinkersConstruct#4619] opened 2021-09-12 14:48 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

1.16.5-1.6.123

### Tinkers' Construct Version

1.16.5-3.1.2.265

### Describe your issue

Steps to reproduce:
1. Get fluid out of the smeltery.
2. While the fluid is flowing out of the smeltery, break the smeltery.
3. Rebuild the smeltery. The output function will fail (input will still works).
4. Replacing the seared drain will fix the issue.

Not sure if it can be/should be fixed.
Doesn't happen with chute or the input function. 

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by StaticPH** [comment] 2021-09-13 00:33
If I understand correctly, you're breaking the smeltery controller. If you are, then this behavior makes sense, as the smeltery fluid data resides in the smeltery controller. If the controller is broken, the drain clearly has no way to continue pouring fluid out, because there simply isn't any.
Now, that's assuming that you were breaking the smeltery controller specifically, or some smeltery block on the same level as or below the drain. I don't believe that breaking a smeltery block _above_ the drain should have any effect upon the drain, though.

**Comment by luckyu19** [comment] 2021-09-13 07:41
> If I understand correctly, you're breaking the smeltery controller. If you are, then this behavior makes sense, as the smeltery fluid data resides in the smeltery controller. If the controller is broken, the drain clearly has no way to continue pouring fluid out, because there simply isn't any.
> Now, that's assuming that you were breaking the smeltery controller specifically, or some smeltery block on the same level as or below the drain. I don't believe that breaking a smeltery block _above_ the drain should have any effect upon the drain, though.

I tested it by breaking one of the seared stones at the level of smeltery controller.

**Comment by KnightMiner** [comment] 2021-09-18 19:00
@StaticPH I think you misunderstood the issue. Seems there is a problem when the smeltery rebuilds, it does not trigger block updates from the drain, which prevents the faucet from clearing its cache, so the faucet believes there is no tank. Easy enough fix luckily.

**Comment by StaticPH** [comment] 2021-09-18 23:10
Ah. I had wondered why they'd been unsure if the behavior was intended, but I think I understand now. Communication is hard. Personally, I'm of the opinion that pouring (from faucets, specifically) should not resume when the smeltery multiblock reforms after being broken (only after being added to, which I think I remember already being the case). That might just be me though.
In any case, am I to assume this issue can be closed then?

**Comment by KnightMiner** [comment] 2021-09-19 01:00
I think you are still misunderstanding the issue. The problem is not that the faucet does not resume pouring. The problem is the faucet *cannot* pour after breaking the smeltery. Interacting with the faucet does nothing after breaking the structure. So no, this cannot be closed yet, as it was a bug which is not in a released build yet.

**Comment by KnightMiner** [comment] 2021-10-06 04:57
Fixed in 3.1.3.271

**Closed as completed by KnightMiner** 2021-10-06 04:57 UTC
Labels: Bug, Resolved, 1.16
