### ISSUE TITLE
Slimelytra has no upgrade/ability slots.

### ISSUE THREAD

**Issue by Darkorg69** [SlimeKnights/TinkersConstruct#4673] opened 2021-12-09 22:33 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.19

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.0.308

### Describe your issue

I poured enderslime into casting basin, slimelytra works but has 0 upgrade slots and 0 ability slots, while Tinker's Encyclopedia states that it has 5 upgrades and 1 ability slot. 

### Crash Report

Game doesn't crash.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Better Materials
Better Punching
PamHC2 - Crops and Trees and Food module
Serene Seasons
Tough as Nails
Thermal Expansion
Thermal Foundation 
Pipez

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment] 2021-12-09 22:34
Ah, this one took awhile to get to Github. It was reported on Discord and no one made an issue report.

Already fixed by 5869854, will be in the next alpha which is planned soon.

----

For the record, if this were not a known issue, I would have told you to test with fewer mods, as bugs like this one could easily be caused by conflicts. Always test with just Tinkers' Construct and Mantle. Other Mods Required should never get beyond 3 mods

**Comment by Darkorg69** [comment] 2021-12-09 22:37
Okay, thanks for the fast reply, waiting for the next update!

**Comment by KnightMiner** [comment] 2021-12-09 22:42
For now, feel free to cheat slimesuit items out of JEI and delete the crafted ones. The ones in JEI have the correct slot numbers. Alternatively, the `/tconstruct slots` command would let you restore the proper number of slots.

**Comment by Darkorg69** [comment] 2021-12-10 00:16
Oh okay, thanks! I didn't know about these ones. Can the Slimelytra be made to be placeable in the Back Curios Slot?

**Comment by KnightMiner** [comment] 2021-12-10 03:56
I have no plans for that. It is armor, not a curio. I don't believe in giving the player free abilities, Tinkers is designed around you making choices.

you can apply modifiers to elytra to make it have some extra defense.

**Comment by KnightMiner** [comment] 2021-12-13 07:14
Fixed in 3.3.1.316

**Closed as completed by KnightMiner** 2021-12-13 07:14 UTC
Labels: Bug, Resolved, 1.16, Confirmed
