### ISSUE TITLE
Atlauncher Mech and Magic

### ISSUE THREAD

**Issue by vicoden** [SlimeKnights/TinkersConstruct#3430] opened 2018-03-23 23:44 UTC
1.12 newest version of both. Mod installs great and all works well. Built a smeltery and it works no issues. Built my first steel hammer and when I try to pull it from the tool forge the client crashes. Server side is fine.

**Comment by SweetSugarSugar** [comment] 2018-03-23 23:47
There is no "newest" version.  Please give a specific version of Tinkers' Construct.  Crash log?

**Comment by vicoden** [comment] 2018-03-24 00:01
Tconstruct version TConstruct-1.12.2-2.9.1.65
Mech and magic version 2.0.6
Have attached crash report
[crash-2018-03-23_19.56.10-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1843860/crash-2018-03-23_19.56.10-client.txt)

thanks!

**Comment by KnightMiner** [comment] 2018-03-24 01:52
Duplicate of #3405, update crafttweaker

**Closed by KnightMiner** 2018-03-24 01:52 UTC

**Comment by vicoden** [comment] 2018-03-24 02:16
That did it! Had version 4.1.5 and upgraded to version 4.1.6.

Thanks so much!
