### ISSUE TITLE
Scythe 3x3 harvest

### ISSUE THREAD

**Issue by PapiDimmi** [SlimeKnights/TinkersConstruct#2834] opened 2017-04-08 20:47 UTC
Right-click functionality for the scythe would be nice.

One of the mods (I don’t know which one, exactly) in the modpack that I’m playing allows me to right-click a fully grown crop to harvest it without having to break and replant it. If you do that with a scythe in your hand, it doesn’t do it in a 3x3 area; you have to actually break and replace the crops, which is pretty annoying.

**Comment by ArukaAlter** [comment] 2017-04-08 20:52
It works if you right click again, tested.

**Comment by PapiDimmi** [comment] 2017-04-08 20:53
What do you mean by “again”?

I just made a scythe and right-clicked a crop, but it didn’t harvest it in a 3x3 area.

**Comment by ArukaAlter** [comment] 2017-04-08 20:56
Hold right click a little.

**Comment by PapiDimmi** [comment] 2017-04-08 21:05
Ohhh. That’s annoying. You can’t just walk out in the field and spam right-click, since you have to look at the same crop and hold right-click for a second.

I hope this isn’t the intended behaviour of the scythe.

**Comment by KnightMiner** [comment] 2017-04-09 00:29
The scythe uses the vanilla took right click, if the blocks right click behavior acts before tools, that is technically the blocks fault, nothing we can do.

Try and find out which mod adds that feature, as I recall scythes worked with EnderCore's crop right click.

**Comment by bookerthegeek** [comment] 2017-04-09 01:51
@PapiDimmi this is not a TC mod issue, but a you issue. You are having what is called a criss mod issue. And not even really an issue as all mods that i know if that add right click harvesting offer a config to turn it off.

So, go find out what mod it is that adds it and ask them.

**Comment by PapiDimmi** [comment] 2017-04-09 07:29
Yeah, it’s probably EnderCore, since I do use that mod.

**Comment by KnightMiner** [comment] 2017-08-06 03:54
Since this is caused by another mod adding a right click action that cancels ours, not much we can do nor is it an issue on our side, so I'm closing this issue

**Closed by KnightMiner** 2017-08-06 03:54 UTC
