### ISSUE TITLE
No support for Mekanism Ores?  (1.11.2)

### ISSUE THREAD

**Issue by Lachesis580** [SlimeKnights/TinkersConstruct#3023] opened 2017-07-21 00:38 UTC
Hi has TinkersConstruct no support for Mekanism ores? 
The smeltery don't smelt tin,copper ect.

Minecraft version: 1.11.2
Forge: 13.20.1.2414
TinkerC: 2.7.1.34
Mekanism: 9.3.2.309

**Comment by KnightMiner** [comment] 2017-07-21 00:43
Duplicate of #2970. This is no longer an issue in 1.12 due to the rework of how integration is handled.

**Closed by KnightMiner** 2017-07-21 00:43 UTC

**Comment by Lachesis580** [comment] 2017-07-21 00:56
so 1.11.2 won't get this fix im right? thought 1.11.2 still get support since the last update is only few days old. So i have to use commands.

**Comment by KnightMiner** [comment] 2017-07-21 01:40
Yeah, no more 1.11 builds will be coming. One option you have is installing another mod that adds those materials, then the mekenism ones will function properly. If you don't want a full content mod there are mods that add just metals.
