### ISSUE TITLE
smeltery visual bug with seared glass

### ISSUE THREAD

**Issue by gamerpudding** [SlimeKnights/TinkersConstruct#3978] opened 2019-11-03 18:54 UTC
my smeltery is 3x3 on the inside and 10 blocks down. the seared glass works at 8 blocks deep but if you look lower then that the fluids disappear but the items/fluids are still in the smeltery and the smeltery still works.

version; stoneblock 2 (1.16.1) 
minecraft version: (1.12.2)
forge version:(14.23.5.2846)
Tinkers Construct:(2.12.0.157)

**Comment by KnightMiner** [comment] 2019-11-03 19:16
Screenshot showing your issue? It explains visual bugs a lot better than words.

Also, fix your versions, you entirely missed Tinkers Construct and there is no Tinkers Construct for 1.14.4

**Comment by gamerpudding** [comment] 2019-11-03 23:39
Here are multiple pictures of the smeltery from different angles

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Van: KnightMiner <notifications@github.com>
Verzonden: Sunday, November 3, 2019 8:16:47 PM
Aan: SlimeKnights/TinkersConstruct <TinkersConstruct@noreply.github.com>
CC: gamerpudding <jarno-hoeckman@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [SlimeKnights/TinkersConstruct] smeltery visual bug with seared glass (#3978)


Screenshot showing your issue? It explains visual bugs a lot better than words.

**Comment by KnightMiner** [comment] 2019-11-04 00:07
Did you attach the screenshots to your email? That does not show up on Github

**Comment by gamerpudding** [comment] 2019-11-04 13:51
The screenshots where attached to the mail that I wrote back to you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Van: KnightMiner <notifications@github.com>
Verzonden: Monday, November 4, 2019 1:08:03 AM
Aan: SlimeKnights/TinkersConstruct <TinkersConstruct@noreply.github.com>
CC: gamerpudding <jarno-hoeckman@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [SlimeKnights/TinkersConstruct] smeltery visual bug with seared glass (#3978)


Did you attach the screenshots to your email? That does not show up on Github

**Comment by KnightMiner** [comment] 2019-11-05 01:07
Yes, those do not show up on Github, I have no way to view them. Upload them to a site such as imgur and link them here.

**Comment by gamerpudding** [comment] 2019-11-05 14:12
![2019-11-04_00 35 30](https://user-images.githubusercontent.com/57328109/68214848-7eff6480-ffde-11e9-97da-67e0d6000155.png)
![2019-11-04_00 33 37](https://user-images.githubusercontent.com/57328109/68214852-7f97fb00-ffde-11e9-91da-b44fa06d5d0c.png)
![2019-11-04_00 33 23](https://user-images.githubusercontent.com/57328109/68214854-7f97fb00-ffde-11e9-941b-cdf5cfa2711a.png)
![2019-11-04_00 33 09](https://user-images.githubusercontent.com/57328109/68214855-7f97fb00-ffde-11e9-84e1-b89a386a54fe.png)
![2019-11-04_00 32 51](https://user-images.githubusercontent.com/57328109/68214856-7f97fb00-ffde-11e9-82e9-21b74bb6cd31.png)
![2019-11-04_00 32 39](https://user-images.githubusercontent.com/57328109/68214861-80309180-ffde-11e9-90d8-b39a5184ff83.png)
![2019-11-04_00 32 27](https://user-images.githubusercontent.com/57328109/68214862-80309180-ffde-11e9-8c04-78518a4278c0.png)

**Comment by gamerpudding** [comment] 2019-11-05 14:13
They should be visible on the site.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Van: KnightMiner <notifications@github.com>
Verzonden: Tuesday, November 5, 2019 2:07:27 AM
Aan: SlimeKnights/TinkersConstruct <TinkersConstruct@noreply.github.com>
CC: gamerpudding <jarno-hoeckman@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [SlimeKnights/TinkersConstruct] smeltery visual bug with seared glass (#3978)


Yes, those do not show up on Github, I have no way to view them. Upload them to a site such as imgur and link them here.

**Comment by bonii-xx** [comment] 2019-11-05 18:11
This might be related to how minecraft decides what to render. Does moving the smeltery controller lower/higher have an impact?

**Comment by gamerpudding** [comment] 2019-11-05 19:26
Moving it down worked. But it would be nice if they could fix it so I can put the controller back on top. Still thanks for the hint I didn’t thought of bringing the controller down

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Van: boni <notifications@github.com>
Verzonden: Tuesday, November 5, 2019 7:11:35 PM
Aan: SlimeKnights/TinkersConstruct <TinkersConstruct@noreply.github.com>
CC: gamerpudding <jarno-hoeckman@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [SlimeKnights/TinkersConstruct] smeltery visual bug with seared glass (#3978)


This might be related to how minecraft decides what to render. Does moving the smeltery controller lower/higher have an impact?

**Comment by bonii-xx** [comment] 2019-11-05 21:30
Minecraft only renders blocks that it deems "visible". Smeltery fluids are drawn by the controller. It has a pretty big area that counts as "visible", but it can't possibly cover everything.

**Comment by YaibaToKen** [comment] 2019-11-08 09:40
Any chance that area could be set dynamically to the Smeltery's current internal size? if so, that should fix this, no?

**Comment by bonii-xx** [comment] 2019-11-10 14:24
[It is.](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/smeltery/tileentity/TileSmeltery.java#L343) That doesn't mean minecraft renders infinite range though.

**Comment by YaibaToKen** [comment] 2019-11-10 16:36
I'd assume it would render the exact same range of blocks the player can see, but I honestly know nothing of MineCraft's render code.

**Comment by bonii-xx** [comment] 2019-11-10 16:52
[It does. See above.](https://github.com/SlimeKnights/TinkersConstruct/issues/3978#issuecomment-550029769)

**Comment by YaibaToKen** [comment] 2019-11-11 11:59
Wait but... if the controller attempts to render fluids contained anywhere inside the smeltery structure and Minecraft should render the full range a player can see in, what's stopping the fluids from rendering? I'm confused ^^'' And sorry for asking so many questions.

**Comment by bonii-xx** [comment] 2019-11-11 14:22
When minecraft decides that the smeltery (which is out of vision) should stop rendering (which causes the fluids to stop rendering), even though the controller - theoretically - has the same "rendering visibility" to minecraft as the whole smeltery structure.

**Comment by YaibaToKen** [comment] 2019-11-12 11:40
But... in the case described by this issue, isn't the smeltery in view? Therefore, shouldn't the fluids be rendering? As far as I can tell, his smeltery isn't particularly big.

**Comment by bonii-xx** [comment] 2019-11-13 12:54
smeltery = controller

**Comment by gamerpudding** [comment] 2019-11-13 21:29
I understand that but why is everything visible when I place the controller at the bottom and not when I place it on top, that’s what I find strange. Recap: controller on the bottom= everything visible / controller on top = visible to 8 blocks deep but when you look up then it loads the rest in and disappears again when you look back down.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Van: boni <notifications@github.com>
Verzonden: Wednesday, November 13, 2019 1:54:22 PM
Aan: SlimeKnights/TinkersConstruct <TinkersConstruct@noreply.github.com>
CC: gamerpudding <jarno-hoeckman@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [SlimeKnights/TinkersConstruct] smeltery visual bug with seared glass (#3978)


smeltery = controller

**Comment by esotericist** [comment] 2019-11-22 22:56
My previous experiments with minecraft's notion of what's in view suggest it always tended to anchor the bottom of the render volume to the 'key' part of the total volume. See: anything involving vanilla armor stands when the base of the armor stand isn't in view.

I know tinkers' construct attempts to compensate for that (based on above link to the source code), but it wouldn't surprise me to learn that with a sufficiently tall smeltery that had the controller on the top layer, it would be attempting to render the fluids at the bottom even while you were looking over the top of the smeltery structure (such that the controller was just barely below your line of vision)

**Comment by esotericist** [comment] 2019-11-22 23:29
On whimsy, I attempted to reproduce this using TConstruct-1.12.2-2.13.0.171.jar and I cannot actually seem to reproduce the problem.

@gamerpudding what version are you running? Your opening post still claims minecraft 1.14 (which is obviously wrong) and doesn't mention what version of tinkers' construct you have, even though knightminer requested you provide that information.

screenshots:
![2019-11-22_15 38 28](https://user-images.githubusercontent.com/1569754/69467723-2ea63780-0d3e-11ea-8ec5-61aa547614f7.png)

![2019-11-22_15 38 39](https://user-images.githubusercontent.com/1569754/69467734-3665dc00-0d3e-11ea-95b1-af3fe27b0a19.png)


* edit to correct which dev requested versions, because apparently I can forget names when they scroll off the screen.

**Comment by bonii-xx** [comment] 2019-12-01 16:01
I'm going to close this, since the issue seems to have been worked around at least, and is not really solvable on our side anyway.

**Closed as completed by bonii-xx** 2019-12-01 16:01 UTC
