### ISSUE TITLE
conflicts with JER and AOA3

### ISSUE THREAD

**Issue by Dancing-Github** [SlimeKnights/TinkersConstruct#4571] opened 2021-07-16 17:21 UTC
the version 3.0.9 works perfectly ，the JER can display the drop information of mobs  in AOA3. However , as  I  update  tic 3 to 3.1.0version , the information cannot be shown .

**Comment by KnightMiner** [comment] 2021-07-16 17:22
Duplicate of #4570.

**Closed as completed by KnightMiner** 2021-07-16 17:22 UTC
Labels: Duplicate, 1.16
