### ISSUE TITLE
Clicking on a fluid in a Smeltery to move its position throws ConcurrentModificationException

### ISSUE THREAD

**Issue by Mg138** [SlimeKnights/TinkersConstruct#4479] opened 2021-05-19 09:27 UTC
**Description**
When clicking on a fluid in a Smeltery (image example below)
![image](https://user-images.githubusercontent.com/33348966/118788639-905d4880-b8c6-11eb-9974-2868d111ccc6.png)
the game crashes with a ConcurrentModificationException.

Crash report: https://paste.ee/p/NZp5u

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.144

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
 No, it's not covered on the roadmap.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Not confirmed. Though the stack trace seems like so.

**Comment by ShinyPorygon** [comment] 2021-05-19 09:28
Duplicate of #4316

**Comment by Mg138** [comment] 2021-05-19 09:42
Confirmed to be an issue with Optifine

**Closed** 2021-05-19 09:42 UTC
Labels: 1.16, Bug, Unreviewed
