### ISSUE TITLE
Issue with all oreberries [OreDict bug]

### ISSUE THREAD

**Issue by Nikslg** [SlimeKnights/TinkersConstruct#1820] opened 2015-11-25 20:48 UTC
I am pretty sure it was already stated here once but got no answer and was ignored.
Could you PLEASE remove "ore:nugget" from all berries?
It doesn't make no sense at all and what's more it's not even used in any Tinkers construct recipe!
It also do mess other mods.
Example:
TinkersConstruct Copper Ingot:
9 Copper Nuggets
IndustrialCraft,Forestry,Galacticraft,ThermalExpansion
9 Copper OreBerries (AND ONLY THEN) OR Nuggets

Not just that.
Aluminum/Aluminium even got it backwards.
ID for Nugget comes after oreberry. And because of that... Some mods take Aluminum/aluminium oreberries as nuggets.
Example: WitchingGadgets (Thaumcraft mod). That appears to happen only with Aluminum, just because Thaumcraft already had nuggets to begin with.
But, Making Iron wand using Iron Oreberries? Isn't its... kinda too much?

**Comment by Zsashas** [comment] 2015-11-29 03:36
I actually made a script to deal with this very issue, as it has been in the mod for too long now.

It also removes the essence oredict from gold berries and puts it on essence berries where it belongs. Again, long-standing issue.

I can't recall whether this needs ModTweaker, or just MineTweaker, I have both anyway.

<ore:nuggetIron>.remove(<TConstruct:oreBerries:0>);
<ore:nuggetGold>.remove(<TConstruct:oreBerries:1>);
<ore:nuggetCopper>.remove(<TConstruct:oreBerries:2>);
<ore:nuggetTin>.remove(<TConstruct:oreBerries:3>);
<ore:nuggetAluminum>.remove(<TConstruct:oreBerries:4>);
<ore:nuggetAluminium>.remove(<TConstruct:oreBerries:4>);

<ore:oreberryEssence>.remove(<TConstruct:oreBerries:1>);
<ore:oreberryEssence>.add(<TConstruct:oreBerries:5>);

**Comment by Nikslg** [comment] 2015-11-29 16:07
I still dont understand why boni wont fix that either...
But fix you gave us is outdated.
"ore:" wont work anymore

oreDict.nuggetIron.remove(<TConstruct:oreBerries:0>);
oreDict.nuggetGold.remove(<TConstruct:oreBerries:1>);
oreDict.nuggetCopper.remove(<TConstruct:oreBerries:2>);
oreDict.nuggetTin.remove(<TConstruct:oreBerries:3>);
oreDict.nuggetAluminium.remove(<TConstruct:oreBerries:4>);
oreDict.nuggetAluminum.remove(<TConstruct:oreBerries:4>);

This worked for vanilla recipes but didn't fix recipe of 2 mods.

**Comment by bonii-xx** [comment] 2015-11-29 16:49
Happy? :P

**Comment by Nikslg** [comment] 2015-11-29 17:13
Kinda, i guess.
I just was wondering why you just cant fix it in current versions.
My friend posted similar thing like this issue about 2 months ago.

**Comment by bonii-xx** [comment] 2015-11-29 17:15
What's the point of fixing something that's never getting released? Just time that could've been used better.

**Comment by Nikslg** [comment] 2015-11-29 17:18
never getting released? what do you mean?

**Comment by Zsashas** [comment] 2015-11-29 17:22
The script I posted works fine for removing the berries from the nugget ore dictionaries. I'm using it right now.

**Comment by Nikslg** [comment] 2015-11-29 17:26
may i ask for a version of minetweaker and mod tweaker you are using?
Because it gives me:
"; expected" while there are no ";" missing

**Comment by Zsashas** [comment] 2015-11-29 17:27
3.0.10B

**Comment by Nikslg** [comment] 2015-11-29 17:44
well your mod tweaker is outdated, yet minetweaker is the last one.
But this still says the same error.
"; expected"

**Comment by Zsashas** [comment] 2015-11-29 17:46
Are you sure you copied it correctly?

<ore:nuggetIron>.remove(<TConstruct:oreBerries:0>);
<ore:nuggetGold>.remove(<TConstruct:oreBerries:1>);
<ore:nuggetCopper>.remove(<TConstruct:oreBerries:2>);
<ore:nuggetTin>.remove(<TConstruct:oreBerries:3>);
<ore:nuggetAluminum>.remove(<TConstruct:oreBerries:4>);
<ore:nuggetAluminium>.remove(<TConstruct:oreBerries:4>);

<ore:oreberryEssence>.remove(<TConstruct:oreBerries:1>);
<ore:oreberryEssence>.add(<TConstruct:oreBerries:5>);

**Comment by Zsashas** [comment] 2015-11-29 17:47
Oh FFS I just noticed it isn't pasting all the code properly...hang on.

**Comment by Nikslg** [comment] 2015-11-29 18:31
this sure works but it doesn't fix some recipes
Thaumcraft still giving berries as result of smelting. Because Script loaded right after loading world and some extra aspects (like Bonus from smelting for infernal furnace and thaunomicon entry) wont change now.

**Comment by Zsashas** [comment] 2015-11-29 18:32
Check that each berry was actually removed from the nugget dictionary, by checking the tooltips.

**Comment by 61352151511** [comment] 2015-11-29 18:48
By never getting released he means he is done releasing versions for 1.7.10. I'm assuming the next version will be for 1.8.8 and that will be the only supported version.

**Comment by Nikslg** [comment] 2015-11-29 18:49
I already did.
They are removed.
But still appear in recipes.
That's why we asked to fix it 2 months ago. Before final update =_=
But it was ignored here

**Comment by Zsashas** [comment] 2015-11-29 18:53
Have you tried completely restarting the instance since adding the script?

**Comment by Nikslg** [comment] 2015-11-29 18:57
Yes, i did twice.
And during game too used /mt reload
Try it yourself.
Get Thaumcraft 4 + Witching Gadgets (requires TravellersGear).
Get yourself all researches, build infernal furnace, and drop some aluminum/aluminium ores into that furnace, get yourself some berries... 
(sigh)
There is no way to remove it. ModTweaker/MineTweaker dont have regular Infernal Furnace bonus output change.

**Comment by bonii-xx** [comment] 2015-11-29 19:04
We wont remove any etablished oredicts. That kills backwards compatibility.

**Comment by Nikslg** [comment] 2015-11-29 19:08
But Tinkers Construct doesnt use berries as Nuggets...
What the point of giving them ore:nugget?

**Comment by bonii-xx** [comment] 2015-11-29 19:09
I never said anything for it. I just said why it wont be removed. :P

**Comment by Zsashas** [comment] 2015-11-29 19:10
I have tested this and it works for me, I have no idea why it isn't working for you.
![2015-11-29_11 09 43](https://cloud.githubusercontent.com/assets/6917535/11459358/c726804e-9689-11e5-8093-13fd2baaa50d.png)

**Comment by Robijnvogel** [comment] 2015-11-29 19:18
See #1756 :/
I admit that I was a little bit pissed that day, because I had elaborated on the issue quite, well... elaborately and then I lost all the text because of a bad connection.

By the way, I have been working on this issue together with Nikslg for quite some time now and have gotten the same results as he did.

And Boni, those wrong oredicts were never a good idea to begin with. If it causes incompatibility with other mods, then that'll only forces those other mods to improve. It's a shame that this'll have to wait until MC 1.8 though.

**Comment by Robijnvogel** [comment] 2015-11-29 19:20
Zsashas, did you install TiC as well? That is kinda key in this issue.

**Comment by Zsashas** [comment] 2015-11-29 19:23
Yes, of course I have TiCon.

**Comment by Nikslg** [comment] 2015-11-29 19:47
![2015-11-29_22 41 36](https://cloud.githubusercontent.com/assets/15956980/11459597/0f9cc2d2-96eb-11e5-9eef-2eff2fdd38be.png)
![script](https://cloud.githubusercontent.com/assets/15956980/11459596/0f9c4636-96eb-11e5-8e4f-d5fb3311e956.png)

What do i do wrong?

**Comment by Zsashas** [comment] 2015-11-29 20:07
I honestly have no idea.

![image](https://cloud.githubusercontent.com/assets/6917535/11459707/b7de4ad8-9691-11e5-8a03-2a6d887b6565.png)

**Comment by Nikslg** [comment] 2015-11-29 20:08
What mods do you have?

**Comment by Zsashas** [comment] 2015-11-29 20:20
Quite a few, I'll try to make a list here...

**Comment by Nikslg** [comment] 2015-11-29 20:30
Btw, that aluminum in your screenshot is not from Tinkers Construct.
That's why you got it fixed.

**Comment by Zsashas** [comment] 2015-11-29 20:30
It cycles through the different nuggets.

**Comment by Nikslg** [comment] 2015-11-29 20:31
You still got different one as output. Look on my screenshot.
TiCon's Aluminium is lighter.

**Comment by Zsashas** [comment] 2015-11-29 20:32
But the point remains, mine outputs a nugget, not an oreberry.

**Comment by Robijnvogel** [comment] 2015-11-29 20:33
Is it really TiC aluminum nuggets that the infernal furnaces spit out?

If so, what are the item ID's of your TiC aluminum nugget and aluminum oreberry?
Because the order of these two matters. If for some reason their ID order is swapped in your instance, this completely explains your results versus ours.

**Comment by Zsashas** [comment] 2015-11-29 20:33
Item IDs would be different for different instances, I don't see how that would make a different unless we were using the same base pack.

**Comment by Nikslg** [comment] 2015-11-29 20:35
If you will use just those 5 mods, you will get same output as we have.

**Comment by Robijnvogel** [comment] 2015-11-29 20:35
Doesn't matter, it's not a TiC nugget, so that conditional question of mine does not apply.

**Comment by Zsashas** [comment] 2015-11-29 20:36
If the oreberry is being removed properly from the oreDict for nuggets, then it shouldn't matter what order or other mods or whatever, it should never be producing oreberries instead of nuggets.

**Comment by Nikslg** [comment] 2015-11-29 20:37
Believe me, it wont change. just try.

**Comment by Robijnvogel** [comment] 2015-11-29 20:37
Would you just test it without any other mods that might add aluminum nuggets please?

**Comment by Zsashas** [comment] 2015-11-29 20:37
Impossible to test without Thaumcraft, which has it's own nuggets.

**Comment by Robijnvogel** [comment] 2015-11-29 20:38
Thaumcraft doesn't even have Aluminum. Not even with TiC installed.

**Comment by Zsashas** [comment] 2015-11-29 20:39
I believe that at least part of the problem is that Witching Gadgets uses Aluminium, and not Aluminum.

**Comment by Nikslg** [comment] 2015-11-29 20:40
Witching Gadgets is the one that adds Aluminium into Thaumcraft.
And also as you know, aluminum nuggets/berries got both ore:nuggetaluminum and ore:nuggetaluminium
But since Berries goes before Nuggets in the item list, it adds those first into recipe.

**Comment by Robijnvogel** [comment] 2015-11-29 20:42
Everyone should use both, because no-one is going to agree on just one name.

What Nikslg means here is that TiC Aluminum Oreberries have the lowest item ID, then TiC Aluminum Nuggets and then Witching Gadgets Aluminium Nuggets

**Comment by Zsashas** [comment] 2015-11-29 20:42
In my instance, oreberries have NO uses other than smelting into nuggets with this script applied. Extensively tested this. Something is interfering in your instances.

**Comment by Robijnvogel** [comment] 2015-11-29 20:43
Dude... What mod are the aluminum or aluminium nuggets from, that you get as bonus from the infernal furnaces?

**Comment by Nikslg** [comment] 2015-11-29 20:44
That's because you got another mod with aluminum nuggets and they have lower item ID than TiCon's nuggets

**Comment by Zsashas** [comment] 2015-11-29 20:44
I'm loading my instance back up right now. I had to temporarily close it.

**Comment by Zsashas** [comment] 2015-11-29 20:53
I mis-remembered which mods added which ores. That's what I get for not having MC open at the time.

Immersive Engineering: Aluminium Nugget 4575:23
Mariculture: Aluminium Nugget 6257:34
TiCon: Aluminum Oreberry 5539:4
TiCon: Aluminum Nugget 5542:22

Infernal Furnace and Infernal Blast Furnace both output IE Nuggets.

**Comment by Nikslg** [comment] 2015-11-29 20:54
So yea, Immersive Engineering is a fix for this issue.

**Comment by Zsashas** [comment] 2015-11-29 20:55
Probably any mod that added Aluminum/ium nuggets of it's own would fix this. But I still don't understand why in your instance, it is still outputting oreberries when they are removed from the ore dictionary. They should be invalid after that.

**Comment by Nikslg** [comment] 2015-11-29 20:55
Dude, just try without those 2 mods. You will get the same output as we are.

**Comment by Zsashas** [comment] 2015-11-29 20:56
It's not the fact that you're getting the output, it's the WHY that confuses me.

**Comment by Nikslg** [comment] 2015-11-29 20:58
TiCon: Aluminum Oreberry 5539:4
TiCon: Aluminum Nugget 5542:22
just as you said.
OreBerry got both Nugget's and Oreberry's OreDict.
Witching Gadgets searches for the first Aluminum nugget oredictionary, and it finds Aluminum Oreberry.

**Comment by Robijnvogel** [comment] 2015-11-29 20:59
*A workaround.
and Mariculture should do as well.

But, without either of those, the problem still happens, unless you prove otherwise.

Zsashas, I think that the Infernal furnace bonuses get determined on game startup or at least somewhere before Minetweaker scripts are loaded. After this, whenever MineTweaker scripts are (re)loaded, the infernal furnaces do not re-evaluate whether the bonus outputs of their smelting recipes still match the original oredictionary, which means those bonuses stay the same.

**Comment by Robijnvogel** [comment] 2015-11-29 21:00
But, Nikslg, after you have removed the TiCon Aluminum Oreberry from the nugget oredictionary, does it still say that it is in that oredictionary in NEI?

**Comment by Zsashas** [comment] 2015-11-29 21:01
So the problem is the fact that the oreberries are set as nuggets in the first place. Back to you, Boni.


NEI shows it as no longer being in that oreDict entry, as it should.

**Comment by Robijnvogel** [comment] 2015-11-29 21:02
I just want to make sure that that counts for us as well, thank you :)

**Comment by bonii-xx** [comment] 2015-11-29 21:06
>NEI shows it as no longer being in that oreDict entry, as it should.
Then the mod in question uses the oredict incorrectly.

**Comment by Zsashas** [comment] 2015-11-29 21:08
The problem is that Witching Gadgets reads the ore dictionary before MineTweaker can modify it. If Oreberries were set correctly to begin with, this wouldn't be an issue.

**Comment by Robijnvogel** [comment] 2015-11-29 21:14
Original issue:
Oreberries are oredicted as nuggets, which causes other mods to created crafting recipes from oreberries to ingots (Thermal Expansion) and other weird behaviour like the infernal furnaces (Witching Gadgets)
Some of these, actually, most of these, can be fixed by using Minetweaker, but this __should not__ be needed, as the issue should not exist to begin with.
The rest can probably be fixed by adding other mods that have little to do with the issue. Again, this __should not__ be needed.

As I see it now, there are two ways to "fix" this:
1. Remove oreberries from nugget dictionaries. Which would be the most logical way to do this, but Boni does not want to do this because of compatibility issues.
2. Somehow switch the Item ID position of the TiC oreberries and nuggets. This is an ugly fix and only covers up the issue, but it should work. This will only fix the Witching Gadgets issue. For the others Minetweaker is still needed.

**Comment by Zsashas** [comment] 2015-11-29 21:15
Honestly, I fail to see what compatibility issues would arise from fixing this.

**Comment by Robijnvogel** [comment] 2015-11-29 21:22
I try to respect Boni's point of view. As the dev, he probably has some insight that we do not have and may be hesitant to change code that was implemented to fix some kind of compatibility.
My theory: the nugget oredict of the berries has something to  do with assigning the smeltery molten metal value.

Or he may be cautious, because he is not the original author of TiC and may not have written that piece of code by himself, so changing it may have unforeseen implications.

**Comment by BluSunrize** [comment] 2015-11-29 21:24
Protip: The OreDictionary is not supposed to be modified after load. So yeah, I don't see anyone going through the effort of fixing this, especially since Minetweaker only gave us a proper reload event in v3.0.10b.

**Comment by Zsashas** [comment] 2015-11-29 21:30
So it seems that there are only two ways to fix this:
1: Add another entire mod that has Aluminum/ium nuggets
2: Boni removes oreberries from the oredictionary.

**Comment by BluSunrize** [comment] 2015-11-29 21:31
And 2 is a stupid solution since that is literally what they are designed to be. >_>

**Comment by Zsashas** [comment] 2015-11-29 21:34
Not really. The oreberries are not nuggets themselves, they are an intermediate step.

**Comment by Robijnvogel** [comment] 2015-11-29 21:35
Since oreberries should be smelted into nuggets, they are definitely not the same.

**Comment by BluSunrize** [comment] 2015-11-29 21:37
Then I guess you should ask boni to change the system. But don't blame WG for usinh the OreDictionary on postInit, like it's supposed to.

**Comment by Robijnvogel** [comment] 2015-11-29 21:49
I guess they (at WG's headquarters) could consider using the same method other mods use for their machine oredictionary recipes. 
But I have heard that removing items from oredictionary entries using MineTweaker is not recommended from various sides now, so they should do with that suggestion whatever they like.

Besides if they would want to fix this, I think that Thaumcraft 4 does not support it. Nikslg and I have taken a quick look at the TC4 API and it does not seem to have a method to _remove_ bonus outputs from the infernal furnace. But that is just a hunch.

**Comment by BluSunrize** [comment] 2015-11-29 21:57
We (the royal we since I write WG alone) at WG headquarters wrote that code over a year ago.
Seriously. It's such a minor bug. Why bother.
I've moved on to IE, I do as little as possible on WG, and fixing thsi by the wway, is nigh impossible.
Thaucmraft doesn't allow me to just change secondary outputs willy nilly. So either you find a way to keep TCon from registering it in the first place or you deal with it, because I'm not doing my recipes on world load, because Minetweaker is a special snowflake.

**Comment by Zsashas** [comment] 2015-11-29 21:59
Once again, looks like it's back to you, Boni.

**Comment by BluSunrize** [comment] 2015-11-29 22:00
No it's just back to: Deal with it. Tinkers 1.7 is done. Witching Gadgets is done. Live with the minor issue that this is and just be happy that compat exists at all.

**Comment by Robijnvogel** [comment] 2015-11-29 22:19
I am still looking at Boni for a final verdict on the matter, well a temporary verdict, because I am afraid that he is going to definitely close this issue if he has to make up his mind right now.

**Comment by bonii-xx** [comment] 2015-11-30 18:00
Oreberries are oredicted as nuggets. The one broken oredict entry is a bug but wont be fixed as stated above. Personally I couldn't care less if some other mod gives back oreberries instead of nuggets as they're completely interchangeable.
The only reason I haven't closed this stuff is so you guys have a place to discuss your tweaking stuff to adjust the game to your needs. There newer was a question whether I'd change it.

**Comment by Nikslg** [comment] 2015-11-30 18:12
To be fair, i found only 2 fixes:
1st would be fix by your, you could just edit ID of nugget and berry. Swap them, fix recipes and that's kinda it. It would fix all problems that will EVER appear with it. WG takes first ore:nugget, and it happened to be oreberry... so it's kinda fail of TiC.
2nd would be another mod that got value lower than ones you did.
like that:
Immersive Engineering: Aluminium Nugget 4575:23
TiCon: Aluminum Oreberry 5539:4
TiCon: Aluminum Nugget 5542:22

**Comment by Zsashas** [comment] 2015-11-30 18:29
If they are meant to be interchangeable then why is there a smelting recipe to turn them into nuggets?

**Comment by Robijnvogel** [comment] 2015-11-30 19:04
Nikslg,
not really, both fixes would still require further tweaking with MineTweaker.

Zsashas,
Yup, the only way they were ever meant to be interchangeable is in the smeltery. Both 16mB. And that is inside-TiC functionality. 
The ore dictionary is meant for compatibility between mods, not for LOC reduction within a mod, which is still the only reason I can think of why oreberries got registered as nuggets.

If oreberries are the same as nuggets, then just be consistent about it and remove oreberries altogether. Just let oreberry bushes grow nuggets directly instead.

And that's probably it for tonight.

**Comment by Nikslg** [comment] 2015-12-13 02:51
Uhm... Sorry to revive this topic but.
I decided to test somethings.
Just to confirm that WG DID IT RIGHT. (though i dont understand why Aluminum cluster is blue but nevermind it)

i decided to add Immersive Engineering to modpack.
and at the same time i got Another Dust (or w/e it was called) too.

So i got Aluminum AND Aluminium cluster.
i got full stack of both.
Tossed (actually accidentally) AOBD Cluster into Infernal Furnace. And i got:
TiC Ingots and oreberries.
WHILE
When i tossed WG Clusters i got Ingots and Nuggets from Immersive Engineering...
Oh and by the way i have 3 types of alum nuggets, yet 3rd type never shows somehow...
EDIT:
Now i decided to manually put AlumiNUM into WG
and AlumiNIUM into AOBD.
I wonder what will happen now
EDIT2:
well somehow they just want to split those mods between...
WG takes IE
While AOBD takes TiC
That even happened with pickaxe of the core.
And even after disabling oredict still giving clusters...

OKAY, CAN SOMEBODY REALLY EXPLAIN TO ME HOW DOES THIS SYSTEM WORK?
I have alternative Nuggets i want to use, how the **** can i set them as default ones?!

**Comment by BluSunrize** [comment] 2015-12-13 11:00
That's the other issue: There is no true consensus on British or US spelling.
Since the majority of the community is US bound, I (as do lots of other modders) feel that the OreDictionary should be written in US English.
HOWEVER, a certain mod developer who is a bit of a special snowflake (*cough*Gregtech*cough*) uses Aluminium as the OreDict name, the British (and German) spelling.
The result of that is, that Tinkers and Immersive register to both names in order to stay compatible with Greg.
Yes it's ugly but that's how it is. We can't help it.

And in the end, the point of the OreDictionary is that it's interchangeable, so who the fuck cares what nugget you get you can still use it for anything anyways.

**Comment by Robijnvogel** [comment] 2015-12-14 08:13
Because oreberries aren't nuggets. They grow on bushes. They are fruit. They should be smelted to nuggets or molten down to molten metal before they can be used in crafting.

But that is totally on TiC and we are probably not going to see this get fixed in any version before MC 1.8. I bet that keeping this issue alive is even making Boni consider postponing it to MC 1.9 if possible. :p

**Comment by Blue64** [comment] 2016-01-07 15:06
I always wondered why that extra i was there, I thought it was simply a typo and they refused to fix it lol I never knew it was actually spelled that way in Britain and Germany, which is awkward, because my dad knows a lot of German, and my British vocabulary is quite Colourful ```:P``` useful info up in here y'all, good work on hashing that out as much as y'all did.

As far as using alternative nuggets, MineTweaker works for tweaking that part too, you can simply add a furnace recipe for example that will cycle through the available types (after removing their native furnace output of course), or perhaps eyeball something similar to the Thermal Expansion Alloy Smelter. While this doesn't fix the problem with the Infernal Furnace output, it does at least offer a minor solution, although somewhat roundabout.

**Comment by Robijnvogel** [comment] 2016-02-13 11:38
Boni, I made a Fork that doesn't add the oreberries to nugget oredicts. Can I post a download link in this issue after I've tested it with a few mods and made sure that it doesn't cause problems?

**Comment by bonii-xx** [comment] 2016-02-13 17:07
Uh, I'm gonna say no just to keep possible complications later down the road away. Please handle in private.

**Comment by Robijnvogel** [comment] 2016-02-13 18:17
Oki

**Closed** 2016-03-01 16:06 UTC
Labels: wontfix

**Comment by Robijnvogel** [comment] 2016-03-20 15:04
Could [this ](http://pastebin.com/przmYTqN) be caused by my removal of the Oreberries from the Ore Dictionary? Or is this actually something in your code?
