### ISSUE TITLE
With Quark installed, pushing seared tanks with pistons sometimes causes tank to behave as if empty

### ISSUE THREAD

**Issue by TheDeviantCrafter** [SlimeKnights/TinkersConstruct#4375] opened 2021-04-18 19:23 UTC
**Issue description:**

Quark adds the ability to push tile entities with pistons. Pushing a seared tank sometimes causes the smeltery to think the tank is empty. The UI will show no lava, and it will refuse to melt items.

The tank will render as empty when the bug occurs. However, The One Probe will show the tank as full. If the tank is mined, the item will show lava in the tooltip.

Breaking and replacing the tank will fix the issue. No lava is ever lost.

**Replication steps:**

1. Install Quark and Tinkers
2. Build a valid smeltery
3. Fill the seared tank with lava
4. Use a sticky piston to pull the seared tank away, causing the multiblock to unform
5. Use a sticky piston to push the seared tank back, reforming the smeltery
6. About 75% of the time, the 

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.2
* Mantle: 1.6.92
* Tinkers Construct: 3.0.2.96
* Quark: r2.4.310

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

This bug requires Quark to be installed. Quark allows tile entities to be pushed using pistons.

**Comment by KnightMiner** [comment] 2021-04-18 19:28
Sounds like quark is missing one of the proper events on moving a tile entity so the TE knows its moved. There is a packet vanilla sends when a block is first placed in the world to write the original TE contents, if that packet is missing the tank's fluid will be invisible. You should be able to drain a bit and it will update the renderer.

All that to say, report this bug to quark, they are failing to send vanilla packets we need

**Comment by TheDeviantCrafter** [comment] 2021-04-18 21:21
The smeltery also doesn't recognize the lava within the tank. Is that caused by the same missing packet or is it a separate issue?

**Comment by KnightMiner** [comment] 2021-04-18 21:30
Thats probably caused by the structure NBT being out of sync. The controller does not believe the tank is part of the structure because you moved it illegally. Place another block to extend the structure. 

 I'm half inclined to just block all piston movement, but its nice to have when there is no smeltery involved.

**Comment by TheDeviantCrafter** [comment] 2021-04-18 22:10
I was using a block swapper to switch from molten blaze to lava and back on command. That use case seems useful enough to be worth persevering. Pipes or fake players can probably do the same thing depending on the pack.

**Comment by KnightMiner** [comment] 2021-04-18 22:31
The problem is with how Quark places blocks. It does not place the tank there, it moves it. And the smeltery does not expect to be moved, so things get out of sync.

**Comment by KnightMiner** [comment] 2021-06-15 17:03
Does this still happen on the latest alpha? I changed some of the logic with how seared tanks sync their fluids

**Comment by KnightMiner** [comment] 2021-08-02 04:17
Closing as this is likely fixed

**Closed as completed by KnightMiner** 2021-08-02 04:17 UTC
Labels: Bug, Can't Fix, Mod interaction, 1.16
