### ISSUE TITLE
Crash on modded client, when trying to put a tool in the tool station

### ISSUE THREAD

**Issue by Burgersim** [SlimeKnights/TinkersConstruct#3379] opened 2018-02-12 01:08 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.6.0.jar)
  SoundFixPatchingLoader (AmbientSounds+v2.2.2+mc1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Extra Alchemy ASM (extraalchemy-0.3.6.2-release.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  CreativePatchingLoader (CreativeCore+v1.9.16+mc1.12.2.jar)
  ItemPatchingLoader (ItemPhysic+Full+1.4.10+mc1.12.2.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 2/12/18 2:01 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at slimeknights.tconstruct.library.utils.ToolBuilder.tryModifyTool(ToolBuilder.java:183)
	at slimeknights.tconstruct.tools.common.inventory.ContainerToolStation.modifyTool(ContainerToolStation.java:275)
	at slimeknights.tconstruct.tools.common.inventory.ContainerToolStation.func_75130_a(ContainerToolStation.java:166)
	at slimeknights.tconstruct.tools.common.inventory.SlotToolStationIn.func_75218_e(SlotToolStationIn.java:32)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:71)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at slimeknights.mantle.inventory.ContainerMultiModule.func_184996_a(ContainerMultiModule.java:121)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_146286_b(GuiMultiModule.java:286)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at slimeknights.tconstruct.library.utils.ToolBuilder.tryModifyTool(ToolBuilder.java:183)
	at slimeknights.tconstruct.tools.common.inventory.ContainerToolStation.modifyTool(ContainerToolStation.java:275)
	at slimeknights.tconstruct.tools.common.inventory.ContainerToolStation.func_75130_a(ContainerToolStation.java:166)
	at slimeknights.tconstruct.tools.common.inventory.SlotToolStationIn.func_75218_e(SlotToolStationIn.java:32)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:71)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at slimeknights.mantle.inventory.ContainerMultiModule.func_184996_a(ContainerMultiModule.java:121)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_146286_b(GuiMultiModule.java:286)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: slimeknights.tconstruct.tools.common.client.GuiToolStation

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Burgersim'/608, l='MpServer', x=-385.11, y=63.00, z=150.37]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-333,69,131), Chunk: (at 3,4,3 in -21,8; contains blocks -336,0,128 to -321,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 134833 game time, 203750 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 28 total; [EntitySquid['Squid'/325, l='MpServer', x=-336.99, y=62.22, z=104.97], EntitySquid['Squid'/326, l='MpServer', x=-341.44, y=62.52, z=101.93], EntitySkeletonWarrior['Skeleton Warrior'/327, l='MpServer', x=-339.57, y=54.00, z=120.21], EntityBrainSlime['Brain Slime'/328, l='MpServer', x=-345.23, y=68.58, z=119.82], EntitySquid['Squid'/329, l='MpServer', x=-352.82, y=53.78, z=170.55], EntitySquid['Squid'/330, l='MpServer', x=-355.18, y=52.85, z=182.85], EntityFilchLizard['Filch Lizard'/208, l='MpServer', x=-455.56, y=67.00, z=87.32], EntitySquid['Squid'/209, l='MpServer', x=-444.68, y=55.81, z=159.64], EntityBrainSlime['Brain Slime'/410, l='MpServer', x=-305.59, y=62.35, z=80.90], EntityFestiveCreeper['Festive Creeper'/669, l='MpServer', x=-386.50, y=17.00, z=79.50], EntityLostMiner['Lost Miner'/414, l='MpServer', x=-305.50, y=29.00, z=207.50], EntityPlayerSP['Burgersim'/608, l='MpServer', x=-385.11, y=63.00, z=150.37], EntitySquid['Squid'/289, l='MpServer', x=-373.71, y=54.78, z=87.34], EntitySquid['Squid'/290, l='MpServer', x=-361.01, y=57.82, z=166.64], EntityZombie['Zombie'/291, l='MpServer', x=-354.19, y=13.00, z=165.36], EntitySquid['Squid'/228, l='MpServer', x=-444.34, y=51.63, z=157.45], EntitySquid['Squid'/292, l='MpServer', x=-353.62, y=55.96, z=174.00], EntitySquid['Squid'/229, l='MpServer', x=-445.57, y=49.98, z=162.14], EntitySquid['Squid'/237, l='MpServer', x=-425.93, y=61.24, z=159.89], EntityBoat['Boat'/371, l='MpServer', x=-335.69, y=62.52, z=81.69], EntityBrainSlime['Brain Slime'/372, l='MpServer', x=-337.02, y=62.21, z=109.60], EntityBrainSlime['Brain Slime'/373, l='MpServer', x=-310.96, y=66.00, z=128.27], EntityLostMiner['Lost Miner'/374, l='MpServer', x=-333.50, y=35.00, z=138.50], EntityCreeper['Creeper'/375, l='MpServer', x=-335.50, y=42.00, z=227.50], EntitySquid['Squid'/250, l='MpServer', x=-415.11, y=61.00, z=165.88], EntitySquid['Squid'/253, l='MpServer', x=-386.33, y=62.36, z=89.49], EntitySquid['Squid'/254, l='MpServer', x=-391.53, y=62.03, z=86.35], EntityLostMiner['Lost Miner'/255, l='MpServer', x=-386.50, y=32.00, z=216.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2379778976 bytes (2269 MB) / 5152178176 bytes (4913 MB) up to 5607784448 bytes (5348 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx6016m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 Optifine OptiFine_1.12.2_HD_U_C8 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                      | Version                     | Source                                           | Signature                                |
	|:--------- |:----------------------- |:--------------------------- |:------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft               | 1.12.2                      | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | mcp                     | 9.42                        | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | FML                     | 8.0.99.99                   | forge-1.12.2-14.23.2.2611-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                   | 14.23.2.2611                | forge-1.12.2-14.23.2.2611-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy       | 1.0.0                       | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | itemphysic              | 1.4.0                       | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | ivtoolkit               | 1.3.3-1.12                  | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | ambientsounds           | 2.0.0                       | AmbientSounds+v2.2.2+mc1.12.2.jar                | None                                     |
	| UCHIJAAAA | antiqueatlas            | 4.4.4                       | antiqueatlas-1.12-4.4.4.jar                      | None                                     |
	| UCHIJAAAA | antiqueatlasoverlay     | 1.2                         | antiqueatlas-1.12-4.4.4.jar                      | None                                     |
	| UCHIJAAAA | architecturecraft       | @VERSION@                   | architecturecraft-1.12-2.68.jar                  | None                                     |
	| UCHIJAAAA | quark                   | r1.4-122                    | Quark-r1.4-122.jar                               | None                                     |
	| UCHIJAAAA | autoreglib              | 1.3-15                      | AutoRegLib-1.3-15(1).jar                         | None                                     |
	| UCHIJAAAA | gorecore                | 1.12.2-0.4.5                | avatarmod-a5.2(1).jar                            | None                                     |
	| UCHIJAAAA | avatarmod               | a5.2                        | avatarmod-a5.2(1).jar                            | None                                     |
	| UCHIJAAAA | forgelin                | 1.6.0                       | Forgelin-1.6.0.jar                               | None                                     |
	| UCHIJAAAA | betterrecords           | 1.12.2-1.5.5                | BetterRecords-1.12.2-1.5.5.jar                   | None                                     |
	| UCHIJAAAA | bibliocraft             | 2.4.3                       | BiblioCraft[v2.4.3][MC1.12.0].jar                | None                                     |
	| UCHIJAAAA | biomesoplenty           | 7.0.1.2302                  | BiomesOPlenty-1.12.2-7.0.1.2302-universal(1).jar | None                                     |
	| UCHIJAAAA | bookshelf               | 2.3.523                     | Bookshelf-1.12.2-2.3.523.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | charset                 | 0.5.0.163                   | Charset-Lib-0.5.0.163.jar                        | None                                     |
	| UCHIJAAAA | jei                     | 4.8.0.114                   | jei_1.12.2-4.8.0.114.jar                         | None                                     |
	| UCHIJAAAA | mantle                  | 1.12-1.3.1.21               | Mantle-1.12-1.3.1.21.jar                         | None                                     |
	| UCHIJAAAA | tconstruct              | 1.12.2-2.9.1.65             | TConstruct-1.12.2-2.9.1.65(1).jar                | None                                     |
	| UCHIJAAAA | ceramics                | 1.12-1.3.3b                 | Ceramics-1.12-1.3.3b(1).jar                      | None                                     |
	| UCHIJAAAA | chameleon               | 1.12-4.1.3                  | Chameleon-1.12-4.1.3(2).jar                      | None                                     |
	| UCHIJAAAA | chiselsandbits          | 14.13                       | chiselsandbits-14.13.jar                         | None                                     |
	| UCHIJAAAA | chococraft              | 0.9.1.52                    | chococraft_1.12.1-0.9.1.52(1).jar                | None                                     |
	| UCHIJAAAA | chunkanimator           | 1.2                         | ChunkAnimator-MC1.12-1.2.jar                     | None                                     |
	| UCHIJAAAA | cookingforblockheads    | 6.3.17                      | CookingForBlockheads_1.12.1-6.3.17.jar           | None                                     |
	| UCHIJAAAA | extendedrenderer        | v1.0                        | coroutil-1.12.1-1.1.24(1).jar                    | None                                     |
	| UCHIJAAAA | coroutil                | 1.12.1-1.1.24               | coroutil-1.12.1-1.1.24(1).jar                    | None                                     |
	| UCHIJAAAA | configmod               | v1.0                        | coroutil-1.12.1-1.1.24(1).jar                    | None                                     |
	| UCHIJAAAA | cravings                | 1.0.5                       | Cravings-1.12.2-1.0.5(1).jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | creativecore            | 1.9.9                       | CreativeCore+v1.9.16+mc1.12.2.jar                | None                                     |
	| UCHIJAAAA | enderore                | 1.12.2-1.0                  | Ender+Ore-1.12.2-1.0.jar                         | None                                     |
	| UCHIJAAAA | extraalchemy            | 0.3.6.2-release             | extraalchemy-0.3.6.2-release.jar                 | None                                     |
	| UCHIJAAAA | extrabitmanipulation    | 1.12-3.2.1                  | ExtraBitManipulation-1.12-3.2.1(1).jar           | None                                     |
	| UCHIJAAAA | extrautils2             | 1.0                         | extrautils2-1.12-1.7.3.jar                       | None                                     |
	| UCHIJAAAA | felling                 | 1.3.2                       | felling-1.3.2-1.12.2(1).jar                      | None                                     |
	| UCHIJAAAA | cfm                     | 4.1.5                       | furniture-4.1.5-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | gravestone              | 1.10.0                      | gravestone-1.10.0(2).jar                         | None                                     |
	| UCHIJAAAA | tesla                   | 1.0.63                      | Tesla-1.12.2-1.0.63(1).jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | teslacorelib            | 1.0.12                      | tesla-core-lib-1.12-1.0.12(1).jar                | None                                     |
	| UCHIJAAAA | industrialforegoing     | 1.12.2-1.12.2               | industrialforegoing-1.12.2-1.7.2-117.jar         | None                                     |
	| UCHIJAAAA | ironchest               | 1.12.2-7.0.34.820           | ironchest-1.12.2-7.0.34.820(1).jar               | None                                     |
	| UCHIJAAAA | jeresources             | 0.8.5.27                    | JustEnoughResources-1.12.2-0.8.5.27.jar          | None                                     |
	| UCHIJAAAA | landlust                | 1.12.2-0.3.6                | landlust-1.12.2-0.3.6.jar                        | None                                     |
	| UCHIJAAAA | morebeautifulplates     | 1.12.2-1.0.3                | morebeautifulplates-1.12.2-1.0.3.jar             | None                                     |
	| UCHIJAAAA | nex                     | 2.1.14.15                   | NetherEx-1.12-2.1.14.15.jar                      | None                                     |
	| UCHIJAAAA | opframe                 | 1.4.0                       | OnlinePicFrame+v1.4.15+mc1.12.2.jar              | None                                     |
	| UCHIJAAAA | harvestcraft            | 1.12.2o                     | Pam's+HarvestCraft+1.12.2o.jar                   | None                                     |
	| UCHIJAAAA | placebo                 | 1.1.4                       | Placebo-1.12.2-1.1.4.jar                         | None                                     |
	| UCHIJAAAA | plants2                 | 2.3.1                       | Plants-1.12.2-2.3.1.jar                          | None                                     |
	| UCHIJAAAA | playerrevive            | 1.0                         | PlayerRevive+v1.2.10+mc1.12.2.jar                | None                                     |
	| UCHIJAAAA | plustic                 | 6.3.6.2                     | plustic-6.3.6.2.jar                              | None                                     |
	| UCHIJAAAA | primitivemobs           | 1.1.5c                      | primitivemobs-1.1.5c_beta.jar                    | None                                     |
	| UCHIJAAAA | reccomplex              | 1.4.7                       | RecurrentComplex-1.4.7.jar                       | None                                     |
	| UCHIJAAAA | xreliquary              | 1.12.2-1.3.4.733            | Reliquary-1.12.2-1.3.4.733.jar                   | None                                     |
	| UCHIJAAAA | roughtweaks             | 1.0                         | roughTweaks0.2.3-1.12.jar                        | None                                     |
	| UCHIJAAAA | spartanshields          | 1.4                         | SpartanShields-1.12.2-1.4.jar                    | None                                     |
	| UCHIJAAAA | spartanweaponry         | beta 1.1.2                  | SpartanWeaponry-1.12.2-beta-1.1.2.jar            | None                                     |
	| UCHIJAAAA | storagedrawers          | 1.12-5.2.5                  | StorageDrawers-1.12.2-5.3.4.jar                  | None                                     |
	| UCHIJAAAA | storagedrawersextra     | @VERSION@                   | StorageDrawersExtras-1.12-3.1.0.jar              | None                                     |
	| UCHIJAAAA | taiga                   | 1.3.0                       | taiga-1.12.2-1.3.0.jar                           | None                                     |
	| UCHIJAAAA | tcomplement             | ${version}                  | TinkersComplement-1.12.1-0.2.2b.jar              | None                                     |
	| UCHIJAAAA | torohealthmod           | 1.12.2-11                   | torohealth-1.12.2-11.jar                         | None                                     |
	| UCHIJAAAA | vbe                     | GRADLE:VERSION-GRADLE:BUILD | Vanilla+Builders+Extension-1.12.2-1.0.8.jar      | None                                     |
	| UCHIJAAAA | teleporter              | 1.6.3-beta4                 | VanillaTeleporter-1.12-1.6.3-beta4.jar           | None                                     |
	| UCHIJAAAA | veining                 | 1.2.1                       | veining-1.2.1-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | wearablebackpacks       | 3.1.2                       | WearableBackpacks-1.12.2-3.1.2.jar               | None                                     |
	| UCHIJAAAA | zombieawareness         | 1.12.1-1.11.11              | zombieawareness-1.12.1-1.11.11(1).jar            | None                                     |
	| UCHIJAAAA | teslacorelib_registries | 1.0.12                      | tesla-core-lib-1.12-1.0.12(1).jar                | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.6.0.jar)
  
SoundFixPatchingLoader (AmbientSounds+v2.2.2+mc1.12.2.jar)
  com.creativemd.ambientsounds.soundfix.SoundFixTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Extra Alchemy ASM (extraalchemy-0.3.6.2-release.jar)
  zabi.minecraft.extraalchemy.asm.PotionTransformer
LoadingPlugin (Quark-r1.4-122.jar)
  vazkii.quark.base.asm.ClassTransformer
CreativePatchingLoader (CreativeCore+v1.9.16+mc1.12.2.jar)
  
ItemPatchingLoader (ItemPhysic+Full+1.4.10+mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13476 Compatibility Profile Context 22.19.171.1024' Renderer: 'AMD Radeon HD 7800 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- CeramicsPlugin (Enabled/Not Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7800 Series GL version 4.5.13476 Compatibility Profile Context 22.19.171.1024, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: AntiqueAtlasExtra.zip (incompatible), ItemBound+v1.8.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3350P CPU @ 3.10GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: KUDA-Shaders v6.1 Legacy.zip
	OpenGlVersion: 4.5.13476 Compatibility Profile Context 22.19.171.1024
	OpenGlRenderer: AMD Radeon HD 7800 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by TherminatorX** [comment] 2018-02-12 01:26
Another dupe of #3372 
TAIGA issue

**Comment by Nexusdog** [comment] 2018-02-12 04:17
Presumably my crash just now is another dupe? 

https://pastebin.com/KJFAvZN8

**Comment by KnightMiner** [comment] 2018-02-12 05:33
Yep, both crashes are #3372, caused by TAIGA

**Closed by KnightMiner** 2018-02-12 05:33 UTC
