### ISSUE TITLE
Bigger stacks mod

### ISSUE THREAD

**Issue by benbenlaw** [SlimeKnights/TinkersConstruct#4821] opened 2022-04-04 09:09 UTC
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

1.8,37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

with the mod bigger stacks https://www.curseforge.com/minecraft/mc-mods/bigger-stacks, crafting stations delete items excess items over stack size of 64 when placed in the crafting station

### Crash Report

No Crash

### Other mods

https://www.curseforge.com/minecraft/mc-mods/bigger-stacks

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment] 2022-04-05 01:18
I have never been convinced its worth supporting mods that increase the max stack size. We have a lot of gameplay that assumes max stack size of 64. Remove that assumption and you don't just get the crafting table being smaller, you get balance issues and a ton of hacks around a constant being bigger than it ever should be.

I can check why its deleting excess items though, as that might be indicative of a bug which also affects tinkers chests (which have a lower stack size cap)

**Comment by PORTB** [comment] 2022-06-22 09:07
Hello, I am the developer of the mod in question. I came across this issue incidentally a few days ago and the latest release of my mod should fix this issue.

@benbenlaw you should have made an issue on my repo or at least left a comment on the curseforge page, I had no idea about this issue

**Comment by ale2468** [comment] 2022-11-30 14:14
Hi. Currently, I have updated sophisticated backpacks and sophisticated cores on Curse Forge and I was experiencing some issues loading Minecraft with this mod. At first, I thought it was sophisticated backpacks/core but I went to the creator's discord to see if they were having any issues with their mod and the creator had said it was a bigger stacks mod. I did have this mod installed in my pack with the sophisticated mods so I disabled Biggers tacks to see if I was able to play Java. It worked. The creator of sophisticated backpacks did say to let the creator of bigger stacks know the issue.

**Comment by KnightMiner** [comment] 2022-11-30 19:58
We do not make bigger stacks, so this is not the right place to let the creator know. This is the Tinkers Construct bug tracker.

**Comment by KnightMiner** [comment] 2022-12-27 02:01
Going to close this issue as the author claims its fixed. Looks like they fixed it by using mixins into my code, so just know in the future any issues reported with Bigger Stacks must be able to be reproduced without the mod as I offer zero support for mods that mixin my code.

**Closed as completed by KnightMiner** 2022-12-27 02:01 UTC
Labels: Bug, Mod interaction, 1.18

**Comment by Nachazo17** [comment] 2023-12-12 04:23
al abrir el minecraft no me aparece como si se pusiera el mod, se necesita algun mod aparte del bigger stacks??

**Comment by KnightMiner** [comment] 2023-12-12 06:16
This is not a tech support forum, this is an issue tracker for confirmed bugs in the game.

For tech support, consider joining our discord.

**Comment by Nachazo17** [comment] 2023-12-12 16:03
> Este no es un foro de soporte técnico, es un rastreador de problemas para errores confirmados en el juego.
> 
> Para obtener soporte técnico, considere unirse a nuestra discordia.

y cual es su discord

**Comment by KnightMiner** [comment] 2023-12-12 16:06
https://discord.gg/njGrvuh
