### ISSUE TITLE
1.12 smeltery

### ISSUE THREAD

**Issue by tyler489** [SlimeKnights/TinkersConstruct#3052] opened 2017-07-27 18:34 UTC
Seems if the smeltery is bigger than 3×3 it wont always dump into a casting basin or casting bench with ingot cast... not sure why this happens and it doesnt happen every time

**Comment by KnightMiner** [comment] 2017-07-27 18:44
Going to need a bit more information than that. First off, specific mod and Forge version. A list of other mods in your pack would be helpful, plus pictures of your setup.

**Comment by Tntdruid** [comment] 2017-07-29 16:53
Got the same problem

Forge: 14.21.1.2420
TC: 1.12-2.7.2.15

Not using a mod pack

**Comment by KnightMiner** [comment] 2017-07-29 18:36
Pictures. And you have other mods installed then that, packs can be private

**Comment by Tntdruid** [comment] 2017-07-29 18:49
@KnightMiner Works now moved the drain, was in the corner. Drain cant be in cornor now?

**Comment by tyler489** [comment] 2017-07-29 19:05
Playing beyond the new frontier https://minecraft.curseforge.com/projects/beyond-the-new-frontier will get pictures later as our world corrupted due to an unrelated issue

**Comment by bonii-xx** [comment] 2017-07-29 21:41
>@KnightMiner Works now moved the drain, was in the corner. Drain cant be in cornor now?

Corners aren't part of the smeltery. You don't need corners.

**Comment by KnightMiner** [comment] 2017-08-07 17:36
@tyler489 were you able to get your world fixed or reproduce this in a different world?

**Comment by viveleroi** [comment] 2017-09-07 02:44
It sounds like this is the issue I'm having as well. I'm able to smelt a few ores, pour a block, but now it fails to smelt anything, it "pours" forever without filling anything up. I don't know if this is TC related, because for me, it affects normal furnaces too. I have to break and re-place them or reboot for them to work again. I can't break the smeltery controller though, or I'll lose everything.

- TConstruct-1.12-2.7.2.19
- forge 1.12.1-14.22.0.2469
- Mantle-1.12-1.3.1.21

Here's my current mod list: https://pste.me/#/fVo33

**Comment by KnightMiner** [comment] 2017-10-22 20:32
Closing for lack of pictures from the original poster.

@viveleroi your issue sounds like a different issue, though it is probably not caused by Tinkers if vanilla blocks are affected.

**Closed by KnightMiner** 2017-10-22 20:32 UTC
Labels: Not enough information

**Comment by viveleroi** [comment] 2017-10-22 20:41
I forgot I had filed this, the issue I had was a Forge issue that I identified, filed, and was fixed:

https://github.com/MinecraftForge/MinecraftForge/issues/4386

**Comment by KnightMiner** [comment] 2017-10-22 21:13
Thanks for the response, good to know your issue has already been fixed in Forge.
