### ISSUE TITLE
Putting in a tool in the workbench causes it to crash [Multiplayer].

### ISSUE THREAD

**Issue by tjkenmate** [SlimeKnights/TinkersConstruct#2903] opened 2017-05-11 21:36 UTC
One of my testers found a bug on our multiplayer server. He went to repair a pickaxe and putting the tool in the slot/shift clicking it in crashed him. 

The tool was a broken stone pickaxe. I suspect it has to do with mod conflicts, however I thought Id let you know anyway.

Crash log for reference
https://pastebin.com/FjqCVTeG

Edit _This was mc 1.11.2 latest version on curseforge_

**Comment by tjkenmate** [comment] 2017-05-11 21:59
Update, this issue seems to be multiplayer only. It doesn't crash in SSP

**Comment by VisualPine** [comment] 2017-05-11 22:56
I was just coming to report this same issue only mine did happen on single player. Happen two times trying to repair a stone pickaxe and a stone longsword.

**Comment by Okimo** [comment] 2017-05-12 01:19
Yup happen to me a while ago It was in Single Player ... I was trying to repair a stone Pickaxe (Wooden Rod, Wooden Biding, Stone Head, named Picky)

**Comment by Wizardon777** [comment] 2017-05-12 22:11
Same here, crash report included.
in single and multiplayer. 
[crash-2017-05-13_01.08.54-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/998049/crash-2017-05-13_01.08.54-client.txt)

**Comment by KnightMiner** [comment] 2017-05-13 02:54
I did some testing and I was unable to reproduce this issue locally on server, and looking at the code I understand why. The crash is caused by [this line](https://github.com/SlimeKnights/TinkersConstruct/blob/1.11.2/src/main/java/slimeknights/tconstruct/library/utils/ToolBuilder.java#L179) returning null, which is run on each modifier in the registry. Our code never returns null for that method, but another mod's modifier could, which would likely be related to the fact that in 1.10.2 null was valid for no match.

Try and narrow down the mods required to reproduce this issue, I trust you will find it happens with just Tinkers, Mantle, and one other mod.

**Comment by tjkenmate** [comment] 2017-05-13 03:43
Thanks for the info, I suspected it was a mod conflict. I'll let you know what mod it is

**Comment by Gladi** [comment] 2017-05-13 12:17
I have this same issue since the modpack has added the following mods
- AdFinders
- astralsorcery
- BetterTitleScreen
- ColossalChests
- CompactStorage
- DefaultOptions
- ForgeEndertech
- mobends
- Reauth
- simplegenerators
- weaponcaseloot

**Comment by Gladi** [comment] 2017-05-13 16:13
I think I narrowed it down to the mod "ArmorPlus" 10.3.0.1 for MC v1.11.2
can someone confirm?

**Comment by Wizardon777** [comment] 2017-05-13 16:38
I can confirm, "ArmorPlus" is the cause...

**Comment by metzen227** [comment] 2017-05-13 16:48
seconded.  downgraded ArmorPlus to 10.2.1.2 and the tinkers tool station crash goes away.

**Comment by Gladi** [comment] 2017-05-13 16:51
I reported it to the author here: https://github.com/TheDragonTeam/ArmorPlus/issues/139

**Comment by sokratis12GR** [comment] 2017-05-13 17:54
Confirmed my side, will be fixed soon

**Comment by bonii-xx** [comment] 2017-05-14 11:08
Just give us a holler when the fix is released and which version it is so we can direct users there.

**Comment by sokratis12GR** [comment] 2017-05-14 11:20
Alright, will do so

**Comment by sokratis12GR** [comment] 2017-05-15 15:34
Issue should be fixed, [armorplus-1.11.2-10.3.1.2](https://minecraft.curseforge.com/projects/armorplus/files/2420119).

**Comment by KnightMiner** [comment] 2017-05-15 15:41
Since you fixed it, I will close this issue.

To anyone experiencing this issue in the future: reproduce with minimal mods to determine which mod is adding the broken modifier.

**Closed by KnightMiner** 2017-05-15 15:41 UTC
Labels: 3rd party mod interaction, bug
