### ISSUE TITLE
Black and purple textures ONLY on modifiers. 1.18.2 - Forge

### ISSUE THREAD

**Issue by aaronjr411** [SlimeKnights/TinkersConstruct#5105] opened 2023-03-07 16:51 UTC
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

the mod works fine, but seems to have some kind of issue with the DynamicTextureLoader, causes only the modifier items to be a black and purple missing texture icon. inside the debug log, there are hundreds of lines talking about this DTL, renderers, etc. 
after turning on the Log Texture errors setting on the TMOL.

eg.:
[07Mar2023 09:37:22.840] [Render thread/DEBUG] [slimeknights.tconstruct.library.client.model.DynamicTextureLoader/]: Skipping loading texture 'tconstruct:item/tool/cleaver/head_tconstruct_skyslime' as it does not exist in the resource pack
[07Mar2023 09:37:22.840] [Render thread/DEBUG] [slimeknights.tconstruct.library.client.model.DynamicTextureLoader/]: Skipping loading texture 'tconstruct:item/tool/cleaver/head_tconstruct_leather' as it does not exist in the resource pack
[07Mar2023 09:37:23.181] [Render thread/DEBUG] [slimeknights.tconstruct.library.client.model.DynamicTextureLoader/]: Skipping loading texture 'tconstruct:item/tool/armor/plate/shield_modifiers/tconstruct_bane_of_sssss' as it does not exist in the resource pack
[07Mar2023 09:37:28.043] [Render thread/DEBUG] [slimeknights.tconstruct.library.client.model.DynamicTextureLoader/]: Skipping loading texture 'tconstruct:item/tool/armor/travelers/goggle_modifiers/tconstruct_hydraulic' as it does not exist in the resource pack

i have tested slowly removing mods one at a time, with a full modlist of mine at 92, this is quite tedious. i have tried only using the shortened list of mods (see modlist section) which fixed it temporarily. only change there was removing all the other mods, no changes to the resource packs or shaders. 

###Update
the perpetrator of the black and purple in this case is having both tinkers and the Supplementaries mod both installed. the supplementaries mod causes some sort of issue with the resource packs and the textures, only affecting tinkers for some reason. Supplementaries adds a resource pack of its own for its mod data

[debug log for Tconstruct Ticket.log](https://github.com/SlimeKnights/TinkersConstruct/files/10911889/debug.log.for.Tconstruct.Ticket.log)

### Crash Report

https://pastebin.com/6mtFahn1 (not sure if relevant, but crashes are happening from using F3 + T[reloading textures])

### Other mods

https://imgur.com/a/RUbTF0I  -- Full Modlist

shortened list for relevance(tested with only these mods and the problem reverts and the textures return, but they return to purple and black after a few reloads)
-BSL Shaders
-Unity Dark mode 1.18.2 Resource pack
-Just Enough Items (JEI)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Rubidium + Oculus

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment] 2023-03-07 17:00
Optifine is not supported. Duplicate of #4316

**Comment by aaronjr411** [comment] 2023-03-07 17:01
update. the problem mod seems to be the Supplementaries mod(https://beta.curseforge.com/minecraft/mc-mods/supplementaries), it uses a resource pack for its data, causes some kind of issue, it is NOT an optifine issue.

**Comment by ShinyPorygon** [comment] 2023-03-07 17:03
Do not use optifine, there are better alternatives such as rubidium + oculus. Bug reports with optifine are invalid. Reproduce without optifine ever being installed in an instance.

**Comment by aaronjr411** [comment] 2023-03-07 17:04
alright bet ill reproduce without optifine. im telling you its the resource pack and the DynamicTextureRenderer

**Comment by aaronjr411** [comment] 2023-03-07 17:08
![image](https://user-images.githubusercontent.com/83424467/223496013-bea8cf0b-7acf-4d6a-b6ea-51f1b4fa7c29.png)

reproduced with the supplementaries mod and NO OPTIFINE. as you can see the shaders arent there.  and here are the video settings with no optifine
![image](https://user-images.githubusercontent.com/83424467/223496219-ae070bf5-c52a-47f2-ad52-b1dff5c4f1ae.png)

it is definitely the supplementaries mod and the way it adds a resource pack for its data:
![image](https://user-images.githubusercontent.com/83424467/223496478-f4745466-ce94-49ad-9157-e0753cd2da51.png)

the hierarchy doesnt make a difference

**Comment by ShinyPorygon** [comment] 2023-03-07 17:11
I still don't believe this is anything we can fix, they are specifically skipping loading our files as it's not specifically in their texture pack. This will be re-opened for the mean time, but the as I mentioned the log file shows them skipping our textures. 
Next time don't mention optifine if it's irrelevant. And still don't use it because there are better alternatives.

**Comment by aaronjr411** [comment] 2023-03-07 17:14
i didnt know if optifine was or wasnt relevant. 

seems like poor support if completely invalidating tickets based on it having optifine, i understand the whole closed source, no support. but it very well may be fixable. just saying.

this is an issue with the DTL and Forge with the way it loads resource packs, i wonder if this can be reproduced with other resource packs. ill certainly update this ticket with any sort of findings like that.

**Comment by ShinyPorygon** [comment] 2023-03-07 17:18
While this belongs more on the discord. Optifine has been shown repteadly to affect everything it shouldn't. Any report with it is invalidated because it can affect worldgen, structures, textures, they rewrite entire apis, corrupt configs, worlds, and everything else. It is entirely justified for a "mod" that can do all of that and has shown too countless times even in this tracker, to instantly close something we genuinely can't fix. If you'd like to continue this discussion of how bad optifine is join the discord discord.gg/njGrvuh

**Comment by aaronjr411** [comment] 2023-03-07 17:20
im not defending optifine whatsoever. just trying to help this issue. ive looked all over for some kind of relevant issue or fix before opting to making a ticket, to no avail. 

i shall switch to rubidium, i only use optifine because this my first time back on MC after several years, im just old fashioned with my mods, gotta catch up with the new 

thanks for the help friend :)

**Comment by aaronjr411** [comment] 2023-03-08 19:28
new update, using any MULTIPLE resource pack seems to cause the DynamicTextureLoader to skip the texture for JUST the modifiers.

![image](https://user-images.githubusercontent.com/83424467/223823916-e320e436-8a25-4aec-9fd1-7586d037b01a.png)

**Comment by KnightMiner** [comment] 2023-03-08 20:25
That seems highly unlikely to me, given that we do not use dynamic texture loading for modifier textures. Its a JSON file that lists the required textures directly rather than a folder scan.

**Comment by israpps** [comment] 2023-03-19 14:40
i had this same issue, with the adition that all weapons looked white

Solution (at least for me): 
> make sure minecraft is the resource pack on top of the enabled list
![image](https://user-images.githubusercontent.com/57065102/226183386-830cbbd3-b331-4186-8dd0-79d3a81bf9bc.png)

**Comment by KnightMiner** [comment] 2023-03-19 15:09
If your tools are white, you have performance mods breaking it like rubidium. Changing resource pack order reloaded it

**Comment by israpps** [comment] 2023-03-19 18:00
> If your tools are white, you have performance mods breaking it like rubidium. Changing resource pack order reloaded it

No. I reloaded resource pack that same day to fix the headphones issue and it didn't solve it.

Tested again just to confirm it, if vanilla pack is not the first one tools go white

**Comment by KnightMiner** [comment] 2023-03-20 05:06
Took a quick look into this issue, appears it could be a race condition as our logic is supposed to run before the model loader initializes, but technically due to how resource loaders work that is not guaranteed. There is a hacky fix I can apply to guarantee it runs first (had a similar issue with some other texture loaders before), so will look into it for the next update. 1.19 will luckily solve this problem entirely, I just have to tell it to stitch the whole directory and it will.

Also, for the record, unless a print out from Tinkers Construct contains the word "error", it is not an error. "debug" means it is for (surprise!) debug. The logs mentioning in the original issue are a feature disabled by default for resource pack developers to debug why their material textures are not loading/locate the proper texture path for their material. If your modpack has it enabled, tell them it should be disabled. However, also know that nothing is wrong, its just Tinkers Construct stating some optional textures do not exist.

**Comment by KnightMiner** [comment] 2023-04-27 08:51
3.6.4.113 has a workaround, might look into this again later for a more proper fix.

**Comment by KnightMiner** [comment] 2024-02-25 05:49
I am going to go ahead and close this issue as the workaround has seemed stable enough for now, and 1.19.3 introduces a new atlas system that will entirely remove the need for the problematic code.

**Closed as completed by KnightMiner** 2024-02-25 05:49 UTC
Labels: Bug, Resolved, 1.18
