### ISSUE TITLE
 Equipping traveler's goggles crashes the game

### ISSUE THREAD

**Issue by PunkPun** [SlimeKnights/TinkersConstruct#4789] opened 2022-03-01 16:58 UTC
### Minecraft Version

1.18.1

### Forge Version

latest

### Mantle Version

?

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

The world becomes corrupted and gives the same crash when entering again

### Crash Report

[crash-2022-03-01_18.54.24-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8163369/crash-2022-03-01_18.54.24-client.txt)

### Reproduced with only Tinkers' Construct?

No

### Confirm the following

- [x] Check if you are using performance enhancers, such as optifine
- [x] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [x] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-03-01 17:00
Duplicate of #4734 if you check the box for checking the pinned issues actually check them instead of making duplicate 16 or 17 of the same thing. Remove optifine.

**Closed as completed by ShinyPorygon** 2022-03-01 17:00 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18

**Comment by PunkPun** [comment] 2022-03-01 17:25
>if you check the box for checking the pinned issues actually check them instead of making duplicate 16 or 17 of the same thing. Remove optifine.

I only looked through the open issues. Even if it's not an crash you can solve there should still be at least one issue open

**Comment by KnightMiner** [comment] 2022-03-01 17:32
The checkbox asked you to look at the pinned issues. There are only three of them
![image](https://user-images.githubusercontent.com/12155288/156219122-a713406c-fdb1-4001-9601-fef8cea82bf8.png)

Even if they are not open, the fact we pinned them and asked you to look at pinned issues would make me assume you look at them. Issues are closed because the issue is resolved, in this case by removing a garbage mod. If we left every issue open where  there is an easy fix like that, the issue tracker would become so cluttered searching is again impossible (as we would have to leave open every issue fixed by updating, which is nearly every issue).

**Comment by PunkPun** [comment] 2022-03-01 17:41
Hmm, I wasn't aware of such a github feature. I also just found #6607. The only open issue on it and it didn't happen to have the keywords I was searching for. I guess it's my bad for not looking into it deeper

**Comment by KnightMiner** [comment] 2022-03-01 19:14
That raises two questions:

* Why did you check the box saying you checked the pinned issues when you did not know what pinned issues are?
* How did you manage to report an issue without seeing the pinned issues? They are right above the new issue button

![image](https://user-images.githubusercontent.com/12155288/156233740-0a894ba5-1c50-483d-94b8-7f65eddf0a3d.png)

**Comment by PunkPun** [comment] 2022-03-01 20:59
I don't really see the point of continuing this further. Nothing but toxicity can come of this. But regardless, I will try to make it clear.

> How did you manage to report an issue without seeing the pinned issues? They are right above the new issue button

The issue embed has quite a lot of information displayed and is visually separate from the rest of the page. So when I came here to do what I came here to do, I mentally skipped over it as if it were an advertisement / waste of my attention. But now with the knowledge that this part of the page is important, I will no longer skip over it. It isn't great design from github, but at the same time I'm not sure how it could be better

> Why did you check the box saying you checked the pinned issues when you did not know what pinned issues are?

As I was in a hurry to get back to having fun, so I didn't bother much. I just saw that it's asking to check the tracker, and I ran a few logical keywords through the search

**Comment by KnightMiner** [comment] 2022-03-01 21:14
> I don't really see the point of continuing this further. Nothing but toxicity can come of this. But regardless, I will try to make it clear.

My goal is to make the issue reporting experience more clear so that others don't make the same mistake. The fact that we have had 16 duplicates of this issue says something can be improved about the template, so a user experience is helpful so I can adjust it. Your response was useful, I'll think about how I can improve the design of the forum.

**Comment by PunkPun** [comment] 2022-03-01 21:41
> My goal is to make the issue reporting experience more clear so that others don't make the same mistake. The fact that we have had 16 duplicates of this issue says something can be improved about the template, so a user experience is helpful so I can adjust it. Your response was useful, I'll think about how I can improve the design of the forum.

Great! Then I want to add a few more things

- Never make a two-part question checkboxes. This is a surefire way to cause misinterpretation
- Since as I understand the only incompatibility with optifine is armour, it would make sense to mention armour it in the FAQ. That way the person will know right of the bat that his exact crash is documented
- Do not greet users with an antagonising welcome. You do not want to discourage users from reporting bugs and crashes. Every response I got here was challenging either my honesty, or intelligence. Even the checkboxes themselves. If you are unable to give a warm welcome just do a cold one. Like "Duplicate of #issue" and close it

**Comment by esotericist** [comment] 2022-03-02 03:29
> Since as I understand the only incompatibility with optifine is armour, it would make sense to mention armour it in the FAQ. That way the person will know right of the bat that his exact crash is documented

point of note, the *current* primary pain point with optifine and tinkers' construct is armor, but that doesn't mean it's the only issue, and it hasn't been the only issue in the past. optifine has developed the habit of outright overriding critical forge logic, and until they stop doing that, we can continue to expect new issues.

and that's setting aside historical issues like optifine breaking world generation, which shouldn't even be possible if optifine was doing what it claimed to be doing.
