### ISSUE TITLE
Gear cast is no where to be seen

### ISSUE THREAD

**Issue by MasterSloth1** [SlimeKnights/TinkersConstruct#4899] opened 2022-06-07 23:34 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.35

### Mantle Version

Mantle-1.16.5-1.6.157

### Tinkers' Construct Version

Tconstruct-1.16.5-3.3.2.335

### Describe your issue

if you create a new instance of minecraft with only
Jei
EmendatusEnigmatica
Mantle
Tconstruct
then you search jei for gear cast you will see its not there, but if you look at a recipe that uses the gear cast you can see the item and how to get it

### Other mods

Jei version jei-1.16.5-7.7.1.152
EmendatusEnigmatica  version - EmendatusEnigmatica-1.2.15-build.7+mc1.16.5.jar

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by MasterSloth1** [comment] 2022-06-07 23:36
oooh my bad this only happens on server single player this works fully as intended

**Comment by ShinyPorygon** [comment] 2022-06-07 23:36
Closing the first issue for works as intended doesn't mean open another and add a mod.

**Comment by MasterSloth1** [comment] 2022-06-07 23:37
lol you said to add a mod that adds gears you closed the first one so i open another with more mods that adds gears

**Comment by KnightMiner** [comment] 2022-06-07 23:37
Duplicate of #4898. If you have followup comments leave them on the original issue, don't make a new one.

**Closed as completed by ShinyPorygon** 2022-06-07 23:36 UTC
Labels: Duplicate, 1.16, Works as Intended
