### ISSUE TITLE
No smeltery pouring animation

### ISSUE THREAD

**Issue by XayahProdigy** [SlimeKnights/TinkersConstruct#3311] opened 2017-12-31 15:29 UTC
As the title already says im having a problem with the smeltery pouring animation.
The problem with it is that I simply don't have any animation except when the block itself forms.
The pouring is completele non-existant and then out of nowhere the block forms.
This happens even with minecraft vanilla materials.
Its the tinker's construct version for minecraft 1.12.2 and im running on Java 8 Update 151 (hope this helps with solving the issue)
Thanks in advance :)

**Comment by KnightMiner** [comment] 2017-12-31 15:34
Please give more information. What version of Tinkers? What version of Forge? Are you playing a mod pack? Do you have other mods installed? Have you tried removing Optifine?

We use a normal TESR for animation, so there is no reason the faucet would lose it's animation unless something is breaking rendering.

**Comment by XayahProdigy** [comment] 2017-12-31 15:38
I haven't tried removing optifine yet.
Im playing the modpack Mech&Magic on the AT-Launcher.
Forge version : forge-1.12.2-14.23.1.2555-universal
Tinkers version : TConstruct-1.12-2.8.1.49

**Comment by XayahProdigy** [comment] 2017-12-31 15:42
And also in the smeltery controller vanilla iron is shown as a pink material. Dunno if this helps though

**Comment by KnightMiner** [comment] 2017-12-31 16:56
Remove Optifine then report back

**Comment by XayahProdigy** [comment] 2017-12-31 17:09
Still no improvement.
optifine version : OptiFine_1.12.2_HD_U_C6

**Comment by KnightMiner** [comment] 2017-12-31 20:40
Oh, so some fluids are working? That would have been helpful. It sounds like you have another mod which adds some of the molten fluids installed  (Embers is in that pack), but your world is defaulting to the other mods fluids. Try creating a new world and see if it works. If so I can point you towards the way to fix your world.

**Comment by XayahProdigy** [comment] 2017-12-31 21:20
Do I create a new world with optifine activated or without?

**Comment by KnightMiner** [comment] 2017-12-31 21:30
Should not matter in this case, I just avoid Optifine as it has a tendency to break things (and causes most of the rendering issues on this tracker)

**Comment by XayahProdigy** [comment] 2018-01-01 00:35
Yeah so i created a new world and the same issue occurs.
I did a little bit of digging into the modpack and it seems that actually the mod "Embers" causes this issue.
The molten metals are listed under this particular mod and it seems this mod doesn't provide any valid texture for some metals.
Is this because the modpack doesn't use the newest version of the mod or do i just have to download a texturepack for "Embers"

**Comment by KnightMiner** [comment] 2018-01-01 00:45
In that case, closing as a duplicate of #3037. The issue is not with embers, it is that both mods register the same fluid and Forge does not know which fluid to use.

**Closed by KnightMiner** 2018-01-01 00:45 UTC
