### ISSUE TITLE
[1.12] Missing Tool Parts images

### ISSUE THREAD

**Issue by Cheezy16** [SlimeKnights/TinkersConstruct#3061] opened 2017-07-28 18:39 UTC
Almost all vanilla Tinkers' tool parts don't have an image in the latest version for 1.12 alpha, this may have been noticed already but I didn't see anything describing this bug. Even when the tools are crafted, the vanilla parts aren't visible on the tools. Materials that aren't affected include Flint, Stone, and a few metals like iron.

**Comment by alexbegt** [comment] 2017-07-28 18:55
Are you running Optifine?

**Comment by Cheezy16** [comment] 2017-07-28 18:58
Yes, i hadn't thought of that... Still, Optifine is useful to have.

**Comment by KnightMiner** [comment] 2017-07-28 21:23
Update or remove Optifine. Duplicate of #3008

**Closed by KnightMiner** 2017-07-28 21:23 UTC
