### ISSUE TITLE
Combining magical wood and unbreakable leads to permanently broken tool

### ISSUE THREAD

**Issue by TheWonderingMage** [SlimeKnights/TinkersConstruct#3335] opened 2018-01-14 11:59 UTC
The Magical Wood modifier Magically Brittle seems to forcefully break tools even when they are Unbreakable (due to 5 reinforces being applied), causing them to be broken without durability loss. This can lead to a tool being broken without being able to be repaired.

Edit:
Tinkers' Construct Version: 1.12-2.8.1.49
Tinkers Tool leveling Version: 1.12-1.0.3.DEV.56fac4f

All the Mods 3 Modpack on the Twitch Launcher

**Comment by KnightMiner** [comment] 2018-01-14 15:23
Duplicate of #3173. Not a Tinkers Construct issue, it's caused by Extra Utilities.

**Closed by KnightMiner** 2018-01-14 15:23 UTC
