### ISSUE TITLE
crash when placing tool in crafting table or tool station

### ISSUE THREAD

**Issue by hottentottententententoonstelling** [SlimeKnights/TinkersConstruct#3224] opened 2017-11-04 05:04 UTC
I get the following crash when placing a random tool in a crafting table or tool station

version: 1.10.2

https://pastebin.com/vGQXz8mb

**Comment by Moose1002** [comment] 2017-11-11 17:38
I also have this problem, I'm playing on the modpack "The Simple Life 2". I really enjoy the pack but without tinkers construct it's kinda boring. I hope someone can find a fix. Thanks

**Comment by LoveFireAmi** [comment] 2017-11-13 06:27
Duplicate of #2776.  Please look up issues before posting them.  Also, you are able to disable rendering items on tables in config.

If that is not the issue, you have multiple mods that interfere with rendering, the most infamous one being OptiFine.

**Comment by bonii-xx** [comment] 2017-11-21 17:22
For once, this has nothing to do with optifine. Looks more like your tool has broken NBT.
What does the tool consist of? (Materials, modifiers,..)

**Comment by bonii-xx** [comment] 2018-01-07 16:24
Closing due to inactivity.

**Closed by bonii-xx** 2018-01-07 16:24 UTC
