### ISSUE TITLE
[Trivial] Lag when pouring molten metals out of the smeltery

### ISSUE THREAD

**Issue by bochen415** [SlimeKnights/TinkersConstruct#1184] opened 2014-11-18 12:39 UTC
As title

When pouring molten metals to Casting Basins (preferably more than one simultaneously) there's a frame rate drop and the player stutters while moving/jumping. When the metal block materializes it gets back to normal.

Tested on 1.7.1c on multiplayer (without Cauldron).
Forge 1236

**Comment by KingLemming** [comment] 2015-03-24 10:03
Yeah, that sort of sounds like a design oops tbh. You should only have to do a local render update on the start and stop.

**Comment by andrewring** [comment] 2015-03-24 12:17
I do appreciate the visible filling effect, though. Just a thought, but could something be done with an animated entity to show the motion instead of a block change? 

Disclaimer: I'm not a minecraft developer.

**Comment by bochen415** [comment] 2015-03-24 12:26
@bonii-xx come on over here for a moment.. Have any thoughts on this?

**Comment by asiekierka** [comment] 2015-03-24 13:14
@KingLemming is right - things that update often, such as liquids in casting basins, should be a TESR. Really.

**Comment by bonii-xx** [comment] 2015-03-24 13:26
Yup, somebody messed up. Can't even git blame because history is a derp :(
I wonder if it was an issue in 1.6.4 too

**Comment by AndyMoreland** [comment] 2015-03-24 20:58
Just checking in to lend support for fixing this -- I just built a 9x9 smeltery and I'm really feeling the pain when I use all 28 drains that it supports :-).

**Comment by jasonmbrown** [comment] 2015-04-07 07:21
Any Possibility of Getting a config Option To Disable Rendering of Liquids in Basins Until there is a fix for this? I drop down to 3-4 fps In my automated Casting Facility. Everywhere else i run at 60-90fps.

**Comment by bochen415** [comment] 2015-04-25 02:13
@jasonmbrown 
There's a workaround for your Casting Facility
You need Thermal Smeltery, Thermal Expansion (+ CoFHCore + Thermal Foundation) and Thermal Casting

![1aavech](https://cloud.githubusercontent.com/assets/8314356/7331053/8a409cda-eb00-11e4-9b84-d29be212e2b5.png)

1xThermal Expansion Igneous Extruder (makes cobble)
1x Magma Crucible (melts ores)
2xEnderIO Crafters (one makes stone tool rods and the other the casting frame)
1xFluid Transposer (fills the casting frame and makes metal blocks)

**Comment by jasonmbrown** [comment] 2015-04-25 13:36
Cool, That looks like it would work wonders... Sadly I cant add anymore mods to the modpack im using, Since my friend is using a craptop lol. the game just crashes for them if we add anything else. It crashes 40% of the time for them normally. But Il keep this setup in mind for the next modpack i play! Thanks for the response!

**Comment by SophisticaSean** [comment] 2015-05-04 05:29
This is a really bad issue on Skyfactory 2, as there is currently no alternative to pouring. On my machine with a 780 I go from 145 FPS down to 80~ when just one or two liquids pour. I played almost every version of Tinker's on 1.6.4 and I definitely do not recall this problem back then. Super nasty issue, I'm considering dismantling all tinkers construct stuff as the FPS death is not fun..

**Comment by TerrorBite** [comment] 2015-05-11 04:04
For anyone interested, I went through the source and tracked down how the fluid level is drawn and animated.

Currently, when a casting table or casting basin block is rendered in the world, [`CastingBlockRender`](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/smeltery/model/CastingBlockRender.java#L16) calls [`BlockSkinRenderHelper.renderLiquidBlock()`](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/client/BlockSkinRenderHelper.java#L860) in order to draw the liquid level. In order to animate the fluid level, the associated [`CastingBlockLogic`](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/smeltery/logic/CastingBlockLogic.java#L22) tile entity currently [forces the block to rerender](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/smeltery/logic/CastingBlockLogic.java#L201) on every tick while pouring. As @mDiyo mentioned, this resets the entire local section, which results in lowered framerate and jitter.

Ideally the `CastingBlockLogic`, as it is a `TileEntity`, should use TESR mechanics to render the fluid. In this case `BlockSkinRenderHelper` can't be used as it relies on a `RenderBlocks`, so the `CastingBlockLogic` would need to do its own rendering.

**Comment by ReikaKalseki** [comment] 2015-05-11 04:13
> In this case BlockSkinRenderHelper can't be used as it relies on a RenderBlocks, so the CastingBlockLogic would need to do its own rendering.

TESRs can access the RenderBlocks; I do it all the time. All you need is the lazyloaded version supplied already.

**Comment by TerrorBite** [comment] 2015-05-11 06:08
I know nothing about the finer details of rendering so I defer to your knowledge here. That's good because it means the existing helper code can be reused.

**Comment by bochen415** [comment] 2015-05-11 06:14
@SophisticaSean 
> This is a really bad issue on Skyfactory 2, as there is currently no alternative to pouring
SkyFactory includes ThermalCasting so there's a violable workaround present in that modpack.

**Comment by Lodran** [comment] 2015-05-26 04:08
Apparently casting basins cause updates continuously, not just when being used.  I built a machine using 160 casting basins to consume the entire output of a pair of ender-thermic pumps, which were pumping out a sea of molten steel.

The machine works, but just assembling it caused me to lag so badly that I could barely move.  I finally ended up building it in it's own dimension, just to contain the lag.

To reproduce, make 160 casting basins, drop them all down in the same area.

**Comment by TherminatorX** [comment] 2015-05-26 16:07
@Lodran Plop down 160 vanilla furnaces or chests and you will have the same issue.

**Comment by ReikaKalseki** [comment] 2015-05-26 16:32
This is where profiling becomes useful, and where the lag from the updateEntity() method gets compared with the rerender.

**Comment by Lodran** [comment] 2015-05-26 17:32
@TherminatorX, I've got a sorter in vanilla with well over 1000 chests, many of which are adorned with item frames.  It doesn't generate the kind of lag that casting basins generate.

**Comment by bookerthegeek** [comment] 2015-05-26 20:06
I believe the poster is stating that unused casting basins will update even if not being used.

Tested in creative on latest forge and tinkers (as of today).

1000 casting basins in a 10x10x10 will lag you much more then a similar setup of any vanilla block not currently active.

**Comment by Lodran** [comment] 2015-05-27 03:15
@bookerthegeek that's exactly what I'm saying.  It's clear from my testing that the lag is coming from network communications, rather than from rendering.  160 casting basins in single player mode make barely noticeable lag.  The same basins in an offsite server (I'm in USA, server's in France) make lag that's so horrific that you can't get in/out of flight mode.

**Comment by ReikaKalseki** [comment] 2015-05-27 03:26
The CPU overhead from the network code should be the same no matter whether an integrated or dedicated server...

**Comment by Lodran** [comment] 2015-05-27 03:34
I'm not talking about CPU overhead, I'm talking about places in the client where the code stalls waiting for some network packet to be responded to.  Those places tend not to be seen when there's not a lot of block updates going on, but basins seem to have a magical ability to make them visible.

At any rate, what I'm seeing is barely visible on single player, and so bad as to make the game unplayable on a multi-player server with somewhat high latency.  It hasn't happened to me with other mods, but that's probably because I haven't found a need to build 160 of the same machine in order to get the performance I want with other mods.

**Comment by bookerthegeek** [comment] 2015-05-27 19:55
Not a coder, but what I've noticed is that The casting basins cause a sever fps drop when you have alot of them in an area. (Alot as in my server setup of about 200 of them). These are not actively in use to get the drop,  just by existing. 

When using them, I can only  automate about 30 before my game becomes unplayable due to render lag.


I am courious what mariculture does differantce as i do not experience this issue when using their ingot caster or their nugent caster. Have not tried their block caster as of yet.

**Comment by AglarCZ** [comment] 2015-09-22 20:20
Any new ideas what to do with this? Bug present on my server too.

**Comment by bochen415** [comment] 2015-09-22 20:28
Use Thermal Casting or any kind of automation that will fill the Casting Basins faster than a faucet or move your smeltery out of view distance.

**Comment by Lodran** [comment] 2015-09-22 20:28
I've eliminated my use of tinker's construct as much as possible, because of the lag.  In my Agrarian Skies 2 world, I only use a single smelter, and a single casting table, to produce gears for which the normal crafting recipes have been disabled.

As for casting liquids that haven't come from a smelter, there's the thermal casting mod.

**Comment by bochen415** [comment] 2015-09-22 20:36
There's also Thermal Smeltery to keep us busy with workarounds..

**Comment by bookerthegeek** [comment] 2015-09-23 22:48
True, but using mod B to fix a problem with mod A is not optimal. Better to resolve the issue in mod A.

**Comment by bochen415** [comment] 2015-09-24 08:31
> True, but using mod B to fix a problem with mod A is not optimal. Better to resolve the issue in mod A.
Look at the Milestone information on the right.

**Comment by bookerthegeek** [comment] 2015-09-24 14:20
Milestone information does not show up on my phone to the right of this post, I'll go check in desktop mode tonight. :(

**Comment by Gunni** [comment] 2016-02-02 03:05
Hi, I just want to poke this issue since I am affected by it. I would be fine with no animation as a setting or similar, do not care, just want it to work...

Literally made a molten glass dimlet to make shittons of glass, and as soon as i wanted to cast the glass into basins, fps tanks....... not fun!

Also, vote to remove the trivial tag and maybe even add a medium/high tag!

**Comment by ReikaKalseki** [comment] 2016-02-02 05:44
Are basins not a TESR now?

**Comment by squeek502** [comment] 2016-02-02 06:43
@ReikaKalseki In 1.7.10, [they still aren't](https://github.com/SlimeKnights/TinkersConstruct/blob/1.7.10/src/main/java/tconstruct/smeltery/model/CastingBlockRender.java). Casting Basins, Casting Tables, and Faucets use ISBRH for all liquid rendering. Basins/Tables [only use a TESR for rendering the itemStack they contain](https://github.com/SlimeKnights/TinkersConstruct/blob/1.7.10/src/main/java/tconstruct/smeltery/model/CastingBasinSpecialRender.java).

**Comment by ReikaKalseki** [comment] 2016-02-02 07:29
That changes *less* than the fluid...

**Comment by squeek502** [comment] 2016-02-02 17:35
Yeah, I think that's how it's always been. For whatever reason, this issue was never addressed.

**Comment by bonii-xx** [comment] 2016-02-07 11:14
Fixed in 1.8

**Closed by bonii-xx** 2016-02-07 11:14 UTC

**Comment by Tadipillarzz** [comment] 2017-07-11 22:25
@bochen415 could you explain to me that Thermal Smeltery setup please!

**Comment by bochen415** [comment] 2017-07-11 23:15
It's been like more than 2 years ago, using 1.10.2 and higher now but the best description is like using the blocks listed on this post 
https://github.com/SlimeKnights/TinkersConstruct/issues/1184#issuecomment-96121602
