### ISSUE TITLE
Only part available is the Large Plate

### ISSUE THREAD

**Issue by CreepyHobo** [SlimeKnights/TinkersConstruct#3118] opened 2017-08-22 04:06 UTC
I just set up my smeltery and when I went to start making tools, I discovered that the only part I could make is the large plate.
![2017-08-21_23 05 17](https://user-images.githubusercontent.com/31232317/29548295-5e3db3d0-86c5-11e7-86b3-58aee0a16412.png)

**Comment by trilexcom** [comment] 2017-08-22 04:10
are you using optifine?

**Comment by CreepyHobo** [comment] 2017-08-22 04:11
yes

**Comment by trilexcom** [comment] 2017-08-22 04:11
remove optifine and try again i bet it will work

**Comment by CreepyHobo** [comment] 2017-08-22 04:14
That fixed it!  Thank You!

**Comment by trilexcom** [comment] 2017-08-22 04:14
your welcome!

**Comment by KnightMiner** [comment] 2017-08-22 04:28
Duplicate of #3008. Worth noting the newest Optifine update does not cause this issue, though that is not to say it does not cause other issues.

**Closed by KnightMiner** 2017-08-22 04:28 UTC
