### ISSUE TITLE
Jei dont work with crafting station chest "gui"

### ISSUE THREAD

**Issue by raalpe** [SlimeKnights/TinkersConstruct#2708] opened 2017-01-08 00:01 UTC
i dont know if its jei or TC but then i have a crafting station with a chest next too so i get the chest gui and open a recipe in jei it says missing items but they are in the chest gui

**Comment by KnightMiner** [comment] 2017-01-08 00:58
Duplicate of #2627.

**Closed by KnightMiner** 2017-01-08 00:58 UTC
