### ISSUE TITLE
Book GUI Pages Unclickable MacOS

### ISSUE THREAD

**Issue by Sand-Master** [SlimeKnights/TinkersConstruct#5016] opened 2022-10-31 20:47 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Mantle Version

1.16.5-1.6.157

### Tinkers' Construct Version

1.16.5-3.3.4.335

### Describe your issue

Whenever I open any of the 4 tinker's construct books (including the encyclopedia as well) I am able to click the forward page, backward page, and return to start buttons on the side, but all clickable chapters in the book and information that is hover-able (like perks and item names) are dead and are unclickable.

Troubleshooting steps:
- I have tried to use java 8 and 11, neither seem to make a difference to fix this issue.
- I have used books from other mods (such as botania) and they do work.
- I have run windows in VM and it does work in the windows virtual environment on the same hardware.

### Other mods

I am mainly using Ragnamod VI as the modpack, but have just used mantle and tinkers' construct in a fresh custom pack and the issue persists.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment] 2022-10-31 20:52
Duplicate of #4663 and already fixed on 1.18.2, this was however fixed after 1.16 stopped receiving updates.

**Closed as completed by ShinyPorygon** 2022-10-31 20:52 UTC
Labels: Bug, Duplicate, 1.16

**Comment by Sand-Master** [comment] 2022-10-31 20:54
So there will never be a fix for 1.16.5?

**Comment by ShinyPorygon** [comment] 2022-10-31 20:58
Try clicking off to the side some, but likely no. 1.16 is already old and mostly unsupported.

**Comment by Sand-Master** [comment] 2022-10-31 20:58
> 

Okay, thank you for at least letting me know what the issue is. I appreciate it!
