### ISSUE TITLE
puting broad sword parts gives me kama

### ISSUE THREAD

**Issue by RaziJemni** [SlimeKnights/TinkersConstruct#4484] opened 2021-05-21 23:07 UTC
like i said in the title
im trying to make a sword with some good parts but when put it together its gives me kama
i tried with wood and stone still the same
i use /give and got a  white clean broad sword with nothing it
i tried the puting the parts in it but it crashed the server and my game
other mods:
archectury
cloth-config
create mod
ferritcore
ftb-ultimine
jei
je resources
optifine
spark

**Versions: 
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: latest update
* Tinkers Construct: 3.0.3.152

**Comment by ShinyPorygon** [comment] 2021-05-21 23:09
Duplicate of #4316

**Comment by RaziJemni** [comment] 2021-05-21 23:11
so its from optifine? should i remove i from the client or the server?

**Comment by ShinyPorygon** [comment] 2021-05-21 23:11
You shouldn't use optifine period. it's horrible in 1.16.

**Comment by RaziJemni** [comment] 2021-05-21 23:13
well it get fixed or optifine has to fix it?

**Comment by ShinyPorygon** [comment] 2021-05-21 23:14
If a bug is caused by that piece of trash mod it will not be fixed by us. It only causes ores to not generate, configs to corrupt, and hundreds of other issues.

**Comment by RaziJemni** [comment] 2021-05-21 23:16
any suggestion for mods that replace optifine?
just some fps boost no need for zoom or shader

**Comment by KnightMiner** [comment] 2021-05-21 23:18
Actually, this bug is not a bug. Look in the tinker station and you will see that you put in the recipe for the kama, not the broadsword. Sword is two tool handles.

So yes, its true we do not support optifine. They break a lot of stuff. But this is not one of the things they broke.

**Closed as completed by KnightMiner** 2021-05-21 23:18 UTC
Labels: 1.16, Works as Intended

**Comment by RaziJemni** [comment] 2021-05-21 23:20
you are right i was using that x thing
omfg im so dumb

**Comment by KnightMiner** [comment] 2021-05-21 23:32
Now, next time you make an issue actually follow the issue template. It would have told you to test with fewer mods, and that would have included testing without optifine.
