### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo

### ISSUE THREAD

**Issue by ThisIsMyUserCuz** [SlimeKnights/TinkersConstruct#4526] opened 2021-06-09 22:01 UTC
Tinkers is crashing due to slimeknights/tconstruct/library/client/MaterialRenderInfo

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.14.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/9/21 2:45 PM
Description: Initializing game

java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo
	at lucraft.mods.lucraftcore.LCConfig$Materials.<init>(LCConfig.java:108)
	at lucraft.mods.lucraftcore.LCConfig.<clinit>(LCConfig.java:36)
	at lucraft.mods.lucraftcore.addonpacks.AddonPackHandler.getAddonPacksDir(AddonPackHandler.java:61)
	at lucraft.mods.lucraftcore.core.LCClientHooks.insertAddonPackResourcePacks(LCClientHooks.java:37)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:789)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.library.client.MaterialRenderInfo
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at lucraft.mods.lucraftcore.LCConfig$Materials.<init>(LCConfig.java:108)
	at lucraft.mods.lucraftcore.LCConfig.<clinit>(LCConfig.java:36)
	at lucraft.mods.lucraftcore.addonpacks.AddonPackHandler.getAddonPacksDir(AddonPackHandler.java:61)
	at lucraft.mods.lucraftcore.core.LCClientHooks.insertAddonPackResourcePacks(LCClientHooks.java:37)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:789)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 474492592 bytes (452 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                        | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| L     | minecraft                         | 1.12.2                   | minecraft.jar                                 | None                                     |
	| L     | mcp                               | 9.42                     | minecraft.jar                                 | None                                     |
	| L     | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | forge                             | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | applecore                         | 3.4.0                    | AppleCore-mc1.12.2-3.4.0.jar                  | None                                     |
	| L     | appleskin                         | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| L     | avaritia                          | 3.3.0                    | Avaritia-1.12.2.jar                           | None                                     |
	| L     | base                              | 3.13.0                   | base-1.12.2-3.13.0.jar                        | None                                     |
	| L     | bookshelf                         | 2.3.557                  | Bookshelf-1.12.2-2.3.557.jar                  | None                                     |
	| L     | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | None                                     |
	| L     | contenttweaker                    | 1.12.2-4.10.0            | ContentTweaker-1.12.2-4.10.0.jar              | None                                     |
	| L     | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.20.647.jar             | None                                     |
	| L     | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.647.jar             | None                                     |
	| L     | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.647.jar             | None                                     |
	| L     | enderio                           | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderiobase                       | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderioconduitsappliedenergistics | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderioconduitsopencomputers      | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderioconduitsrefinedstorage     | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderioconduits                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderiointegrationforestry        | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderiointegrationtic             | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderiointegrationticlate         | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderioinvpanel                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderiomachines                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | enderiopowertools                 | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                     | None                                     |
	| L     | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                    | None                                     |
	| L     | heroesexpansion                   | 1.12.2-1.3.5             | HeroesExpansion-1.12.2-1.3.5.jar              | None                                     |
	| L     | infinity                          | 1.12                     | infinity-1.12.jar                             | None                                     |
	| L     | inventorypets                     | 2.0.6                    | inventorypets-1.12-2.0.6.jar                  | None                                     |
	| L     | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | None                                     |
	| L     | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar             | None                                     |
	| L     | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| L     | ironfurnaces                      | 1.3.5                    | ironfurnaces-1.3.5.jar                        | None                                     |
	| L     | jei                               | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| L     | lucraftcore                       | 1.12.2-2.4.14            | LucraftCore-1.12.2-2.4.14.jar                 | None                                     |
	| L     | oreexcavation                     | 1.4.140                  | OreExcavation-1.4.140.jar                     | None                                     |
	| L     | projecte                          | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                   | None                                     |
	| L     | speedsterheroes                   | 1.12.2-2.2.1             | SpeedsterHeroes-1.12.2-2.2.1.jar              | None                                     |
	| L     | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183 (3).jar          | None                                     |
	| L     | wawla                             | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                      | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.14.jar)
  lucraft.mods.lucraftcore.core.LCTransformer

* Forge:  1.12.2
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

Mods:
AppleCore-mc1.12.2-3.4.0 
AppleSkin-mc1.12-1.0.14
Avaritia-1.12.2
base-1.12.2-3.13.0
Bookshelf-1.12.2-2.3.557
CodeChickenLib-1.12.2-3.2.3.358-universal
ContentTweaker-1.12.2-4.10.0
CraftTweaker2-1.12-4.1.20.647
EnderIO-1.12.2-5.3.70
extrautils2-1.12-1.9.9
HeroesExpansion-1.12.2-1.3.5
infinity-1.12
inventorypets-1.12-2.0.6
InventoryTweaks-1.63
IronBackpacks-1.12.2-3.0.8-12
ironchest-1.12.2-7.0.72.847
ironfurnaces-1.3.5
jei_1.12.2-4.16.1.301
LucraftCore-1.12.2-2.4.14
OreExcavation-1.4.140
ProjectE-1.12.2-PE1.4.1
SpeedsterHeroes-1.12.2-2.2.1
TConstruct-1.12.2-2.13.0.183
Wawla-1.12.2-2.6.275
Mantle-1.12-1.3.3.55

**Comment by KnightMiner** [comment] 2021-06-09 22:09
Duplicate of #4441. You could spend 5 seconds and look at the pinned issue instead of making another duplicate.

**Closed as completed by KnightMiner** 2021-06-09 22:09 UTC
Labels: Duplicate, Can't Fix, Mod interaction, 1.12
