### ISSUE TITLE
Modded ores turning into iron

### ISSUE THREAD

**Issue by noellestaken** [SlimeKnights/TinkersConstruct#4383] opened 2021-04-20 07:03 UTC
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.92
* Tinkers Construct: 3.0.2.96

When I try to use Immersive Engineering’s ores in the smeltery, the ore goes in and melts, but turns into iron blocks and ingots when casted. I am using version 4.2.4-134 of Immersive Engineering.

**Comment by PrincessOfEvil** [comment] 2021-04-20 07:21
Duplicate of #4283.

**Closed as completed by PrincessOfEvil** 2021-04-20 07:21 UTC
Labels: Bug, Duplicate, 1.16
