### ISSUE TITLE
Game crushes after equping "Travelers gear"

### ISSUE THREAD

**Issue by Betislav** [SlimeKnights/TinkersConstruct#4829] opened 2022-04-10 12:50 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.88 

### Mantle Version

1.8.37 

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

[crash-2022-04-09_14.58.13-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8458967/crash-2022-04-09_14.58.13-client.txt)
[crash-2022-04-09_16.29.39-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8458968/crash-2022-04-09_16.29.39-client.txt)
[crash-2022-04-09_16.31.22-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8458969/crash-2022-04-09_16.31.22-client.txt)
[crash-2022-04-09_16.34.03-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8458970/crash-2022-04-09_16.34.03-client.txt)
[crash-2022-04-09_16.46.21-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8458971/crash-2022-04-09_16.46.21-client.txt)
[crash-2022-04-09_16.47.35-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8458972/crash-2022-04-09_16.47.35-client.txt)
[crash-2022-04-09_16.49.15-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8458973/crash-2022-04-09_16.49.15-client.txt)
[crash-2022-04-09_16.51.18-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8458974/crash-2022-04-09_16.51.18-client.txt)
[crash-2022-04-09_16.55.44-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8458975/crash-2022-04-09_16.55.44-client.txt)

Yes I was testing what is the issue, tried to turn off the shaders, even starting a new world, everytime I equip some part of "Travelers gear", it crashed. (I didnt try "Plate armor".)
Server console showed some issue with "item ID".
Server is runing on Hamachi. 
Game leted me to log in, but instantly crashed afterwards.
Quickly solving the issue - killed myself trough console and burning that gear in lava(revange). 

### Other mods

Included in crash report.

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment] 2022-04-10 12:53
Duplicate of #4734 remove optifine

If you want to use shaders, use rubidium + oculus. It allows you to use optifine shaders without using optifine. 
https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3654785
https://www.curseforge.com/minecraft/mc-mods/oculus/files/3654792

**Closed as completed by ShinyPorygon** 2022-04-10 12:53 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
