### ISSUE TITLE
Game crash error while trying to make a custom modpack

### ISSUE THREAD

**Issue by Gr3nKnight** [SlimeKnights/TinkersConstruct#4481] opened 2021-05-19 22:17 UTC
"The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo
Exit Code: -1"

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  midnight (themidnight-0.3.5.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.14.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 5/19/21 5:56 PM
Description: Initializing game

java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo
	at lucraft.mods.lucraftcore.LCConfig$Materials.<init>(LCConfig.java:108)
	at lucraft.mods.lucraftcore.LCConfig.<clinit>(LCConfig.java:36)
	at lucraft.mods.lucraftcore.addonpacks.AddonPackHandler.getAddonPacksDir(AddonPackHandler.java:61)
	at lucraft.mods.lucraftcore.core.LCClientHooks.insertAddonPackResourcePacks(LCClientHooks.java:37)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:789)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.library.client.MaterialRenderInfo
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at lucraft.mods.lucraftcore.LCConfig$Materials.<init>(LCConfig.java:108)
	at lucraft.mods.lucraftcore.LCConfig.<clinit>(LCConfig.java:36)
	at lucraft.mods.lucraftcore.addonpacks.AddonPackHandler.getAddonPacksDir(AddonPackHandler.java:61)
	at lucraft.mods.lucraftcore.core.LCClientHooks.insertAddonPackResourcePacks(LCClientHooks.java:37)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:789)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 740577208 bytes (706 MB) / 1400373248 bytes (1335 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 133 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                                | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
	|       | minecraft                         | 1.12.2                   | minecraft.jar                                         | None                                     |
	|       | mcp                               | 9.42                     | minecraft.jar                                         | None                                     |
	|       | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | forge                             | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | openmodscore                      | 0.12.2                   | minecraft.jar                                         | None                                     |
	|       | actuallyadditions                 | 1.12.2-r152              | ActuallyAdditions-1.12.2-r152.jar                     | None                                     |
	|       | aireducer                         | 0.2.1                    | AIReducer-1.12.2-0.2.1.jar                            | None                                     |
	|       | akashictome                       | 1.2-12                   | AkashicTome-1.2-12.jar                                | None                                     |
	|       | alcatrazcore                      | 1.0.4                    | alcatrazcore-1.0.4.jar                                | None                                     |
	|       | appliedenergistics2               | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar                  | None                                     |
	|       | armorunder                        | 1.0.0                    | armorunder-mc1.12.2-1.0.0.jar                         | None                                     |
	|       | aroma1997core                     | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                      | None                                     |
	|       | aroma1997sdimension               | 2.0.0.2                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar       | None                                     |
	|       | autoreglib                        | 1.3-32                   | AutoRegLib-1.3-32.jar                                 | None                                     |
	|       | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                                | None                                     |
	|       | betterbuilderswands               | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar       | None                                     |
	|       | biomesoplenty                     | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar         | None                                     |
	|       | bookshelf                         | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                          | None                                     |
	|       | brandonscore                      | 2.4.19                   | BrandonsCore-1.12.2-2.4.19.214-universal.jar          | None                                     |
	|       | buildcraftcompat                  | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                          | None                                     |
	|       | buildcraftbuilders                | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                          | None                                     |
	|       | buildcraftcore                    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                          | None                                     |
	|       | buildcraftenergy                  | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                          | None                                     |
	|       | buildcraftfactory                 | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                          | None                                     |
	|       | buildcraftlib                     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                          | None                                     |
	|       | buildcraftrobotics                | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                          | None                                     |
	|       | buildcraftsilicon                 | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                          | None                                     |
	|       | buildcrafttransport               | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                          | None                                     |
	|       | buildcraftbuilders                | 7.99.24.8                | buildcraft-builders-7.99.24.8.jar                     | None                                     |
	|       | buildcraftcompat                  | 7.99.24.8                | buildcraft-compat-7.99.24.8.jar                       | None                                     |
	|       | buildcraftcore                    | 7.99.24.8                | buildcraft-core-7.99.24.8.jar                         | None                                     |
	|       | buildcraftlib                     | 7.99.24.8                | buildcraft-core-7.99.24.8.jar                         | None                                     |
	|       | buildcrafttransport               | 7.99.24.8                | buildcraft-transport-7.99.24.8.jar                    | None                                     |
	|       | carrots                           | 1.0.0b1                  | carrotslib-mc1.12.2-1.0.0b1.jar                       | None                                     |
	|       | cctweaked                         | 1.89.2                   | cc-tweaked-1.12.2-1.89.2.jar                          | None                                     |
	|       | computercraft                     | 1.89.2                   | cc-tweaked-1.12.2-1.89.2.jar                          | None                                     |
	|       | chesttransporter                  | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                     | None                                     |
	|       | chisel                            | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                          | None                                     |
	|       | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar         | None                                     |
	|       | conarm                            | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                            | None                                     |
	|       | controlling                       | 3.0.10                   | Controlling-3.0.10.jar                                | None                                     |
	|       | ctm                               | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                             | None                                     |
	|       | danknull                          | 1.7.91                   | DankNull-1.12.2-1.7.91.jar                            | None                                     |
	|       | darkutils                         | 1.8.230                  | DarkUtils-1.12.2-1.8.230.jar                          | None                                     |
	|       | diethopper                        | 1.1                      | diethopper-1.1.jar                                    | None                                     |
	|       | draconicevolution                 | 2.3.27                   | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar    | None                                     |
	|       | dynamictrees                      | 1.12.2-0.9.23            | DynamicTrees-1.12.2-0.9.23.jar                        | None                                     |
	|       | dynamictreesbop                   | 1.12.2-1.5.1             | DynamicTreesBOP-1.12.2-1.5.1.jar                      | None                                     |
	|       | dynamictreesextrautils2           | 1.12.2-1.1.0             | DynamicTreesExtraUtils2-1.12.2-1.1.0.jar              | None                                     |
	|       | dynamictreesforestry              | 1.12.2-1.0.10            | DynamicTreesForestry-1.12.2-1.0.10.jar                | None                                     |
	|       | dynamictreesic2                   | 1.12.2-1.2.3             | DynamicTreesIC2-1.12.2-1.2.3.jar                      | None                                     |
	|       | dynamictreesnatura                | 1.12.2-1.1.7             | DynamicTreesNatura-1.12.2-1.1.7.jar                   | None                                     |
	|       | dynamictreesquark                 | 1.12.2-1.0.6             | DynamicTreesQuark-1.12.2-1.0.6.jar                    | None                                     |
	|       | dynamictreestc                    | 1.12.2-1.4.2             | DynamicTreesTC-1.12.2-1.4.2.jar                       | None                                     |
	|       | dynamictreesttf                   | 1.12.2-1.2.3             | dynamictreesTheTwilightForest-1.12.2-1.2.3.jar        | None                                     |
	|       | dynamictreestconstruct            | 1.12.2-1.2.7             | DynamicTreesTinkersConstruct-1.12.2-1.2.7.jar         | None                                     |
	|       | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                           | None                                     |
	|       | enderio                           | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderiobase                       | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderioconduitsappliedenergistics | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderioconduitsopencomputers      | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderioconduitsrefinedstorage     | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderioconduits                   | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderiointegrationforestry        | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderiointegrationtic             | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderiointegrationticlate         | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderioinvpanel                   | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderiomachines                   | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderiopowertools                 | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                             | None                                     |
	|       | enderio                           | 5.2.66                   | EnderIO-base-1.12.2-5.2.66.jar                        | None                                     |
	|       | enderiobase                       | 5.2.66                   | EnderIO-base-1.12.2-5.2.66.jar                        | None                                     |
	|       | enderioconduits                   | 5.2.66                   | EnderIO-conduits-1.12.2-5.2.66.jar                    | None                                     |
	|       | enderiopowertools                 | 5.2.66                   | EnderIO-conduits-1.12.2-5.2.66.jar                    | None                                     |
	|       | enderioconduitsappliedenergistics | 5.2.66                   | EnderIO-conduits-appliedenergistics-1.12.2-5.2.66.jar | None                                     |
	|       | enderiointegrationforestry        | 5.2.66                   | EnderIO-integration-forestry-1.12.2-5.2.66.jar        | None                                     |
	|       | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                            | None                                     |
	|       | fencejumper                       | 1.0.5                    | fencejumper-1.12-1.0.5.jar                            | None                                     |
	|       | firstaid                          | 1.6.16                   | firstaid-1.6.16.jar                                   | None                                     |
	|       | forestry                          | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                         | None                                     |
	|       | forgelin                          | 1.8.4                    | Forgelin-1.8.4.jar                                    | None                                     |
	|       | ftblib                            | 5.4.7.2                  | FTBLib-5.4.7.2.jar                                    | None                                     |
	|       | ftbutilities                      | 5.4.1.131                | FTBUtilities-5.4.1.131.jar                            | None                                     |
	|       | gravestone                        | 1.10.3                   | gravestone-1.10.3.jar                                 | None                                     |
	|       | heroesexpansion                   | 1.12.2-1.3.5             | HeroesExpansion-1.12.2-1.3.5.jar                      | None                                     |
	|       | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	|       | immersivepetroleum                | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                   | None                                     |
	|       | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar            | None                                     |
	|       | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                              | None                                     |
	|       | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                     | None                                     |
	|       | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                       | None                                     |
	|       | jei                               | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                             | None                                     |
	|       | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                           | None                                     |
	|       | jeresources                       | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar               | None                                     |
	|       | longfallboots                     | 1.2.1a                   | longfallboots-1.2.1b.jar                              | None                                     |
	|       | lostcities                        | 2.0.22                   | lostcities-1.12-2.0.22.jar                            | None                                     |
	|       | lostsouls                         | 1.1.4                    | lostsouls-1.12-1.1.4.jar                              | None                                     |
	|       | lucraftcore                       | 1.12.2-2.4.14            | LucraftCore-1.12.2-2.4.14.jar                         | None                                     |
	|       | lycanitesmobs                     | 2.0.7.2 - MC 1.12.2      | lycanitesmobs-1.12.2-2.0.7.2.jar                      | None                                     |
	|       | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                              | None                                     |
	|       | mcjtylib_ng                       | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                               | None                                     |
	|       | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                         | None                                     |
	|       | natura                            | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                            | None                                     |
	|       | notenoughwands                    | 1.8.1                    | notenoughwands-1.12-1.8.1.jar                         | None                                     |
	|       | openblocks                        | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                           | None                                     |
	|       | openmods                          | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                         | None                                     |
	|       | p455w0rdslib                      | 2.3.161                  | p455w0rdslib-1.12.2-2.3.161.jar                       | None                                     |
	|       | patchouli                         | 1.0-23.6                 | Patchouli-1.0-23.6.jar                                | None                                     |
	|       | quark                             | r1.6-179                 | Quark-r1.6-179.jar                                    | None                                     |
	|       | quickleafdecay                    | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                     | None                                     |
	|       | realistictorches                  | 2.1.2                    | RealisticTorches-1.12.2-2.1.2.jar                     | None                                     |
	|       | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar               | None                                     |
	|       | rustic                            | 1.1.7                    | rustic-1.1.7.jar                                      | None                                     |
	|       | scalinghealth                     | 1.3.37                   | ScalingHealth-1.12.2-1.3.42+147.jar                   | None                                     |
	|       | silentlib                         | 3.0.13                   | SilentLib-1.12.2-3.0.14+168.jar                       | None                                     |
	|       | spartanweaponry                   | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar                 | None                                     |
	|       | speedsterheroes                   | 1.12.2-2.2.1             | SpeedsterHeroes-1.12.2-2.2.1.jar                      | None                                     |
	|       | srparasites                       | 1.9.0                    | SRParasites-1.12.2v1.9.0ALPHA14.jar                   | None                                     |
	|       | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                      | None                                     |
	|       | teslacorelib                      | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                      | None                                     |
	|       | teslacorelib_registries           | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                      | None                                     |
	|       | thaumcraft                        | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                      | None                                     |
	|       | tcinventoryscan                   | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar            | None                                     |
	|       | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                                    | None                                     |
	|       | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                   | None                                     |
	|       | torchmaster                       | 1.8.4.84                 | torchmaster_1.12.2-1.8.4.84.jar                       | None                                     |
	|       | toughasnails                      | 3.1.0.139                | ToughAsNails-1.12.2-3.1.0.139-universal.jar           | None                                     |
	|       | tanaddons                         | 3.4.24                   | ToughExpansion-1.12-3.4.24.jar                        | None                                     |
	|       | trumpetskeleton                   | 1.12-1.0.2.1             | trumpetskeleton-1.12-1.0.2.1.jar                      | None                                     |
	|       | twilightforest                    | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar         | None                                     |
	|       | waystones                         | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                            | None                                     |
	|       | immersiveengineering              | 0.12-98                  | ImmersiveEngineering-0.12-98.jar                      | None                                     |
	|       | llibrary                          | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                            | None                                     |
	|       | midnight                          | 0.3.5                    | themidnight-0.3.5.jar                                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Forgelin-1.8.4.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.14.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.47' Renderer: 'NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2'
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.47, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor

**Comment by KnightMiner** [comment] 2021-05-19 22:35
Duplicate of #4441, not our bug. LUCraft is using one of our classes wrongly, probably due to a poorly made core mod, report to them.

**Closed as completed by KnightMiner** 2021-05-19 22:35 UTC
Labels: Duplicate, Can't Fix, Mod interaction, 1.12
