### ISSUE TITLE
Crash when using a tool in a tool station

### ISSUE THREAD

**Issue by SerialCrasher23** [SlimeKnights/TinkersConstruct#3383] opened 2018-02-16 21:24 UTC
https://pastebin.com/FsDt7brS
Whenever I try to add the tool in the tool station, the game crash. May be related to the Forge version? I'm using 2611

**Comment by TherminatorX** [comment] 2018-02-16 22:18
Dupe of #3372, known TAIGA issue

**Closed** 2018-02-16 23:43 UTC
