### ISSUE TITLE
Crash when trying to put on slime mob skull helmet

### ISSUE THREAD

**Issue by CinnamonShaey** [SlimeKnights/TinkersConstruct#4779] opened 2022-02-22 22:03 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

Mantle-1.18.1-1.8.31.jar

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.1.46.jar

### Describe your issue

when i try to put on the slime mob skull helmets no matter which one it crashes my game, not the server only my client and when i try to log back on it crashes right away when i look inside my inventory

### Crash Report

https://pastebin.com/Fg03UTLx

### Reproduced with only Tinkers' Construct?

No

### Other mods required

its over 10 its something like 30 ish

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-22 22:03
Duplicate of #4734 Good to know that you didn't actually check the issue tracker. Remove optifine.

**Closed as completed by ShinyPorygon** 2022-02-22 22:03 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18

**Comment by CinnamonShaey** [comment] 2022-02-22 22:56
i did tho, dident search well enough apparently but i did try and search cause its not really tinkers "armor" so im my head that title is wrong

**Comment by KnightMiner** [comment] 2022-02-22 23:05
The search checkbox tells you to check "pinned issues". Do you know how to find pinned issues? Its right above the new issue button on the issues page (which you should have visited during your search)
![image](https://user-images.githubusercontent.com/12155288/155234547-a9026c3d-3120-430d-bb2f-70da3558a9ff.png)

**Comment by CinnamonShaey** [comment] 2022-02-22 23:08
well, that is my fault then i missed that, sorry im not perfect

**Comment by KnightMiner** [comment] 2022-02-22 23:17
Not asking you to be perfect. Don't be so hard on yourself. The reason the issue template is so detailed is to help prevent you from making mistakes. Sure, they still happen, please learn from your mistakes so next time you do better at finding existing issues.

**Comment by CinnamonShaey** [comment] 2022-02-22 23:18
yea i do get that, i did try, just not well enough
