### ISSUE TITLE
Optifine internal shaders breaks rendering of some blocks

### ISSUE THREAD

**Issue by TheFakePlayerGame** [SlimeKnights/TinkersConstruct#5230] opened 2024-05-25 07:39 UTC
### Minecraft Version

1.19.2

### Forge Version

43.3.0

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

Block textures don't render properly.
MacOS
![2024-05-25_09 36 22](https://github.com/SlimeKnights/TinkersConstruct/assets/170792598/3c3e51e2-7f78-4e49-b5e1-6684ea881d22)
Only happens with optifine when internal shaders were turned on, have not tested with other shaders but can confirm it does not happen with shaders off.

### Other mods

optifine

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment] 2024-05-25 08:50
Duplicate of #4316 Optifine is not supported.

**Closed as completed by ShinyPorygon** 2024-05-25 08:50 UTC
Labels: Performance Enhancers/Optifine, Can't Fix, 1.19
