### ISSUE TITLE
molten iron turns into copper when poured into basin or casting table

### ISSUE THREAD

**Issue by ianm1647** [SlimeKnights/TinkersConstruct#4386] opened 2021-04-20 20:14 UTC
Molten iron cools into copper ingot/block when poured into either the casting table/basin.
It was while using the melter so I can get started with Tinker Tools.

Versions:
Minecraft: 1.16.5
Forge: 36.1.4
Mantle: 1.6.92 
Tinkers Construct: 3.0.3.111

I looked on the list of issues and couldn't find this on there

I'm using a big list of mods , somewhere around 250. It cannot be recreated by itself, and I'm not sure what is creating the problem.

**Comment by ShinyPorygon** [comment] 2021-04-20 20:19
Duplicate of #4283

**Comment by KnightMiner** [comment] 2021-04-20 21:57
> I looked on the list of issues and couldn't find this on there

Did you try the pinned issues at the top?

**Closed as completed** 2021-04-20 21:56 UTC
Labels: Bug, Duplicate, Performance Enhancers/Optifine, 1.16
