### ISSUE TITLE
[1.12] [Compatibility] Tools cannot be used by player simulation machines from other mods

### ISSUE THREAD

**Issue by Jack-McKalling** [SlimeKnights/TinkersConstruct#4135] opened 2020-06-23 09:35 UTC
**Issue description:**
Tinkers tools such as the scythe and hammer effectively cannot be used in a fake player simulator from other mods, such as the Automated User from Cyclic, or Player Simulator from Integrated Tunnels. The area of effect on the item gets completely ignored such that only one block is affected, and any right-click effect the tool would normally have when manually used never occurs.

Right clicking a scythe on plants with a Player Simulator has no effect, other than frustration that nothing happens. Continuously left-clicking a hammer with silk touch on stone has the effect that only the single middle block gets broken and drops stone (not cobblestone), so it does break the block using the tool properties as opposed to just any random item.

With Tinkers Tool Levelling installed, the tool does increase in XP by a Player Simulator (although only for the single block that gets affected), but this doesn't happen in an Automated User.

I used the following setup for testing, but I reproduced with even less mods as well, listed down below.
![scythe harvesting](https://user-images.githubusercontent.com/14236702/85384767-c45aad00-b541-11ea-89e4-8933ad6277dc.jpg)
Setup of simulator:
* Variable card inserted into "Click Item", choice(Redstone high, Item-Scythe, Item-empty)
* Right click: true
* Right hand: true
* Continuous click: false
* Check damage: false
* Check NBT: false
* all other settings on default

Scythe properties:
* Supremium tough tool rod
* Superium scythe head
* Manyullyn tough binding
* Prudentium tough tool rod
* 3x creative modifier
* 5x Reinforced; Unbreaking
* 3x Luck

Hammer properties:
* Supremium tough tool rod
* Cobalt hammer head
* Manyullyn large plate
* Sponge large plate
* 2x creative modifier
* 5x Reinforced; Unbreaking

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183
* Tinkers Complement: 1.12.2-0.4.3
* Tinkers Tool Leveling: 1.12.2-1.1.0

**Can it be reproduced with *just* Tinkers Construct? Remove any mods besides Mantle and Tinkers Construct to test.**

Requires:
* Cyclops Core 1.12.2-1.6.4
* CommonCapabilities 1.12.2-2.4.6
* Cyclic 1.20.3
* Integrated Dynamics 1.12.2-1.1.6
* IntegratedDynamics Compat 1.0.0
* Integrated Tunnels 1.12.2-1.6.11
* IntegratedTunnels Compat 1.0.0

Not affected by mods in screenshot:
* Cooking for Blockheads (Tool Rack)
* Tiny Progressions (Growth Crystal tier 3)
* Mystical Agriculture / Mystical Agraditions (scythe/hammer tool materials)

**Comment by KnightMiner** [comment] 2021-01-26 04:35
Looks like this was caused by Integrated Tunnels and fixed on their side, closing

**Closed as completed by KnightMiner** 2021-01-26 04:35 UTC
