### ISSUE TITLE
Two Major crashes that need fixing in order to have my pack working again

### ISSUE THREAD

**Issue by TacticalUniverse** [SlimeKnights/TinkersConstruct#3631] opened 2018-08-31 18:48 UTC
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**
https://gist.github.com/TacticalUniverse/bfd2d174f8c19c799635836bff2e48db

https://gist.github.com/TacticalUniverse/47d27fb236b16c087b7c24a3c93b60f9

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2755 and up
* Mantle: 1.3.2.24
* Tinkers Construct: 2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Not sure as its happening as I start the pack up.

**Comment by KnightMiner** [comment] 2018-09-01 04:04
Try that last question again. It means you are supposed to test with just Tinkers installed, or find the list of mods. This does not happen when I play the mod, so the issue is something with your setup, hep us find the mod that causes this.

**Comment by TacticalUniverse** [comment] 2018-09-01 17:27
I already found out that it is PlusTiC doing the crash and that is why I referenced the issue to them

**Comment by KnightMiner** [comment] 2018-09-01 17:39
In that case, closing this as a PlusTiC issue.

**Closed by KnightMiner** 2018-09-01 17:39 UTC
Labels: Not enough information
