### ISSUE TITLE
Tinkers Construct causing Abstract Error

### ISSUE THREAD

**Issue by reesmr** [SlimeKnights/TinkersConstruct#4642] opened 2021-10-19 20:01 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

When I launch the game, it lets me get as far as the world select, but once I select a world, the game crashes. I will attach the crash report.

### Crash Report

[crash-2021-10-19_15.40.28-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/7376345/crash-2021-10-19_15.40.28-client.txt)

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment] 2021-10-19 20:04
Duplicate of #4631

**Closed as completed by ShinyPorygon** 2021-10-19 20:04 UTC
Labels: Duplicate, 1.16

**Comment by KnightMiner** [comment] 2021-10-19 20:22
Also, you lied on your report. You did not reproduce this issue with only Tinkers, it requires JEI to happen. The issue template is not meant to be ignored, its meant to give you some steps to follow which may solve your problem.

If you are not willing to follow a minimal set of steps to report your issue, why do you expect us to spend time helping you?

**Comment by reesmr** [comment] 2021-10-19 20:47
> Also, you lied on your report. You did not reproduce this issue with only Tinkers, it requires JEI to happen. The issue template is not meant to be ignored, its meant to give you some steps to follow which may solve your problem.
> 
> If you are not willing to follow a minimal set of steps to report your issue, why do you expect us to spend time helping you?

I'm sorry, I misunderstood the question. I did test it with and without many mods but I did not realize which one.
