### ISSUE TITLE
Piggybackpack mob suffocation in ceiling made the piggybackpack not work anymore

### ISSUE THREAD

**Issue by turtleisaac** [SlimeKnights/TinkersConstruct#3637] opened 2018-09-03 01:29 UTC
Had chicken on, it suffocated in ceiling. Piggybackpack no longer works, cant pick up new mobs with it

**Comment by KnightMiner** [comment] 2018-09-03 11:51
Did you take the piggybackpack off your back before trying to pick up another mob?

**Comment by turtleisaac** [comment] 2018-09-03 14:45
yes

**Comment by KnightMiner** [comment] 2019-10-13 22:18
I cannot reproduce this in the latest version, and since this issue is pretty old I'm closing this.

**Closed by KnightMiner** 2019-10-13 22:18 UTC
