### ISSUE TITLE
Fluid Dupe / Makes Quitting from Tinkers Mod 

### ISSUE THREAD

**Issue by JezzyCrazyTV** [SlimeKnights/TinkersConstruct#4811] opened 2022-03-22 14:41 UTC
### Minecraft Version

1.16.5

### Forge Version

v. 0.194.1.6

### Mantle Version

Idk

### Tinkers' Construct Version

36.2.20

### Describe your issue

Im using Create and Beyond tinkers and when i like for an example put Gold inside a Ingot Frame then i get a Gold ingot very normal but then when i put an other ore like iron i still get gold and even if i put cobalt and ore i even can make blood to a ball then everything without a cast will turn into blood like the first thing i did with that shape its going to stay like that.
(And using Optifine tho idk if thats the reason and Btw Create and Beyond is the Modpack so Tinkers is just a mod so i wont play with just Tinkers. I searched everywhere on Google)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/82102312/159506466-13a87ab2-acef-4599-99c1-d47f8f62ab05.gif)

### Other mods

Create and Beyond

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment] 2022-03-22 14:45
Well. Quite a few things... 

A) There is not really enough information here to even determine what exact versions you are using. Nor really what the issue is.

B) This sounds like an extremely old bug with performant. 

C) Optifine causes many issues beyond belief

D) Create Above and Beyond has not updated in over 2 months for 1.16, they have an older version of tinkers. Which assuming you've not touched the pack you'd also have this older version.

**Comment by KnightMiner** [comment] 2022-03-22 14:59
I agree that this sounds like #4283. Please confirm whether you are using Performant. If you are not, provide more information including a full mod list (the fact you added Optifine implies you may have modified the pack further so just give the full list you are using)

**Comment by JezzyCrazyTV** [comment] 2022-03-22 15:33
Yeah i do just remember i used Performant but nothing changed so i can delet that (i dint know you guys react so fast i watch my issue being up for 1 min then go) [Im going to Delet Performant and Restart]

**Comment by JezzyCrazyTV** [comment] 2022-03-22 15:35
> Well. Quite a few things...
> 
> A) There is not really enough information here to even determine what exact versions you are using. Nor really what the issue is.
> 
> B) This sounds like an extremely old bug with performant.
> 
> C) Optifine causes many issues beyond belief
> 
> D) Create Above and Beyond has not updated in over 2 months for 1.16, they have an older version of tinkers. Which assuming you've not touched the pack you'd also have this older version.

Btw you can send me a new version of tinkers 1.16.5 that would be nice

**Comment by JezzyCrazyTV** [comment] 2022-03-22 15:36
Btw guys im going to try that and what you guys say because my minecraft went from smooth to just a potato pc it happend and i did nothing so im just going to try things and recall my self.

**Comment by JezzyCrazyTV** [comment] 2022-03-22 15:37
> I agree that this sounds like #4283. Please confirm whether you are using Performant. If you are not, provide more information including a full mod list (the fact you added Optifine implies you may have modified the pack further so just give the full list you are using)

Oh dint saw that and sorry for bad title then.

**Comment by JezzyCrazyTV** [comment] 2022-03-22 15:43
Bruh the Converter Website just delet 99% of my video

**Comment by JezzyCrazyTV** [comment] 2022-03-22 15:50
I guess it works now.?
Thanks for the help.
(I State if the error does Happend wonce more.)

**Comment by KnightMiner** [comment] 2022-03-22 17:15
Sounds like you were using performant and removing it fixed the issue, so going to close this as a duplicate of #4283. If you see this again and do not have performant, comment here with a full mod list.

**Closed as completed by KnightMiner** 2022-03-22 17:15 UTC
Labels: Duplicate, Performance Enhancers/Optifine, 1.16
