### ISSUE TITLE
[1.16] Materials and You Hand Axe Entry has Wrong Tool

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#4436] opened 2021-05-04 04:14 UTC
**Issue description:**
In Materials and You Hand Axe Entry has the icon and title of the Pickax 
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16
* Forge: 36.1.15
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.136

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
The issue came with the new update. 
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes

**Comment by KnightMiner** [comment] 2021-05-04 04:42
Can't reproduce personally, but I see the old name for axe is being referenced on that page, so perhaps that is a cause in some worlds

**Comment by KnightMiner** [comment] 2021-05-07 07:30
Fixed in 3.0.3.144

**Closed as completed by KnightMiner** 2021-05-07 07:30 UTC
Labels: Bug, Resolved, 1.16
