### ISSUE TITLE
[1.12] Invar Not Possible?

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#3081] opened 2017-08-05 02:47 UTC
We are not seeing invar being an alloy possible in the smeltery.  Is this a change or is it a bug?

2 Iron and 1 Nickel correct?

**Comment by Landmaster** [comment] 2017-08-05 12:18
@MokahTGS Possible duplicate of #2813; for now, use an addon mod that supports invar alloying, such as PlusTiC.

**Comment by KnightMiner** [comment] 2017-08-06 01:49
Duplicate of #2813

**Closed** 2017-08-06 01:50 UTC
Labels: duplicate
