### ISSUE TITLE
Multiple smelteries results in incorrect fluid usage.

### ISSUE THREAD

**Issue by mrStorrs** [SlimeKnights/TinkersConstruct#4727] opened 2022-01-21 22:47 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Describe your issue

When you have more than one smelteries built and there is different molten fluid in each, the fluid type will get "stuck" with the last used fluid of the first smeltery you use.

Steps to replicate:
1. build 2 smelteries
2. In smeltery A put iron
3. In smeltery B put copper
4. Create an ingot in smeltery A (ingot will come out iron)
----Here the smelter will use some of the molten iron to make a iron ingot
5. Create an ingot in smeltery B (ingot will again come out iron instead of copper)
----Here the smelter will use copper, but will produce an iron ingot.

This can be done with any fluid. You could make gold ingots using water.  

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by Random832** [comment] 2022-01-21 22:57
Are you *sure* you're not using any performance enhancing mods? this sounds very similar to a bug we've had in the past from Performant. It's supposed to have been fixed there a while ago too, so either you're on an old version of it or something weird is going on.

**Comment by KnightMiner** [comment] 2022-01-21 22:59
I suspect this is a duplicate of #4283. As Random said, Performant bug, nothing we ca do. You probably need to update Performant, or remove it.

Fill out the issue template properly next time instead of lying and saying you reproduced a bug with just TiC when you did not. If I am wrong and you actually are getting this with just TiC I apologize, say so and provide more information and I will look into this again. I have never experienced what you claim though, so I have almost 0 doubt its Performant.

**Closed as completed by KnightMiner** 2022-01-21 22:59 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Mod interaction, 1.16
