### ISSUE TITLE
im trying to launch modded minecraft with forge 1.12.2 and i keep getting this error message

### ISSUE THREAD

**Issue by subandrew684626** [SlimeKnights/TinkersConstruct#4486] opened 2021-05-23 18:27 UTC
[minecraft crash error.txt](https://github.com/SlimeKnights/TinkersConstruct/files/6528666/minecraft.crash.error.txt)

 this is the pastebin for the entire thing but this is what a small portian is

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo
Exit Code: -1

how do i fix this its driving me insane

**Comment by KnightMiner** [comment] 2021-05-23 18:39
Duplicate of #4441, not our bug. LUCraft is using one of our classes wrongly, probably due to a poorly made core mod, report to them.

**Closed as completed by KnightMiner** 2021-05-23 18:39 UTC
Labels: Duplicate, Mod interaction, 1.12
