### ISSUE TITLE
Huge lag when activating a faucet with redstone repeatedly (2.2.0b)

### ISSUE THREAD

**Issue by homemmakako** [SlimeKnights/TinkersConstruct#1962] opened 2016-03-20 13:45 UTC
I had 3 faucets pouring into casting tables and they worked just fine by hand. However, after making a redstone clock (with a redstone comparator) to quickly activate all of the faucets, my fps went from 40 to 5. I also tried using a lever and right clicking it continuously insted of a clock (I thought the problem could be the high frequency of the clock) but the outcome was the same, except the the fps went to 12 instead of 5.

**Comment by bonii-xx** [comment] 2016-03-20 16:23
Do you have a screenshot of the setup?

**Comment by homemmakako** [comment] 2016-03-20 21:19
http://prntscr.com/ahsjd4

**Comment by bonii-xx** [comment] 2016-03-22 17:09
Works fine for me so far.

Judging by your already low 40fps without anything going on I wager it's the graphic updates of the redstone causing it.

**Comment by laz2727** [comment] 2016-03-22 17:12
Probably the lamp.

2016-03-22 22:09 GMT+05:00 boni <notifications@github.com>:

**Comment by TherminatorX** [comment] 2016-03-22 20:49
@laz2727 The lamp is not powered by the redstone dust in this screenshot, and is only an indicator of the clock being on.

That said, redstone by itself can cause lighting-related lag when switching states. Always light up your circuitry to prevent this from becoming a problem. (This is just advice and may not solve the root of the problem)

**Comment by TherminatorX** [comment] 2016-03-22 21:55
Interesting quirk found: faucets will drain when they detect a change in redstone power level, not just having or not having a signal. This is definitely an issue, and it might be the cause of this.

**Comment by TherminatorX** [comment] 2016-03-22 22:07
@homemmakako Until Boni fixes this 'pour' performance :wink:, I suggest rearranging your setup to this:
http://imgur.com/wthd34R
Hooray for vanilla mechanics! (And basins depositing solid contents into hoppers)
Just be careful logging out while it's running, as per #1967

**Comment by homemmakako** [comment] 2016-03-23 19:23
Yeah, I guess I'll have to wait, though that other setup seems like a good idea as well. Oh, and btw @TherminatorX , nice pun :D

**Comment by codewarrior0** [comment] 2016-03-25 14:23
>I wager it's the graphic updates of the redstone causing it.

What's curious is that this only happens when the redstone clock is directly adjacent to the smeltery. Putting the clock one block away from the smeltery, yet still in the same chunk, does not exhibit the FPS loss or the stutter.

Just a hunch: Could this have anything to do with the way the smeltery multiblock will rebuild itself whenever a block is changed adjacent to it?

**Comment by bonii-xx** [comment] 2016-03-25 14:35
That is a good hunch. Smelteries recheck themselves when blocks adjacent to them change. This should only happen when the block next to one of them changes.. I guess the redstone clock causes that though.

**Comment by bonii-xx** [comment] 2016-03-26 08:49
I can confirm that redstone changes next to smeltery blocks cause the issue. The bad news is that I can't fix it because there's no way to determine if it was a redstone change or a block placed. The good news is that you can simply prevent it by not placing rapidly changing redstone next to them. >_>

**Comment by codewarrior0** [comment] 2016-03-26 09:01
Even placing the redstone wire horizontally away from the seared faucet exhibits this issue. This makes redstone-automated casting pretty much unusable.

Do you have any other ideas for continuous casting? As wonky as they were, I kind of liked the old casting channels, just because a faucet above them would run continuously as long as the channel wasn't completely full.

**Comment by laz2727** [comment] 2016-03-26 12:24
Just slow the redstone down. You don't need to switch the faucets every two
rs ticks.

**Comment by laz2727** [comment] 2016-03-26 12:24
Oh, and any pipes would probably work.

**Comment by bonii-xx** [comment] 2016-03-26 14:09
Can you check if a XU redstone clock on a smeltery wall also causes issues? No vanilla redstone.

I suspect that either the block updates changed between 1.7 and 1.8 or that it's only vanilla redstone that causes it.

**Comment by codewarrior0** [comment] 2016-03-26 14:10
A NeoTech redstone clock on the smeltery wall does cause the issue.

**Comment by bonii-xx** [comment] 2016-04-05 15:44
It looks like vanilla redstone is bugged, and firing update events left and right to all neighbor blocks of neighbors. I brutally blacklisted redstone for the updates for now.

**Comment by codewarrior0** [comment] 2016-04-06 01:12
Not sure if this is relevant, but it seems that in 1.7.10, block updates are issued while a faucet is emptying into a basin. My FPS drops while I have three basins filling, and goes back up to normal when they're done. 

This doesn't happen on natural terrain, but it does happen in the part of my base where I built my smeltery - where I have a lot of IE wire connectors [which are very expensive to render](https://github.com/BluSunrize/ImmersiveEngineering/issues/701).

**Comment by laz2727** [comment] 2016-04-06 06:54
It was a rendering bug that was fixed in 1.8.9.

**Comment by RenEvo** [comment] 2016-04-19 17:16
@bonii-xx couldn't you just whitelist the smeltry blocks in that update, rather than individually blacklisting? This could solve all modded and vanilla update issues I would think.

i.e.:

```
if(neighborBlock != this) {
    return;
}
```

I would assume that only smeltry block updates should trigger smeltry changes?

**Closed** 2016-05-29 13:27 UTC
Labels: bug, Resolved
