### ISSUE TITLE
Materials converts into first material used in Smeltery

### ISSUE THREAD

**Issue by AarcherCZE** [SlimeKnights/TinkersConstruct#4524] opened 2021-06-08 15:55 UTC
**Issue description:**
When using the smeltery for getting ingots or blocks, the first material is correct but next materials will change to the first one (eg. when already used Smeltery for Bronze, every other material will be Bronze, be it gold, copper, iron, etc.). Only happens with ingots and blocks, parts are OK. If I need to work with other material, I have to restart the server.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.2
* Mantle: 1.6.103
* Tinkers Construct: 3.0.4.171

Not mentioned on the roadmap or "What's new?"

Happens only with Tinkers Construct, as it happens to both vanilla and modded materials.

The two photos attached are from a single player world where I first took a bronze ingot and then I proceeded to take out a gold ingot. It can be clearly seen that Molten Gold is going out but after all, it is a bronze ingot.
![2021-06-08_17 53 43](https://user-images.githubusercontent.com/78590444/121217900-9077b500-c882-11eb-9f34-85fb7acb36c5.png)
![2021-06-08_17 53 48](https://user-images.githubusercontent.com/78590444/121217922-940b3c00-c882-11eb-8bf1-bcab047c0a68.png)

**Comment by PrincessOfEvil** [comment] 2021-06-08 15:56
Please confirm that you don't actually have an ancient version of Performant installed.

**Comment by ShinyPorygon** [comment] 2021-06-08 15:56
Performant?

**Comment by KnightMiner** [comment] 2021-06-08 15:58
Considering they skipped half the issue template, I'm going to assume performant. Nothing in the base mod would cause this bug.

So duplicate of #4283. Properly fill out the issue template if you disagree.

**Closed as completed by KnightMiner** 2021-06-08 15:58 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, Mod interaction, 1.16

**Comment by AarcherCZE** [comment] 2021-06-08 16:22
Sorry for the issue template. First time reporting something, so it was very new for me.

Performant updated and the issue disappeared. Thanks for the quick answer.
