### ISSUE TITLE
Issues with Tinker's construct crashing the game when opening worlds

### ISSUE THREAD

**Issue by foxesinthewood** [SlimeKnights/TinkersConstruct#4757] opened 2022-02-16 03:25 UTC
### Minecraft Version

1.16.5

### Forge Version

Java

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.0.2.84

### Describe your issue

Crashing worlds as soon as I open them.

### Crash Report

---- Minecraft Crash Report ---- // Don't be sad, have a hug! <3  Time: 2/15/22 7:13 PM Description: Unexpected error  java.lang.AbstractMethodError: Method slimeknights/tconstruct/library/recipe/casting/ItemCastingRecipe$Basin.getType()Lnet/minecraft/item/crafting/IRecipeType; is abstract 	at slimeknights.tconstruct.library.recipe.casting.ItemCastingRecipe$Basin.getType(ItemCastingRecipe.java) ~[?:1.16.5-3.0.2.84] {re:classloading} 	at slimeknights.tconstruct.plugin.jei.casting.CastingBasinCategory.isHandled(CastingBasinCategory.java:23) ~[?:1.16.5-3.0.2.84] {re:classloading} 	at slimeknights.tconstruct.plugin.jei.casting.CastingBasinCategory.isHandled(CastingBasinCategory.java:10) ~[?:1.16.5-3.0.2.84] {re:classloading} 	at mezz.jei.recipes.RecipeManagerInternal.addRecipe(RecipeManagerInternal.java:117) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.recipes.RecipeManagerInternal.addRecipeTyped(RecipeManagerInternal.java:101) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:94) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.recipes.RecipeManagerInternal.<init>(RecipeManagerInternal.java:86) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:145) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:74) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$6904/842945898.accept(Unknown Source) ~[?:?] {} 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {} 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {} 	at net.minecraftforge.eventbus.EventBus$$Lambda$3023/1842314090.invoke(Unknown Source) ~[?:?] {} 	at net.minecraftforge.eventbus.EventBus$$Lambda$3229/1209048612.invoke(Unknown Source) ~[?:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {} 	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:779) ~[?:?] {re:classloading} 	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1314) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:light.NetworkLightUpdateMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) ~[?:?] {re:classloading} 	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) ~[?:?] {re:classloading} 	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?] {re:classloading,xf:OptiFine:default} 	at net.minecraft.network.PacketThreadUtil$$Lambda$9069/1849145050.run(Unknown Source) ~[?:?] {} 	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?] {re:classloading} 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading} 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A} 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {} 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {} 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {} 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.20.jar:36.2] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/703232177.call(Unknown Source) [forge-1.16.5-36.2.20.jar:36.2] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at slimeknights.tconstruct.library.recipe.casting.ItemCastingRecipe$Basin.getType(ItemCastingRecipe.java) ~[?:1.16.5-3.0.2.84] {re:classloading} 	at slimeknights.tconstruct.plugin.jei.casting.CastingBasinCategory.isHandled(CastingBasinCategory.java:23) ~[?:1.16.5-3.0.2.84] {re:classloading} 	at slimeknights.tconstruct.plugin.jei.casting.CastingBasinCategory.isHandled(CastingBasinCategory.java:10) ~[?:1.16.5-3.0.2.84] {re:classloading} 	at mezz.jei.recipes.RecipeManagerInternal.addRecipe(RecipeManagerInternal.java:117) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.recipes.RecipeManagerInternal.addRecipeTyped(RecipeManagerInternal.java:101) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:94) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.recipes.RecipeManagerInternal.<init>(RecipeManagerInternal.java:86) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:145) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:74) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106) ~[?:7.7.1.145] {re:classloading} 	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$6904/842945898.accept(Unknown Source) ~[?:?] {} 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {} 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {} 	at net.minecraftforge.eventbus.EventBus$$Lambda$3023/1842314090.invoke(Unknown Source) ~[?:?] {} 	at net.minecraftforge.eventbus.EventBus$$Lambda$3229/1209048612.invoke(Unknown Source) ~[?:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {} 	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:779) ~[?:?] {re:classloading} 	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1314) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:light.NetworkLightUpdateMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) ~[?:?] {re:classloading} 	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) ~[?:?] {re:classloading} 	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?] {re:classloading,xf:OptiFine:default} 	at net.minecraft.network.PacketThreadUtil$$Lambda$9069/1849145050.run(Unknown Source) ~[?:?] {} 	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?] {re:classloading} 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading} 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default} -- Affected level -- Details: 	All players: 1 total; [ClientPlayerEntity['foxesofthewood'/17, l='ClientLevel', x=8.50, y=65.00, z=8.50]] 	Chunk stats: Client Chunk Cache: 441, 0 	Level dimension: minecraft:overworld 	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511) 	Level time: 0 game time, 0 day time 	Server brand: forge 	Server type: Integrated singleplayer server Stacktrace: 	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A} 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A} 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {} 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {} 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {} 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.20.jar:36.2] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/703232177.call(Unknown Source) [forge-1.16.5-36.2.20.jar:36.2] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}   -- System Details -- Details: 	Minecraft Version: 1.16.5 	Minecraft Version ID: 1.16.5 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 1.8.0_51, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 783304216 bytes (747 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB) 	CPUs: 16 	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	ModLauncher: 8.0.9+86+master.3cf110c 	ModLauncher launch target: fmlclient 	ModLauncher naming: srg 	ModLauncher services:  		/mixin-0.8.4.jar mixin PLUGINSERVICE  		/eventbus-4.0.0.jar eventbus PLUGINSERVICE  		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE  		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE  		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE  		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE  		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE  		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE  		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE  		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE  	FML: 36.2 	Forge: net.minecraftforge:36.2.20 	FML Language Providers:  		javafml@36.2 		minecraft@1 	Mod List:  		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE 		TConstruct-1.16.5-3.0.2.84.jar                    |Tinkers' Construct            |tconstruct                    |3.0.2.84            |DONE      |Manifest: NOSIGNATURE 		FarmersDelight-1.16.5-0.5.4.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.5.4        |DONE      |Manifest: NOSIGNATURE 		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5 		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90 		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: NOSIGNATURE 		Mantle-1.16.5-1.6.157.jar                         |Mantle                        |mantle                        |1.6.157             |DONE      |Manifest: NOSIGNATURE 		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |DONE      |Manifest: NOSIGNATURE 		JRFTL+[1.16.5]-1.2.jar                            |JRFTL                         |jrftl                         |1.2                 |DONE      |Manifest: NOSIGNATURE 		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE 		WAWLA-1.16.5-8.0.1.jar                            |WAWLA                         |wawla                         |8.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5 		WailaHarvestability-mc1.16.x-forge-1.1.15.jar     |Waila Harvestability          |wailaharvestability           |1.1.15              |DONE      |Manifest: NOSIGNATURE 		jei-1.16.5-7.7.1.145.jar                          |Just Enough Items             |jei                           |7.7.1.145           |DONE      |Manifest: NOSIGNATURE 	Crash Report UUID: eeee8f45-9b70-4bbb-8af4-d3443c5c2cc2 	Launched Version: 1.16.5-forge-36.2.20 	Backend library: LWJGL version 3.2.2 build 10 	Backend API: NVIDIA GeForce RTX 2060 with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 496.49, NVIDIA Corporation 	GL Caps: Using framebuffer using OpenGL 3.0 	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	Graphics mode: fancy 	Resource Packs: vanilla, mod_resources, file/FreshAnimations_v1.5 (2).zip (incompatible) 	Current Language: English (US) 	CPU: 16x AMD Ryzen 9 4900HS with Radeon Graphics  	OptiFine Version: OptiFine_1.16.5_HD_U_G8 	OptiFine Build: 20210515-161946 	Render Distance Chunks: 8 	Mipmaps: 4 	Anisotropic Filtering: 1 	Antialiasing: 0 	Multitexture: false 	Shaders: BSL_v8.1.02.1.zip 	OpenGlVersion: 4.6.0 NVIDIA 496.49 	OpenGlRenderer: NVIDIA GeForce RTX 2060 with Max-Q Design/PCIe/SSE2 	OpenGlVendor: NVIDIA Corporation 	CpuCount: 16

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Bookshelf-1.16.5-10.0.1, create-mc1.16.5_v0.3.2g, FarmersDelight-1.16.5-0.5.4, flywheel-1.16-0.2.5, Hwyla-forge-1.10.11-B78_1.16.2, jei-1.16.5-7.7.1.145, JRFTL+[1.16.5]-1.2, Mantle-1.16.5-1.6.157, OptiFine_1.16.5_HD_U_G8, TConstruct-1.16.5-3.0.2.84, WailaHarvestability-mc1.16.x-forge-1.1.15, WAWLA-1.16.5-8.0.1

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [ ] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment] 2022-02-16 03:28
Seriously, this one again? Duplicate of #4631, which was fixed 5 months ago. Why are you playing an ancient TiC alpha?

**Closed as completed by KnightMiner** 2022-02-16 03:28 UTC
Labels: Duplicate, 1.16, Update

**Comment by foxesinthewood** [comment] 2022-02-16 03:30
Sorry, new to reporting. I'll be sure to check the faq next time!

**Comment by foxesinthewood** [comment] 2022-02-16 03:31
> 
Didn't know I was. Thanks for telling me!

**Comment by KnightMiner** [comment] 2022-02-16 03:34
Whenever you report an issue, always start by finding the latest version of the mod for your Minecraft version. Thats not a FAQ thing, that just ensures it was not already fixed. After you are on the latest version, if it still happens that is when you make the report.

**Comment by foxesinthewood** [comment] 2022-02-16 03:36
> 

Oh. Sorry!
