### ISSUE TITLE
Tools are untextured with rubidium installed

### ISSUE THREAD

**Issue by BigDaddyRichard** [SlimeKnights/TinkersConstruct#4995] opened 2022-09-14 19:34 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

whenever i have Rubidium in my modlist (its version number is 0.5.3a in case that helps) all of the tool and weapon textures are blank, the tool parts however are not.

### Other mods

Rubidium version 0.5.3a

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment] 2022-09-14 19:40
This bug is not our problem, we simply use forge rendering systems. However, I am getting tired of people reporting it to us instead of Rubidium, so I am going to leave this issue open until I have a link to the issue on Rubidium's tracker.

So, report this bug to Rubidium and link it here so I know they are aware they are breaking forge rendering.

**Comment by BigDaddyRichard** [comment] 2022-09-14 19:46
apparently this issue was reported a while ago on their forums and hasn't been fixed yet, kinda annoying honestly

**Comment by BigDaddyRichard** [comment] 2022-09-14 19:46
https://github.com/Asek3/Rubidium/issues/166

**Comment by Cannoner** [comment] 2022-10-26 23:04
Found a workaround for this:

> Find the "rubidium-mixins.properties" config file, then add "mixin.features.item=false" (without the quotes) underneath the notice.

From here:
https://mineyourmind.net/forum/threads/how-to-fix-broken-t-construct-item-textures.32974/

**Comment by KnightMiner** [comment] 2024-09-20 07:05
I'm going to go ahead and close this as its caused by Rubidium breaking forge rendering, and I cannot do anything to fix this. There is a workaround, or you can install a newer performance mod that likely lacks this issue.

**Closed as not planned by KnightMiner** 2024-09-20 07:05 UTC
Labels: Bug, Performance Enhancers/Optifine, Can't Fix, 1.18, Other mod
