### ISSUE TITLE
PvP attacks with secondary damages (e.g. Piercing) prevent knockback on the player attacked.

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4931] opened 2022-07-02 05:42 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.51

### Mantle Version

1.9.28

### Tinkers' Construct Version

3.5.1.32

### Describe your issue

Attacking another player with a weapon that deals multiple damages (e.g. Piercing) will prevent the player from getting knockbacked most of the times.

https://user-images.githubusercontent.com/7185104/176988163-64321da6-4a0f-4773-a243-276dd7923801.mp4

This seems to be a problem with https://github.com/SlimeKnights/TinkersConstruct/blob/3.5.1.31/src/main/java/slimeknights/tconstruct/library/tools/helper/ToolAttackUtil.java#L332
As commenting this line makes the knockback work properly again.

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment] 2022-09-20 22:41
Fixed in 3.4.2.40, hopefully. Any PvP related bugs tend to be whack-a-mole so will be interesting to see what new bug was caused by the fix.

**Closed as completed by KnightMiner** 2022-09-20 22:41 UTC
Labels: Bug, Resolved, Confirmed, 1.18
