### ISSUE TITLE
Missing tool modifier textures

### ISSUE THREAD

**Issue by TheTraveller-g** [SlimeKnights/TinkersConstruct#4940] opened 2022-07-15 19:03 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

I dont know why but all the modifiers for the tools and armor have no texture visible on the tools
![image](https://user-images.githubusercontent.com/100040437/179292292-66e7e918-6e8f-4919-9731-ba38086cb20d.png)
![image](https://user-images.githubusercontent.com/100040437/179292359-47bcc9f9-5b09-4393-bbe6-8b93836db6e7.png)

### Other mods

[mods.txt](https://github.com/SlimeKnights/TinkersConstruct/files/9123333/mods.txt)

### Tried reproducing with just Tinkers?

I will go do that now

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment] 2022-07-15 19:06
Yes, because its not done yet. It takes time and effort to make modifier textures, its not super high priority. The code is all there, you are free to contribute textures if you want them faster.

**Comment by TheTraveller-g** [comment] 2022-07-15 23:44
No seriously tinkers alone does not have this problem
i tried with tinkers alone and the bug was not present
the bug only appears when there are more than 44 mods

**Comment by KnightMiner** [comment] 2022-07-16 00:38
I *highly* doubt this is caused by having "more than 44 mods". You installed some mod that is conflicting with it. Find out which mod that is.

**Comment by TheTraveller-g** [comment] 2022-07-16 00:39
no i did try all the mods
none of them cause an issue

**Comment by ShinyPorygon** [comment] 2022-07-16 00:41
I have 50 mods in my test pack at this point (need to cut that down whoops). It is not caused by "having more than x mods"

**Comment by TheTraveller-g** [comment] 2022-07-16 00:45
> I have 50 mods in my test pack at this point (need to cut that down whoops). It is not caused by "having more than x mods"

can you send me the mod list i want to test to see if i can replicate it on my installation

**Comment by ShinyPorygon** [comment] 2022-07-16 00:49
Considering that I'm about to fall asleep no, it's 100% something on your end. This also proves more by 1.18.2 packs that have well over 200 mods. There is nothing that would make "just x amount of mods break it" unless it can be reproduced with just tinkers and one or two specific mods nothing can be done

Also it's probably better to join the discord and continue a discussion vs 500 GitHub comments https://discord.gg/njGrvuh

**Comment by aethaerya** [comment] 2022-07-16 03:05
![image](https://user-images.githubusercontent.com/28931355/179336759-b36c672b-5ee2-413a-bbc8-889baabf23d1.png)

I've got 150+ mods :p

**Comment by TheTraveller-g** [comment] 2022-07-16 11:29
can someone at least test it with the mods on the modlist to see if its not just happening to me and finding what mod causes the bug will take hours to find all by myself

**Comment by KnightMiner** [comment] 2022-07-16 18:40
It would take hours for someone else to find too 

You are the one experience the bug. If you want it fixed, you need to give us more info.

Try a binary search, remove half of the mods at a time. If the bug stops, you can guess the half you removed caused it

**Comment by Srjoao** [comment] 2022-07-25 05:38
i am having a simmilar problem but when i hit (F3 + T) to reload textures the modifiers textures appears (this is happening even with only tinkers)
(same mods and minecraft versions) (forge 40.1.68) 
- google translated -

**Comment by KnightMiner** [comment] 2022-07-25 15:47
Again, without an exact, minimal modlist nothing we can do

**Comment by Srjoao** [comment] 2022-07-26 01:55
sorry for the delay

here the modlist that i tried
[mods 1.ods](https://github.com/SlimeKnights/TinkersConstruct/files/9185865/mods.1.ods)
[mods 2.ods](https://github.com/SlimeKnights/TinkersConstruct/files/9185870/mods.2.ods)
the first list was my first try, the second was a test to see if the textures load with only tinkers

and I'm using tlauncher I'm going to look for another launcher to check if it's a incompatibility with the launcher

**Comment by KnightMiner** [comment] 2022-09-04 05:10
Closing for lack of minimal mod list. Unless I am able to reproduce in dev there is nothing I can do.

**Closed as not planned by KnightMiner** 2022-09-04 05:10 UTC
Labels: Not enough information, Can't reproduce, 1.18
