### ISSUE TITLE
Cast Chest loses all casts when unloaded and tools lose names when exiting the game

### ISSUE THREAD

**Issue by averegemodenjoyer** [SlimeKnights/TinkersConstruct#5217] opened 2024-04-23 11:30 UTC
### Minecraft Version

1.19.2

### Forge Version

43.3.5

### Mantle Version

1.10.24

### Tinkers' Construct Version

1.19.2

### Describe your issue

Whenever the cast chest is unloaded it loses all it's casts. A temporary fix is to break it, then place it down again (all your casts are in back when you do this). Haven't tested this with the part chest but it may be bugged as well since it works in a similar way. 

Also when renaming weapons/tools at an anvil, they lose their name upon exiting the game

### Other mods

None of the mods in the modpack should interfere with this

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment] 2024-04-23 15:37
Duplicate of #5213 , as for your second issue that should really be its own issue. I can't reproduce that with just tinkers, the tools keep their names after renaming them in an anvil and join the game.

"None of the mods in the modpack should interfere with this" is not a list of all your mods for future reference. Because clearly one of them is messing with it.

**Closed as completed by ShinyPorygon** 2024-04-23 15:37 UTC
Labels: Bug, Duplicate, 1.19
