### ISSUE TITLE
Seared Drains Break Connections With Extra-Modular Conduits

### ISSUE THREAD

**Issue by Fearaniar** [SlimeKnights/TinkersConstruct#4227] opened 2020-12-13 03:58 UTC
Trying to use the fluid-conduit systems in mods such as Ender IO and Thermal Expansion result in a forced disconnection upon game reload. As this was an issue with two different mods, it seemed reasonable to bring the problem here.

The conduits work fine when first placed, but were I to logoff and log back in, they will have disconnected themselves. They will re-attach if there is a block-update in the immediate proximity (such as placing a block or opening a chest) but will otherwise refuse to work.

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.8.4
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

     - Will reply with specifics if this is no simple issue.

**Comment by Abril253** [comment] 2021-01-01 20:02
[https://github.com/SlimeKnights/TinkersConstruct/issues/4108](url)
Same problem

**Comment by KnightMiner** [comment] 2021-01-26 04:03
Yeah, duplicate of #4108. I can say the 1.16 multiblock code fixes this but doubt 1.12 will get a fix

**Closed as completed by KnightMiner** 2021-01-26 04:03 UTC
