### ISSUE TITLE
Tank Duplication with Immersive Engineering

### ISSUE THREAD

**Issue by SheReyy** [SlimeKnights/TinkersConstruct#4935] opened 2022-07-10 20:37 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.33

### Mantle Version

 Mantle-1.16.5-1.6.157.jar

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.4.335.jar

### Describe your issue

If you fill multiple Tanks with Creosote Oil, and then, stack them, and try to make Treated Wood Planks, you'll get multiple Tinkers Tanks if you try to extract all the treated planks with shift-click.

![image](https://user-images.githubusercontent.com/91336389/178161312-33f4a3ca-ca8b-4f32-8431-148a978c7e8d.png)
![image](https://user-images.githubusercontent.com/91336389/178161318-17a208fc-454a-4016-8b97-a5c714a787be.png)

### Other mods

ImmersiveEngineering-1.16.5-5.1.0-148.jar

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by ShinyPorygon** [comment] 2022-07-10 20:44
Crosspost on IE github as well please

Applies to 1.18 as well.

**Comment by SheReyy** [comment] 2022-07-11 12:22
> Crosspost on IE github as well please
> 
> Applies to 1.18 as well.

Can't this be fixed by making the tanks from tinkers, not stack? Or have a config for this?

**Comment by KnightMiner** [comment] 2022-07-11 16:18
No. That is not a fix, that is a workaround.

**Comment by SheReyy** [comment] 2022-07-11 17:17
I fixed it on my end through various means. This issue can be closed if no workarounds will be used.

**Comment by KnightMiner** [comment] 2022-07-11 17:22
No, this issue will remain open until we hear back from the immersive engineering devs. There is a good chance they can do a proper fix.

**Comment by SheReyy** [comment] 2022-07-11 17:29
Yes, but this will not be a consistent fix, since IE does not provide support for 1.16 anymore, so you might wanna remove the 1.16 label.

**Comment by KnightMiner** [comment] 2022-07-11 18:12
Please, do not tell me how to manage my issue tracker. I have a lot more experience than you do with my own issue tracker, and am getting tired of explaining my reasoning for every action I take on this issue.

This issue affects 1.16, so it is labeled 1.16. I do not want a duplicate of this issue reported only labeled 1.16 thus this remains 1.16.

For my own book keeping,  BluSunrize/ImmersiveEngineering#5342 is the issue that is not a duplicate.

**Comment by KnightMiner** [comment] 2022-07-25 03:33
Fixed in immersive engineering.

**Closed as completed by KnightMiner** 2022-07-25 03:33 UTC
Labels: Bug, Mod interaction, 1.16, Confirmed, 1.18
