### ISSUE TITLE
Plant tonic recipe not available Betweenlands

### ISSUE THREAD

**Issue by MrWobbie** [SlimeKnights/TinkersConstruct#4212] opened 2020-10-27 11:46 UTC
**Issue description:**

I am playing on a sevtech ages server and noticed that i can't make the plant tonic, in the JEI it is not visible unless i look what i can do with the weedwoodbucket in the crafting table. It shows an empty bucket with sap. Trying the recipe had no succes. Normal buckets are able to pick up swamp water but none of the betweenlands are. i did see another post about this and suggested disabling the smeltery module in TinkersModules.cfg, it did fix the problem but removed the seared blocks.

**Versions:**
Sevtech Ages: 3.1.7
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Betweenlands-3,5,10

**Comment by KnightMiner** [comment] 2020-10-27 16:43
Let me explain #3904 more indepth. TiC hides unused buckets for fluids TiC registers. There is no reason it should hide custom Betweenlands buckets unless they somehow get them declared as our fluids (which should be impossible). However, this is purely visual, it will have no impact on actual available recipes.

You have to remember with SevTech the modpack changes a lot of recipes, for as much as I know, disabling our module disabled one of SevTech's custom scripts as it now errors. I suggest you try reproducing with just the two mods

**Comment by MrWobbie** [comment] 2020-10-27 21:23
Alright i'll give it a try, thanks for explaining it. I wasn't really sure if it was a fix or not.
I will give feedback when i tried the reproducing

**Comment by MrWobbie** [comment] 2020-10-27 21:32
I tried it with just those mods, and it worked.
Version: 
Minecraft 1.12.2
Forge 14.23.5.2854
Betweenlands: 3.6.2
Tinkers:1.12.2.-2.13.0.183
I forgot to mention that when i started a sevtech singeplayer game, it did work.

**Comment by KnightMiner** [comment] 2020-10-28 04:18
To be clear, the recipe worked fine with just those mods? And its working fine in SevTech singleplayer?

If you are able, I suggest testing on a server with just those mods. I am guessing this is a bug in Sevtech due to the number of mods though, I find it unlikely Tinkers Construct is causing anything unless Betweenlands has a broken integration (we have no betweenlands integration), especially if it only happens on a server.

**Comment by MrWobbie** [comment] 2020-10-28 09:38
Correct, both ways work fine.
I do not own a server unfortunately, so i am not really sure if i can test it.
But it would make sense that another mod is causing this, but which one is hard to find out, because i am not sure if it is just our server in particular. I already asked on the pack creator his discord if anyone had this issue but so far no responses yet.

**Comment by DeiusShrab** [comment] 2021-02-23 06:58
I've been able to reproduce this in SevTech Ages 3.1.7
It appears that the recipe has been changed to require a Weedwood or Syrmorite bucket filled with swamp water, rather than an empty one, and a ball of sap.
This change isn't reflected in JEI or any of the recipe displays in-game, I found it by random experimenting.

**Comment by KnightMiner** [comment] 2021-02-23 07:00
Ah, so the actual bug is something is causing our logic to hide our unused buckets to hide those buckets, and that stops you from noticing the recipe changed. I can say this is fixed in 1.16, if 1.12 gets another build I'll probably just toss a config option to disable this fix as there is honestly no reason this should happen

**Comment by KnightMiner** [comment] 2022-01-31 19:22
Closing as 1.16 received a beta making 1.12 end of support. Still never figured out why this would happen as our logic only is supposed to hide our own buckets. Possibly an obscure bug with NBT items in JEI, possibly something more complicated involving a modpack tweaker mod.

My intended "fix" was to just disable the hiding logic with a config option (default to enabled as it shouldn't be broken)

**Closed as completed by KnightMiner** 2022-01-31 19:22 UTC
Labels: Won't Fix, Not enough information, 1.12
