### ISSUE TITLE
Config for slime recipes turning off doesnt work

### ISSUE THREAD

**Issue by Gartebex-Ugandi** [SlimeKnights/TinkersConstruct#4976] opened 2022-08-18 06:05 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.25

### Mantle Version

Mantle-1.18.2-1.9.27.jar

### Tinkers' Construct Version

 TConstruct-1.18.2-3.5.1.31.jar

### Describe your issue

For some reason, the config for turning off the tinkers construct slime fixing recipes doesnt work.

### Other mods

JEI
Tinkers construct

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment] 2022-08-18 06:32
Are you sure you understand the config? It does not disable those recipes, it just disables our copies of them. Vanilla also has a copy of those recipes (just more restrictive)

In any case, the config options are just for convenience, you really should use a datapack to modify recipes.

**Comment by Gartebex-Ugandi** [comment] 2022-08-18 09:50
i perhaps meant the copies of them... my bad.

**Comment by Gartebex-Ugandi** [comment] 2022-08-19 11:52
> Are you sure you understand the config? It does not disable those recipes, it just disables our copies of them. Vanilla also has a copy of those recipes (just more restrictive)
> 
> In any case, the config options are just for convenience, you really should use a datapack to modify recipes.

Wait what ?, i dont undestand, could you explain it in details pls ?

**Comment by KnightMiner** [comment] 2022-08-19 18:11
you can remove recipes using datapacks. If you do not know how datapacks work, look it up on the minecraft wiki

**Comment by Gartebex-Ugandi** [comment] 2022-08-20 05:01
I did with crafttweaker.

**Comment by KnightMiner** [comment] 2022-08-20 12:19
So, is there still a bug or did you find the cause of your issue?

**Comment by Gartebex-Ugandi** [comment] 2022-08-21 06:10
I think its still a bug. Like i technically didnt tried it alone with tinkers. But i only used jei so i can view it. You can also try it too if you wish to.

**Comment by KnightMiner** [comment] 2022-08-21 07:56
If there is still a bug its unclear to me what the bug is. Is the config option not disabling *our* copy of the recipes?

What the config option should do: Prevent crafting various slime items from tinkers slime balls
What the config option should not do: prevent crafting the slime items in the first place

If the former is not working, show exactly which recipes still exist with the config option disabled.

**Comment by Gartebex-Ugandi** [comment] 2022-08-21 09:31
> If there is still a bug its unclear to me what the bug is. Is the config option not disabling _our_ copy of the recipes?
> 
> What the config option should do: Prevent crafting various slime items from tinkers slime balls What the config option should not do: prevent crafting the slime items in the first place
> 
> If the former is not working, show exactly which recipes still exist with the config option disabled.

Yes, its not disabling those recipes.

**Comment by Gartebex-Ugandi** [comment] 2022-08-21 09:52
![Screenshot 2022-08-21 113901](https://user-images.githubusercontent.com/102457574/185785247-8bdfabc5-7b42-4737-857b-42d138a122d4.png)

https://user-images.githubusercontent.com/102457574/185785482-97a8a6f8-4dd0-4b95-bce7-959b1ac5a372.mov

**Comment by ShinyPorygon** [comment] 2022-08-22 09:22
Out of curiosity "tried reproducing with just tinkers" you put no. Do you have any other mod that would also add the same thing?

**Comment by Gartebex-Ugandi** [comment] 2022-08-23 09:16
nope, i meant like i used it with jei.

**Comment by KnightMiner** [comment] 2022-09-04 20:21
Yep, I cannot reproduce. Just tested now, with the config off:

![image](https://user-images.githubusercontent.com/12155288/188332002-8ce16517-da9a-4f6b-a032-6c7e845ffeea.png)

Reproduce with fewer mods

**Comment by Gartebex-Ugandi** [comment] 2022-09-17 17:08
I basically just used mods that you used in your testing, not sure why it bugs for me.

**Comment by Gartebex-Ugandi** [comment] 2022-09-18 08:59
Wait, do you need to reload to show the changes in the recipes ?

**Comment by KnightMiner** [comment] 2022-09-18 13:31
Are you editing the config files while the game is running?

**Comment by Gartebex-Ugandi** [comment] 2022-09-23 09:22
I think i didnt, idk.
But its been a long time i tested it out, so things couldve changed.

**Comment by Gartebex-Ugandi** [comment] 2022-09-23 09:50
Eh, perhaps i tried everything, /reload, even restarting the game, and also using configured to turn it off. But coudnt make it work.
I think the issue is in the compiled version of tinkers construct, maybe a mistake is rather in there, could you perhaps make an instance on curseforge with tinkers and try it in there ? And maybe show the results?

**Comment by Gartebex-Ugandi** [comment] 2022-09-30 08:22
Wait, you just did that, didnt you ?

**Comment by KnightMiner** [comment] 2022-11-23 07:10
![image](https://user-images.githubusercontent.com/12155288/203489585-8d880f98-81c5-41c0-a82b-9833296f3a97.png)
Tested again outside of dev. I cannot reproduce this bug, so closing this issue.

Give me steps to reproduce this issue if you want a reopen.

**Closed as completed by KnightMiner** 2022-11-23 07:10 UTC
Labels: Bug, Needs Update, Can't reproduce, 1.18
