### ISSUE TITLE
Astral Sorcery and Tinker's Construct

### ISSUE THREAD

**Issue by Biggiememe** [SlimeKnights/TinkersConstruct#3820] opened 2019-04-11 18:03 UTC
**Issue description:**
Whenever I try to run both Astral Sorcery and Tinker's Construct (along with baubles and Mantle), It seems that it crashes on start up for no apparent reason. Though I have figured out that only those 4 mods don't work together, as they work fine alone

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/cXkgNg73

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2 - 14.23.5.2834
* Mantle: Mantle-1.12-1.3.3.49.jar
* Tinkers Construct: TConstruct-1.12.2-2.12.0.135.jar

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Astral Sorcery: AstralSorcery-1.12.2-1.10.13.jar
Baubles (Needed to even run Astral Sorcery): Baubles-1.12-1.5.2.jar

**Comment by KnightMiner** [comment] 2019-04-11 21:38
Duplicate of #3819

**Closed by KnightMiner** 2019-04-11 21:38 UTC
