### ISSUE TITLE
Tinker's axe-like tools (I.E: Handaxe) do not seem compatiable with HT's TreeChop

### ISSUE THREAD

**Issue by rapscalionjack** [SlimeKnights/TinkersConstruct#5014] opened 2022-10-27 01:50 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

HT's TreeChop is a mod that lets you chop a part of a tree down to bring the rest of the tree down as well. The mod lets you use different axes, either by default or whitelisting them in the config, to chop trees down. However, the axe-like tools in Tinker's don't seem to work with TreeChop, breaking the blocks normally rather than activating the tree chopping action. 

Example:
![ezgif com-gif-maker-2](https://user-images.githubusercontent.com/116773525/198171615-f6c54408-f99a-40bc-aa47-b81e3f841202.gif)

The original creator of HT's TreeChop attempted to add support between their mod and Tinker's, but it ultimately removed in later updates. Is it possible for support for this mod to come to Tinker's?

### Other mods

HT's TreeChop 0.16.3

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment] 2022-10-27 01:55
Their bug, they are hardcoding to instance of checks instead of using tool actions most likely. Nothing we can do to fix it.

**Comment by Jemy191** [comment] 2023-01-18 21:20
There a quick easy fix you can do in "config\treechop-common.toml"
at line 89 in the "item" field remove the entry "#tconstruct:modifiable/harvest"
If the line change it in [compatibility.general.blacklist] section.

Also KnightMiner seem to be wrong. There an api to add compatibility with ht tree.
hammertater blacklisted tinker construct because of the tree falling feature that conflict.
Here the link to that api: https://github.com/hammertater/treechop/blob/main/docs/compatibility.md#items

**Comment by KnightMiner** [comment] 2023-01-19 03:42
If this is an intentional blacklist, then going to close this as works as intended. If you disagree, discuss this on their issue tracker as that is where you would have to change it.

**Closed as completed by KnightMiner** 2023-01-19 03:42 UTC
Labels: Bug, Can't Fix, Mod interaction, Works as Intended, 1.18, Other mod

**Comment by hammertater** [comment] 2023-01-26 03:33
For anyone who stumbles across this issue, see https://github.com/hammertater/treechop/issues/144 for the status of TreeChop support for Tinker's tools.
