### ISSUE TITLE
Forge Multipart microblocks missing textures in crafting station

### ISSUE THREAD

**Issue by juraj-hrivnak** [SlimeKnights/TinkersConstruct#4257] opened 2021-01-30 19:07 UTC
### Better explained by photos:
![2021-01-30_20 01 36](https://user-images.githubusercontent.com/71150936/106365442-ff258e80-6335-11eb-819e-cdb2bb45dbed.png)
![2021-01-30_20 01 40](https://user-images.githubusercontent.com/71150936/106365452-08aef680-6336-11eb-80fb-1a8b4f591def.png)

`It looks like the models are not rendered, not only textures.`

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854 
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.183

**Required mods are:**
- CodeChicken Lib 1.8+
- Forge Multipart CBE
- ProjectRed
- MrTJPCore

**Comment by KnightMiner** [comment] 2021-01-30 23:25
Duplicate of #2111 (multipart probably render same as chests). Sideeffect of how we render items in 1.12. Not changing in 1.12, fixed in 1.16.

**Closed as completed by KnightMiner** 2021-01-30 23:25 UTC
Labels: Bug, Duplicate, 1.12
