### ISSUE TITLE
1.10.2 Something with Slime Grass and Chisel

### ISSUE THREAD

**Issue by Shadows-of-Fire** [SlimeKnights/TinkersConstruct#2249] opened 2016-07-16 06:52 UTC
https://gist.github.com/Shadows-of-Fire/5c8c0f782bc451e53e82aa20a9e319a2
Not really sure what happened. I also don't know if it's on TiC's end or Chisel's end.

**Comment by LovelyFlare** [comment] 2016-07-16 07:02
Sounds like a duplicate of #2244

**Closed** 2016-08-20 15:42 UTC
Labels: duplicate, Resolved
