### ISSUE TITLE
Crash - Tesselating block model 

### ISSUE THREAD

**Issue by SHXRKIEgg** [SlimeKnights/TinkersConstruct#4601] opened 2021-08-14 23:48 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

Mantle-1.16.5-1.6.115.jar

### Tinkers' Construct Version

TConstruct-1.16.5-3.1.1.252.jar

### Describe your issue

Crashing when placing Block{tconstruct:clear_glass_pane}

### Crash Report

https://pastebin.com/SXhnLqse

### Reproduced with only Tinkers' Construct?

No / Haven't tried

### Other mods required

Using [Better Minecraft Modpack](https://www.curseforge.com/minecraft/modpacks/better-minecraft-plus)
Mods List: https://pastebin.com/seF8zvn0 or it can be found on the bottom of the curseforge page

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine - Tested with and without

**Comment by ShinyPorygon** [comment] 2021-08-14 23:50
Duplicate of #4316 Don't lie when your crash report gives you away :P

**Comment by KnightMiner** [comment] 2021-08-14 23:51
For the record, if it still crashes without optifine as you claim, give me a crash report without optifine and we can reopen. Also reduce your modlist size, I can do nothing with a list of 100 mods, the issue template told you to find a list of 10 or less.

**Closed as completed by ShinyPorygon** 2021-08-14 23:50 UTC
Labels: Performance Enhancers/Optifine, 1.16

**Comment by ShinyPorygon** [comment] 2021-08-14 23:53
For the second record, performant is also a performance enhancer.
