### ISSUE TITLE
Iron turning into gold

### ISSUE THREAD

**Issue by Thewraith01** [SlimeKnights/TinkersConstruct#4393] opened 2021-04-22 04:16 UTC
i put a brick in the casting table and made an ingot cast, both the iron and the gold are already in the smeltery. i poured out a gold ingot (i guess casts only cost 1 ingot now) then when i poured out the iron it poured out as iron and all the graphics were right, however as soon as it cooled and showed the iron ingot texture it instantaneously changed into the gold ingot texture and was still gold when i took it out of the casting table

**Comment by KnightMiner** [comment] 2021-04-22 04:34
Duplicate of #4283. Failed to use issue template as well.

**Closed as completed by KnightMiner** 2021-04-22 04:34 UTC
Labels: Duplicate, Performance Enhancers/Optifine, 1.16
