### ISSUE TITLE
1.9 texture errors

### ISSUE THREAD

**Issue by tyler489** [SlimeKnights/TinkersConstruct#2111] opened 2016-05-26 00:29 UTC
placing a chest in the casting basin results in the purple and black missing texture error nothing major

**Comment by LovelyFlare** [comment] 2016-05-26 01:54
Duplicate of #2066

**Comment by bonii-xx** [comment] 2016-05-26 06:33
Nope, not a duplicate. Simply mojang not having models for their chests. Blame mojang for not using their own system. :P

**Closed by bonii-xx** 2016-05-26 06:33 UTC
Labels: cantfix

**Comment by LovelyFlare** [comment] 2016-05-26 20:01
Well it does happen on item racks as well since they use the same rendering .~.

**Comment by KnightMiner** [comment] 2016-05-26 21:29
Its not a duplicate, but it is related, as both "builtin/entity" and "tintindex" require data from outside the model to work.
