### ISSUE TITLE
Crash with Rapier attacking mobs in nether! And shocking modifier charging up instantly and way to fast!

### ISSUE THREAD

**Issue by SirAron111** [SlimeKnights/TinkersConstruct#3974] opened 2019-10-24 15:51 UTC
**Issue description:**
First of all! Attacking to fast with rapier can somehow cause this crash when hitting nether mobs. https://paste.dimdev.org/fojotaneva.mccrash I have no idea why that is a thing.
Also strangely this even happens with just tinkers and any mod that adds Shocking materials like Electrum or Embers etc. The modifier recharges nearly instantly after it got discharged making it a free super dmg on any weapon. What happened to needing to walk around with the tool to build up static charge?

**If crashed, link to crash report (use a site such as pastebin):**
https://paste.dimdev.org/fojotaneva.mccrash

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2   14.23.5.2847 
* Mantle: Mantle-1.12-1.3.3.55.jar
* Tinkers Construct: TConstruct-1.12.2-2.12.0.157.jar

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

Modlist in the crash report

**Comment by KnightMiner** [comment] 2019-10-24 17:58
Your crash is a duplicate of #3783.

----

Please open a separate ticket for the electron issue, it's difficult to handle multiple issues in one issue. Also, when it asks for mods needed to reporduce, that is a *minimal* mod list, not a full mod list. Should not have any more than 5. Verify the electron issue happens with just tinkers and a mod that adds electron.

**Closed as completed by KnightMiner** 2019-10-24 17:58 UTC
