### ISSUE TITLE
Bug in Tinker's 1.16.5

### ISSUE THREAD

**Issue by SrBenitoo** [SlimeKnights/TinkersConstruct#4515] opened 2021-06-05 19:24 UTC
BUG:
1.16.5
In the overworlds islands, the liquid is only visual, it isn't a liquid.
I don't know if I wrote something wrong or if you didn't understand something because I don't speak english
uwu

**Comment by PrincessOfEvil** [comment] 2021-06-05 19:28
Duplicate of #4295.

**Closed as completed by PrincessOfEvil** 2021-06-05 19:28 UTC
Labels: Bug, Duplicate, 1.16
