### ISSUE TITLE
new smeltery controller recipe not updated in the mighty smelting guidebooks

### ISSUE THREAD

**Issue by Jake-Watkins** [SlimeKnights/TinkersConstruct#4876] opened 2022-05-21 08:01 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Mantle Version

1.18.2-1.9.20

### Tinkers' Construct Version

1.18.2-3.5.0.18

### Describe your issue

commit https://github.com/SlimeKnights/TinkersConstruct/commit/90717d71698261f6736eccde457b6ae53a55acc3
updates the smeltery controller recipe but does not update the guidebooks, 

the mighty smelting book still lists using the heater

The FAQ also needs updated
https://github.com/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-FAQ#how-do-i-craft-a-smeltery-controller

### Other mods

bonsaitrees3-3.1.0
libnonymous-2.1.0

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment] 2022-05-21 08:15
Duplicate of #4867.

**Closed as not planned by KnightMiner** 2022-05-21 08:15 UTC
Labels: Duplicate, 1.18
