### ISSUE TITLE
Crafting Station resource duplication

### ISSUE THREAD

**Issue by Cazadorsniper** [SlimeKnights/TinkersConstruct#3773] opened 2019-02-24 02:18 UTC
**Issue description:**
1. Have 2 players look inside the crafting station
2. One player has to put a resource inside (doesn't matter which one), for example we used a gold ingot. As you know it will craft 9 golden nuggets.
3. 2nd player has to take the golden nuggets, meanwhile for the first player the gold ingot is still in the crafting station, while for the 2nd player its not.
4. Now you have 1 gold ingot and 9 nuggets which you can use to craft another gold ingot. It does work vice-versa as well.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 2808
* Mantle: 1.3.3.42
* Tinkers Construct: 2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Only the crafting station was used to reproduce this.

**Comment by KnightMiner** [comment] 2019-02-27 02:38
Duplicate of #3714

**Closed by KnightMiner** 2019-02-27 02:38 UTC
