### ISSUE TITLE
[1.12] Text being out of bounds and Invisible Textures

### ISSUE THREAD

**Issue by ProxyPlayerHD** [SlimeKnights/TinkersConstruct#3048] opened 2017-07-26 20:14 UTC
this is not a serious thing, but it makes the Book kinda hard to read when stuff like this happens:
![950a11fc46799f785385ea45e2475b28](https://user-images.githubusercontent.com/13576843/28641486-c1de2396-724f-11e7-9e76-ed4514e2f64d.png)

EDIT: nvm imma make this a real issue
![2017-07-26_22 53 18](https://user-images.githubusercontent.com/13576843/28643221-6bd47f58-7255-11e7-9efb-6549c231506a.png)
A lot of Materials are invisible... i have no idea why.

**Comment by KnightMiner** [comment] 2017-07-26 21:11
Duplicate of #2987, remove Optifine to fix.

Your edit is the ninth duplicate of #3008, update or remove Optifine to fix.

Please keep one bug per issue and search before posting.

**Closed by KnightMiner** 2017-07-26 21:11 UTC

**Comment by ProxyPlayerHD** [comment] 2017-07-26 21:39
oh, oops.. sry.

**Comment by KnightMiner** [comment] 2017-07-26 21:52
If you are already using the latest and textures still do not load, report it to the issue on Optifine's tracker. There is a chance it was just fixed in a.beta as well.

**Comment by alexbegt** [comment] 2017-07-27 00:06
"OptiFine 1.12 HD U C5 pre" has the fix, which is listed under "Preview versions" on the OptiFine download page

**Comment by ProxyPlayerHD** [comment] 2017-07-27 06:42
![2017-07-27_08 41 17](https://user-images.githubusercontent.com/13576843/28657417-60f9e0e4-72a7-11e7-8c67-3af88878966b.png)

Awesome, thanks!

but may i ask. why?
I know Optifine can cause 3D Renders to be broken... but why 2D textures?

**Comment by KnightMiner** [comment] 2017-07-27 07:04
Forge changed how it loads textures, and Optifine is not the best when it comes to compatibly with Forge changes as they replace a lot of Forge's systems.

The other issue you see is #3031 for the GUI, and #2627 for the JEI chest, both unrelated to Optifine. Again, one issue per report and check if it has been reported

**Comment by bonii-xx** [comment] 2017-07-27 07:06
>as they replace a lot of Forge's systems.
Nearly. They copy the WHOLE CLASS and then make their changes to it. Meaning if Forge changes something, theirs doesn't match anymore.
