### ISSUE TITLE
Stencil Table - Tesselating block model crash

### ISSUE THREAD

**Issue by jlbrewer** [SlimeKnights/TinkersConstruct#2108] opened 2016-05-23 15:06 UTC
DISCLAIMER: I'm using a toaster of a laptop as far as Minecraft is concerned. Core i3, integrated graphics, 4 GB RAM. Drivers are up to date as of at least April. Graphics are set to Fast.

Pack is Jaded's Roulette alpha 1.9 with some mods added (Quark + building pretties mods) and some mods disabled (all the quest stuff, Journey Map).

New world, nothing built but a crafting station, stencil table and part builder. Game crashed after I opened up the stencil table. On reload, crashed again immediately with the same error just from looking at it.

[crash-2016-05-23_10.43.00-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/277708/crash-2016-05-23_10.43.00-client.txt)

**Comment by TherminatorX** [comment] 2016-05-23 17:52
Please use http://pastebin.com/ instead of making people download your crashlog to help you. :)

**Comment by KnightMiner** [comment] 2016-05-23 17:57
Duplicate of #2092 it seems, update Tinkers or downgrade Mantle to fix.

**Comment by jlbrewer** [comment] 2016-05-23 21:05
Updated Tinker's and this was resolved, though before I close out, any idea why I can't seem to access the crafting station interface at all?

**Comment by KnightMiner** [comment] 2016-05-23 21:29
Could be #2064. The poster there fixed it by changing his mod list around and re-downloading Tinkers, so it is most likely a mod conflict.

**Closed** 2016-05-24 23:04 UTC
