### ISSUE TITLE
T.Con buggy behavior with Dank Null Dock with Null and Tinkers Crafting Table

### ISSUE THREAD

**Issue by ArkavianX** [SlimeKnights/TinkersConstruct#4694] opened 2021-12-26 03:23 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Mantle Version

ATM 6 & Sky

### Tinkers' Construct Version

ATM 6 & Sky

### Describe your issue

Conflict with T.Con & Dank Null 

When you place a T.Con Crafting table near dank null storage dock with at least tier 4+ dank null the player personal inventory breaks, the crafting table tries to connect to the dock and shows an empty page, 

https://github.com/Tfarcenim/Dank-Storage/issues/152
https://github.com/ldtteam/minecolonies/issues/7867

### Reproduced with only Tinkers' Construct?

No

### Other mods required

This conflict is in ATM 6 & Sky mod packs.

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment] 2021-12-26 03:26
If you want help or anything you need to provide actual mod version numbers, not modpack name, not 1.16.5, actual mod version numbers.

**Comment by KnightMiner** [comment] 2021-12-26 04:05
Tinkers' Construct has a tag blacklist for things the table shouldnt connect to. Both the modpack and the Dank Null devs can choose to blacklist the block if it breaks things. The table cannot work with every inventory, just most of them (and there is no method we can call to say "is this inventory normal enough that it should work?

Anyways, rule is reproduce with minimal mods. If your list has more than 10 mods, its too many. Saying "you can reproduce in this modpack" is not helpful as I cannot put a modpack in my development environment to fix it.

**Comment by Random832** [comment] 2021-12-26 14:20
I have confirmed/reproduced this bug with Tinkers Construct 324, Mantle 152, and Dank Storage 3.16 - I was able to confirm that the side inventory shows up as empty with any tier dank [not just tier 4 and above, but see below].

The description "player personal inventory breaks" is too vague, but the Dank appears to be mapped to the top rows of the player inventory grid within the crafting station GUI rather than the side inventory [this is easiest to test with a Dank 1 - in this case, the 3 main rows of player inventory are shifted down one row, and the top row alone is mapped to the dank]. This may explain why the OP seemed to think the problem required a Dank 4, since that has enough slots to completely push the player inventory out of the gui slots.

The discussion at the linked Minecolonies bug report suggests this is ultimately a bug in Dank Storage, though it's hard to investigate that further without more knowledge about Minecolonies and instructions on the apparent dupe glitch. [with Tinkers Construct, it causes a desync that may appear to be a dupe glitch when playing in creative mode]

**Comment by KnightMiner** [comment] 2022-01-11 18:51
Fixed in dank null

**Closed as completed by KnightMiner** 2022-01-11 18:51 UTC
Labels: Bug, Resolved, Mod interaction, 1.16
