### ISSUE TITLE
Conflict with EU2

### ISSUE THREAD

**Issue by charlesbevans** [SlimeKnights/TinkersConstruct#2680] opened 2016-12-26 20:55 UTC
There's a conflict with the recent versions of EU2 (1.1.3, 1.1.3a) have a conflict with TiCon that keeps the game from running. (EU2 1.1.3 can run with Mantle, but not Mantle and TiCon.)
I don't know if Tema made a mistake, or just stumbled on an old TiCon bug.
Posted in https://github.com/rwtema/extrautilities/issues/1185

**Comment by TherminatorX** [comment] 2016-12-27 02:07
Looking at the log, I don't see how this is a TCon issue. The mod isn't mentioned anywhere in the error sections.

**Comment by charlesbevans** [comment] 2016-12-27 05:53
TCon will run by itself (plus Mantle). EU2 will run by itself. TCon and the most recent EU2 crash if run together. Since the crash involves 2 mods, I informed both.

**Comment by KnightMiner** [comment] 2017-01-08 17:01
I cannot reproduce in my pack, which has had both mods for ages on the latest. SkyFactory 3 additionally has both on the latest and has had no such reports. I assume another mod is required to cause the issue, reproduce this with the minimal mods so it can be properly debugged.

**Comment by ArukaAlter** [comment] 2017-01-08 17:11
CodeChickenLib makes the combination run, the crash is triggered without it.

**Comment by Malus-Lupo** [comment] 2017-01-08 17:17
[crash-2017-01-08_12.16.53-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/692303/crash-2017-01-08_12.16.53-client.txt)
Crash reproduced with only Mantle, Tcon, and Extra Utilities.

**Comment by bonii-xx** [comment] 2017-01-08 17:30
Looks like @rwtema forgot an access transformer or similar.

**Comment by KnightMiner** [comment] 2017-01-09 04:14
@ArukaAlter: I don't use CodeChickenLib, which is why I assumed something else is to blame. Its possible a few different mods somehow fix it, likely because they apply the same AT.

**Comment by KnightMiner** [comment] 2017-10-22 21:04
Closing as an issue in Extra Utilites that is likely fixed by now. If not, please comment and we can look into it again.

**Closed by KnightMiner** 2017-10-22 21:04 UTC
Labels: Not enough information
