### ISSUE TITLE
TC 1.10.2 Crashes when pre-initializing

### ISSUE THREAD

**Issue by Villfuk02** [SlimeKnights/TinkersConstruct#2485] opened 2016-10-12 14:45 UTC
Please help me, i tried different java versions, tc versions and mantle versions (but all for 1.10.2).

Here is crash report:

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 11.10.16 19:35
Description: Initializing game

java.lang.Error: java.lang.reflect.InvocationTargetException
   at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
   at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
   at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
   at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:609)
   at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
   at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
   at net.minecraft.client.main.Main.main(SourceFile:124)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:89)
   ... 33 more
Caused by: java.lang.NullPointerException
   at slimeknights.tconstruct.shared.TinkerCommons.preInit(TinkerCommons.java:329)
   ... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
   at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
   at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
   at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
   at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:609)
   at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
   at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)

-- Initialization --
Details:
Stacktrace:
   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
   at net.minecraft.client.main.Main.main(SourceFile:124)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
   Minecraft Version: 1.10.2
   Operating System: Windows 10 (amd64) version 10.0
   Java Version: 1.8.0_25, Oracle Corporation
   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
   Memory: 507862576 bytes (484 MB) / 702021632 bytes (669 MB) up to 1908932608 bytes (1820 MB)
   JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
   IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
   FML: MCP 9.32 Powered by Forge 12.18.2.2097 5 mods loaded, 5 mods active
   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
   UCH   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
   UCH   FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2097.jar) 
   UCH   Forge{12.18.2.2097} [Minecraft Forge] (forge-1.10.2-12.18.2.2097.jar) 
   UCH   mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
   UC   tconstruct{1.10.2-2.5.5.jenkins393} [Tinkers' Construct] (TConstruct-1.10.2-2.5.5.jar) 
   Loaded coremods (and transformers): 
   GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 369.09' Renderer: 'GeForce GT 610/PCIe/SSE2'
   Pulsar/tconstruct loaded Pulses: 
      - TinkerCommons (Enabled/Forced)
      - TinkerWorld (Enabled/Not Forced)
      - TinkerTools (Enabled/Not Forced)
      - TinkerHarvestTools (Enabled/Forced)
      - TinkerMeleeWeapons (Enabled/Forced)
      - TinkerRangedWeapons (Enabled/Forced)
      - TinkerModifiers (Enabled/Forced)
      - TinkerSmeltery (Enabled/Not Forced)
      - TinkerGadgets (Enabled/Not Forced)
      - TinkerOredict (Enabled/Forced)
      - TinkerIntegration (Enabled/Forced)
      - TinkerFluids (Enabled/Forced)
      - TinkerMaterials (Enabled/Forced)
      - TinkerModelRegister (Enabled/Forced)

   Launched Version: 1.10.2-forge1.10.2-12.18.2.2097
   LWJGL: 2.9.4
   OpenGL: GeForce GT 610/PCIe/SSE2 GL version 4.5.0 NVIDIA 369.09, NVIDIA Corporation
   GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

   Using VBOs: Yes
   Is Modded: Definitely; Client brand changed to 'fml,forge'
   Type: Client (map_client.txt)
   Resource Packs: 
   Current Language: English (United Kingdom)
   Profiler Position: N/A (disabled)
   CPU: 2x Pentium(R) Dual-Core CPU E5700 @ 3.00GHz

Thank you for any feedback

**Comment by KnightMiner** [comment] 2016-10-12 15:02
Duplicate of #2464. Forges fault, update to build 2098 to fix.

**Closed by KnightMiner** 2016-10-12 15:02 UTC

**Comment by Villfuk02** [comment] 2016-10-12 17:25
THX SO MUCH!
