### ISSUE TITLE
Removing crafting limitations?

### ISSUE THREAD

**Issue by FinDragon** [SlimeKnights/TinkersConstruct#2918] opened 2017-05-20 10:48 UTC
I might be just stupid, it usually happens. But since there is clearly limitations with Crafting, such as in my fresh server I can build and mold all the parts but cannot freely slap them together immediately, is there also a way to remove those limits? I've been googling the matter the whole day and haven't really found a thing.

What I found fun in the mod originally was the whole "Hey, neat new resource, I wonder if I can make a weapon out of it" And now I can't do that because I have yet to build wooden shovels and shiz. Not enjoying myself.

Thanks.

**Comment by KnightMiner** [comment] 2017-05-20 12:45
What do you mean by crafting limits? We have no limitations on making tool parts except that some required a smeltery.

**Comment by FinDragon** [comment] 2017-05-20 13:46
I've been trying to make a Bronze cleaver for a while now. ACtually, I tried making a wooden, flint and paer ones too. ANd I can't do it. I have all the right workstations, smelter all that jazz I know how the mod works. What I CAN do on the other hand, is to make wooden shovel, wooden pick etc. I can make ALL the parts for cleaver. I just can't put it together.

**Comment by ArukaAlter** [comment] 2017-05-20 14:10
It seems like something done by the old Iguana's Tinkers' Tweaks, not something directly from Tinkers'.

**Comment by KnightMiner** [comment] 2017-05-20 14:21
Please give mod versions. Also try to reproduce with just Tinkers and Mantle, as it sounds like some mod is changing the crafting behavior.

**Comment by FinDragon** [comment] 2017-05-20 15:27
![mods](https://cloud.githubusercontent.com/assets/28823788/26276864/50a776fa-3d89-11e7-8fc5-45f23c97f6d1.png)

That's everything there is right now.
Baubles 1.4.4
extrautilities2 1.0
Angelring 2 Bauble 0.2.3
Botania r1.9-342
Chest Transporter 2.7.6
CodeChickenLib 2.6.0.254
Decocraft 2.4.1
IndustrialCraft 2 2.7.9-ex111
Infernal Mobs 1.7.2
Just ENough Items 4.3.5.275
LLibrary 1.7.5
Jurassicraft 2.0.5
Mantle 1.2.0.26
MineColonies 1.11-0.6.2114
Not Enough Items 2.2.0.216
Pam's HarvestCraft 1.0
Tinkers COnstruct 2.7.0.6
ToroHealth Damage Indicators 1.11.2-11
Tree CHopper 1.1

**Comment by FinDragon** [comment] 2017-05-20 15:38
![dotdot](https://cloud.githubusercontent.com/assets/28823788/26276971/6ae32242-3d8b-11e7-8ad0-6d4542350b08.png)

A screencap of the situation. Gamemode doesn't affect the results.

**Comment by TherminatorX** [comment] 2017-05-20 17:17
Dupe of #2875, update your mods

**Closed** 2017-05-20 18:01 UTC
Labels: duplicate

**Comment by FinDragon** [comment] 2017-05-20 22:41
I find it quite unprofessional to close a thread before making sure that your advice has worked. My mods have been picked, downloaded and added on the 19th. Less than 2 days ago. I can't imagine that you have released a new version after that. Nor that anyone else would have either.
