### ISSUE TITLE
Tinkerers doesn't play nice with Mana and Artifice

### ISSUE THREAD

**Issue by poosenugget** [SlimeKnights/TinkersConstruct#4637] opened 2021-10-07 02:02 UTC
### Minecraft Version

1.16.5

### Forge Version

36.20

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

I made a modpack; recently added mana and artifice, and now the whole pack keeps crashing due to an abstract something to do with the casting table.

### Crash Report

https://pastebin.com/h47Dn4LU

### Reproduced with only Tinkers' Construct?

No

### Other mods required

I don't know
Mana and Artifice

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment] 2021-10-07 02:11
Duplicate of #4631 (a pinned issue), already fixed in the most recent build.

**Closed as completed by KnightMiner** 2021-10-07 02:11 UTC
Labels: Duplicate, 1.16, Update
