### ISSUE TITLE
Smeltery/Foundry controller destroys itself in the nether smeltery

### ISSUE THREAD

**Issue by 3Monika4** [SlimeKnights/TinkersConstruct#4763] opened 2022-02-18 00:31 UTC
### Minecraft Version

1.16.5

### Forge Version

36.3.23

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Describe your issue

The smeltery controller/foundry controller destroys itself and pops out of place from the smeltery in the middle of cooking for no apparent reason, only happens in the nether smeltery. I'm trying to melt down blazes into blazing blood and about 1-2 minutes into smelting, the controller pops off and stops production in the smeltery. I have to keep putting it back every time this happens so it can continue. Is this a bug or am I doing something wrong? Attached is an image of the smeltery. I am playing with a modpack called World of Dragons 2 if that helps at all 
![2022-02-17_17 06 14](https://user-images.githubusercontent.com/60331524/154594322-1d51937f-ec03-4978-8abb-fa0d8dd62c36.png)
 

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-18 00:33
This doesn't happen with just tinkers. Hence it couldn't have been reproduced with only tinkers construct. If you can try and figure out which mod may be causing this we can help but just giving a modpack isn't that much help

**Comment by KnightMiner** [comment] 2022-02-18 00:33
First, lets test without performance enchancers, based on the boxes you checked I assume you are using optifine.

second, lets honestly test with just tinkers construct. Saying you are playing with a modpack then saying you reproduced with just tinkers is not honest.

**Comment by 3Monika4** [comment] 2022-02-18 00:38
Alright I'll go through the mods and test it out. I'll update it when I'm finished

**Comment by KnightMiner** [comment] 2022-02-21 19:37
You can also try reporting this bug to World of Dragons II. If this is an intentional modpack feature, they would have more info. Spending a few minutes looking into the mod list, I would probably blame https://www.curseforge.com/minecraft/mc-mods/harder-spawners. That mod randomly breaks light giving blocks near the spawner, and the controller gives off light. You might want to try placing the smeltery a distance below, but I am going to close this as being caused by harder spawners.

**Closed as completed** 2022-02-21 19:41 UTC
Labels: 1.16, Works as Intended, Other mod
