### ISSUE TITLE
Forge fix #4898 since build 2716 causes tconstruct-API to report errors in minecraft.log

### ISSUE THREAD

**Issue by jcardii** [SlimeKnights/TinkersConstruct#3651] opened 2018-09-26 21:57 UTC
**Issue description:**
An update made to June build of forge causes 51 lines of errors to be generated in minecraft log,
I don't observe any in-game effects from the errors generated.
See https://github.com/MinecraftForge/MinecraftForge/pull/4898. This appears to be a permanent change to Forge's `ModelLoader` behavior.

The first two errors (repeated with variations of "multimodel" and "material model") are:
[10:15:31] [main/ERROR] [tconstruct-API]: Could not load multimodel tconstruct:tools/arrow.tcon#inventory
[10:15:31] [main/ERROR] [tconstruct-API]: Could not load material model tconstruct:parts/arrow_head.tmat#inventory

...

**If crashed, link to crash report (use a site such as pastebin):**
Not a crash

**Versions:**
* Minecraft: 1.12.2
* Forge: v14.23.4.2716 (and later through )
* Mantle: 1.12-1.3.2.24
* Tinkers Construct: 1.12.2-2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Just Forge/Tinkers Construct/Mantle loaded, no resource packs
[10:15:45] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 6 mods : minecraft@1.12.2,tconstruct@1.12.2-2.10.1.87,FML@8.0.99.99,forge@14.23.4.2716,mantle@1.12-1.3.2.24,mcp@9.42

**Comment by bonii-xx** [comment] 2018-10-14 17:13
Thanks for the heads up. It doesn't seem to cause any issues, I assume that it's caused by an earlier loading pass. The error logs themselves are from our custom model loaders. Will fix later ;)

**Comment by 3TUSK** [comment] 2019-03-31 07:23
Bump on this, for I have observed same log output with the following setup:

  * Minecraft: 1.12.2
  * Forge: 14.23.5.2808
  * Mantle: 1.12-1.3.3.49
  * Tinkers Construct: 1.12.2-2.12.0.135

where Mantle and TiCon are latest as of I am writing this sentence.
The only other mod present in my test modpack (besides Forge, Mantle and TiCon) is JEI, version 1.12.2-4.14.3.238.  
No game contents seem to be affected, either.

Log file may be found here: https://paste.ubuntu.com/p/KWpT4Fpngc/
(Yes it is the same log from #3810 :p)

**Comment by PhageSpace** [comment] 2019-06-17 08:22
> Thanks for the heads up. It doesn't seem to cause any issues, I assume that it's caused by an earlier loading pass. The error logs themselves are from our custom model loaders. Will fix later ;)

It crashes mine.

**Comment by sustained** [comment] 2019-06-19 14:06
Another bump. I also have this issue with the following setup:

* Minecraft 1.12.2
* Forge 14.23.5.2836
* Mantle 1.3.3.55
* Tinker's Construct 1.12.2-5.0-353c71c

Relevant log entries [here](https://gist.github.com/sustained/ad03912a9070af27402295847d7332ab).

Doesn't seem to cause any issues at runtime but I'm just going through each error and checking them all as I want my pack to be nice and stable!

Can provide more info. if needed but is basically FTB Ultimate Reloaded with a few additions and removals.

**Comment by HaddockA** [comment] 2019-07-14 01:04
I see that the modder isn't interested in making sure that these messsages appear, so I removed this mod.

**Comment by sustained** [comment] 2019-07-14 14:26
Okay, have fun playing without an awesome mod!

Also:

> Will fix later :)

> I see that the modder isn't interested in making sure that these messsages appear

:joy:

**Comment by HaddockA** [comment] 2019-07-16 08:08
> 
> 
> Okay, have fun playing without an awesome mod!
> 
> Also:
> 
> > Will fix later :)
> 
> > I see that the modder isn't interested in making sure that these messsages appear
> 
> joy

"awesome mod" -> You're going to decide for me what an "awesome" mod is?
"Will fix later" -> Posted on Oct 14, 2018 and still not fixed. You look foolish now with that emoticon.

I suggest you get a job.

**Comment by sustained** [comment] 2019-07-16 17:31
Sure thing buddy, I will get a job. Could I get a reference from you?

**Comment by KnightMiner** [comment] 2019-07-16 18:35
Yes, we are aware of this issue. It has no impact on gameplay and we have not had time to fix. Stop spamming this issue with unrelated comments. If a few log errors that do nothing to gameplay stop you from using the mod, so be it. This will be fixed when it is fixed.

**Comment by KnightMiner** [comment] 2021-06-15 17:59
I could not find exactly where to suppress this error, and as it has no impact on gameplay going to close this as not worth fixing in another release. 1.16 does not have this issue.

**Closed by KnightMiner** 2021-06-15 17:59 UTC
Labels: 1.12, Enhancement, Forge
