### ISSUE TITLE
Incorrect animation on chisel use

### ISSUE THREAD

**Issue by TheQuadShot** [SlimeKnights/TinkersConstruct#1572] opened 2015-04-25 20:22 UTC
When using a chisel, it does the eating animation. It does apply "change" to block. 
It would also be nice if the chisel would "go back" to beginning of changes, instead of it being a "one way" change. (I end up with blocks that I don't want and I can't change them)

**Comment by TherminatorX** [comment] 2015-04-26 21:11
Change the title and focus of your issue and it might make it past the first look.
The chisel using the eating animation is just that: an animation.
However, I would like the idea of a "cycle" or something, to undo a change if there's some client-sever desync.

**Comment by Wulfson** [comment] 2015-04-27 22:19
The chisel using the eating animation is working as intended.

**Comment by TheQuadShot** [comment] 2015-04-28 02:33
lol, Your kidding me, right!?

**Comment by laz2727** [comment] 2015-04-28 11:13
Nope. This is the correct animation.

**Comment by TherminatorX** [comment] 2015-04-28 13:53
@TheQuadShot Use the second part of your issue, or close this one and open a new one based on it. The first part only makes long-term users roll their eyes, no offense meant.

**Closed** 2015-04-28 16:39 UTC
