### ISSUE TITLE
Item textures missing and templates textures missing

### ISSUE THREAD

**Issue by fistidgious** [SlimeKnights/TinkersConstruct#3043] opened 2017-07-25 23:22 UTC
hi i run forge 1.12-12,21.1.2423, TC-1.12-2.7.1.9, Mantle-1.12-1.3.0.15

item textures for alot of parts are missing as with nearly all the templates, i use optifine and soartex fanver but get same issues with out optifine or a resource pack

images provides
![2017-07-26_00 13 09](https://user-images.githubusercontent.com/13280443/28597928-7a2d2950-7198-11e7-8c58-6fbe48c0c41a.png)
![2017-07-26_00 13 22](https://user-images.githubusercontent.com/13280443/28597927-7a2cd234-7198-11e7-8e17-5fab02692a87.png)
![2017-07-26_00 14 09](https://user-images.githubusercontent.com/13280443/28597926-7a2922e2-7198-11e7-9f66-c6f2b5befc72.png)

**Comment by KnightMiner** [comment] 2017-07-25 23:26
Fifth duplicate of #3008. Update Optifine

**Closed by KnightMiner** 2017-07-25 23:26 UTC
