### ISSUE TITLE
[1.10.2] (2.5.6) Unbreakable Weapon + Insatiable trait

### ISSUE THREAD

**Issue by Tiax** [SlimeKnights/TinkersConstruct#2502] opened 2016-10-18 00:44 UTC
How to reproduce:

* Craft a Manyullyn weapon, add 5x Reinforcement modifier for the "Unbreakable" trait
* Hit mobs with it (confirmed with both, single target + AOE effect)
* Check durability (e.g. holding shift or in a Tool station) and notice it went down from its maximum and eventually breaks!

Is this a bug or intended behaviour?

**Comment by KnightMiner** [comment] 2016-10-18 03:10
Appears to be a duplicate of #2499, given they are both an interaction between manyullyn's insatiable and unbreakable.

**Closed by KnightMiner** 2016-10-18 03:10 UTC
