### ISSUE TITLE
Crash when using Tool Bench

### ISSUE THREAD

**Issue by H3roDude** [SlimeKnights/TinkersConstruct#3416] opened 2018-03-12 15:26 UTC
"On the Latest verison of Tinkers"
When i put a tool insidet he middle slot of the Bench the game crashes me.
Crashreport: https://pastebin.com/RSz7bLG2
Its on a Server, installed mods are in the crashreport.

**Comment by KnightMiner** [comment] 2018-03-12 15:50
Duplicate of #3372. TAIGA issue.

**Closed by KnightMiner** 2018-03-12 15:50 UTC
