### ISSUE TITLE
Unexpected Error when killing stuff

### ISSUE THREAD

**Issue by Seth0067** [SlimeKnights/TinkersConstruct#3894] opened 2019-07-04 01:19 UTC
I kill things and some particles seem to be causing a crash (at least that's how i read it).

https://pastebin.com/mUTW0k3v
https://pastebin.com/QV4ucmES

**Versions:**
* Minecraft: 1.12
* Forge: 2838
* Mantle: Mantle-1.12-1.3.3.55.jar
* Tinkers Construct: TConstruct-1.12.2-2.12.0.157.jar

I'm sorry, I have not tried to replicate without other mods, I am playing the Dimension Zero modpack at https://www.curseforge.com/minecraft/modpacks/dimension-zero

**Comment by KnightMiner** [comment] 2019-07-04 01:26
Duplicate of #3783, caused by dynamic surroundings. And had it not been a duplicate, you *need* to reproduce it with minimal mods. Saying download these 100 mods to get the bug does not help us solve it.

**Closed by KnightMiner** 2019-07-04 01:26 UTC
