### ISSUE TITLE
Too little space for schematics

### ISSUE THREAD

**Issue by Mech4nik** [SlimeKnights/TinkersConstruct#4233] opened 2020-12-24 18:00 UTC
**ATTENTION! MACHINE TRANSLATION USED!**
Since the modification is popular, a huge number of additions have been created for it. But a problem arises: I, for example, have only 48 patterns, and the interface of the cutting pattern table fits only 40. Could you add a menu scroll?

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Tinkers Construct: 2.13.0.179

**Comment by KnightMiner** [comment] 2020-12-24 18:56
Duplicate of #3995. It's already fixed in the 1.16 branch, and it's a pretty major rewrite if we wanted to add to 1.12. I know it's not great, but none of the devs have time to fix this in 1.12 right now.

**Closed as completed by KnightMiner** 2020-12-24 18:56 UTC
