### ISSUE TITLE
Piggybackpack deletes mounted entity in single player

### ISSUE THREAD

**Issue by LemADEC** [SlimeKnights/TinkersConstruct#3881] opened 2019-06-18 20:27 UTC
**Issue description:**
Mounted entity is deleted when reloading single player world.

**If crashed, link to crash report (use a site such as pastebin):**
n/a

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Single player with no other mods

Steps to reproduce:
1- use piggybackpack on a pig
2- close single player world
3- reopen single player world
=> pig is no longer mounted on player

Issue is also reproduced with spongeforge-1.12.2-2838-7.1.7-RC3782 in Single player.

Issue is not reproduced with spongeforge-1.12.2-2838-7.1.7-RC3777 (and many other mods) in multiplayer. In that case, the pig is dismounted when its player/mount disconnects.

**Comment by KnightMiner** [comment] 2019-10-13 20:58
I can reproduce this, but it looks to be extremely difficult to fix. For some reason, when closing the game Minecraft saves the players data (and thus the piggybackpack) to NBT twice. The first time the player is listed as having entities riding it, the second time the player is not. Of course, the second time its called is the one that is written to the NBT file causing the data to be lost.

**Comment by KnightMiner** [comment] 2021-06-15 17:31
Marking as unreviewed as a reminder to double check if this changed in 1.16.

**Comment by KnightMiner** [comment] 2021-12-22 00:27
I have confirmed this does not affect 1.16. Since this is unfixable and 1.12 is mostly EOL, going to close this issue.

**Closed by KnightMiner** 2021-12-22 00:27 UTC
Labels: Bug, Can't Fix, 1.12
