### ISSUE TITLE
Crash when used with Chicken Chunks 

### ISSUE THREAD

**Issue by Metabitly** [SlimeKnights/TinkersConstruct#4672] opened 2021-12-07 10:46 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.19

### Mantle Version

Mantle-1.16.5-1.6.147

### Tinkers' Construct Version

TConstruct-1.16.5-3.3.0.308

### Describe your issue

Updating Mantle/Tinkers' causes a "Rendering Block Entity" error when trying to load blocks from chicken chunks (ChickenChunks-1.16.5-2.9.0.88-universal).
Downgrading Mantle/Tinkers' to previous version restores functionality.
Tested with all mods in crash log, works with everyone except current Tinkers' update.
Double checked that Optifine was not the culprit by reproducing in new modpack.  All updates and modifications have been done in curseforge.

[crash-2021-12-07_01.32.47-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/7667624/crash-2021-12-07_01.32.47-client.txt)

### Crash Report

https://github.com/SlimeKnights/TinkersConstruct/files/7667624/crash-2021-12-07_01.32.47-client.txt

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment] 2021-12-07 10:47
Duplicate of #4667

**Closed as completed by ShinyPorygon** 2021-12-07 10:47 UTC
Labels: Bug, Duplicate, 1.16

**Comment by Metabitly** [comment] 2021-12-07 11:06
@ShinyPorygon Thank you, new to github and missed the duplicates. Cheers =D
