### ISSUE TITLE
Potion buckets having weird interaction with Create

### ISSUE THREAD

**Issue by Ashley123477** [SlimeKnights/TinkersConstruct#5146] opened 2023-07-08 15:08 UTC
### Minecraft Version

1.18.2

### Forge Version

40.2.9

### Mantle Version

Mantle-1.18.2-1.9.45

### Tinkers' Construct Version

TConstruct-1.18.2-3.6.4.113

### Describe your issue

So i dont really believe this is an issue but could be a little confusing for people using Create and Tinkers together.

The issue exactly is to do with how Tinkers manages potions, essentially making them look like buckets, i believe which they are textured bottles?

Due to this JEI shows some weird behaviour with create.

See images for example
![2023-07-08_16 05 26](https://github.com/SlimeKnights/TinkersConstruct/assets/26034936/d468a916-51ee-4aa0-8b53-2b134529322c)
![2023-07-08_16 00 06](https://github.com/SlimeKnights/TinkersConstruct/assets/26034936/5bf3b42e-fd75-46f4-b12c-4b48e23f7cd2)

In the first image. What looks like a bucket is getting drained a returning a glass bottle
In the second image it is showing filling a glass bottle with potion to return a bucket with potion

### Crash Report

None

### Other mods

create-1.18.2-0.5.1.b

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment] 2023-07-08 15:16
Yeah, nothing to do with Tinkers. This is just Create not making the input and output sizes match, you probably would find other examples if you dug enough. That, or its a bug in Create as they assume all potion items hold 250mb of potion (which is simply not true)

Tinkers is not retexturing potion bottles anywhere. Potion buckets are a distinct item that holds 1000mb of potion. It acts as a bucket like the milk bucket, drink it for effects.

I recommend reporting this issue to create, see what they have to say. Just know they are done with 1.18.2 for the most part, but maybe they can fix it for later versions.

**Comment by Ashley123477** [comment] 2023-07-08 15:50
https://github.com/Creators-of-Create/Create/issues/4124

**Comment by KnightMiner** [comment] 2024-09-20 06:59
I'm going to go ahead and close this issue given its a bug in Create that we cannot fix caused by a faulty check on their side. Seems they fixed it with a hacky fix on 1.20.1, ignoring my suggestion for a clean fix (their hacky fix is hardcoding to buckets while the clean fix is just checking for a fluid handler).

Anyways, nothing more to do on this issue.

**Closed as completed by KnightMiner** 2024-09-20 06:59 UTC
Labels: Bug, Can't Fix, Mod interaction, 1.18, Other mod, 1.19
