### ISSUE TITLE
Rendering glitch

### ISSUE THREAD

**Issue by Alex7896** [SlimeKnights/TinkersConstruct#3721] opened 2019-01-12 15:02 UTC
Issue description: Shield, chest ant others block not rendering in casting.
Screenshot: https://i.imgur.com/QehB3Tq.png[/img]

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2795
* Mantle: 1.3.3.39
* Tinkers Construct: 2.12.0.113

**Comment by KnightMiner** [comment] 2019-03-28 13:29
Duplicate of #2111. As of right now we have no way to handle chests as vanilla ignored their own systems with those items. Possibly something we can deal with in the future, but nothing we can do now.

**Closed** 2019-03-28 13:30 UTC
Labels: duplicate

**Comment by Alex7896** [comment] 2019-03-31 10:15
Is it not possible just to remake the model of the chest, which will be displayed normally?

**Comment by KnightMiner** [comment] 2019-03-31 14:56
If we special case it, sure, but that won't work for shields.

**Comment by Alex7896** [comment] 2019-03-31 17:14
But, shields from other mods are displayed correctly, can make the model identical?


![2019-03-31_20 11 27](https://user-images.githubusercontent.com/42738314/55292292-867be100-53f1-11e9-8abe-20caeb4367d9.png)

**Comment by KnightMiner** [comment] 2019-03-31 18:02
We do not have any plans to replace vanilla models at the moment, plus I assume the other mods don't use patterns meaning no need for dynamic textures, which is why they can render it fine.

**Comment by Alex7896** [comment] 2019-03-31 18:15
Replacing models would be nice, but is it possible to somehow manually disable those models that are not displayed? For example, create a blacklist.

**Comment by KnightMiner** [comment] 2019-03-31 18:28
And display what instead? The missing model is intentional so people don't think their items disappeared.

**Comment by Alex7896** [comment] 2019-03-31 18:52
I asked only for myself if I could turn them off. I just do not want to see the black and purple texture.
