### ISSUE TITLE
Tinkers tools render as items in vivecraft

### ISSUE THREAD

**Issue by DogeMoment** [SlimeKnights/TinkersConstruct#4503] opened 2021-06-01 00:36 UTC
I know this is a pretty niche issue but if you have the time it's basically a where the game sees it as an item or something and displays it as a little item in your hand rather than as a full sized tool

This issue only happens with vivecraft, but from what i've seen the vivecraft devs have tried to fix it and it looks like it's probably a bug on the mod's side.

**Comment by TheOnlyMann** [comment] 2021-06-01 00:38
First, deleting issue format doesnt help anything.
Second, pretty sure vivecraft uses Optifine, which is incompatible for the most part with Tcon

**Comment by KnightMiner** [comment] 2021-06-01 00:38
Vivecraft? Never heard of it. They are probably misusing the model format, a vanilla feature that Forge also extends. This is not Tinker fault, this is someone remaking the renderer.

Tell the vivecraft devs to look into the Forge model system a bit more, notably the perspective mapper.

**Comment by TheOnlyMann** [comment] 2021-06-01 00:39
http://www.vivecraft.org/
VR minecraft basically
uses Optifine for what i know

**Comment by DogeMoment** [comment] 2021-06-01 00:59
> Vivecraft? Never heard of it. They are probably misusing the model format, a vanilla feature that Forge also extends. This is not Tinker fault, this is someone remaking the renderer.
> 
> Tell the vivecraft devs to look into the Forge model system a bit more, notably the perspective mapper.

alright

**Comment by KnightMiner** [comment] 2021-06-01 01:00
Leave this open until the issue is resolved.

**Comment by KnightMiner** [comment] 2021-09-18 18:18
Going to close this as there is probably nothing we can do. If there is a Vivecraft issue, feel free to link it here. Going to guess they don't properly work with the forge model hooks.

**Closed as completed by KnightMiner** 2021-09-18 18:18 UTC
Labels: Bug, Can't Fix, Mod interaction, 1.16
