### ISSUE TITLE
Plate Armour crashes the game when viewed inside Invetory

### ISSUE THREAD

**Issue by TheBigGibon** [SlimeKnights/TinkersConstruct#4765] opened 2022-02-18 16:29 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

Mantle-1.18.1-1.8.31

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.1.46

### Describe your issue

As the title states, I made the plate armour, I tried to right click it on me, and the game crashed. I was playing on a server, I got a saving world... screen before the game closing and giving me a bug/crash report.
I tried recreating it in a singleplayer world, thinking it was a problem with the Artifacts mod and Sophisticated Backpack, thinking that the models you get on your player somehow interacted weirdly with the plat armour.
I got into creative and magicked a new set of armour, I right clicked a piece on, and nothing happened, I opened the inventory and it was working still. I decided to change to survival, because the Creative menu doesn't show a player model, and as soon as I pressed E to open my inventory in Survival the game crashed, with a saving world... screen

[crash-2022-02-18_17.11.36-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8098621/crash-2022-02-18_17.11.36-client.txt)
[crash-2022-02-18_13.49.54-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8098622/crash-2022-02-18_13.49.54-client.txt)
[crash-2022-02-18_13.55.14-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8098623/crash-2022-02-18_13.55.14-client.txt)

The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class slimeknights.tconstruct.tools.client.PlateArmorModel cannot be cast to class net.minecraft.client.model.HumanoidModel (slimeknights.tconstruct.tools.client.PlateArmorModel is in module tconstruct@3.4.1.46 of loader 'TRANSFORMER' @fbe70d8; net.minecraft.client.model.HumanoidModel is in module minecraft@1.18.1 of loader 'TRANSFORMER' @fbe70d8)
Exit Code: -1

These are the crash reports I had gotten.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

AdHooks-1.18.1-7.0.0.1-build.0050
advancednetherite-1.10.0-1.18.1
alexsmobs-1.17.0
Amplified Nether 1.0.1 ~ Forge
Apotheosis-1.18.1-5.3.3
appleskin-forge-mc1.18-2.3.0
artifacts-1.18.1-4.0.2
AutoRegLib-1.7-53
balm-2.4.2+0
chipped-1.18.1-1.2.1-forge
citadel-1.10.10-1.18
create-mc1.18.1_v0.4d
curios-forge-1.18.1-5.0.6.1
DungeonCrawl-1.18.1-2.3.7
expandability-5.0.0-forge
flywheel-forge-1.18-0.6.0
ForgeEndertech-1.18.1-8.0.0.0-build.0040
FramedBlocks-4.2.0
jei-1.18.1-9.2.1.69
journeymap-1.18.1-5.8.0beta15
majrusz-library-1.18.1-2.7.1
Mantle-1.18.1-1.8.31
morevillagers-FORGE-1.18.1-3.1.2
Neat 1.8-30
Patchouli-1.18.1-65
Placebo-1.18.1-6.1.1
preview_OptiFine_1.18.1_HD_U_H5_pre5
Quark-3.1-336
rechiseled-1.0.8-mc1.18
sophisticatedbackpacks-1.18.1-3.15.1.505
StorageDrawers-1.18.1-10.1.1
supermartijn642configlib-1.0.9-mc1.18
supermartijn642corelib-1.0.16b-mc1.18
TConstruct-1.18.1-3.4.1.46
TerraBlender-forge-1.18.1-1.1.0.76
Terralith_v2.0.12_Fabric+Forge
valhelsia_core-1.18.1-0.3.2
valhelsia_structures-1.18.1-0.1.1
walljump-forge-1.18.1-1.3.7
waystones-forge-1.18.1-9.0.3
wonderful-enchantments-1.18.1-1.6.2
wthit-forge-4.5.1

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [ ] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [ ] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-18 16:30
Duplicate of #4734 At least you were honest that you didn't check the tracker. Optifine is a terrible mod.

**Closed as completed by ShinyPorygon** 2022-02-18 16:30 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18

**Comment by TheBigGibon** [comment] 2022-02-18 16:38
Honestly, I should have checked the tracker, sorry for wasting your time.
Is this bug client side i.e. my friends can still use optifine while I disable it on my side, so I could use the armour?
I am so happy to be back with this mod. I checked your Road map, and I can't wait for the new versions, all be it for 1.18.1.
I don't know if the Rapier is still part of the mod, but can't wait for it to get introduced to 1.18.1
I hope I can find an optifine alternative, or at least have the game running without it.

**Comment by ShinyPorygon** [comment] 2022-02-18 16:41
Anyone with optifine will crash when getting anywhere near anyone wearing tinkers armor. They are literally deleting part of forge code that makes the armor render. So if someone without optifine is wearing it, anyone with optifine will still crash.

https://github.com/NordicGamerFE/usefulmods/tree/main/Performance Here are alternative performance mods, some may still break stuff but not as badly.

**Comment by TheBigGibon** [comment] 2022-02-18 16:50
Thanks a lot!
