### ISSUE TITLE
REFERENCE, Tinkers contruct electrum tools massive FPS hit.

### ISSUE THREAD

**Issue by frenchiveruti** [SlimeKnights/TinkersConstruct#2968] opened 2017-06-12 17:17 UTC
Hello, similar to #2851 , I created a pickaxe with an electrum head, when the pick isn't charged, everything is awesome, running at ~80fps.
When it charges, the pickaxe adopts a weird texture and also takes over my fps when I'm wield it.
Here are some pics.
http://imgur.com/a/hnNGw

I was using Optifine, and ran into this, I disabled it, and the problem persisted, I'm playing a mod pack called FoolCraft and I reported this issue also there.
scalda/FoolCraft#540

Thanks, let me know if I missed something or you need any more info.

**Comment by bonii-xx** [comment] 2017-06-12 18:25
Yup, has happened several times, usually optifine or similar fault though. Does it happen with only tic? Either way, the charged thing is just the vanilla enchantment effect. So it's either vanillas fault or something screws it up. I think there's some (clientside) mods that can remove the enchantment effect, if you absolutely need it.

**Comment by frenchiveruti** [comment] 2017-06-12 18:34
I see, so it's something to do with Optifine configs? Maybe resetting them solves the issue for me, I'll try it.  
Aside from that, who's able to fix this? I mean, who's or what causes this?
I think it has something to do with renders because for example Draconic Evolution breaks another textures when I see on JEI an item that has some weird effect on it, like those broken enchantment overlays.
Here are some other pics related to that:
http://imgur.com/a/bubTH

Is this something that any modder can fix or is intrinsic to vanilla Minecraft?
Thanks

**Comment by frenchiveruti** [comment] 2017-06-12 18:39
Maybe it has something to do with graphics drivers?

**Comment by KnightMiner** [comment] 2017-10-22 20:46
I am going to close this as fixed in #3182, since I assume the cause of the lag was the large amount of quads all getting the enchantment animation.

**Closed by KnightMiner** 2017-10-22 20:46 UTC
Labels: cantfix
