### ISSUE TITLE
Slime Boots no longer allow me to bounce. they just negate damage

### ISSUE THREAD

**Issue by Lord006** [SlimeKnights/TinkersConstruct#3191] opened 2017-10-08 18:23 UTC
When trying to bounce with the boots, i do not. i instead negate the fall damage and stay still. it's rather annoying.

**Comment by KnightMiner** [comment] 2017-10-08 18:30
Please give a mod list. I have seen conflicts with slimeboots and various advanced movement mods before

**Comment by bonii-xx** [comment] 2017-10-09 13:22
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by Dragnier** [comment] 2017-10-09 23:08
I am having the same issue and I only have about 79 mods loaded and I don't think any of them are advanced movement mods... but I could be wrong. Also, I have only tried the blue slime boots, not any of the others; so I don't know if that has anything to do with it at all. I'm still going to try and find the specific conflicting mod, but if anyone has any suggestions of where to start, that would be helpful.

Here is my mod list:


    JourneyMap (by techbrew)
    Inventory Tweaks (by Kobata)
    Morpheus (by Quetzi)
    Just Enough Items (JEI) (by mezz)
    Redstone Flux (by TeamCoFH)
    CoFH Core (by TeamCoFH)
    CoFH World (by TeamCoFH)
    CodeChicken Lib 1.8.+ (by covers1624)
    Actually Additions (by Ellpeck)
    AppleSkin (by squeek502)
    GraveStone Mod (by EuhDawson)
    Just Enough Resources (JER) (by Way2muchnoise)
    ValkyrieLib (by ValkyrieofNight)
    Environmental Tech (by ValkyrieofNight)
    Bookshelf (by darkh4x)
    Dark Utilities (by darkh4x)
    AutoRegLib (by Vazkii)
    Quark (by Vazkii)
    Controlling (by jaredlll08)
    BetterFps (by Guichaguri)
    The One Probe (by McJty)
    Cucumber (by BlakeBr0)
    BdLib (by bdew)
    Advanced Generators (by bdew)
    Neat (by Vazkii)
    NetherPortalFix (by BlayTheNinth)
    McJtyLib (by McJty)
    XNet (by McJty)
    ShetiPhianCore (by ShetiPhian)
    Spartan Shields (by ObliviousSpartan)
    SwingThroughGrass (by exidex)
    EnderTanks (by ShetiPhian)
    Bad Wither No Cookie - Reloaded (by kreezxil)
    InfiniteFluids (by josephcsible)
    Baubles (by azanor)
    Actually Baubles (by Jacky1356400)
    Lapis Stays in the Enchanting Table (by csb987)
    NoNausea (by lumien231)
    Applied Llamagistics (by Thiakil)
    CraftingCraft (by BlayTheNinth)
    Better Advancements (by Way2muchnoise)
    Applied Fluidics (by Thiakil)
    The Weirding Gadget (by AtomicBlom)
    ArchitectureCraft - ElytraDev Version (by darkevilmac)
    Bow Infinity Fix (by Parker8283)
    Bedrock Ores (by SangarWasTaken)
    EluLib (by elucent)
    Blockcraftery (by elucent)
    Environmental Creepers (by masa_)
    Mantle (by mDiyo)
    Chisels & Bits (by AlgorithmX2)
    TOP Addons (by DrManganese)
    Roots (by elucent)
    The Twilight Forest (by Benimatic)
    Cyclic (by Lothrazar)
    Exchangers (by Jacky1356400)
    Roguelike Dungeons (by Greymerk)
    ET Lunar [Environmental Tech Addon] (by ValkyrieofNight)
    Thermal Dynamics (by TeamCoFH)
    Thermal Foundation (by TeamCoFH)
    Platforms (by ShetiPhian)
    Redstone Arsenal (by TeamCoFH)
    Tinkers Construct (by mDiyo)
    PlusTiC (by Landmaster_phuong0429)
    Mystical Agradditions (by BlakeBr0)
    Thermal Expansion (by TeamCoFH)
    Mob Grinding Utils (by Vadis365)
    Cosmetic Armor Reworked (by ZLainSama)
    MultiStorage (by ShetiPhian)
    RFTools (by McJty)
    Thermal Cultivation (by TeamCoFH)
    Mystical Agriculture (by BlakeBr0)
    Quick Leaf Decay (by lumien231)
    Harvestables (by TechnicianLP)

**Comment by KnightMiner** [comment] 2017-10-09 23:41
I don't see anything that stands out, I would try removing any core mods (those listed at the top of any crash report).

Also, I noticed you have cosmetic armor reworked, so make sure the boots are in your functional armor slot and not the visual one.

**Comment by Dragnier** [comment] 2017-10-10 00:07
They are in the proper slot or they would't negate the fall damage. Also, there have not been any crashes; the boots just don't bounce. I may start with Cyclic since it does add a wall climbing glove that I didn't notice before.

**Comment by KnightMiner** [comment] 2017-10-10 00:33
You can force a crash report by holding F3 and C to get that information of coremods

**Comment by Dragnier** [comment] 2017-10-10 11:02
After restarting my game with no mod changes at all, the boots have started working again. Haven't stopped working again yet, so I'll try to pay attention to what might cause it should it happen again.

**Comment by KnightMiner** [comment] 2017-10-10 14:03
Well, since it's working and we don't k ow why it was not, I'll close this.

**Closed by KnightMiner** 2017-10-10 14:03 UTC

**Comment by Lord006** [comment] 2017-12-26 22:27
sorry for not getting back to this. I resolved the problem with a simple
restart.
