### ISSUE TITLE
1.11.2 start up crash no config file

### ISSUE THREAD

**Issue by warcommando2** [SlimeKnights/TinkersConstruct#2873] opened 2017-04-30 18:39 UTC
Hi there;

I added your mods mantle and tinkers on start up it seems fine but after a few minutes I end up getting a crash. Please see paste bin link for the crash report. I am at a loss since I can not find the config file for tinkers in the mods or config file. Any help is appreciated.

https://pastebin.com/u103nEcD

-Cryo

**Comment by bonii-xx** [comment] 2017-05-01 14:39
That's pretty weird. It doesn't find a class that's definitively present. Is that on a server? Can you reproduce it with only TiC and Mantle? You have so many (core)mods in there that might mess with classloading.

**Comment by warcommando2** [comment] 2017-05-01 16:48
I am at work atm boni I will be trying your method tonight and some more trouble shooting by 1 mod at a time to find the culprit. Unfortunately a lot of the mods require cores to con-inside with them, and my server i have for HermletteCraft Chronicles is similar to client just minus client side mods, I duplicated the same crash both client and server twice. some of the mods i use to use on 1.10.2 with no problems before as soon as i jumped to 1.11 in a fresh start from scratch (last 3 weeks) but i will find out whats causing it and i will reply back with my findings as soon as i can.

-Cryo

**Comment by warcommando2** [comment] 2017-05-02 00:43
@bonii-xx I figured it out:

Kitsu's forgecraft, better with mods,FTButil, and FTBlib are causing the issue to load the config class.

**Comment by bonii-xx** [comment] 2017-05-02 18:35
Best report it to them, probably something messed up/using wrong classloader.

**Comment by bonii-xx** [comment] 2017-05-02 18:39
Closing this in favor of #2880 since it's already aptly named and linked

**Closed by bonii-xx** 2017-05-02 18:39 UTC
