### ISSUE TITLE
Crash when putting iron into crafting station

### ISSUE THREAD

**Issue by thehypertext** [SlimeKnights/TinkersConstruct#3858] opened 2019-05-15 17:16 UTC
Everytime you put an iron ingot into a crafting station the game freezes and then it crashes.

https://hastebin.com/xihawefiqe.rb

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.5.2836
* Mantle: 1.12-1.3.3.42  
* Tinkers Construct: 1.12.2-2.12.0.123   

It can't be reproduced with only TConstruct. Mods are listed in the crash log.

**Comment by KnightMiner** [comment] 2019-05-16 00:33
Yes, you have a mod list in the crash log, but that is far from the minimum mod list. Saying it crashes with these 100 mods does not help us.

Please get a minimum mod list to reproduce this issue. As best I can tell, someone added a broken crafting recipe which probably breaks in the vanilla table as well, we really need to know what that recipe that breaks is in order to do anything here.

To debug this, try removing half the mods and seeing if the issue persists. Core mods (listed at the top of the report) are often causes of issues like this, so try removing some of them first.

**Comment by thehypertext** [comment] 2019-05-17 18:08
The minimum Mods are
Mantle
TConstruct
Flan's Mod

It's seems to be a problem with the content packs for Flan's
The packs are
Modern Warfare-Content Pack-1.12.2-5.5.2
Simple Parts-Content Pack-1.12.2-5.5.2
WW2-Content Pack-1.12.2-5.5.2

**Comment by thehypertext** [comment] 2019-05-25 11:53
When I remove TConstruct, the game doesn't crash. So it could be that TConstruct isn't working with Flan's

**Comment by thehypertext** [comment] 2019-05-25 11:54
It is only crashing in the crafting station. Not in the vanilla table.

**Comment by fireflightg** [comment] 2019-07-04 20:24
yes i have this problem too i have narrowed it down to tic pls help

**Comment by bonii-xx** [comment] 2019-09-18 16:30
Crashlog is not available anymore

**Comment by KnightMiner** [comment] 2019-10-13 23:03
Closing as the crashlog is gone. If someone has a new crashlog with just the minimal required mods listed above, feel free to post it here.

In any case, this looks like a bug with Flan's Mod adding a broken recipe, so not much we can do anyways.

**Closed by KnightMiner** 2019-10-13 23:03 UTC
Labels: 3rd party mod interaction, Not enough information
