### ISSUE TITLE
[1.10.2] Client crash loading TConstruct

### ISSUE THREAD

**Issue by Morpheus1101** [SlimeKnights/TinkersConstruct#2942] opened 2017-06-02 09:27 UTC
Crash Log @ https://puu.sh/w8voz/7f393dc390.txt

**Comment by bonii-xx** [comment] 2017-06-02 11:58
Looks like some other mod screws it up. I remember some mod causing classloading issues... FTBUtils or so?

**Comment by Azejma** [comment] 2017-06-02 12:58
cam some one help me @ #2943

**Comment by KnightMiner** [comment] 2017-10-22 20:50
Closing as caused by another mod. We do not do anything that might cause the Forge model loader class to not load, but with the amount of core mods you have there is a good chance at least one of them does

**Closed by KnightMiner** 2017-10-22 20:50 UTC
Labels: 3rd party mod interaction
