### ISSUE TITLE
Tessellating Block Issue 

### ISSUE THREAD

**Issue by gconlon2002** [SlimeKnights/TinkersConstruct#3594] opened 2018-07-31 15:31 UTC
A couple of times i have experienced this crash, it seems when i load up a world and teleport the tinkers tool table crashes the game.
https://hastebin.com/xazucodepu.rb

**Comment by SweetSugarSugar** [comment] 2018-07-31 17:35
You have OptiFine installed.

**Comment by gconlon2002** [comment] 2018-07-31 17:44
It has happened with and without optifine. I first experienced it without optifine.

**Comment by KnightMiner** [comment] 2018-07-31 17:57
Duplicate of #3576

**Closed by KnightMiner** 2018-07-31 17:57 UTC
