### ISSUE TITLE
Crafting Stations doesn't show translated Strongbox title.

### ISSUE THREAD

**Issue by Slyklaw** [SlimeKnights/TinkersConstruct#3818] opened 2019-04-08 05:08 UTC
**Issue description:**
Place a Crafting Station next to a TE Strongbox, then open the Crafting Station. The title of the inventory is untranslated. It should show "Strongbox".

![table](https://user-images.githubusercontent.com/44900062/55699469-360a1200-59f5-11e9-88ac-496c7c7f8433.png)

**Comment by KnightMiner** [comment] 2019-04-08 17:07
That sounds really odd, we just return a translation key for all of our inventories, and display them translation using the same key.

Can you please answer the rest of the questions from the issue template? Specifically, we need versions of the mods, and need to know if this happens with just Tinkers and Thermal Expansion (plus either mod's dependencies)

**Comment by Slyklaw** [comment] 2019-04-08 23:36
Yes, this is with only the latest released version of Tinkers and TE (and their required dependencies).

CodeChickenLib 3.2.2.353
CoFH Core 4.6.2.25
CoFH World 1.3.0.6
Mantle 1.3.3.49
Redstone Flux 2.1.0.6
Thermal Expansion 5.5.3.41
Thermal Foundation 2.6.2.26
Tinkers Construct 2.12.0.135

**Comment by KnightMiner** [comment] 2019-09-21 19:44
Closing as a duplicate of #3948 as KingLemming responded on that one

**Closed by KnightMiner** 2019-09-21 19:44 UTC
Labels: 3rd party mod interaction, Not enough information
