### ISSUE TITLE
Shuriken Bugs (1.9, 2.3.0)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2099] opened 2016-05-19 21:07 UTC
Firing one Shuriken while having many of the same type (or possibly even different types) will show all of them reloading
![2016-05-19_01 04 06](https://cloud.githubusercontent.com/assets/14182009/15409618/94792ef8-1de3-11e6-9ba9-9f85fc0f31e2.png)

Shurikens will bypass the Wither's armor (not sure if this is a bug but the Wither armor should deflect all projectiles)
![2016-05-19_01 04 58](https://cloud.githubusercontent.com/assets/14182009/15409677/e6619868-1de3-11e6-91b9-34c69698c746.png)

And a minor graphical bug of the shuriken textures overlaying (sometimes the textures will overlay each other while running but I doubt that this can be fixed)
![2016-05-19_01 00 25](https://cloud.githubusercontent.com/assets/14182009/15409685/ee118da2-1de3-11e6-9a6e-2c14debd4ba5.png)

Not using OptiFine this time :3

**Comment by KnightMiner** [comment] 2016-05-19 22:28
First one sounds intentional. What is the point of a cool down if you can just switch to another slot immeditelly and use that?

I am not sure about the wither armor, but I would assume that is a bug.

**Comment by bonii-xx** [comment] 2016-05-20 06:37
Cooldown is working as intended (that's actually an MC feature)
Wither Armor... will have to check that, since it will probably affect all future projectiles as well then.
Z-fighting with modifiers can't really be prevented easily without breaking other things.

**Comment by LovelyFlare** [comment] 2016-05-27 23:35
Shurikens will also lag the game when there are many of them in a tool forge and on the ground
![2016-05-27_00 59 01](https://cloud.githubusercontent.com/assets/14182009/15623481/eedb2cac-2441-11e6-9722-aa61d348153a.png)
![2016-05-27_00 59 54](https://cloud.githubusercontent.com/assets/14182009/15623480/eed91110-2441-11e6-8e5c-2072b343db21.png)

Also, they damage endermen
![2016-05-27_00 54 44](https://cloud.githubusercontent.com/assets/14182009/15623488/18eed0f2-2442-11e6-9eb6-65d93876ec4b.png)
![2016-05-27_00 54 47](https://cloud.githubusercontent.com/assets/14182009/15623489/18efe6cc-2442-11e6-9696-746e6c762057.png)

**Comment by C1ffisme** [comment] 2016-05-28 02:44
> Shurikens will bypass the Wither's armor (not sure if this is a bug but the Wither armor should deflect all projectiles)

Hmm... The shurikens have such a low range, this might even be intentional, or at least balanced. (Sort of a "ranged melee weapon")

**Comment by bonii-xx** [comment] 2016-10-29 13:24
Has been fixed in either 2.5.6 or next release

**Closed by bonii-xx** 2016-10-29 13:24 UTC
Labels: bug, Resolved
