### ISSUE TITLE
java.lang.NoSuchMethodError on Rendering entity in world

### ISSUE THREAD

**Issue by YuriEdkillers** [SlimeKnights/TinkersConstruct#4474] opened 2021-05-16 12:01 UTC
the game instantly saves and crashes when trying to render slimes (?)
I was excited to play tinkers construct after so long but about 5 minutes in, the game closed by itself (1st crash report)
I tried updating to the latest forge install and generated a new world which instantly closed (2nd crash report)

included : 2 crash reports
https://pastebin.com/tyxLYczw using forge 36.1.10
https://pastebin.com/0E2Pmg2V using forge 36.1.18

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.10 & 36.1.18
* Mantle: 1.6.97
* Tinkers Construct: 3.0.3.152

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I couldn't find any similar issue and it's kind of a game breaker

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
no other mods were used : only tconstruct, mantle, forge and minecraft appears as mod loaded in game

**Comment by ShinyPorygon** [comment] 2021-05-16 12:03
Duplicate of #4316.
![Optifine](https://user-images.githubusercontent.com/35193007/118396449-98468f80-b61d-11eb-8218-d764a01de6c6.gif)

**Closed as completed** 2021-05-16 12:30 UTC
Labels: Performance Enhancers/Optifine, 1.16
