### ISSUE TITLE
Smeltery (controller?) makes items in iron chest disappear

### ISSUE THREAD

**Issue by Nathipha** [SlimeKnights/TinkersConstruct#3670] opened 2018-10-27 21:20 UTC
**Issue description:**
I'm playing on a server with FTB Revelation 2.5.0 with Tinkers Construct, Iron Chests,.... If there's an "Iron Chests" chest (tested with iron and gold) close to a smeltery, all items in the chest disappear a couple of seconds after opening the chest. Re-opening the chest makes them reappear but often they disappear again after a couple of seconds.
Breaking the smeltery controller fixes this issue, putting it down again causes it to happen again but it only seems to happen in the same chunk the controller is in.
The smeltery does cross a chunkborder but I'm not sure if it's related to that: A single wall sticks out into a second chunk and the chests in that other chunk seem to be fine.

**If crashed, link to crash report (use a site such as pastebin):**
No crash

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2759
* Mantle: 1.3.2.24
* Tinkers Construct: 2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
No, you also need "Iron Chests".
We also tested it with "Immersive Engineering"'s crates and it didn't bug out, so not sure if TC or "Iron Chests" is causing this.

**Comment by bonii-xx** [comment] 2018-11-05 19:11
Sounds like you're desyncing with the server. Is it reproducible in singleplayer? Are you running Sponge?

**Comment by Nathipha** [comment] 2018-11-06 19:50
It's affecting 3 out of 4 players (not sure about the 4th) with a smeltery that's shared between 2 players. We all live decently close to where the server is hosted, so I'm not sure why we would be desyncing.

I quickly tested it in SP with the smeltery crossing chunk borders but it didn't bug out in any of the chunks. Afterwards I also tested it with 2 iron chests next to my own smeltery on the server and again it didn't happen. Then again, the first 2 or 3 times I checked in the other player's chests it didn't happen either but after that it happened every time.

It's just the basic FTB pack (plus Roguelike Dungeons), I didn't add it and there's also no file called "Sponge"  in the "mods" folder on the server, so I don't think so.

**Comment by Jkosio23** [comment] 2018-11-12 17:31
I'm getting this bug in singleplayer on ultimate alchemy!

**Comment by laz2727** [comment] 2018-11-12 18:42
Same here, but with tinker table. Especially likes to glitch on inventory
updates. Purely visual though, you can just click the slots and stuff
reappears. I've seen it in SSP though.
<https://github.com/SlimeKnights/TinkersConstruct/issues/3670#issuecomment-437965420>

>

**Comment by bonii-xx** [comment] 2018-11-12 19:39
Sounds like iron chests are having an issue with block updates or similar.

**Comment by Ryuhouji** [comment] 2018-11-26 07:09
This issue is present in my Custom Modpack (WIP). Disabling tinkers' construct does prevent the issue. Items will go invisible after a few seconds in any ironchest. I disabled the tinkers' tooltips and the issue disappeared. It /could/ be a problem with Iron Chests, but making a change to tinkers fixed it so..... try that if you can't do without either mod(like me)

**Comment by cuproPanda** [comment] 2019-01-09 20:36
This issue also affects Immersive Engineering's Wooden Storage Crates located in the same chunk as the smeltery controller. Single player and multiplayer on Enigmatica 2 Expert

**Comment by CourtArtanis** [comment] 2019-01-10 06:37
Happens in SP and MP
Tested 2 different mod combinations :
TConstruct-1.12.2-2.12.0.113
Mantle-1.12-1.3.3.39
ironchest-1.12.2-7.0.54.838

and

TConstruct-1.12.2-2.12.0.113
Mantle-1.12-1.3.3.39
ImmersiveEngineering-0.12-88

Both combinations produce the disappearing result for all ironchest chests, and the wooden storage crate from immersive engineering, respectively.
Items only disappear temporarily. Updating the inventories with a new item or grabbing an invisible item that you knew was there, makes all items appear again temporarily.
Only happens when in the same chunk as a smeltery.

**Comment by laz2727** [comment] 2019-01-11 13:36
By the way, i also noticed this happening with a Ex Nihilo Creatio Auto Sifter as the culprit instead of smeltery. Though i don't really see why world rendering would affect storage.

**Comment by cuproPanda** [comment] 2019-01-11 16:39
I haven't noticed any issues with the Auto Heavy Sieve from Ex Compressum or its chunk. My base is designed vertically, so if it's a per-chunk issue it usually shows up pretty quickly. After some quick testing with the Auto Sifter, I couldn't find any issues with it either, however it wasn't processing anything even with 1500 rotational power. Perhaps when it's set up correctly the Auto Sifter causes an issue, but so far for me the culprit has been the smeltery/controller. After removing the smelteries I haven't had a single issue.

**Comment by NoLoginFound** [comment] 2019-01-17 10:08
It also affects thaumcraft "aracane workbench" and "research table".

**Comment by NoLoginFound** [comment] 2019-01-17 12:50
You need to have a big smeltery to reproduce that. Reproduced with only ironchest and tconstruct(built from current sources). Wasn't happening for 3x3x3 internal space. Happening with 5x5x4 internal space.

**Comment by NoLoginFound** [comment] 2019-01-17 15:56
Seems that this happens because MultiblockDetection sends too many updates when it overrides master for each slave block.
I guess there's no real need to do it unconditionally.
I don't know to what extent it must be checked, so I've tried the simple check for master position.
As far as I see, it solves the issue and doesn't cause any new issues (at least smeltery pours liquids and updates its state/size correctly)
I tried this by replacing this:

`   ((MultiServantLogic) slave).overrideMaster(master);
          IBlockState state = world.getBlockState(pos);
          world.notifyBlockUpdate(pos, state, state, 3);`

With this:

` MultiServantLogic slaveLogic =((MultiServantLogic) slave);
          if(null == slaveLogic.getMasterPosition() || !slaveLogic.getMasterPosition().equals(master)){
            slaveLogic.overrideMaster(master);
            IBlockState state = world.getBlockState(pos);
            world.notifyBlockUpdate(pos, state, state, 3);
          }`

Not making it a pull request because I don't know if such simple check is sufficient.

Not sure if it's allowed or helpful, but I've attached the build file in case you are as frustrated with disappearing inventory as I am, so you can try it at your own risk (I see this issue is opened for a long time, so probably waiting for an official fix will take a lot?). Will play myself on enigmatica 2:expert with this build for some time.
[jar.zip](https://github.com/SlimeKnights/TinkersConstruct/files/2769414/jar.zip)

**Comment by sandokanski** [comment] 2019-03-04 11:51
It happens for me in Stoneblock 2 v. 1.7.0 with the iron chest used to collect items from the casting table. Also happens with the Immersive Engineering Coke Oven that was unfortunate to be in the same chunk as the Smeltery Controller. It does not happen with the Small Storage Crate which is now used in place of the Iron Chest. 
It also happens in SevTech Ages v. 3.0.8 with Extended Crafting tables.

Workaround: Use Small Storage Crate instead of Iron Chest. Do not put anything else that has inventory interface in the same chunk as the Smeltery Controller.

**Comment by ridjack** [comment] 2019-04-27 14:27
Just wanted to note that this is definitely still occurring in the latest Enigmatica 2 Expert. I've seen it with Thaumcraft's Arcane Workbench and Research Table, as well as Immersive Engineering's Storage Crates.

I have not tried the above fix, for what that's worth.

**Comment by xXdRaGoNrIdDeRXx** [comment] 2019-06-01 16:07
wondering when this will get fixed

**Comment by alexbegt** [comment] 2019-06-07 00:55
This has been fixed on the Iron Chests side, updating to the latest version should fix this issue. So sorry for it taking months.

**Closed by alexbegt** 2019-06-07 00:55 UTC
Labels: 3rd party mod interaction
