### ISSUE TITLE
missing animatiation in tinkers construct with board tools

### ISSUE THREAD

**Issue by Helionys** [SlimeKnights/TinkersConstruct#4920] opened 2022-06-23 21:10 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.51

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

When i use the broad axe on a tree in 1.16.5 version, cutting it shows the animation of each block being destroyed, but in the 1.18.2, only the animation of the targeted block is seen, is there any solution for this? It's exactly the same with any other 2-handed tool. Help please.

https://user-images.githubusercontent.com/108089293/175398186-f856296f-aa62-45c6-93d9-f8854ff4988e.mp4

.

### Other mods

Justs TConstruct-1.18.2-3.5.1.31 and Mantle-1.18.2-1.9.27

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by ShinyPorygon** [comment] 2022-06-23 21:15
Unable to reproduce on the same version. Make sure that no other mods are present

**Comment by Helionys** [comment] 2022-06-23 21:27
i did, sorry for the clip, i test it with only the TConstruct and the mantle mods and happens the same issue, the clip is only for more context.
I play a lot in the 1.16.5 version, but when i try in the 1.18.2 version, i notice that the animation of the breaking blocks is gone.

**Comment by KnightMiner** [comment] 2022-06-23 21:34
Most likely a performance mod is breaking things. The above clips make it look like you use a lot of shader mods.  Shaders are likely to blame.

**Comment by Helionys** [comment] 2022-06-23 21:39
> Most likely a performance mod is breaking things. The above clips make it look like you use a lot of shader mods. Shaders are likely to blame.

You are right in the clip i use BSL shader, but like i said, i testet in a clean instalation whit only thouse mods, and no shaders. :(

**Comment by KnightMiner** [comment] 2022-06-23 21:42
The clip in both cases shows the breaking animation. Do you have a clip showing a lack of breaking animation?

**Comment by Helionys** [comment] 2022-06-23 22:02
In the first half of the clip shows only the animation of the target block blowing up, but in the second half shows the target and all the others blowing up

**Comment by KnightMiner** [comment] 2022-06-23 23:02
Oh, you want breaking particles, not breaking animation. Breaking animation typically means the cracking texture.

Can you upload a video showing no breaking particles on that minimal setup without shaders?

**Comment by Helionys** [comment] 2022-06-24 00:54
You 

> Oh, you want breaking particles, not breaking animation. Breaking animation typically means the cracking texture.
> 
> Can you upload a video showing no breaking particles on that minimal setup without shaders?

You nail it!

here is the clip

https://user-images.githubusercontent.com/108089293/175438705-8b2e3940-df73-4e25-ac95-0c8313bc4946.mp4


https://user-images.githubusercontent.com/108089293/175438915-98006ffa-395d-42ef-a1cb-77bbae4bf2f5.mp4

**Comment by KnightMiner** [comment] 2022-12-28 03:35
Fixed in 3.6.0.73

**Closed as completed by KnightMiner** 2022-12-28 03:35 UTC
Labels: Bug, Resolved, 1.18
