### ISSUE TITLE
[Create: Above & Beyond] All Parts & Weapon's textures are white, only shape is conserved.

### ISSUE THREAD

**Issue by Alonsinwhat** [SlimeKnights/TinkersConstruct#4657] opened 2021-11-13 19:34 UTC
### Minecraft Version

1.16.5

### Forge Version

Forge 36.2.8

### Mantle Version

Mantle-1.16.5-1.6.127

### Tinkers' Construct Version

TConstruct-1.16.5-3.1.3.271

### Describe your issue

Game wont load textures correctly, probably because of Halogen or other mod in the pack.

Everything will just be white, without any colors indicating material, only name.
![image](https://user-images.githubusercontent.com/79758771/141656756-f528c41e-2e08-41e3-845c-f67fdba4f787.png)

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Tried with Create: Above & Beyondd, with Halogen installed. I think this might be the problem.

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment] 2021-11-13 19:36
Duplicate # 3 of #4614. This is why that last checkbox exists. This bug is caused by a performance enhancer, which taking 5 minutes to test would have told you.

The reason we don't support performance enhancers is they often break vanilla or forge code. This case they are breaking forge code, so yell at them to stop breaking forge code.

**Comment by ShinyPorygon** [comment] 2021-11-13 19:36
Duplicate of #4614 

Also good job actually searching the tracker since you said you did.

**Closed as completed by KnightMiner** 2021-11-13 19:36 UTC
Labels: Duplicate, Performance Enhancers/Optifine, 1.16
