### ISSUE TITLE
Crash That May Be Caused By Crit

### ISSUE THREAD

**Issue by StarVYT** [SlimeKnights/TinkersConstruct#3515] opened 2018-05-30 16:59 UTC
Hello! It appears that if I land a critical hit on an entity, the game will sometimes crash. I believe this may have something to do with Dynamic Surroundings, since I saw someone get the exact same crash as me [here](https://pastebin.com/TVY3e4ry), and they also have DS installed. Based on the loaded entities, they were in the nether, which I was as well, but I could not find anything about what they posted. The crash happens on both [client](https://pastebin.com/Xn2JnRPR) and [server](https://pastebin.com/1e3QkPQ7). On the client, it happens on line 74 in slimeknights.tconstruct.shared.client.ParticleEffect, which calls super for the renderParticle method, and the class extends ParticleCrit, which DS changes some things for. Thanks for reading!

**Comment by KnightMiner** [comment] 2018-05-30 21:42
You say you think this is caused by Dynamic Surroundings, does it happen without Dynamic Surroundings?

**Comment by StarVYT** [comment] 2018-05-30 23:43
Upon further testing, I installed only Mantle, Tinker's Construct, and Dynamic Surroundings, and the crash doesn't seem to happen anymore, which is odd, since the log states there's a TC method being called. I'll have to look into it more.

**Comment by bonii-xx** [comment] 2018-05-31 12:52
It must be save to extend ParticleCrit. I assume dynamic surroundings just spawns its own crit particle, which has absolutely no impact on the ones TiC spawns. I don't see how those could interfere besides some heavy coremodding. In either case it's very unlikely that it has something to do with TiC. I'm also using dynamic surroundings and TiC in my own modpack without problems. ;)

Give us a heads up if you find anything, I'll close the issue for now since there's nothing to do for us.

**Closed by bonii-xx** 2018-05-31 12:52 UTC
