### ISSUE TITLE
amethyst bronze color is not correct, enhancements not visible either

### ISSUE THREAD

**Issue by Chest0** [SlimeKnights/TinkersConstruct#4922] opened 2022-06-25 21:46 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Mantle Version

1.18.2-1.9.27

### Tinkers' Construct Version

1.18.2-3.5.1.31

### Describe your issue

I'm playing with a modpack on a server with a few friends, and my friend says my sword is purple and sent a screenshot showing the correct color of amethyst bronze, with a diamond enhancement on it. on my end, the sword appears brownish, like normal bronze, and the same goes for my pickaxe.
the normal sword on my friend's client:
![image](https://user-images.githubusercontent.com/108198574/175791080-a472bffd-1691-4175-b86e-6a93e6bfe9f6.png)
sword on my client:
![image](https://user-images.githubusercontent.com/108198574/175791090-46852d24-c694-4d3a-9377-c15cc76e1b09.png)
when using tinker's alone, the sword looks like normal, purple metal with the diamond blade.
here is the CurseForge modpack I am using.
https://drive.google.com/file/d/1Fo2txzL5YCG7ylSb4V_AlPujtpRyTIL4/view?usp=sharing 

### Other mods

create
tinker's
waystones
mekanism
better netherite
(full modpack included within issue)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment] 2022-06-26 04:42
Is this a newly crafted sword, or is this a sword that  you have had around since alpha builds of the mod? Try a newly crafted sword.

**Comment by Chest0** [comment] 2022-06-26 13:49
I haven't updated the mod, my friends and i have all same versions and we started up the server just 2 days ago. The only difference is that the sword looks brown to me and to.him the sword is the normal texture. I've yet to try deleting each mod one by one to see compat issues, but using the exact version of TC and Mantle alone is just fine.

**Comment by KnightMiner** [comment] 2022-06-26 17:46
there is literally no reason it should look brown to you unless you are using a resource pack. Or Optifine or other performance mods. So really not much else I can say.

The fact it only happens for you strongly implies you have a client sided mod installed that your friend does not which is breaking this,

**Comment by sorinstratu1998** [comment] 2022-06-27 18:56
{
  "fallbacks": [
    "metal"
  ],
  "color": "754d73",
  "luminosity": 0,
  "generator": {
    "transformer": {
      "type": "tconstruct:recolor_sprite",
      "color_mapping": {
        "type": "tconstruct:grey_to_color",
        "palette": [
          {
            "grey": 0,
            "color": "754d73"
          },
          {
            "grey": 63,
            "color": "d775c0"
          },
          {
            "grey": 102,
            "color": "d279be"
          },
          {
            "grey": 140,
            "color": "ce7ebb"
          },
          {
            "grey": 178,
            "color": "cd7ebb"
          },
          {
            "grey": 216,
            "color": "dba3ce"
          },
          {
            "grey": 255,
            "color": "e6bfdd"
          }
        ]
      }
    },
    "supportedStats": [
      "tconstruct:head",
      "tconstruct:handle",
      "tconstruct:extra",
      "tconstruct:repair_kit",
      "tconstruct:plate"
    ],
    "ignoreMaterialStats": false
  }
}

**Comment by sorinstratu1998** [comment] 2022-06-27 19:00
assets/tconstruct/tinkering/materials/amethyst_bronze.json
change the content to the one I sent earlier

**Comment by sorinstratu1998** [comment] 2022-06-27 19:08
![2022-06-27_21 01 09](https://user-images.githubusercontent.com/107169719/176017227-59eb9f49-5a11-4e2e-9f62-7f0699b63322.png)

**Comment by KnightMiner** [comment] 2022-06-27 19:18
Changing that file should not change the colors. The problem here is amethyst bronze is using the fallback texture instead of the proper textures. This is not possible unless you have a mod breaking rendering in some way making the fallback textures not load, which if that did happen would not be server exclusive.

Sure, I can fix the color (which I will do eventually), but that does not fix the heart of the problem. I suspect you will find Queens Slime is solid green instead of a gradient.

**Comment by Sorinstratu** [comment] 2022-06-27 19:23
Previously, this metal was Silicon Bronze or Tinker Bronze after 1.16.5 it was changed according to this textures from the old material

**Comment by Chest0** [comment] 2022-06-27 20:14
> .

Queen slime is solid green, but i do not get how mune and his client are rendering the texture differently even though his is the same?

**Comment by Chest0** [comment] 2022-06-27 20:16
Also, how do you get the enhancementa to be visible? That is another thing that won't work

**Comment by Sorinstratu** [comment] 2022-06-27 20:25
For Queens Slime, everything is different because metal consists of two different colors

**Comment by Sorinstratu** [comment] 2022-06-27 20:28
Waiting for the release for 1.18.2

**Comment by KnightMiner** [comment] 2022-06-27 20:35
You do not need to leave multiple comments for a single reply, spend a bit longer to get a single coherent reply. You can edit old comments as well if needed.

> Queen slime is solid green, but i do not get how mune and his client are rendering the texture differently even though his is the same?

That means texture loading is broken on your client. As usual, I blame performance mods as this works in a normal forge client, both for me and many people playing on servers.

> Also, how do you get the enhancementa to be visible? That is another thing that won't work

You mean modifiers to be visible? Not all modifier textures are done. The ones that are done run on the same code that makes queens slime not solid green. So again, you have a performance mod breaking things most likely.

> Waiting for the release for 1.18.2

Release does not automatically fix all bugs. Tinkers is marked release or beta based on major features not being finished yet (like bows). Even when its released, there are bound to be bugs, otherwise Minecraft would still be in beta status to this day.

**Comment by Sorinstratu** [comment] 2022-06-27 20:56
> You do not need to leave multiple comments for a single reply, spend a bit longer to get a single coherent reply. You can edit old comments as well if needed.
> 
> 
> 
> > Queen slime is solid green, but i do not get how mune and his client are rendering the texture differently even though his is the same?
> 
> 
> 
> That means texture loading is broken on your client. As usual, I blame performance mods as this works in a normal forge client, both for me and many people playing on servers.
> 
> 
> 
> > Also, how do you get the enhancementa to be visible? That is another thing that won't work
> 
> 
> 
> You mean modifiers to be visible? Not all modifier textures are done. The ones that are done run on the same code that makes queens slime not solid green. So again, you have a performance mod breaking things most likely.
> 
> 
> 
> > Waiting for the release for 1.18.2
> 
> 
> 
> Release does not automatically fix all bugs. Tinkers is marked release or beta based on major features not being finished yet (like bows). Even when its released, there are bound to be bugs, otherwise Minecraft would still be in beta status to this day.
> 
> 
> 
> 

Some mods or plugins may change or destroy model textures.
EXAMPLES:OptiFine or Kubejs or ResourcesPacks or Mantle

![image](https://user-images.githubusercontent.com/91439401/176033714-718de006-28f7-4051-b5a2-7a5134b98a24.jpeg)
On the official page Curseforge/tconstruct

Upgrades, not everyone has a texture, not everyone works either


And bugs will be Minecraft all the time. 😀

**Comment by KnightMiner** [comment] 2022-06-27 21:00
... you do realize Mantle is **the library required for Tinkers Construct**? Mantle is not a performance mod breaking stuff, **I intentionally moved content from Tinkers Construct to Mantle**, which also is entirely unrelated to this bug. Do not lump it in the same category as Optifine, where the dev deletes forge code and then takes 4 months to look at the issue report.

**Comment by Chest0** [comment] 2022-06-27 23:30
Is there any history with betterfps affecting textures? I know sodium/rubidium messes up textures, but i already changed config for those. The only other optimizer is probably betterfps. I'll look into rubidium configs a bit more, but the only config i have changes is setting 'mixin.textures.item=false'

**Comment by Sorinstratu** [comment] 2022-06-27 23:57
> Is there any history with betterfps affecting textures? I know sodium/rubidium messes up textures, but i already changed config for those. The only other optimizer is probably betterfps. I'll look into rubidium configs a bit more, but the only config i have changes is setting 'mixin.textures.item=false'

I'm trying to explain that textures of tools are generated through TinkeringModel with Mantle and do not have the simple texture.png. Apparently, the color calculation or color generator is not correct.

**Comment by KnightMiner** [comment] 2022-06-28 04:36
Look, I know how my own code works. The textures are correctly generated. The fallback color is wrong hence why the original issue mentioned the color is so different, but no one should ever see the fallback color

Regarding `<performance mod>`, I don't care if performance mod has a history of breaking tinkers. **test without it**. Honestly, test with as few mods as possible. I cannot help you if the bug only happens on a server with an unknown list of 100 mods. I need minimal test cases so I can reproduce it. Without that, I cannot help anyone.

**Comment by KnightMiner** [comment] 2022-11-23 07:00
I am going to close this as I have gotten no confirmation from the original poster that they ever reprouced this with just tinkers, and I cannot do anything about an issue that takes 100 mods to reproduce.  Get me a list of 5 or fewer mods that cause this bug and we can reopen.

**Closed as completed by KnightMiner** 2022-11-23 07:00 UTC
Labels: Bug, Needs Update, Not enough information, 1.18
