### ISSUE TITLE
Game Crashes when equipping travelers goggles if optifine is being used

### ISSUE THREAD

**Issue by ProgramPotato** [SlimeKnights/TinkersConstruct#4778] opened 2022-02-22 21:40 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

Game Crashes if you equip Travelers goggles while optifine is being used with or without shaders

[crash-2022-02-22_14.33.15-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8120337/crash-2022-02-22_14.33.15-client.txt)

### Crash Report

https://github.com/SlimeKnights/TinkersConstruct/files/8120337/crash-2022-02-22_14.33.15-client.txt

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Optifine_1.18.1_HD_U_H4

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-22 21:44
Duplicate of #4734 Good to know that you didn't actually check the issue tracker. Remove optifine.

**Closed as completed by ShinyPorygon** 2022-02-22 21:44 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
