### ISSUE TITLE
[Crash] Updating screen events

### ISSUE THREAD

**Issue by Sanofus** [SlimeKnights/TinkersConstruct#3491] opened 2018-05-18 19:46 UTC
It happend twice as I was trying to put my pick axe in the tool station.

[crash-2018-05-18_21.37.56-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2018403/crash-2018-05-18_21.37.56-client.txt)
[crash-2018-05-18_21.43.53-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2018404/crash-2018-05-18_21.43.53-client.txt)

**Comment by KnightMiner** [comment] 2018-05-18 19:55
Duplicate of #3372, TAIGA's fault.

**Closed by KnightMiner** 2018-05-18 19:55 UTC

**Comment by Sanofus** [comment] 2018-05-18 19:58
But I did not use a material from TAIGA.

**Comment by KnightMiner** [comment] 2018-05-18 20:03
Does not matter, one of their modifiers was broken causing the crash when any tool is placed in the tool station

**Comment by Sanofus** [comment] 2018-05-18 20:08
Is there a work around for that? Because that makes TAIGA completly useless if no tool can by placed in the tool station.

**Comment by KnightMiner** [comment] 2018-05-23 18:53
Yeah, the work around unfortunately is don't use TAIGA. You might be able to find an older version without the crash, but the issue is ultimately from a hasty port without testing.
