### ISSUE TITLE
Items Invisible?

### ISSUE THREAD

**Issue by BlazingV** [SlimeKnights/TinkersConstruct#3067] opened 2017-07-30 15:48 UTC
Most casts and about half the tools/tool parts are invisible when I craft them and/or look at them through JEI.

Minecraft Version: **1.12**
Forge Build: **14.21.1.2426**

Screenshots are included below.

![screenshot_19](https://user-images.githubusercontent.com/16764953/28754907-cfa0f130-7546-11e7-8120-795920647a25.png)
![screenshot_20](https://user-images.githubusercontent.com/16764953/28754908-cfa656f2-7546-11e7-8a7f-47bcd7952ca4.png)
![screenshot_21](https://user-images.githubusercontent.com/16764953/28754909-cfe14546-7546-11e7-8513-389baf98ff04.png)
![screenshot_22](https://user-images.githubusercontent.com/16764953/28754910-cfe35958-7546-11e7-8153-a6d5a8d5a99c.png)
![screenshot_23](https://user-images.githubusercontent.com/16764953/28754911-cfed62ae-7546-11e7-8e31-7681b32d327d.png)
![screenshot_24](https://user-images.githubusercontent.com/16764953/28754912-cff0dba0-7546-11e7-9b0f-de8b2fb7ceba.png)
![screenshot_25](https://user-images.githubusercontent.com/16764953/28754913-d019167e-7546-11e7-95c7-211704a1b307.png)
![screenshot_26](https://user-images.githubusercontent.com/16764953/28754914-d01c9d12-7546-11e7-953b-0bc05fde092c.png)

**Comment by TheSnowyChickens** [comment] 2017-07-30 15:51
Update Optifine, or play without.

**Comment by KnightMiner** [comment] 2017-07-30 15:52
Duplicate of #3008

**Closed by KnightMiner** 2017-07-30 15:52 UTC
