### ISSUE TITLE
Plate Armor Crash

### ISSUE THREAD

**Issue by BagusTresna** [SlimeKnights/TinkersConstruct#4828] opened 2022-04-09 13:18 UTC
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

when using / place plate armor on armor stand, the game suddenly crashes

[crash-2022-04-09_21.01.40-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8456982/crash-2022-04-09_21.01.40-client.txt)

### Other mods

yes

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by ShinyPorygon** [comment] 2022-04-09 13:22
Duplicate of #4734 Remove optifine

**Closed as completed by ShinyPorygon** 2022-04-09 13:22 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
