### ISSUE TITLE
1.12 TConstruct conflict with ExNihilo Creatio

### ISSUE THREAD

**Issue by Travis9x** [SlimeKnights/TinkersConstruct#3153] opened 2017-09-10 18:27 UTC
I know this involves two separate mods, so I am posting this crash on both mods' threads/pages.  Crash detail as follows:

[PasteBin link](https://pastebin.com/0Juv7Ght)

**Comment by KnightMiner** [comment] 2017-09-10 21:56
Duplicate of #4139/on ex nihilo's side

**Closed by KnightMiner** 2017-09-10 21:56 UTC
