### ISSUE TITLE
FPS drop JEI + Tinker's

### ISSUE THREAD

**Issue by NerdCraft** [SlimeKnights/TinkersConstruct#2926] opened 2017-05-25 15:05 UTC
![2017-05-24_16 09 00](https://cloud.githubusercontent.com/assets/13489837/26455707/612482c8-4141-11e7-88c6-cc0179cba07c.png)
![2017-05-24_16 09 08](https://cloud.githubusercontent.com/assets/13489837/26455708/6127c96a-4141-11e7-9bb2-61a3b9a3f41d.png)
![2017-05-24_16 09 14](https://cloud.githubusercontent.com/assets/13489837/26455706/611834f0-4141-11e7-9a28-0c16b7c3f9be.png)

**Comment by bonii-xx** [comment] 2017-05-25 16:06
Yes, many complex items drawn at once is slow.

**Comment by NerdCraft** [comment] 2017-05-25 16:23
Is there a way to fix this?

**Comment by bonii-xx** [comment] 2017-05-25 16:23
Displaying less items at once in JEI

**Comment by NerdCraft** [comment] 2017-05-25 16:25
Will this be fixed in the mod? Because it does not happen in 1.10.2

**Comment by bonii-xx** [comment] 2017-05-25 16:26
This can't be fixed in the mod. It's not a bug in the mod. You can only remove anything that impacts rendering and see if it gets better.

**Closed** 2017-05-25 16:27 UTC
Labels: OptiFine
