### ISSUE TITLE
java.util.NoSuchElementException: Missing key ICHOR

### ISSUE THREAD

**Issue by ModernGamingWorld** [SlimeKnights/TinkersConstruct#5202] opened 2024-04-03 04:18 UTC
### Minecraft Version

1.19.2

### Forge Version

43.3.9

### Mantle Version

Mantle-1.19.2-1.10.23

### Tinkers' Construct Version

3.8.0.14

### Describe your issue

Description: Exception in server tick loop

java.util.NoSuchElementException: Missing key ICHOR
	at slimeknights.mantle.registration.object.EnumObject.get(EnumObject.java:53) ~[Mantle-1.19.2-1.10.23.jar%231097!/:1.19.2-1.10.23] {re:classloading}
	at slimeknights.tconstruct.fluids.TinkerFluids.lambda$static$3(TinkerFluids.java:81) ~[TConstruct-1.19.2-3.8.0.14.jar%231277!/:1.19.2-3.8.0.14] {re:classloading,pl:eventbus:A}
	at slimeknights.tconstruct.fluids.item.ContainerFoodItem$FluidContainerFoodItem.initCapabilities(ContainerFoodItem.java:87) ~[TConstruct-1.19.2-3.8.0.14.jar%231277!/:1.19.2-3.8.0.14] {re:classloading}
	at net.minecraft.world.item.ItemStack.lambda$forgeInit$12(ItemStack.java:1012) ~[client-1.19.2-20220805.130853-srg.jar%231341!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:itemstack,re:classloading,pl:accesstransformer:B,xf:fml:forge:itemstack,pl:mixin:APP:recipeessentials.mixins.json:nbt.ItemStackMixin,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.item_cache_flag.ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinItemStack,pl:mixin:APP:ars_instrumentum.mixins.json:GlyphCostMixin,pl:mixin:APP:easyshulkerboxes.common.mixins.json:ItemStackMixin,pl:mixin:APP:relics.mixins.json:ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemStackMixin,pl:mixin:APP:skilltree.mixins.json:minecraft/ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinItemStack,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapabilities(CapabilityProvider.java:87) ~[forge-1.19.2-43.3.9-universal.jar%231346!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:182) ~[forge-1.19.2-43.3.9-universal.jar%231346!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:33) ~[forge-1.19.2-43.3.9-universal.jar%231346!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.fluids.FluidUtil.getFluidHandler(FluidUtil.java:426) ~[forge-1.19.2-43.3.9-universal.jar%231346!/:?] {re:classloading}
	at net.minecraftforge.fluids.FluidUtil.getFluidContained(FluidUtil.java:437) ~[forge-1.19.2-43.3.9-universal.jar%231346!/:?] {re:classloading}
	at me.desht.pneumaticcraft.common.event.MiscEventHandler.handleFuelEvent(MiscEventHandler.java:105) ~[pneumaticcraft-repressurized-1.19.2-4.3.14-49.jar%231185!/:1.19.2-4.3.14-49] {re:classloading}
	at me.desht.pneumaticcraft.common.event.__MiscEventHandler_handleFuelEvent_FurnaceFuelBurnTimeEvent.invoke(.dynamic) ~[pneumaticcraft-repressurized-1.19.2-4.3.14-49.jar%231185!/:1.19.2-4.3.14-49] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.getItemBurnTime(ForgeEventFactory.java:214) ~[forge-1.19.2-43.3.9-universal.jar%231346!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraftforge.common.ForgeHooks.getBurnTime(ForgeHooks.java:1273) ~[forge-1.19.2-43.3.9-universal.jar%231346!/:?] {re:mixin,re:classloading,pl:mixin:APP:apotheosis.mixins.json:ForgeHooksMixin,pl:mixin:APP:tombstone.mixins.json:ForgeHooksMixin,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.m_58399_(AbstractFurnaceBlockEntity.java:366) ~[client-1.19.2-20220805.130853-srg.jar%231341!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:AbstractFurnaceBlockEntityAccessor,pl:mixin:APP:botania_forge.mixins.json:AbstractFurnaceBlockEntityForgeAccessor,pl:mixin:APP:itemproductionlib.mixins.json:minecraft/AbstractFurnaceBlockEntityMixin,pl:mixin:APP:decorative_blocks.mixins.json:AbstractFurnaceTileEntityMixin,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.AbstractFurnaceBlockEntityAccess,pl:mixin:APP:immersiveengineering.mixins.json:accessors.FurnaceTEAccess,pl:mixin:APP:polymorph.mixins.json:AccessorAbstractFurnaceBlockEntity,pl:mixin:A}
	at com.minecolonies.api.compatibility.CompatibilityManager.discoverFuel(CompatibilityManager.java:758) ~[minecolonies-1.19.2-1.1.516-BETA.jar%231120!/:1.19.2-1.1.516-BETA] {re:classloading}
	at com.minecolonies.api.compatibility.CompatibilityManager.discover(CompatibilityManager.java:222) ~[minecolonies-1.19.2-1.1.516-BETA.jar%231120!/:1.19.2-1.1.516-BETA] {re:classloading}
	at com.minecolonies.core.event.DataPackSyncEventHandler$ServerEvents.discoverCompatLists(DataPackSyncEventHandler.java:54) ~[minecolonies-1.19.2-1.1.516-BETA.jar%231120!/:1.19.2-1.1.516-BETA] {re:classloading}
	at com.minecolonies.core.event.DataPackSyncEventHandler$ServerEvents.onServerStarted(DataPackSyncEventHandler.java:125) ~[minecolonies-1.19.2-1.1.516-BETA.jar%231120!/:1.19.2-1.1.516-BETA] {re:classloading}
	at com.minecolonies.core.event.__ServerEvents_onServerStarted_ServerStartedEvent.invoke(.dynamic) ~[minecolonies-1.19.2-1.1.516-BETA.jar%231120!/:1.19.2-1.1.516-BETA] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:109) ~[forge-1.19.2-43.3.9-universal.jar%231346!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:629) ~[client-1.19.2-20220805.130853-srg.jar%231341!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231341!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

### Other mods

https://www.curseforge.com/minecraft/modpacks/monumental-experience/files/5231266

I added to this version and logged into world and crashed

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Rubidium/Embeddium, Other (specify under other mods)

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment] 2024-04-03 04:22
Wonder what that mod is doing that causes this to crash on world load. I could see crashing when you use the bottle on a tank but not on world load. Easy enough fix in any case.

**Comment by ModernGamingWorld** [comment] 2024-04-03 04:23
Yeah idk, My modpack is like 500 to 600ish mods, so anything can happen lol

It does mention Minecolonies, so that might be what;s conflicted

but your free to test with my pack if u like

**Comment by KnightMiner** [comment] 2024-04-03 05:05
Nah, I know what the issue is, at a quick glance it would crash if you tried to right click one of our tanks with an ichor bottle. It crashing on startup is weird, but fixing the non-startup crash fixes the startup one.

**Comment by KnightMiner** [comment] 2024-04-08 05:47
Fixed in v3.8.1.16

**Closed as completed by KnightMiner** 2024-04-08 05:47 UTC
Labels: Bug, Resolved, Confirmed, 1.19
