### ISSUE TITLE
Crafting duplication (or crafting without using items in multiplayer)

### ISSUE THREAD

**Issue by MrGREGhimself** [SlimeKnights/TinkersConstruct#3714] opened 2019-01-06 15:11 UTC
**Issue description:**
In multiplayer Player1 puts items in the Tinkers Crafting Table (for example 4 blocks of sand), output shows 1 Sandstone. If before Player1 collects Sandstone, Player2 opens table's inventory then the output item will stay (get duplicated if crafted) or if Player1 puls the ingredients out, Player2 can still collect the output item. 
This works with both vanilla and modded items.
This is not the case in other crafting tables. 

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2796
* Mantle: 1.3.3.39
* Modpack: FTB presents Stoneblock 2 (1.0.1)
* Tinkers Construct: 2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Not tested just with Tinkers Construct.

**Comment by Sunekaer** [comment] 2019-01-07 15:53
Another:
Issue: When a crafting station (The tinkers one that can access a chest inventory) is placed next to a cobble generator (Mine is tier 3) If you have an item in the crafting table and you use JEI to select a new recipe and as long as you have the items, the item that was in the crafting table will get put into the cobblestone generator because that crafting station has access to it's inventory. Now, instead of generating cobblestone it would generate the item that got put in there. Also, if you try to shift+click it out of there, it will put it into the crafting table and continue generating the material.

**Comment by KnightMiner** [comment] 2019-01-07 17:10
@Sunekaer do not hijax an issue to report an unrelated issue. Open a new ticket

**Comment by Sunekaer** [comment] 2019-01-07 17:57
Thought it would be the same thing causing it

**Comment by Sunekaer** [comment] 2019-01-07 17:58
But this is not a dupe just the cobble gen items being "hopper" in to the table?

**Comment by KnightMiner** [comment] 2019-01-07 18:22
The topic issue is about a multiplayer dupe bug, the other one is about inserting items into a side inventory. And I did not say its not a dupe bug, just not on our side as all we do is hopper items into the side inventory.

**Comment by yaroslav4167** [comment] 2019-01-20 14:46
I have a similar problem.
This works in workbenches that allow two players to be in them simultaneously.
Reproduce : [https://youtu.be/Aex9fl405as](https://youtu.be/Aex9fl405as)
In my minecraft I installed only the tested mod and forge. 
I already wrote to the forge [here](http://www.minecraftforge.net/forum/topic/68345-bugduplicate-on-craft-tables-1122/) / [here](https://github.com/MinecraftForge/MinecraftForge/issues/5383), I was advised to contact mod developers.
I'm tested this bug with mods: TConstruct, RealBench, ThaumCraft (Bug works)

**Comment by rbandboy** [comment] 2019-01-25 02:03
Further tested, reproducible with TCon 2.12.0.115 in forge 14.23.5.2796.  Unless this has already been addressed, I would recommend investigation.

**Comment by rbandboy** [comment] 2019-01-25 02:10
Perhaps this is an issue with 1.3.3.39 Mantle?

**Comment by runescapejon** [comment] 2019-03-09 20:47
Here a demonstration GIF: https://gyazo.com/98048f21770b58ecb1199d4a8b6bfc65

**Comment by winnetrie83** [comment] 2019-03-10 15:13
Hello, me and my son just discovered this bug too. We reported it here: [https://github.com/Sunekaer/stoneBlock/issues/794](url)
You can see it happen in this video: [https://youtu.be/b1-OFFwMuVk](url)

**Comment by bonii-xx** [comment] 2019-03-15 15:40
Thanks for all the reports, I found the missing synchronisation.

**Comment by bonii-xx** [comment] 2019-03-15 16:44
I threw out a test build with the fix here: https://minecraft.curseforge.com/projects/tinkers-construct/files/2687590
Maybe some of you could test it and see if you can reproduce the issue. SSP and MP in dev worked fine so far, but that's quite isolated.

**Comment by runescapejon** [comment] 2019-03-15 16:54
Just test it https://gyazo.com/1d04470eb3c6abf8a46cd50f6cb10eca not fix on my forge server

**Comment by KnightMiner** [comment] 2019-03-15 17:35
Did you update on both the clients and the server? It appears to be mostly working when I test in dev

**Comment by runescapejon** [comment] 2019-03-15 17:37
Yes i just double make sure and yeah i do i have version TConstruct-1.12.2-2.12.0.120 and Mantle-1.12-1.3.3.42

**Comment by runescapejon** [comment] 2019-03-15 17:43
Ohh it's semi fix it seem if both players are currently in the crafting station it's fixed but however if one player craft an item (example diamond craft it to diamond block) then once crafting slots are in the crafting station and you got a crafting output then get player number two to right click the crafting station then you both can perform the bug.

**Comment by winnetrie83** [comment] 2019-03-15 17:58
@runescapejon i think that's exactly what i reported before this "fix". Look at the video i linked. I'm not a ware of a duping bug in single player.

**Comment by bonii-xx** [comment] 2019-03-15 18:03
K, so still one sync missing it seems, thanks for the test.

**Comment by KnightMiner** [comment] 2019-03-21 01:33
Should be fixed by eda98a6 now. I've uploaded a second test build with the fix here if you'd like to test it: https://minecraft.curseforge.com/projects/tinkers-construct/files/2689863

**Comment by runescapejon** [comment] 2019-03-21 07:42
Yes can confirm the dupe bug is finally fixed. Thank for all your time. <3

**Comment by runescapejon** [comment] 2019-03-21 08:10
Also there a debug https://github.com/SlimeKnights/TinkersConstruct/blob/8bf35c3f12b34ae82f3b3aec593cfb90107662cf/src/main/java/slimeknights/tconstruct/tools/common/inventory/ContainerCraftingStation.java#L171
that is triggering whenever you right click the table.

**Closed** 2019-03-30 22:18 UTC
Labels: Resolved, bug
