### ISSUE TITLE
1.16.5 TConstruct Crashes on World Load with JEI

### ISSUE THREAD

**Issue by ImpMind** [SlimeKnights/TinkersConstruct#4631] opened 2021-10-04 11:08 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.6

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

Whenever I load a world, it saves and crashes. It seems to be something to do with JEI because when I take it out it no longer crashes, but I would like to use JEI along with Tinkers.

### Crash Report

https://gist.github.com/ImpMind/4723bc92e46de582bb6367c514d9af1b

### Reproduced with only Tinkers' Construct?

No

### Other mods required

jei-1.16.5-7.7.1.122
Mantle-1.16.5-1.6.123
TConstruct-1.16.5-3.1.2.265

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by luckyu19** [comment] 2021-10-04 11:58
Able to replicate this bug with the aforementioned mods version and even after updating forge to 36.2.8 the issue persisted.
[crash-2021-10-04_19.52.51-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/7277799/crash-2021-10-04_19.52.51-client.txt)
Seems like there's several crash reported over on JEI, I would suggest linking this their issue tracker as well as it seems to be a problem on their end.

**Comment by ImpMind** [comment] 2021-10-04 12:07
> Able to replicate this bug with the aforementioned mods version and even after updating forge to 36.2.8 the issue persisted. [crash-2021-10-04_19.52.51-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/7277799/crash-2021-10-04_19.52.51-client.txt) Seems like there's several crash reported over on JEI, I would suggest linking this their issue tracker as well as it seems to be a problem on their end.

Okay, I'll try reporting this there and see their response, thanks.

**Comment by juanfrommexic** [comment] 2021-10-04 16:56
jei seems to be the problem. I installed older version and everything works just fine.

**Comment by KnightMiner** [comment] 2021-10-04 17:10
This is not a JEI bug really. Its a Tinkers bug. However, I think a bug in JEI that was recently fixed cause us to finally realize this bug exists. Looks like mezz/JustEnoughItems#2506.

Point of this comment is to say don't go posting this on the JEI issue tracker, I know what the issue is and how to fix it. This is a bug in Tinkers we just did not notice before as that method was never called before.

**Comment by juanfrommexic** [comment] 2021-10-04 17:15
It's probably how you described it but still downloading older version works as a temporary solution.

**Comment by Nessuno6** [comment] 2021-10-05 15:50
dunque se io volessi usare sia tinker che jei come potrei fare?

**Comment by KnightMiner** [comment] 2021-10-05 15:58
> dunque se io volessi usare sia tinker che jei come potrei fare?

Be patient or downgrade JEI

**Comment by Nessuno6** [comment] 2021-10-05 16:06
sorrry for lenguage i wrote this in italian and i have not noticed it

what do you mean with be patient... is there a way to use both?

**Comment by KnightMiner** [comment] 2021-10-05 17:24
I mean wait and it will be fixed.

**Comment by KnightMiner** [comment] 2021-10-06 04:57
Fixed in 3.1.3.271

**Closed as completed by KnightMiner** 2021-10-06 04:57 UTC
Labels: Bug, Resolved, 1.16, Confirmed
