### ISSUE TITLE
Crash on updating faucet connected to filling tank/gauge

### ISSUE THREAD

**Issue by Psymatics** [SlimeKnights/TinkersConstruct#3297] opened 2017-12-23 11:24 UTC
This is...obnoxious.

I have a small smeltery to melt items, that immediately drains into a gauge, and then from the gauge into a Tinker Tank. In order to keep the liquid pouring I run a redstone clock of some sort that connects directly to the gauge and/or faucets to keep them updating. However if that clock updates the second faucet while the first one is pouring, the game crashes.

My current workaround is using clock-rigged Glowstone Lamps adjacent to the Faucets, while keeping the faucets constantly powered. This doesn't cause a crash, but it's a lot more complicated to set up.

[crash-2017-12-23_04.22.07-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1584047/crash-2017-12-23_04.22.07-server.txt)

**Comment by bonii-xx** [comment] 2017-12-23 13:36
Can you reproduce this reliably? You're running an old version of TiC, I think there was a fix in that region in that update. See if you can reproduce on 2.8.1.49

**Comment by Psymatics** [comment] 2018-01-19 22:11
Sheesh, has it been a month already? Sorry for taking so long.

As of the latest TiC build, this doesn't seem to occur. Thanks for keeping this mod maintained!

Now I just need to figure out why my modpack can't load a world on the newer Forge versions so I can update TiC.

**Comment by bonii-xx** [comment] 2018-01-21 16:19
It probably was one of the fixes in that update then. Great to hear that it works.

**Comment by Psymatics** [comment] 2018-01-21 19:35
Wait... nevermind. It still happens. Looks like it doesn't like rapid-fire redstone pulses, cause I tried it using an observer clock and it started crashing again until I threw a repeater into the circuit. I don't have the crash report on me now, but I can provide soon.

**Comment by Psymatics** [comment] 2018-01-22 22:47
Here we go.

[crash-2018-01-20_00.04.38-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/1653840/crash-2018-01-20_00.04.38-server.txt)

**Comment by bonii-xx** [comment] 2018-01-23 19:10
Uploading like that is fine. For small crashlogs like this one a pastebin is fine too, since it allows direct viewing online. Some people just use gists.

Anyway, sad to see that crash still exists, I was hoping exactly this crash was fixed in this release :(

**Comment by bonii-xx** [comment] 2018-01-23 19:46
This crash doesn't make any sense ta all. Can you provide a screenshot of the setup? I can't reproduce it.

**Comment by Psymatics** [comment] 2018-01-24 01:06
Okay, this is embarrassing...I can't replicate it with the same setup...[this](https://imgur.com/a/gyzm3) is the setup I've been using to replicate it.

**Comment by bonii-xx** [comment] 2018-01-24 19:04
Are you playing Singleplayer or on a Server? Does it crash the client or the server?

**Comment by Psymatics** [comment] 2018-01-24 20:26
Singleplayer.the crash appears to be server-side, because it crashes before I log on.

**Comment by KnightMiner** [comment] 2018-03-06 22:43
Same as #3390, this crash should be impossible. Seems to be some sort of race condition where Minecraft starts to empty the tank before it finished filling it. Not sure there is anything we can do as there is no place in the code to catch this crash, the stack is never null on the line its crashing. Try updating everything to the latest versions, and we will see if it still happens

**Comment by Psymatics** [comment] 2018-03-06 22:51
Will do!

**Comment by KnightMiner** [comment] 2019-05-26 21:50
Most likely fixed alongside #3390, as the slight delay will prevent a block update from immediately causing the faucet to pour.

**Comment by KnightMiner** [comment] 2019-10-14 19:57
Should be in the 2.12.0.156 build, so closing this.

**Closed by KnightMiner** 2019-10-14 19:57 UTC
Labels: Resolved, bug
