### ISSUE TITLE
Plate Chestplate crashes client

### ISSUE THREAD

**Issue by ghost** [SlimeKnights/TinkersConstruct#4781] opened 2022-02-24 20:11 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

When a player equips a plate chestplate (made with cobalt) it crashes the game and when they rejoin the server if they open their inventory or go into third person the game will crash again, only happens when optifine installed

crash report: [crash-2022-02-24_13.06.06-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8135426/crash-2022-02-24_13.06.06-client.txt)

### Crash Report

https://pastebin.com/wnKeHETk

### Reproduced with only Tinkers' Construct?

No

### Other mods required

OptiFine_1.18.1_HD_U_H4
ComplementaryShaders_v4.3.3
lazydfu-1.0-1.18+

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-24 20:11
Duplicate of #4734. Actually read through the pinned issues like you said you did. Remove optifine

**Closed as completed by ShinyPorygon** 2022-02-24 20:11 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
