### ISSUE TITLE
Magical wood from Extra Utilities 2 + Unbreakable bug

### ISSUE THREAD

**Issue by herobrine150400** [SlimeKnights/TinkersConstruct#3341] opened 2018-01-18 19:27 UTC
I made a Shortbow using the magical wood from Extra Utilities 2 and I put 5 "Reinforced" modificators which made it unbreakable; the magical wood has the "Magically Brittle" trait, which may break the tool every time it is used, even unbreakable ones.

The problem is that whenever a magical wooden tool with unbreakable is broken, it can't be repaired anymore, the same thing happens when a tool that has magical wood embossment breaks

This bug only happens if the magical wooden tool is broken by the "Magically Brittle" trait, and only if it is unbreakable, otherwise it can be repaired.

I went to a Creative world and reproduced this bug again, this time with a lumberaxe:

[Imgur](https://i.imgur.com/tajrPmO.png)

Minecraft: 1.12.2
Forge: 14.23.12587
Mantle: 1.3.1.21
Tinkers' Construct: 1.12.2-2.9.0.55
Tinkers' Tool Leveling: 1.12-1.0.3
Extra Utilities 2: 1.12-1.7.2

**Comment by KnightMiner** [comment] 2018-01-19 06:32
Duplicate of #3173.

**Closed by KnightMiner** 2018-01-19 06:32 UTC

**Comment by herobrine150400** [comment] 2018-01-19 15:36
OK, reported this to RWTema, thanks.
