### ISSUE TITLE
some pages only have black rectangles over latters on some books

### ISSUE THREAD

**Issue by pascaldulieu** [SlimeKnights/TinkersConstruct#1717] opened 2015-08-03 06:15 UTC
In "Materials and you: Volume 2" and "mighty Smelting" a few of the pages have black rectangles over the letters making the pages and the books useless.

![2015-08-03_07 12 17](https://cloud.githubusercontent.com/assets/2935785/9031748/2647dfb0-39af-11e5-9d17-327293be55c2.png)
![2015-08-03_07 12 20](https://cloud.githubusercontent.com/assets/2935785/9031749/26488adc-39af-11e5-81e1-7dd8a0cc7f6c.png)
![2015-08-03_07 12 21](https://cloud.githubusercontent.com/assets/2935785/9031750/2648fb70-39af-11e5-9bcc-1f31ee1bb104.png)
![2015-08-03_07 12 22](https://cloud.githubusercontent.com/assets/2935785/9031746/26464c0e-39af-11e5-900f-fd534334cdc8.png)
![2015-08-03_07 12 23](https://cloud.githubusercontent.com/assets/2935785/9031747/2647f040-39af-11e5-987d-ca5e2414053a.png)
![2015-08-03_07 12 24](https://cloud.githubusercontent.com/assets/2935785/9031751/264a566e-39af-11e5-813a-63b64e10e5f7.png)
![2015-08-03_07 12 25](https://cloud.githubusercontent.com/assets/2935785/9031752/265b3c68-39af-11e5-83d4-af7bf39988d1.png)
![2015-08-03_07 12 25_2](https://cloud.githubusercontent.com/assets/2935785/9031753/265c76a0-39af-11e5-9a67-d9097bc087b5.png)
![2015-08-03_07 12 26](https://cloud.githubusercontent.com/assets/2935785/9031755/265e92e6-39af-11e5-9917-a24e38ad2ce6.png)
![2015-08-03_07 12 27](https://cloud.githubusercontent.com/assets/2935785/9031757/26663802-39af-11e5-89b7-2c3ea8523126.png)
![2015-08-03_07 13 06](https://cloud.githubusercontent.com/assets/2935785/9031754/265ccb50-39af-11e5-8640-562cc971dbfe.png)
![2015-08-03_07 13 07](https://cloud.githubusercontent.com/assets/2935785/9031756/2660bb16-39af-11e5-8c64-41c2f9154fef.png)

**Comment by Adaptivity** [comment] 2015-08-04 06:42
Duplicate of: #1560
You can *try* the fix from here: https://github.com/SlimeKnights/Mantle/pull/39
"You can test it with this class file: https://www.dropbox.com/s/58w8t4e3l48ybku/GuiManual.class?dl=0
Replace the one in mantle.jar/mantle/client/gui with this one (made with a bytecode editor)."
I didn't get a chance to test it yet.

**Closed** 2016-02-13 08:33 UTC
