### ISSUE TITLE
White Textures 1.16.5

### ISSUE THREAD

**Issue by WoodChipings** [SlimeKnights/TinkersConstruct#4647] opened 2021-10-26 16:21 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.4

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.1.3.271

### Describe your issue

Every item in the game that has to do with tinkers tools just have a white texture. I have no idea why because I am not using optifine. I can provide a mod list via screenshots.

And yes I have tested it by itself and it didn't have the issue. I also tested with some other mods with it and it still didn't have the issue.

![Capture](https://user-images.githubusercontent.com/75452961/138919994-47a5ca73-0812-40d0-a45b-63af5c91d3b9.PNG)
![Capture1](https://user-images.githubusercontent.com/75452961/138919996-de3d0fc5-2c9d-4d31-92e3-63d536ab711e.PNG)
![Capture2](https://user-images.githubusercontent.com/75452961/138919997-a8eaa3dd-c01a-4e84-9024-4df8c8993b3d.PNG)
![Capture3](https://user-images.githubusercontent.com/75452961/138919998-2a13cccb-83ad-4b64-88c5-ae34611e4310.PNG)
![Capture4](https://user-images.githubusercontent.com/75452961/138920001-70bc08e4-0af2-4ee2-87e8-50dbb7f0b3ef.PNG)
![Capture5](https://user-images.githubusercontent.com/75452961/138920003-406465f5-49cd-4702-a4db-55e282b2b69d.PNG)
![Capture6](https://user-images.githubusercontent.com/75452961/138920004-98158fae-189b-4004-b95d-7ded17cadc27.PNG)
![Capture7](https://user-images.githubusercontent.com/75452961/138920006-b4820a5d-cafd-4fee-aa17-9757fe42047f.PNG)
![Capture8](https://user-images.githubusercontent.com/75452961/138920008-485212a3-c883-489d-8857-8d2910f1aad8.PNG)
![Capture9](https://user-images.githubusercontent.com/75452961/138920009-d7288f80-8abe-4755-8d8f-1ac3321f1771.PNG)
![Capture10](https://user-images.githubusercontent.com/75452961/138920011-e3d94b2b-5fb1-4d2c-b318-6359589befd8.PNG)
![Capture11](https://user-images.githubusercontent.com/75452961/138920013-ee3d06d2-2bb8-4562-a530-ac0255b8b8a0.PNG)
![Capture12](https://user-images.githubusercontent.com/75452961/138920014-82913ed4-f550-4e2b-8f4c-54f4811a5fa0.PNG)
![Capture13](https://user-images.githubusercontent.com/75452961/138920015-a5ec8ed8-1ed6-4b22-ad16-dc4c97334eb7.PNG)
![Capture14](https://user-images.githubusercontent.com/75452961/138920016-01b92ebb-c5ab-4d51-9707-c96e28419637.PNG)
![Capture15](https://user-images.githubusercontent.com/75452961/138920017-b8659f67-d18b-4c01-8a7e-8ed8ce425665.PNG)
![Capture16](https://user-images.githubusercontent.com/75452961/138920019-51d88011-6c3f-4101-b890-af14d980bec7.PNG)
![Capture17](https://user-images.githubusercontent.com/75452961/138920020-0e4b429d-c975-4bc4-acea-23ab7fd226da.PNG)
![Capture18](https://user-images.githubusercontent.com/75452961/138920022-1620d0f8-9895-44c5-9539-7181319ada62.PNG)
![Capture19](https://user-images.githubusercontent.com/75452961/138920024-c3ebe131-35a3-48f6-a1b9-71e737c3c0c9.PNG)
![Capture20](https://user-images.githubusercontent.com/75452961/138920027-1582d575-7e67-47c2-ad7a-72b15a424dd1.PNG)
![Capture21](https://user-images.githubusercontent.com/75452961/138920028-62a0580f-016c-4ee0-8672-03a89bd55230.PNG)
![Capture22](https://user-images.githubusercontent.com/75452961/138920030-cd8f8b9a-4447-497b-9657-f9155e11730d.PNG)
![Capture23](https://user-images.githubusercontent.com/75452961/138920033-572e63a1-6165-4f09-bb4c-93da7ad89ac0.PNG)
![Capture24](https://user-images.githubusercontent.com/75452961/138920035-ba5032b5-9d8e-4576-aa77-d8b39cb6b3ee.PNG)
![Capture25](https://user-images.githubusercontent.com/75452961/138920037-17418d25-360b-4df8-a78c-68f95c9e6c98.PNG)
![Capture26](https://user-images.githubusercontent.com/75452961/138920040-e8737d69-9273-4582-b59d-a68225050557.PNG)
![Capture27](https://user-images.githubusercontent.com/75452961/138920041-767ccb95-dfbd-4692-b420-482dbe555742.PNG)
![Capture28](https://user-images.githubusercontent.com/75452961/138920042-f1f22100-1c22-4d6c-a57e-088a5b378a5a.PNG)

### Reproduced with only Tinkers' Construct?

No

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment] 2021-10-26 16:24
Duplicate of #4614

**Closed as completed by ShinyPorygon** 2021-10-26 16:24 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.16

**Comment by WoodChipings** [comment] 2021-10-26 16:46
My bad I didn't find that. I also fixed my issue. I had a mod called Sodium which I don't even remember installing that made them white.

**Comment by KnightMiner** [comment] 2021-10-26 17:30
That is why we asked you if you had performance enhancers on the issue template. It's not hard to check if one is installed.

It's also why we asked you to narrow down the mod list. If we did not know the cause, this issue report would not have been helpful without more debugging.
