### ISSUE TITLE
Recipes and/or JEI integration broken in newest release

### ISSUE THREAD

**Issue by kojul** [SlimeKnights/TinkersConstruct#2575] opened 2016-11-19 00:41 UTC
Cannot view Tool Forge recipe.
Stencil table recipe is only viewable as a pattern and either 1) lavawood, 2) a rail, and 3) a melon and you can actually craft them with these items.
Part builder recipe is only viewable as a pattern and either 1) firewood, 2) a powered rail, and 3) a cactus and you can actually craft them with these items.

Forge version 12.18.2.2151
Mantle 1.1.1
Tinkers version 1.10.2-2.5.6b
JEI version 3.13.3.377

To reproduce, install above and look at recipes. Not sure if the part builder and stencil table are intentional recipes, just noticing them for the first time.

JEI version 3.13.2.346 is last working version released 11/3/16.

**Comment by kojul** [comment] 2016-11-19 00:46
Note that this isn't just the tool forge missing and unless the stencil and part builder recipes are supposed to allow the above items, something is wrong with the recipes themselves.

**Comment by KnightMiner** [comment] 2016-11-19 03:01
Duplicate of #2539. We know, it just won't be fixed until the next release

**Closed by KnightMiner** 2016-11-19 03:01 UTC
