### ISSUE TITLE
Blood in smelter causes client fatal error when switching active liquid in smelter

### ISSUE THREAD

**Issue by ab9rf** [SlimeKnights/TinkersConstruct#3152] opened 2017-09-10 15:32 UTC
Smelter contains 40 mb of blood and was being used to melt clay. Any attempt to change the bottom fluid is active causes a client disconnect. Certain other things seem also to cause crashes. Server log shows the following:
```
[21:35:30] [Netty Epoll Server IO #1/ERROR] [FML]: There was a critical exception handling a packet on channel tconstruct
io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Null string not allowed
...stacktrace omitted...
[21:35:30] [Netty Epoll Server IO #1/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
[21:35:34] [Server thread/ERROR] [tconstruct-TinkerSmeltery]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[21:35:34] [Server thread/ERROR] [tconstruct-TinkerSmeltery]:   fluid.tconstruct.copper/5184mb
[21:35:34] [Server thread/ERROR] [tconstruct-TinkerSmeltery]:   fluid.tconstruct.blood/40mb
[21:35:34] [Server thread/ERROR] [tconstruct-TinkerSmeltery]:   fluid.tconstruct.iron/2592mb
```
for stacktrace, see https://gist.github.com/ab9rf/fab80ab468ac2a05b3857715a879ead2

TC version: TConstruct-1.12-2.7.3.30.jar
Mantle version: Mantle-1.12-1.3.1.21.jar
Forge: forge-1.12.1-14.22.0.2474-universal.jar

This may be being caused by an attempt to melt clay in the smelter.

**Comment by ab9rf** [comment] 2017-09-10 17:14
Update: We built another smelter from scratch. A butterfly then died in the smelter, and after this the server log started to report there being blood in the smelter, and players started getting disconnected with errors of the same sort.

It seems fairly clear that these errors are connected to there being blood in the smelter.

**Comment by ab9rf** [comment] 2017-09-11 21:18
Additional note: restarting the server that was having this problem caused it to go away; after restart, clients showed blood in the smelter (which before they did not).. I haven't had time to test, but it would be worth investigating whether a code path difference that is causing blood to not be fully or properly registered in the fluid registry at server start. If I get time I'll spin up a test server and see if I can investigate the edge cases.

Also, this is likely the same issue as #3139.

**Comment by KnightMiner** [comment] 2017-09-11 22:26
Duplicate of #2994. Its a really unusual error that seems to only happen in large packs so its unfortunately difficult to solve.

**Closed by KnightMiner** 2017-09-11 22:26 UTC
