### ISSUE TITLE
1.16.5 Crash when loading world

### ISSUE THREAD

**Issue by Gaemering9000** [SlimeKnights/TinkersConstruct#4701] opened 2021-12-29 22:48 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.0.2.73

### Describe your issue

When loading world, game crashes. Suspected mod is Tinker's Construct.
All mods are confirmed Forge and 1.16.5.

### Crash Report

https://pastebin.com/R7geYLDg

### Reproduced with only Tinkers' Construct?

No

### Other mods required

JustEnoughItems -  7.7.1.130
Mekanism - 10.1.0.445
Waystones - 7.6.4
Clumps - 6.0.0.25
JourneyMap - 5.7.3
FastWorkbench - 4.6.1
ConnectedTexturesMod - 1.1.2.6
Controlling - 7.0.0.27
Placebo - 4.6.1
Citadel - 1.8.1
Bookshelf - 10.3.29
Enchantment Descriptions  - 7.0.17
RandomPatches - 2.4.4
Ice and Fire - 2.1.9
Cloth Config - 4.13.49
COFH Core - 1.4.0.6
Thermal Foundation - 1.4.1.3
Thermal Expansion - 1.4.1.3
Thermal Innovation - 1.4.1.3
Thermal Locomotion - 1.4.1.2
Appleskin - 2.2.0
CraftingTweaks - 12.2.1
BetterAdvancements - 0.1.0.108

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment] 2021-12-29 22:51
You're on a very old version, try downloading the latest and see if the crash still happens

**Comment by KnightMiner** [comment] 2021-12-29 22:53
I thought surely by now enough people would have updated to the version fixed **4 months ago** so I could unpin that issue. Apparently not.

Duplicate of #4631

**Closed as completed by KnightMiner** 2021-12-29 22:53 UTC
Labels: Duplicate, Invalid, 1.16, Update
