### ISSUE TITLE
[1.10.2] Seared Furnace spits out cooked items

### ISSUE THREAD

**Issue by sipes42** [SlimeKnights/TinkersConstruct#2954] opened 2017-06-05 23:29 UTC
I am not sure if this is a bug or feature, and I can't seem to figure out what causes it. Sometimes cooked items will remain in the furnace almost indefinitely, other times it will just spit all the cooked items it has onto the ground. I was curious about why this occurs, and if there are specific ways to replicate or prevent this behavior.

**Comment by sipes42** [comment] 2017-06-05 23:36
Is it possible for this to be caused by the chunk containing the controller loading before another chunk containing part of the structure is loaded?

**Comment by KnightMiner** [comment] 2017-06-06 03:16
The only reason the items would be spit out is of somehow the furnace structure became smaller. In older versions this could be possible if part of the world unloaded causing the structure to become invalid, but if you use the latest 1.10.2 version that should not be an issue. Can you verify what version you are having this issue in?

**Comment by sipes42** [comment] 2017-06-07 03:46
1.10.2-2.6.5

**Comment by KnightMiner** [comment] 2017-10-22 20:49
So, typical questions then:

* Are you using any other mods that may change how chunk loading happens?
* Can you reproduce with just Tinkers and dependencies?
* Can you reproduce this in the latest 1.12 versions?

**Comment by bonii-xx** [comment] 2018-01-07 16:39
Closing due to unsupported version

**Closed by bonii-xx** 2018-01-07 16:39 UTC
Labels: Needs Confirmation, Unsupported Version
