### ISSUE TITLE
[1.12.2] Scythe client crash

### ISSUE THREAD

**Issue by vertex101** [SlimeKnights/TinkersConstruct#3356] opened 2018-01-27 21:14 UTC
i am getting a client crash when using the scythe to attack enderman within the End 

https://paste.ee/p/R1Pf9

Tinkers Version: TConstruct-1.12.2-2.9.0.55

**Comment by KnightMiner** [comment] 2018-01-27 22:30
Duplicate of #3337

**Closed by KnightMiner** 2018-01-27 22:30 UTC
