### ISSUE TITLE
tinker items do not appear on dedicated servers

### ISSUE THREAD

**Issue by RapidMesck** [SlimeKnights/TinkersConstruct#4795] opened 2022-03-11 02:32 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.27

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.3.332

### Describe your issue

the tools, parts, etc are not appearing on the dedicated server, only in singleplayer

### Other mods

[Tinker's Planner] [Tinkers' Rapier] [TAIGA 2]

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Magnesium, Optifine

### Searched for known issues?

Searched open issues

**Comment by aethaerya** [comment] 2022-03-11 02:55
![image](https://user-images.githubusercontent.com/28931355/157793215-8189532f-559b-4646-bfa6-0e251b8382d6.png)
![image](https://user-images.githubusercontent.com/28931355/157793546-7a6675e7-d9eb-4241-a0bb-a2ef583bdad6.png)

Not sure if Optifine is the cause, but I advise against putting Optifine on your dedicated server as it breaks worldgen as well.

**Comment by RapidMesck** [comment] 2022-03-11 02:56
> ![image](https://user-images.githubusercontent.com/28931355/157793215-8189532f-559b-4646-bfa6-0e251b8382d6.png)
> 
> Not sure if Optifine is the cause, but I advise against putting Optifine on your dedicated server as it breaks worldgen as well.

I tested it without the optfine and the same thing happened

**Comment by aethaerya** [comment] 2022-03-11 02:58
Try to reproduce it with _only_ Tinkers' Construct & Mantle.

**Comment by RapidMesck** [comment] 2022-03-11 03:01
apparently it was only a visual bu. sorry for opening an issue

**Comment by aethaerya** [comment] 2022-03-11 03:04
Issues help people in the future. As long as people are truthful in their reports & properly follow the procedures, all is fine.

**Comment by KnightMiner** [comment] 2022-03-11 03:54
> apparently it was only a visual bu. sorry for opening an issue

What do you mean by it was only a visual bug? What is the visual bug you are seeing?

**Comment by RapidMesck** [comment] 2022-03-12 17:13
> > apparently it was only a visual bu. sorry for opening an issue
> 
> What do you mean by it was only a visual bug? What is the visual bug you are seeing?

the items do not appear but are functional

**Comment by KnightMiner** [comment] 2022-05-14 20:54
Going to close this as there is no where near enough information for me to do anything. Most often this is caused by a mod list mismatch between client and server. It could also be you just don't see items in JEI or in creative, which are entirely separate things. Give more information if you want us to actually solve this, such as detailed steps to reproduce

**Closed as completed by KnightMiner** 2022-05-14 20:54 UTC
Labels: Bug, Not enough information, 1.16
