### ISSUE TITLE
Duplication bug with the smeltery

### ISSUE THREAD

**Issue by ChrisJacobsJr** [SlimeKnights/TinkersConstruct#4347] opened 2021-04-12 20:39 UTC
**Issue description:**
My smeltery has a capacity of 18 slots. Whenever I drop 19 or more items of any kind into the smeltery, and try to take them out of the smeltery via the smeltery controller, they will reappear, creating more items. In the case of actual meltable items, which I have only tested with thermal expansion's gold and copper dust, they will reappear in the smeltery item space after melting, which produces infinite molten metal until the item entities despawn. I have tested with dirt and cobblestone, which don't smelt into anything but still produce infinite copies until the item entities in the smeltery despawn.

If it helps, the inside of my smeltery consists of 3*3*2 (X*Z*Y) empty space.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.73

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I checked with CTRL+F and did not find anything relevant with 'dupe' or 'duplication'
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes.

**Comment by KnightMiner** [comment] 2021-04-12 20:55
Duplicate of #4284. Your alpha is old, this has been fixed for over a week.

**Closed as completed by KnightMiner** 2021-04-12 20:55 UTC
Labels: Bug, Duplicate, 1.16, Update
