### ISSUE TITLE
Shurikens making the wrong sounds when they hit things

### ISSUE THREAD

**Issue by ShaunDreclin** [SlimeKnights/TinkersConstruct#2782] opened 2017-02-22 22:39 UTC
when my shurikens hit stone like blocks they make the "wood sawing" sound effect that the tool station plays when you make/edit a tool, and when they hit blocks like trees it plays a loud metal "clang" sound effect like placing down a frypan

**Comment by LovelyFlare** [comment] 2017-02-22 23:56
Duplicate of #2567

**Closed** 2017-03-09 03:12 UTC
Labels: duplicate
