### ISSUE TITLE
The JEI Category of Entity Melting is EMPTY

### ISSUE THREAD

**Issue by WizardJoker** [SlimeKnights/TinkersConstruct#5267] opened 2024-10-07 12:34 UTC
### Minecraft Version

1.19.2

### Forge Version

43.4.4

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.4.50

### Describe your issue

![屏幕截图 2024-10-07 201551](https://github.com/user-attachments/assets/b3d15e64-e01a-41da-877e-0a24dd21a732)
The Category of Entity Melting shows nothing.
latest.log: https://mclo.gs/wLPshgz

### Other mods

JEI: 11.8.1.1031

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment] 2024-10-07 12:44
This appears to be a problem with the latest JEI, they may have changed something up, using a previous version (such as .1024) will make it re-appear. Something may have to be adjusted in tinkers to match whatever they possibly changed.

**Comment by KnightMiner** [comment] 2024-10-07 15:37
Report this issue to JEI and link it here. They should not be changing their API in such a way that requires mods to update, especially not with a class cast exception when I am not doing any casts in my code.

**Comment by KnightMiner** [comment] 2024-10-07 18:56
Quick look at my code, the crashing line is caused by creating a focus link. I do it between an invisible ingredient and a rendered one, as that allows me to lookup entity melting recipes using a spawn egg rather than having to list add entities in JEI. I suspect something changed recently in JEI causing focus links to break with invisible ingredients.

This is almost certainly a JEI bug as it was a change in their API that caused this to work before and no longer work, just was likely an unexpected usecase of focus links.

**Comment by mezz** [comment] 2024-10-08 02:13
This turned out to be a JEI bug, and has been fixed in version `11.8.1.1033` and higher.

![2024-10-08_11 12 13](https://github.com/user-attachments/assets/73df00aa-3268-458f-a753-b76f79e44e3f)

**Comment by KnightMiner** [comment] 2024-10-08 17:11
Closing as fixed in JEI, looks like that version is already available on CurseForge and alike.

If you still have any issues after updating let me know and we can reopen and look into it further.

**Closed as completed by KnightMiner** 2024-10-08 17:11 UTC
Labels: Bug, Resolved, Mod interaction, Other mod, 1.19
