### ISSUE TITLE
[1.16.5] Casting only outputs what you put in it first. Wont output correctly after that.

### ISSUE THREAD

**Issue by Gbergz** [SlimeKnights/TinkersConstruct#4283] opened 2021-04-01 19:47 UTC
**Issue description:**
If you put copper into the smeltery and output that to ingot. Then you decide to smelt Iron instead and output that. It'll still output copper.

**If crashed, link to crash report (use a site such as pastebin):**
No crash.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.2
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.73

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Sorry not sure where to find this.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes it can be reproduced in a clean instance with just Tinkers Construct.

**GIF Showing the issue**
https://gyazo.com/35291ec29285125775cb5c40acf1f2f0

**Comment by KnightMiner** [comment] 2021-04-01 19:49
Server or singleplayer?

**Comment by Gbergz** [comment] 2021-04-01 19:49
Singleplayer

**Comment by rxwsh** [comment] 2021-04-01 20:57
For me this only happened in my 70 mods modpack, when I tested it with only Mantle, TiC and JEI it worked fine. I used the basin for blocks though.

**Comment by Gbergz** [comment] 2021-04-01 21:07
> For me this only happened in my 70 mods modpack, when I tested it with only Mantle, TiC and JEI it worked fine. I used the basin for blocks though.

Could actually re-produce it in an instance with just TiC, Mantle & JEI. Then I couldn't for the love of god reproduce it again for a second time.. It's reproducable in a heavy environment 100% of the time though.

**Comment by moon-st0ne** [comment] 2021-04-01 23:37
was on the SlimeKnights discord, discussing this bug. here's what i've collected so far:
- the first thing you cast out of the smeltery will become the thing that all smelteries and melters in that world cast, regardless of what's actually inside, presumably until either the game is restarted or a new world is made
- the casting is global to the world, so every new smeltery or melter you build will only cast that liquid
- it doesn't appear to be mod-specific; after getting every smelter to create osmium, i removed mekanism and ran into the same bug with vanilla iron and gold ore
- i've got some screenshots and videos to share:

here's a melter with tin inside pouring out a gold ingot:
https://media.discordapp.net/attachments/395801350731989003/827324025260474378/unknown.png
here's a brand new smeltery filled with tin, pouring out a gold ingot:
https://dl.dropboxusercontent.com/s/mmcepv7mp13280x/niHvAt8ke7.mp4
here's what lead to all smelteries in the world making gold - me trying to replicate this with vanilla iron and gold:
https://dl.dropboxusercontent.com/s/ixyawqy34xgmhli/LOyyEliZ4I.mp4
here's a different world where osmium is what's duplicated, testing with a bunch of different liquids from different mod ores:
https://dl.dropboxusercontent.com/s/bovl7zlddvt0v49/2S2EiUoxdB.mp4

unrelated, but here's another bug i found while testing this - if you put a crafting station next to a seared window, this happens
https://i.imgur.com/LMwq8nA.png

**Comment by KnightMiner** [comment] 2021-04-02 00:48
Unrelated bugs go to other reports.

----

I cannot reproduce this on a fresh instance, so I need more information.

One common point of confusion here, the smeltery does not do casting recipes, casting basins and tables do. So to figure out the problem:

* Does this happen when you use a seared tank to cast into a table?
* Does this happen when a smeltery casts into a seared tank? May have to leave and rejoin world
* Does this happen with just Tinkers? The original poster claims it did, but the most recent comments are using 90 other mods
* Are you running a custom Forge install at all? Optifine, non-vanilla client, etc. 

A copy of your game log would help too.

Edit: forgot to be careful in my wording of commit messages, that commit only maybe fixes this

**Comment by KnightMiner** [comment] 2021-04-02 01:45
Some debugging on discord revealed the following:

* The problem happens with casting tables, not the smeltery
* Performant is to blame, this issue was reported to them so I will leave this open to keep track of it

**Comment by IchigoGames** [comment] 2021-04-09 19:21
can confirm if you put gold in it it will only give you gold even if you have iron in it

**Comment by moon-st0ne** [comment] 2021-04-09 20:17
> can confirm if you put gold in it it will only give you gold even if you have iron in it

this issue is closed now, since it is caused specifically by the mod Performant caching recipes, including recipes used by the casting table/basin. disable the recipe caching module of Performant or remove the mod entirely.

**Comment by DeuceWins** [comment] 2021-04-11 21:20
I have the same problem with basins, with both rose gold and tinkers bronze. Both came out as gold.

**Comment by KnightMiner** [comment] 2021-04-21 04:33
Fixed in latest Performant release

**Closed as completed by KnightMiner** 2021-04-21 04:33 UTC
Labels: Bug, Performance Enhancers/Optifine, Mod interaction, 1.16
