### ISSUE TITLE
Crash with Traveller's gear and plate armor with Optifine

### ISSUE THREAD

**Issue by GabrieleFerrante** [SlimeKnights/TinkersConstruct#4752] opened 2022-02-14 19:15 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.76

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.45

### Describe your issue

Having the inventory open while having Traveller's gear or Plate armor equipped crashes the game, since it says in the crash log:
`java.lang.ClassCastException: class slimeknights.tconstruct.tools.client.PlateArmorModel cannot be cast to class net.minecraft.client.model.HumanoidModel (slimeknights.tconstruct.tools.client.PlateArmorModel is in module tconstruct@3.4.1.45 of loader 'TRANSFORMER' @41ccb3b9; net.minecraft.client.model.HumanoidModel is in module minecraft@1.18.1 of loader 'TRANSFORMER' @41ccb3b9)`
This happens only with optifine though.

### Crash Report

https://pastebin.com/raw/j50RCg9a

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Optifine 1.18

### Confirm the following

- [X] Check if you are not using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you have look at FAQ to see if your issue is answered
- [ ] Check if you did not read all of the above checkboxes and just checked all the boxes

**Comment by KnightMiner** [comment] 2022-02-14 19:16
![image](https://user-images.githubusercontent.com/12155288/153930913-adee966e-cdad-4151-8b67-a66704e47b68.png)
I don't get how you managed to read the last checkbox but not the first or second. Quite impressive honestly. You really should have checked none of the boxes, as you are obviously lying about having checked pinned issues as this is a duplicate of the pinned issue.

Duplicate of #4734. Optifine is a garbage mod, stop using it.

**Closed as completed by KnightMiner** 2022-02-14 19:16 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
