### ISSUE TITLE
[1.12-2.7.4.34] Blood In Smeltery Causes Crash?

### ISSUE THREAD

**Issue by Tailsdeveraux** [SlimeKnights/TinkersConstruct#3260] opened 2017-12-04 12:46 UTC
Hello, I've recently started up a new minecraft server running Direwolf20 1.12 version 1.1.0, it contains Tinker's Construct 2.7.4.34, which seems to be the source of the following error, which causes affected clients to disconnect from the server.

The error seems to originate from having a mob fall into an active smelter, leaving behind blood.
I can provide a full modlist at request. 

As the game doesn't actually crash, I didn't grab a clientside error log yet, I can reproduce this bug at request. Below is what is seen serverside when a client is disconnected by this bug.

https://pastebin.com/xuwDJwKP

What do you make of this?

**Comment by KnightMiner** [comment] 2017-12-04 13:15
Duplicate of #2994.

**Closed by KnightMiner** 2017-12-04 13:15 UTC
