### ISSUE TITLE
Game crashes when pulling up a mob head in JEI

### ISSUE THREAD

**Issue by AztecTlatoani56** [SlimeKnights/TinkersConstruct#4959] opened 2022-08-04 19:25 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

Whenever I search "bl" or "z" or any other set of character that bring up a mob head at the Just Enough Items interface my game crashes. 

### Crash Report

https://mcpaste.io/1e8df75df3a23aef

### Other mods

Just Enough Items
Chunk Pregenerator

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine, Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Checked the FAQ

**Comment by ShinyPorygon** [comment] 2022-08-04 19:37
Duplicate of #4316 if you did actually check the pinned issues you would have seen this.

**Closed as completed by ShinyPorygon** 2022-08-04 19:37 UTC
Labels: Performance Enhancers/Optifine, Can't Fix, 1.18
