### ISSUE TITLE
I'm sure you probably know this issue but there's a render issue with Chests in Station.

### ISSUE THREAD

**Issue by RepoDraghon** [SlimeKnights/TinkersConstruct#4336] opened 2021-04-11 03:06 UTC
Crafting station renders Chests as Purple/Black boxes

Versions: Java
Minecraft: 1.12.2
Forge: 14.23.2855
Mantle: 1.12-1.3.3.55
Tinkers Construct: 1.12.2-2.13.0.183

Can it be reproduced with *just* Tinkers Construct? Honestly, I haven't tried.
If not, list the other mods *required* to reproduce the issue. The issue happens on FTB Academy, Direwolf20 mod pack
![2021-04-10_19 54 56](https://user-images.githubusercontent.com/8423696/114290939-2c7a7100-9a38-11eb-9abe-15588b6e9cff.png)
![2021-04-10_19 54 50](https://user-images.githubusercontent.com/8423696/114290940-300df800-9a38-11eb-8639-6fce95d895fc.png)

, and my custom pack.

**Comment by KnightMiner** [comment] 2021-04-11 03:16
Duplicate of #2111. Won't be fixed in 1.12, already fixed in 1.16.

**Closed as completed by KnightMiner** 2021-04-11 03:16 UTC
Labels: Bug, Duplicate, 1.12

**Comment by RepoDraghon** [comment] 2021-04-11 18:18
OK, I thought so, sorry for the inconvenience...
