### ISSUE TITLE
Mod failed Loading / crash

### ISSUE THREAD

**Issue by itsdinkd** [SlimeKnights/TinkersConstruct#5151] opened 2023-07-21 18:05 UTC
Not needed

**Comment by KnightMiner** [comment] 2023-07-24 20:59
Yeah, because a crash report with 250 mods is something I can easily test and reproduce. There is a reason the issue template asks you to test with fewer mods, as I can actually confirm the issue exists and was fixed with fewer mods.

I do not see anything in the crash report that says Tinkers is to blame, and the fact you say it is random crashing and blaming other mods makes me certain this is not our bug, so reporting it to us is wrong. The crash report says someone broke the crash loader making us unable to load any of deferred registers and the rest is in Forge code. So my suspicion is your have one of your many mods breaking stuff. Test with fewer mods to find the culprit rather than report it to a mod that even you know is not the problem.

**Closed as not planned** 2023-07-24 21:00 UTC
Labels: Not enough information, Can't reproduce, Can't Fix, Mod interaction, 1.18, Did not follow issue template, Other mod

**Comment by itsdinkd** [comment] 2023-07-25 05:50
I didn't follow the issue template, yet I selected the option that was offered in the template. Maybe don't make it a option to select if you're just going to reply saying that i should test with little mods.

I recommend learning what your template is before telling people to follow something that they followed lmfao. No where does it say "do not open this if you did not test with a smaller set of mods" but from the looks of your response it should probably be there to save everyones time. The point of this issue is for awareness and in case anyone else experienced it. Jesus christ you need to chill out. 


Moral of the story: delete the NO option, learn your templates, don't be an asshole.

**Comment by KnightMiner** [comment] 2023-07-25 23:17
The issue template tells you multiple times to reproduce with a smaller mod set. I give you the option to say "no" because I get a lot of people who just lie about it rather than putting in effort if I do not give you the option to click no. If you bothered to read it, you would see that it tells you to test.

This tells you to test by removing other mods
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/12155288/bb35240e-9ef3-43f2-b8f2-0a880d38d807)

This tells you to list the smallest set to reproduce the issue.
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/12155288/37c8d926-94e0-464f-b988-7b4ed5fa41e4)

And more importantly, I did not close your issue for failure to follow the template, I closed it because you yourself said this is not a tinkers issue, its randomly blames different mods. Since you had no idea what caused the issue, and nothing in the crash indicated it was our fault, there was nothing I could do.

If you cannot put in the effort to narrow down the bug, we cannot help you. If that makes me an "asshole" because I cannot magically solve your issue, then sorry for not having magical powers. I am just a person making mods in my spare time, I cannot wish away your problems. I can however help you solve things if you actually put in effort to be helped. You are not too special to follow our issue template.
