### ISSUE TITLE
[1.12] Render bug

### ISSUE THREAD

**Issue by Pilad** [SlimeKnights/TinkersConstruct#3089] opened 2017-08-06 20:07 UTC
If use optifine OptiFine_1.12_HD_U_C4 and TConstruct-1.12-2.7.2.15
http://i.imgur.com/j1U777h.png
Without optifine is good.

**Comment by KnightMiner** [comment] 2017-08-06 20:42
Duplicate of #3008.

**Closed by KnightMiner** 2017-08-06 20:42 UTC
