### ISSUE TITLE
On the bright side, I bought you a teddy bear!

### ISSUE THREAD

**Issue by ZEkA10000** [SlimeKnights/TinkersConstruct#4389] opened 2021-04-21 14:54 UTC
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):** https://gist.githubusercontent.com/natanfudge/78d4e5e48dabada86d0bc615065b985f/raw/3e30a8676f7231543bb9fb262ac5e643b2c6d53c/crash.txt

**Versions:**
* Minecraft: ForgeOptifine 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.111

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
I just created Obsidian tool...
![2021-04-21_16 49 28](https://user-images.githubusercontent.com/25690631/115574546-65cd9f00-a2ca-11eb-9a07-f37607289a4c.png)
When pickaxe part is created it crashes. (Divide by zero)

**Comment by PrincessOfEvil** [comment] 2021-04-21 14:57
Duplicate of #4316. Optifine is not supported.

**Closed as completed by PrincessOfEvil** 2021-04-21 14:57 UTC
Labels: Bug, Performance Enhancers/Optifine, 1.16
