### ISSUE TITLE
TC Smeltery kick from server

### ISSUE THREAD

**Issue by KmaserX** [SlimeKnights/TinkersConstruct#3139] opened 2017-09-02 18:34 UTC
Minecraft version 1.12
Modpack: All The Mods 3 v2.8

When I click a metal in the smeltery it kicks me from the server
It seems to happen after I make pigiron, so blood in the smeltery.
I use blocks to get out en the fluids dissapear until I break the blocks(cobblestone).

Crash in server log:
`[Netty Epoll Server IO #6/ERROR] [FML]: There was a critical exception handling a packet on channel tconstruct
io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Null string not allowed
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.jar:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAll(SimpleNetworkWrapper.java:235) ~[SimpleNetworkWrapper.class:?]
	at slimeknights.tconstruct.common.TinkerNetwork.sendToAll(TinkerNetwork.java:73) ~[TinkerNetwork.class:?]
	at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.onTankChanged(TileSmeltery.java:356) ~[TileSmeltery.class:?]
	at slimeknights.tconstruct.smeltery.network.SmelteryFluidClicked.handleServerSafe(SmelteryFluidClicked.java:37) ~[SmelteryFluidClicked.class:?]
	at slimeknights.mantle.network.AbstractPacketThreadsafe$2.run(AbstractPacketThreadsafe.java:31) ~[AbstractPacketThreadsafe$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) ~[nx.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_131]
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19) ~[gm.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137) ~[fy.class:?]
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:108) ~[FluidStack.class:?]
	at slimeknights.tconstruct.smeltery.network.SmelteryFluidUpdatePacket.toBytes(SmelteryFluidUpdatePacket.java:65) ~[SmelteryFluidUpdatePacket.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.jar:?]
	... 21 more

`

**Comment by KnightMiner** [comment] 2017-09-11 22:26
Duplicate of #2994.

**Closed by KnightMiner** 2017-09-11 22:26 UTC
