### ISSUE TITLE
Missing tiny amount of fluid when pouring

### ISSUE THREAD

**Issue by SereneRebel** [SlimeKnights/TinkersConstruct#3678] opened 2018-11-05 14:12 UTC
**Issue description:**
Losing small amount of fluid when pouring. I had 1 block of bronze when playing sky adventures in single player when i poured 1 block worth of molten bronze into a casting basin it finished pouring with 
1152mB / 1296mB. 

the smeltery is a 4x4x4 interior and inside it's own chunk, no automation.
![2018-11-05_22 08 39](https://user-images.githubusercontent.com/25892745/48002889-d2c73b80-e147-11e8-9088-80988ca799fd.png)

This also happened with iron and copper while playing stoneblock pack

**If crashed, link to crash report (use a site such as pastebin):**
No Crash

**Versions:**
* Minecraft:  1.12.2
* Forge:  14.23.5.2770
* Mantle: 
* Tinkers Construct: 1.12.2-2.10.1.87
* FTB Sky Adventures pack 1.2.1 & Stoneblock 1.0.17

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Unsure

**Comment by KnightMiner** [comment] 2018-11-05 14:58
Please try reproducing with just Tinkers Construct like the last question asked. "Unsure" is not an acceptable answer for that.

I personally have never seen this happen unless you break the faucet while it pours, so it sounds like a mod is breaking something.

**Comment by SereneRebel** [comment] 2018-11-05 23:53
Rightly so, I'll do some testing tonight, 
Being in a large mod-pack it is quite possible something else is messing with it. I'd only just noticed the issue and made note of it in the chance someone else may have seen it before.

**Comment by SereneRebel** [comment] 2018-11-06 12:53
I've now tested this scenario with only tinkers loaded and i cannot replicate so it is indeed looking like another mod is messing with it in both the FTB Sky Adventures pack as well as the Stoneblock pack.

Perhaps someone more skilled than I could find it

**Comment by KnightMiner** [comment] 2019-05-07 18:50
Since you cannot replicate it and are not sure which mod is causing this, I will close this for now as there is not much we can do without knowing the mod breaking it. If someone can get a minimal mod list to reproduce we can reopen this.

**Closed by KnightMiner** 2019-05-07 18:50 UTC
Labels: 3rd party mod interaction, Not enough information
