### ISSUE TITLE
Game Breaking Vanishing Offhand Tinker's Construct's Tool Upon Rightclick Auto Harvesting

### ISSUE THREAD

**Issue by FriendlyGamer** [SlimeKnights/TinkersConstruct#3779] opened 2019-03-01 06:06 UTC
As mentioned in the title my tool vanished when I right click to harvest the wheat. Not sure if this is a overlooked issue with this mod or some odd thing is happening between other mod(s) in my server's pack. 
* Minecraft:1.12.2 
* Forge: Ending in 2815
* Mantle: 1.12 ending in 42
* Tinkers Construct: 1.12.2 ending in 115

Appears to be directly related to both Tinker's Constructs' features (auto harvest and off hand tool usage with the mod's own tool.).  

Let me know if this indeed an issue with the mod or do I need to put my server's pack under further testing. Thanks in advance!

**Comment by bonii-xx** [comment] 2019-03-01 17:40
1. Can you reproduce it, and how?
2. Can you reproduce it with only TiC & Mantle, no other mods?

**Comment by FriendlyGamer** [comment] 2019-03-01 18:13
> 1. Can you reproduce it, and how?
> 2. Can you reproduce it with only TiC & Mantle, no other mods?

I found out it likely Repurpose being involved as it's the mod that add the right click harvesting and that it didn't worked at all when TiC+Mantle. to reproduce it with Repurpose is the following... 
1. Place down wheat seeds (bone mealing is recommended to speed up the process)  
2. Right click while having BOTH TiC tools in each hand (main+offhand) to see that a tool had vanished.  
Should I refer Repurpose to this issue so they can look into this?

**Comment by KnightMiner** [comment] 2019-03-02 08:06
Yes, and also mention which right click harvest mod here so we know the cause.

**Comment by FriendlyGamer** [comment] 2019-03-02 13:24
> Yes, and also mention which right click harvest mod here so we know the cause.

Done https://minecraft.curseforge.com/projects/repurpose/issues/16 let hope they reply soon about this.

**Comment by KnightMiner** [comment] 2021-01-26 04:54
Closing as the author of that mod apparently dropped support for 1.12, and there is not much we can do on our side.

**Closed by KnightMiner** 2021-01-26 04:54 UTC
Labels: 3rd party mod interaction
