### ISSUE TITLE
Updating screen events crash 

### ISSUE THREAD

**Issue by slow-excellence** [SlimeKnights/TinkersConstruct#1815] opened 2015-11-22 19:56 UTC
[crash log](https://github.com/SlimeKnights/TinkersConstruct/files/41129/crash-2015-08-12_00.35.44-client.txt)

Client crashes whenever I put the Traveller's Gloves into a crafting table or tool bench. Currently running FTB Infinity Expert mode with the TConstruct 1.8.8.jar on both the server and client.

**Comment by KnightMiner** [comment] 2015-11-22 23:46
Duplicate of #1808. The issue is with FTB Infinity Expert and not here, as Infinity Expert failed to add the proper NBT for the traveler's gear when it changed the recipe.

**Closed** 2015-11-23 08:44 UTC
