### ISSUE TITLE
Scorched lamps with molten materials

### ISSUE THREAD

**Issue by Set2Minecraft** [SlimeKnights/TinkersConstruct#4620] opened 2021-09-12 20:12 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.1.252

### Describe your issue

I have no idea if this is a bug or enhancement, because I do not know if it is intentional.
Here is the issue: 
Scorched lamps with molten materials do not glow or produce light, this does include lava and blazing blood, which I would think, would be at least those too.

### Reproduced with only Tinkers' Construct?

No

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment] 2021-09-12 20:13
Duplicate of #4316 Optifine is not supported.

**Closed as completed by ShinyPorygon** 2021-09-12 20:13 UTC
Labels: Performance Enhancers/Optifine, Can't Fix, 1.16
