### ISSUE TITLE
Crash when equipping travellers armor

### ISSUE THREAD

**Issue by yeetgrenadewastaken** [SlimeKnights/TinkersConstruct#4816] opened 2022-03-26 23:44 UTC
### Minecraft Version

1.18.1

### Forge Version

39.1.0

### Mantle Version

 Mantle-1.18.1-1.8.37.jar

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.2.60.jar

### Describe your issue

Game crashed when equipping Traveller's leggings. This was the message: The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class slimeknights.tconstruct.tools.client.TravelersGearModel cannot be cast to class net.minecraft.client.model.HumanoidModel (slimeknights.tconstruct.tools.client.TravelersGearModel is in module tconstruct@3.4.2.60 of loader 'TRANSFORMER' @3a3ed300; net.minecraft.client.model.HumanoidModel is in module minecraft@1.18.1 of loader 'TRANSFORMER' @3a3ed300)
Exit Code: -1
[crash-2022-03-26_16.36.35-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8356529/crash-2022-03-26_16.36.35-client.txt)

### Crash Report

https://github.com/SlimeKnights/TinkersConstruct/files/8356529/crash-2022-03-26_16.36.35-client.txt

### Other mods

QueenOfMissiles
AI-Improvements-1.18-0.4.0.jar

[AppleSkin]()
squeek502
appleskin-forge-mc1.18-2.4.0.jar

[AttributeFix]()
DarkhaxDev
AttributeFix-Forge-1.18.1-13.0.5.jar

[Balm (Forge Edition)]()
BlayTheNinth
balm-2.4.3+0.jar

[Better Azalea]()
SameDifferent
azalea-FORGE-3.1.1.jar

[Biomes O' Plenty]()
Forstride
BiomesOPlenty-1.18.1-15.0.0.104-universal.jar

[Clumps]()
Jaredlll08
Clumps-forge-1.18.1-8.0.0+5.jar

[Comforts (Forge)]()
TheIllusiveC4
comforts-forge-1.18.1-5.0.0.2.jar

[Controlling]()
Jaredlll08
Controlling-forge-1.18.1-9.0+15.jar

[Cosmetic Armor Reworked]()
LainMI
CosmeticArmorReworked-1.18.1-v1a.jar

[Craftable Creative Ability]()
xianmouyin
cca-1.18.1-1.3.jar

[Crafting Tweaks]()
BlayTheNinth
craftingtweaks-forge-1.18.1-14.0.2.jar

[Dungeons Enhanced]()
Valarauko9
dungeons_enhanced-1.18.1-3.0.jar

[DynamicRegistries]()
silverminer007
dynamicregistries-1.18.1-1.0.0.jar

[Enchantment Descriptions]()
DarkhaxDev
EnchantmentDescriptions-Forge-1.18.1-9.0.13.jar

[Explorer's Compass]()
Chaosyr
ExplorersCompass-1.18.1-1.1.2-forge.jar

[FastFurnace]()
Shadows_of_Fire
FastFurnace-1.18.1-6.0.2.jar

[Feature NBT Deadlock Be Gone]()
telepathicgrunt
feature_nbt_deadlock_be_gone_forge-1.0.0+1.18.1.jar

[Hunter illager]()
bagu_chan500
HunterIllager-1.18.1-3.1.6.jar

[Just Enough Items (JEI)]()
mezz
jei-1.18.1-9.4.1.112.jar

[Just Enough Resources (JER)]()
way2muchnoise
JustEnoughResources-1.18.1-0.13.1.141.jar

[LevelHearts]()
FireController1847
levelhearts-1.18-2.4.0.jar

[Macaw's Bridges]()
sketch_macaw
mcw-bridges-2.0.2-mc1.18.1.jar

[Macaw's Windows]()
sketch_macaw
mcw-windows-2.0.3-mc1.18.1.jar

[Mantle]()
mDiyo
Mantle-1.18.1-1.8.37.jar

[Mod Name Tooltip]()
mezz
modnametooltip-1.18.1-1.18.0.jar

[Mouse Tweaks]()
YaLTeR
MouseTweaks-forge-mc1.18-2.21.jar

[Nature's Compass]()
Chaosyr
NaturesCompass-1.18.1-1.9.5-forge.jar

[Neat]()
Vazkii
Neat 1.8-30.jar

[NetherPortalFix]()
BlayTheNinth
netherportalfix-forge-1.18-9.0.0.jar

[No Null Processors]()
telepathicgrunt
no_null_processors_forge-2.0.2+1.18.1.jar

[Ore Excavation]()
Funwayguy
OreExcavation-1.10.160.jar

[Paragliders]()
Tictim
Paraglider-1.18-1.5.0.0.jar

[Placebo]()
Shadows_of_Fire
Placebo-1.18.1-6.1.1.jar

[Repurposed Structures (Forge)]()
telepathicgrunt
repurposed_structures_forge-4.2.11+1.18.1.jar

[Shrines Structures]()
silverminer007
Shrines-1.18.1-3.0.0-Beta22.jar

[Slab Machines]()
Mrbysco
SlabMachines-1.18.1-1.1.1.jar

[Structure Gel API]()
ModdingLegacy
structure_gel-1.18.1-2.1.3.jar

[SwingThroughGrass]()
exidex
swingthroughgrass-1.18.1-1.8.0.jar

[TerraBlender (Forge)]()
TheAdubbz
TerraBlender-forge-1.18.1-1.1.0.77.jar

[TerraForged]()
won_ton_
TerraForged-1.18.1-0.3.0-alpha-2.jar

[Tinkers Construct]()
mDiyo
TConstruct-1.18.1-3.4.2.60.jar

[Tinkers' Rapier]()
sz0999312
tinker_rapier-1.0.0-1.18.1.jar

[Torch Slabs Mod]()
EndlesNights
torchslabmod-1.18.1_v1.7.5.jar

[Waystones]()
BlayTheNinth
waystones-forge-1.18.1-9.0.4.jar

[Xaero's Minimap]()
xaero96
Xaeros_Minimap_22.3.0_Forge_1.18.jar

[YUNG's API (Forge)]()
YUNGNICKYOUNG
YungsApi-1.18.1-Forge-26.jar

[YUNG's Better Dungeons (Forge)]()
YUNGNICKYOUNG
BetterDungeons-Forge-1.18.1-1.0.1.jar

[YUNG's Better Mineshafts (Forge)]()
YUNGNICKYOUNG
BetterMineshafts-Forge-1.18.1-1.0.jar

[YUNG's Better Strongholds (Forge)]()
YUNGNICKYOUNG
BetterStrongholds-Forge-1.18.1-1.0.2.jar

[YUNG's Bridges (Forge)]()
YUNGNICKYOUNG
YungsBridges-Forge-1.18.1-1.0.jar

[YUNG's Extras (Forge)]()
YUNGNICKYOUNG

### Tried reproducing with just Tinkers?

I will go do that now

### Performance Enchancers

Optifine

### Searched for known issues?

Checked pinned issues

**Comment by ShinyPorygon** [comment] 2022-03-26 23:46
Duplicate of #4734 
Remove optifine.

**Closed as completed by ShinyPorygon** 2022-03-26 23:46 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18

**Comment by yeetgrenadewastaken** [comment] 2022-03-26 23:52
Issue is gone after removing optifine
