### ISSUE TITLE
tinkers construct 1.8 crash

### ISSUE THREAD

**Issue by SDUBZ** [SlimeKnights/TinkersConstruct#1853] opened 2015-12-31 12:28 UTC
a crash when mining http://pastebin.com/RZWvfW9H

**Comment by bonii-xx** [comment] 2015-12-31 14:47
Duplicate of #1850.
Find out what block it was and which mod added it, then you can tell the author.

**Closed by bonii-xx** 2015-12-31 14:47 UTC
Labels: duplicate

**Comment by SDUBZ** [comment] 2016-01-01 10:28
yeah it wasnt tinkers it was techreborn mod sorry :/
