### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by Dyson78** [SlimeKnights/TinkersConstruct#3094] opened 2017-08-12 04:04 UTC
Missing a lot of images just shows blank image
Minecraft 1.12
Forge 14.21.1.2420
Optifine 1.12.HDUC4
Tinkers Construct 1.12-2.7.2.15
Mantle 1.3.1.18
![mc](https://user-images.githubusercontent.com/16409136/29237698-a97712be-7ef1-11e7-9ce5-02a87ccf338b.PNG)

**Comment by KnightMiner** [comment] 2017-08-12 04:06
Duplicate of #3008.

**Closed by KnightMiner** 2017-08-12 04:06 UTC
