### ISSUE TITLE
Items not displaying

### ISSUE THREAD

**Issue by GeneralRocky** [SlimeKnights/TinkersConstruct#3077] opened 2017-08-03 10:24 UTC
For some reason, nearly every stencil/tool part is invisible, even in the book and while I am holding them. They definitely work, because I have created a few tools to test them, but they do not have an image. I'm attaching a few pictures so you can see what I mean. I have tried using different versions of Forge, Tinkers Construct, and Mantle, all without success.

![screen shot 2017-08-03 at 6 20 22 am](https://user-images.githubusercontent.com/30690346/28917639-529aa35e-7814-11e7-81ca-3ec6f517c8f8.png)
![screen shot 2017-08-03 at 6 21 26 am](https://user-images.githubusercontent.com/30690346/28917640-52c5ed8e-7814-11e7-99c5-476f653c2a0e.png)
![screen shot 2017-08-03 at 6 19 45 am](https://user-images.githubusercontent.com/30690346/28917642-52cbdd7a-7814-11e7-88e7-54cbaa563261.png)
![screen shot 2017-08-03 at 6 20 01 am](https://user-images.githubusercontent.com/30690346/28917643-52d2cfd6-7814-11e7-92cc-48c60295cf20.png)
![screen shot 2017-08-03 at 6 23 10 am](https://user-images.githubusercontent.com/30690346/28917644-52e0237a-7814-11e7-82c7-0cbe599320ca.png)

Thank you!

**Comment by TheLEGObrick** [comment] 2017-08-03 11:14
I had the same issue too, and it seems like that mods that change item texture properties(?) (aka Optifine) cause most of the texturest to disappear. As such, if you have optifine installed, you'll have to get rid of it.

**Comment by AvengerStar** [comment] 2017-08-03 13:31
Optifine indeed causes this issue, I was constantly running into it. Probably have to wait for an update for most likely Optifine to fix itself causing it.

**Comment by GeneralRocky** [comment] 2017-08-03 14:17
Ah that stinks, I love Optifine... I wonder if downgrading to Optifine C3 or C2 instead of C4 (the most recent) would solve the problem too. Thanks for the help though, that was really bothering me!

**Comment by KnightMiner** [comment] 2017-08-03 14:31
There already was an update that fixed it, C5, which you would know if you searched and found that this is a duplicate of #3008.

**Closed by KnightMiner** 2017-08-03 14:31 UTC
