### ISSUE TITLE
tinkers construct book doesn't load

### ISSUE THREAD

**Issue by pervysuhdude** [SlimeKnights/TinkersConstruct#3617] opened 2018-08-16 16:26 UTC
i play hexxit in version 1.12.2

**If crashed, link to crash report (use a site such as pastebin):**

1.12.2
* Minecraft: hexxit
* Forge: 
* Mantle: 
* Tinkers Construct: 

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

**Comment by rylm** [comment] 2018-08-16 18:01
I have the same issue

**Comment by KnightMiner** [comment] 2018-08-16 18:09
Duplicate of #3617

**Closed by KnightMiner** 2018-08-16 18:09 UTC
