### ISSUE TITLE
Missing texture Constatan Bone Cleaver

### ISSUE THREAD

**Issue by Arkyo** [SlimeKnights/TinkersConstruct#3117] opened 2017-08-21 15:02 UTC
![image](https://user-images.githubusercontent.com/25037295/29525313-ce94fea0-86c4-11e7-85b1-63346887e135.png)

**Comment by bonii-xx** [comment] 2017-08-21 16:31
Constantan is not from TiC, and I see nothing wrong? Looks like the enchant effect is pretty bright, turning it white.

**Comment by dshadowwolf** [comment] 2017-09-19 15:51
@bonii-xx I think he's referring to the fact that its all white - something I've seen happen in other cases when integrating Base Metals and Modern Metals with Tinkers' ... Not sure what causes it, but my guess is the color of the material throws off the texture generation. If you'd like I'll look closer while giving the in-progress ports of both of those to 1.12 a solid test and see if I can find what happens

**Comment by Zarafa04** [comment] 2017-10-18 04:43
The Glow Is From the Shocking trait
shocking charges your weapon when you move to deal more damage
and on most ranged weapons it only affects the melee attack (except shurikens) you need to put it on the ammo to effect ranged attacks electrum gives shocking (probably other things too)

**Comment by dshadowwolf** [comment] 2017-10-18 12:07
I have learned that there is an issue with interfacing with Tinkers' caused by mods not updating to match the ordering or process by which Tinkers' initializes in 1.12 - and possibly the same in 1.11 in places. If the mod isn't matching the process properly, none of its material colors actually carry through except for the Tool Forge and material fluids.

**Comment by Zarafa04** [comment] 2017-10-18 12:16
It's supposed to be glowing its not a bug when its charge it goes all white

**Comment by Zarafa04** [comment] 2017-10-18 12:16
With the enchanting glow

**Comment by Zarafa04** [comment] 2017-10-18 12:42
Sharpening Kit | Tinkers' Construct Wiki | FANDOM powered by Wikia
Tinkers' Construct Wiki - Fandom446 × 268Search by image
An obsidian sharpening kit applied to a tool (white due to electrum glow)

**Comment by Zarafa04** [comment] 2017-10-18 12:44
http://tinkers-construct.wikia.com/wiki/Sharpening_Kit

**Comment by KnightMiner** [comment] 2017-10-22 20:29
Closing this as an issue in an addon with their materials. Reopen if it turns out to happen with just vanilla Tinkers materials.

**Closed by KnightMiner** 2017-10-22 20:29 UTC
Labels: Not enough information
