### ISSUE TITLE
Page contents cutoff

### ISSUE THREAD

**Issue by karakufire** [SlimeKnights/TinkersConstruct#4720] opened 2022-01-16 08:10 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.23

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Describe your issue

In reviewing #4707, I found text overflow in Puny Smelting, p38, in Japanese.
This situation will be caused, not only in Japanese, when multiple columns are misaligned by long text that it breaks lines.
![image](https://user-images.githubusercontent.com/10906521/149651944-143606a3-df93-449f-a512-b77d4202bf44.png)

Forcing people to revise their translations is not very kind.
I think you should review the column layout.

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by koh-gh** [comment] 2022-01-16 08:35
I was aware of this problem, but I recognize that cleaning up the display of the book is not a currently priority thing.
This can be improved somewhat by using a smaller font with a resource pack.
![2022-01-16_17 33 20](https://user-images.githubusercontent.com/36918206/149652937-4e41e9fc-55df-4986-9a83-eb36b1a1cbd1.png)

**Comment by karakufire** [comment] 2022-01-16 16:33
Not all TiC players install font mod/resourcepack in their installation. And I think that font mod/resourcepack is not only for resolve this problem, it provide players to use fonts what their favorite or readable,
Also, this problem will limits font variety of players' selection in font mod/resourcepack. In other words it will make that the fonts players to use the most will be hard to use due to this issue.
And I don't think it's a desirable situation at all to leave players in a situation where the presence of a problem forces them to install these things.

**Comment by KnightMiner** [comment] 2022-01-16 17:27
The issue has to do with how the book calculates columns. It has logic in place to prevent the case described by this bug, though its pretty finicky. In any case, its really a Mantle bug, as that is where the book library comes from. Mind posting there?

As a workaround for the Japanese translation, you can override the title for a particular page to make it shorter. I do it in the english version of the book, shortening `Unarmed Attack` to `Unarmed` (might be in the encyclopedia). I can give you more info if you want to try that workaround.

**Comment by koh-gh** [comment] 2022-01-17 01:19
![2022-01-17_10 06 33](https://user-images.githubusercontent.com/36918206/149686460-0e129d62-c08b-4c07-856d-4ac36dae4fa9.png)
![2022-01-17_10 06 48](https://user-images.githubusercontent.com/36918206/149686469-129d1e6f-5b71-489a-b11a-dcb1e87ccd9a.png)
This one?

I added "upgrades.diamond" section in language.lang of "Puny Smelting", but not worked.
Is this only encyclopedia?

**Comment by koh-gh** [comment] 2022-01-17 01:37
It's done.
![2022-01-17_10 30 45](https://user-images.githubusercontent.com/36918206/149687720-b65d24ad-807d-4761-9e88-a4f9384d58f2.png)
![2022-01-17_10 30 56](https://user-images.githubusercontent.com/36918206/149687727-aff67247-7455-459a-be1d-5dda10bfdc07.png)



However, it seems that I need to update the file in "sections" folder to make this happen. This file is not language-specific, but common to all languages, so I can't seem to fix it.

**Comment by KnightMiner** [comment] 2022-01-17 05:30
You have to give the page a name in the section. If it has no name, you cannot use the trick. You will notice in the sections, unarmed is the one with a name

**Comment by koh-gh** [comment] 2022-01-17 06:19
I'm aware.
"abilities.json" in "sections" directory has the following description.
https://github.com/SlimeKnights/TinkersConstruct/blob/bb16fbebc14ecf7a34d650d8f70650db68405cae/src/main/resources/assets/tconstruct/book/encyclopedia/sections/abilities.json#L159-L167
"Unarmed" has "name" section, and "zoom" has not "name" section.
And "language.json" has the following description.
https://github.com/SlimeKnights/TinkersConstruct/blob/bb16fbebc14ecf7a34d650d8f70650db68405cae/src/main/resources/assets/tconstruct/book/encyclopedia/en_us/language.lang#L45-L52

I found that I could fix as above by adding a `name` section to the diamond in sections/upgrades.json of Puny Smelting, and adding `upgrades.diamond=ダイヤ` to language.json. However, this fix should not be acceptable for solving the issue because changing the file of "sections" directory affects all languages.

Depending on the language, the length of the translated word will vary. For example, in Japanese, "unarmed" is not too long, so this trick is unnecessary. The best thing would be to change it so that the substitution can be done in a file in the directory for each language. Is this a Mantle task?

**Comment by KnightMiner** [comment] 2022-01-17 06:46
No, it does not affect all languages. If the language does not set `upgrades.diamond`, it gets the default. I was just lazy and did not set names on all of them. Test with the english page to verify.

All pages have a name, setting name just means it has a sensible one instead of autogenerated like `upgrades.page47`

In other words, set the name in the section, it will not break anything.

**Comment by koh-gh** [comment] 2022-01-17 07:45
It worked. But not good. Japanese is good but English is broken(replaced by Japanese words).
![2022-01-17_16 22 07](https://user-images.githubusercontent.com/36918206/149727938-1e50d708-3cde-44ab-93fd-73dd4deb538d.png)
![2022-01-17_16 25 41](https://user-images.githubusercontent.com/36918206/149727954-8d36fbed-7f4b-4e24-95c2-84fbee4f8f2b.png)

Actually, should the language.json has all modifier entries in en_us, even if the same in English? Because other language may substitute it.

**Comment by koh-gh** [comment] 2022-01-17 08:22
Sorry. This was a bit inaccurate. If I set the language to Japanese first, and then change it to English, it will look like the above. If I started Minecraft in English, it was displayed in English. If this is the case, do I not need to worry about it?

**Comment by karakufire** [comment] 2022-01-17 12:02
I apologise  that the Japanese translator is kindly reviewing them translation, but this issue is overflow of page content that can occur when many sentences are used that are too long to be broken lines.
Therefore, no matter how changing translation, the issue itselft will nod be fixed in the end because it's only a workaround.

@KnightMiner In the beginning I thought to request you to transfer this issue into Mantle's. But currently, should I repost same issue itself to the Mantle repository? Since there is now an exchange of information on workarounds that bypasses this issue.

**Comment by koh-gh** [comment] 2022-01-18 02:49
Thank you for fixing the issue of keeping undesirable cache. By using trick, I will add a fix to PR that resolve the issue with broken lists. I will leave the handling of this issue to the author and developer.

**Comment by KnightMiner** [comment] 2022-01-18 05:38
> I apologise that the Japanese translator is kindly reviewing them translation, but this issue is overflow of page content that can occur when many sentences are used that are too long to be broken lines.
Therefore, no matter how changing translation, the issue itselft will nod be fixed in the end because it's only a workaround.

Yes, I am aware the workaround does not fix the issue. That is why I requested reporting the issue to Mantle so it can be properly tracked and fixed in the future.

**Comment by KnightMiner** [comment] 2024-02-13 07:50
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/12155288/128826b6-7523-44e4-b4c3-b3ea5f17de82)
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/12155288/e6dc024b-d665-4880-af40-ea0a2ea58252)
After quite a bit of debugging, I managed to find the cause of this issue and fix it. The logic I had in place that was meant to deal with this issue by calculating the number of lines a "too long" line of text would take was running on the string including the bullet point, which often caused it to split the text at the space between the bullet point and the word. For long words containing no spaces, this caused a discrepancy between the Mantle text rendering logic that never splits there, and the estimated split length which considers a split there. I have updated the logic in Mantle to correct for this, so the next Mantle version should fix this. Will leave a comment when its updated.

**Comment by koh-gh** [comment] 2024-02-14 01:16
Is it for 1.18? The original issue was for 1.16.

**Comment by karakufire** [comment] 2024-02-14 14:04
I recognized that resolved means this issue is resolved on whole this mod lifecycle.
In other words TiC has already terminated of update for minecraft 1.16 if my thought is correct.

**Comment by KnightMiner** [comment] 2024-02-14 17:31
1.16 is unlikey to receive another release at this point, though I'll consider it before the 1.19 port

**Comment by KnightMiner** [comment] 2024-02-25 05:38
Fixed in Mantle 1.9.50 for 1.18. I'll keep this issue in mind as a potential issue for backport to 1.16 though.

**Comment by KnightMiner** [comment] 2024-02-28 20:14
Fixed in 3.7.0.152 for 1.18.2. I have labeled this for backport so if I do another 1.16.5 build, it will be addressed.

**Closed as completed by KnightMiner** 2024-02-28 20:14 UTC
Labels: Bug, Resolved, Mantle, 1.16, Confirmed, 1.18, Backport
