### ISSUE TITLE
Crash when viewing modifiers in book

### ISSUE THREAD

**Issue by SpartanSamuel** [SlimeKnights/TinkersConstruct#2697] opened 2017-01-04 00:14 UTC
I can get to the first two pages (the modifier table of contents and the following page, Haste) but after that it's an instant crash. This is used in a modpack (listing in the crash log), and I'm pretty sure it's some sort of incompatibility with another mod but can't determine which from the log. I've verified I can view the modifiers fine in a test world with just TC.

http://pastebin.com/WSRU8hQm

Minecraft: 1.10.2
Forge: 12.18.3.2202
Tinkers' Construct: 2.6.1
Mantle: 1.1.3

**Comment by KnightMiner** [comment] 2017-01-04 02:32
Duplicate of #2689. Already changed the book code to catch the crash, so fixed in the next version.

**Closed by KnightMiner** 2017-01-04 02:32 UTC

**Comment by QuantumWraith** [comment] 2017-01-04 12:27
[Here's a list of the mods we have in common that I have yet to test.](https://gist.github.com/QuantumWraith/1aeef52c1a793bc08319d29061e49e8b)

**Comment by QuantumWraith** [comment] 2017-01-04 12:29
[Here's a list of the mods we have in common that I have yet to test.](https://gist.github.com/QuantumWraith/7d8993b49274714743514c6b53c09313)

**Comment by QuantumWraith** [comment] 2017-01-04 12:34
[Here's a list of the mods we have in common that I have yet to test.](https://gist.github.com/QuantumWraith/e334f841a084478ebf323e313d6858f2)

**Comment by SpartanSamuel** [comment] 2017-01-05 00:00
Just ran the gauntlet on my modpack. I'm not sure why it didn't come up for you, but for me it's specifically Applied Energistics 2.

**Comment by SpartanSamuel** [comment] 2017-01-05 00:09
You're probably right about there being a combination of mods causing the issue. Simply removing AE2 from my pack fixed the issue, but testing a new instance with only AE2 and TC didn't cause the crash.

**Comment by SpartanSamuel** [comment] 2017-01-05 00:10
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2742
