### ISSUE TITLE
[1.16.5] Crash with EnderStorage (possibly with CodeChickenLib)

### ISSUE THREAD

**Issue by FoxMcloud5655** [SlimeKnights/TinkersConstruct#4670] opened 2021-12-07 06:48 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.19

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.0.308

### Describe your issue

Upon rendering an Ender Chest (not vanilla; from the EnderStorage mod), the client crashes immediately.  Doesn't matter if it's in the inventory, the world, the creative menu, or in JEI.

```
Description: Rendering Block Entity

java.lang.ExceptionInInitializerError: null
	at codechicken.enderstorage.client.render.tile.RenderTileEnderChest.render(RenderTileEnderChest.java:50) ~[?:1.16.5-2.8.0.168] {re:classloading}
	at codechicken.enderstorage.client.render.tile.RenderTileEnderChest.func_225616_a_(RenderTileEnderChest.java:32) ~[?:1.16.5-2.8.0.168] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228857_b_(TileEntityRendererDispatcher.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$42080/443724251.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:118) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1043) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:mixin:APP:supplementaries.mixins.json:ParrotPartingMixin,pl:mixin:APP:supplementaries.mixins.json:WorldRendererMixin,pl:mixin:APP:betterendforge.mixins.json:WorldRendererMixin,pl:mixin:APP:structure_gel.mixins.json:WorldRendererMixin,pl:mixin:APP:mythicbotany.mixins.json:MixinWorldRenderer,pl:mixin:APP:flywheel.mixins.json:BeginFrameMixin,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:appliedenergistics2.mixins.json:spatial.SkyRenderMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:APP:quark.mixins.json:client.WorldRendererMixin,pl:mixin:APP:charm.mixins.json:WorldRendererMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorWorldRenderer,pl:mixin:APP:assets/botania/botania.mixins.json:MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:flickerfix.mixins.json:MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:flickerfix.mixins.json:MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.19.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$487/1404708351.call(Unknown Source) [forge-1.16.5-36.2.19.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
Caused by: java.lang.NullPointerException
	at slimeknights.tconstruct.tools.logic.EquipmentChangeWatcher.attachCapability(EquipmentChangeWatcher.java:74) ~[?:1.16.5-3.3.0.308] {re:classloading}
	at slimeknights.tconstruct.tools.logic.EquipmentChangeWatcher$$Lambda$33135/793837303.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2509/186481417.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2830/1767847980.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:597) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:591) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:83) ~[?:?] {re:computing_frames,re:mixin,re:classloading,re:ChickenASM,re:codechicken.mixin.forge.ForgeMixinBackend}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:78) ~[?:?] {re:computing_frames,re:mixin,re:classloading,re:ChickenASM,re:codechicken.mixin.forge.ForgeMixinBackend}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:62) ~[?:?] {re:computing_frames,re:mixin,re:classloading,re:ChickenASM,re:codechicken.mixin.forge.ForgeMixinBackend}
	at net.minecraft.entity.Entity.<init>(Entity.java:221) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:performant.mixins.json:client.EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:randompatches.mixins.json:EntityMixin,pl:mixin:APP:betterendforge.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:spiderstpo.mixins.json:EntityMixin,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:expandability.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:performant.mixins.json:entity.EntityUpdateMixin,pl:mixin:APP:performant.mixins.json:entity.EntityMixin,pl:mixin:APP:performant.mixins.json:entity.EntityFPSMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.entity.item.ItemEntity.<init>(ItemEntity.java:47) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:itemphysic:tick,xf:fml:itemphysic:attack,xf:fml:itemphysic:collide,xf:fml:itemphysic:overrideMethod,re:mixin,pl:accesstransformer:B,xf:fml:itemphysic:tick,xf:fml:itemphysic:attack,xf:fml:itemphysic:collide,xf:fml:itemphysic:overrideMethod,re:classloading,pl:accesstransformer:B,xf:fml:itemphysic:tick,xf:fml:itemphysic:attack,xf:fml:itemphysic:collide,xf:fml:itemphysic:overrideMethod,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ItemEntityAccess,pl:mixin:APP:charm.mixins.json:accessor.ItemEntityAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorItemEntity,pl:mixin:APP:performant.mixins.json:entity.ItemEntityMixin,pl:mixin:A}
	at codechicken.lib.render.RenderUtils.<clinit>(RenderUtils.java:42) ~[?:1.16.5-4.0.4.435] {re:classloading}
	... 24 more
```

### Reproduced with only Tinkers' Construct?

No

### Other mods required

CodeChickenLib-1.16.5-4.0.4.435-universal
EnderStorage-1.16.5-2.8.0.168-universal

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment] 2021-12-07 06:55
Duplicate of #4667, its a bug in CCL that I am surprised Tinkers was the first mod it broke.

**Closed as completed by KnightMiner** 2021-12-07 06:55 UTC
Labels: Duplicate, Can't Fix, Mod interaction, 1.16

**Comment by FoxMcloud5655** [comment] 2021-12-07 06:59
My apologies; I searched the tracker for all open issues and didn't think to look at the closed issues.
