### ISSUE TITLE
Tinker's Construct Crafting Station disabled in Direwolf20 1.12 due to dupe bug

### ISSUE THREAD

**Issue by urikkiru** [SlimeKnights/TinkersConstruct#3419] opened 2018-03-17 03:03 UTC
I'm posting this issue to track the fact that for the last 2 versions of the Direwolf20 1.12 modpack, the recipe for the tinker's crafting station has been disabled. This has been in response to a reported dupe bug with the table.

https://forum.feed-the-beast.com/threads/dupe-bug-in-tc-crafting-table.269531/

I see no mention of it on this issue tracker, so just trying to make people aware. This bug report probably needs a *lot* more detail to be actionable, but at the moment it seems there's a stalemate where the Direwolf20 1.12 pack will keep the table disabled until this bug is fixed, and there's no issue being tracked here or discussion on it.

Given that one of the first things many people do when playing a modpack with Tinker's is build a crafting station, I thought this issue ought to have some more visibility.

**Comment by speaktorob** [comment] 2018-05-13 14:47
If you don't mind the dupe bug and want to re-enable the recipe, go into the folder `<modpack folder>/scripts` and edit `00_default.zs` and put `//` in front of these two lines:
```
// recipes.remove(<tconstruct:tooltables>);
// <tconstruct:tooltables>.addTooltip(format.red("Disabled due to a dupe bug"));
```
All lines beginning `//` in this file will be ignored when FTB processes it.

**Comment by urikkiru** [comment] 2018-05-13 21:50
I agree, it's an easy fix to do this. However, the core reason for this to be in here is to track the status of this problem. It was disabled for a (supposedly) good reason, so if there's a dupe bug it should be addressed.

**Comment by speaktorob** [comment] 2018-05-17 18:30
Totally agreed, I'd love to see it fixed. I only left those instructions for anyone that finds this issue via Google - like I did! Thanks for making it. 👍

**Comment by Undrhil** [comment] 2018-05-22 05:08
Or they can cheat in the Crafting Station after making a vanilla crafting table and throw the crafting table and one blank pattern out (so as to not be "cheating").

**Comment by RandomLibrarian** [comment] 2018-06-05 13:02
Now if we could get the server files for the May 16 release...

**Comment by borg286** [comment] 2018-06-25 22:15
I just enabled the crafting station, and tried to reproduce the bug. I was unable to get any duping, or deduping. I propose that we reenable the crafting station and see if this " every now and then it will not consume certain items" comes back. I've encountered other 1.12 packs that use tcon where when I use NEI to pull recipes in, that in some cases (haven't figured out the trigger yet) an item from your inventory will be pulled into an empty slot in the crafting grid. This item will disrupt the recipe causing the output item to not appear. The item that NEI moved into the crafting grid won't have a texture until you click on that square, thus pulling it out. The recipe works then, so you can pull your output item out.

I recall some work on the crafting station being done a while back where if it was placed next to a pedestal of some sort that using NEI to pull items from adjacent inventories would happen to pull it from the pedestal. The problem was that this should have been something that it wasn't designed for. I think that somehow items could get pushed into the pedestal which made it break. There was quite a bit of being blocked on other features before that got resolved.  One of the artifacts of the fixes was the way NEI and the crafting station searched through inventories, and extracted items to populate the crafting grid. Many lets players have simply been living with the fact that when they notice the recipe doesn't work they have to click around and hunt for the ghost item. 

While I consider both the ghost items and lacking the crafting station annoying, I consider the lack of a crafting grid game breaking for me. Modded minecraft has too many items for my personal inventory to be big enough for my NEI crafting needs.

**Comment by KnightMiner** [comment] 2018-07-03 19:09
As far as I can tell this was re-enabled in Direwolf20 and no one has experienced it recently, so closing this as fixed.

**Closed by KnightMiner** 2018-07-03 19:09 UTC
