### ISSUE TITLE
Crash when user joins multiplayer server wearing tinkers' boots.

### ISSUE THREAD

**Issue by ShibeTemple** [SlimeKnights/TinkersConstruct#4796] opened 2022-03-13 06:36 UTC
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

1.18.1-1.8.31

### Tinkers' Construct Version

1.18.1-3.4.1.46

### Describe your issue

A friend was able to wear the tinkers boots, and walked around for a bit but crashed later with unknown reproducible steps. Now, whenever she joins, her client crashes and so does anyone's in the area with the same crash report source. This happens consistently.

### Crash Report

Client wearing the boots: https://gist.github.com/ShibeTemple/2584a3c820ac376f85f6f034df0058b3 Other Player: https://gist.github.com/ShibeTemple/a43b22f6a0e64b0208e8bf1b6b3479f3

### Other mods

    [The Splash Milk (by marblegatekeeper)](https://www.curseforge.com/minecraft/mc-mods/the-splash-milk)
    [Scaffolding Drops Nearby (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/scaffolding-drops-nearby)
    [Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
    [Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
    [Shutup Experimental Settings! (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings)
    [Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
    [Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
    [Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
    [EnderTanks (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/endertanks)
    [Jet Boots (by black_dog20)](https://www.curseforge.com/minecraft/mc-mods/jet-boots)
    [Playdate (by Frogipher)](https://www.curseforge.com/minecraft/mc-mods/playdate)
    [Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
    [GUI Compass (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/gui-compass)
    [Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
    [Collective (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
    [Malum (by sammysemicolon)](https://www.curseforge.com/minecraft/mc-mods/malum)
    [Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
    [Builder's Delight (Forge) (by Tynoxs)](https://www.curseforge.com/minecraft/mc-mods/builders-delight-forge)
    [ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)
    [Project: Vibrant Journeys (by OrderedChaosDev)](https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys)
    [spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
    [Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials)
    [Hammer Lib (by Zeitheron)](https://www.curseforge.com/minecraft/mc-mods/hammer-lib)
    [Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
    [Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
    [Better Biome Blend (by FionaTheMortal)](https://www.curseforge.com/minecraft/mc-mods/better-biome-blend)
    [Ultimate Car Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod)
    [Oreberries Replanted (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/oreberries-replanted)
    [Simply Light (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/simply-light)
    [Coupons (by ShyNieke)](https://www.curseforge.com/minecraft/mc-mods/coupons)
    [Comforts (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
    [Simple Planes (Forge) (by przemykomo)](https://www.curseforge.com/minecraft/mc-mods/simple-planes)
    [Literal Sky Block (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/literal-sky-block)
    [Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
    [Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
    [Death Counter (by ohaiiChun)](https://www.curseforge.com/minecraft/mc-mods/death-counter)
    [Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
    [Equipment Compare (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/equipment-compare)
    [Just Enough Keys [JEK] [Forge] (by starmun)](https://www.curseforge.com/minecraft/mc-mods/just-enough-keys)
    [Seamless Loading Screen (Forge) (by TimScript)](https://www.curseforge.com/minecraft/mc-mods/seamless-loading-screen-forge)
    [World Name Randomizer (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/world-name-randomizer)
    [MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm)
    [Emotecraft (Forge) (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/emotecraft-forge)
    [Extended Creative Inventory (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/extended-creative-inventory)
    [Curios Quark Oddities Backpack (by 6LeoMC)](https://www.curseforge.com/minecraft/mc-mods/curios-quark-oddities-backpack)
    [Ping (by Girafi)](https://www.curseforge.com/minecraft/mc-mods/ping)
    [Industrial Reborn (by Maciej916)](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn)
    [Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
    [Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
    [Better Mods Button [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/better-mods-button)
    [OpenBlocks Elevator (by vsngarcia)](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
    [Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
    [Some Assembly Required (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/some-assembly-required)
    [Water Strainer (by Ruuubi)](https://www.curseforge.com/minecraft/mc-mods/water-strainer)
    [CleanView (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cleanview)
    [Dynamic View[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dynamic-view)
    [Building Gadgets (by Direwolf20)](https://www.curseforge.com/minecraft/mc-mods/building-gadgets)
    [Legendary Tooltips (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips)
    [Dark Paintings (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-paintings)
    [AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
    [Corn Delight (by sz0999312)](https://www.curseforge.com/minecraft/mc-mods/corn-delight)
    [TellMe (by masady)](https://www.curseforge.com/minecraft/mc-mods/tellme)
    [Fire Extinguisher - Stop Fire (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/fire-extinguisher)
    [Moyai (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/moyai)
    [YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
    [Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
    [Chunk Loaders (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders)
    [Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
    [Chipped (by grimbop)](https://www.curseforge.com/minecraft/mc-mods/chipped)
    [Sushi Go Crafting (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/sushigocrafting)
    [Solar Flux Reborn (by Zeitheron)](https://www.curseforge.com/minecraft/mc-mods/solar-flux-reborn)
    [Energy Meter (by DamnRelentless)](https://www.curseforge.com/minecraft/mc-mods/energymeter)
    [Advancement Screenshot (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/advancement-screenshot)
    [Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
    [Item Highlighter (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/item-highlighter)
    [Little Logistics (by Sveid_)](https://www.curseforge.com/minecraft/mc-mods/little-logistics)
    [Effective (Forge) (by BottomTextDanny)](https://www.curseforge.com/minecraft/mc-mods/effective-forge)
    [Find My Friends (by lukegrahamlandry)](https://www.curseforge.com/minecraft/mc-mods/find-my-friends)
    [TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
    [Productive Bees (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/productivebees)
    [Backpacked (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/backpacked)
    [Emojiful (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/emojiful)
    [More Minecarts and Rails (by goldey3)](https://www.curseforge.com/minecraft/mc-mods/more-minecarts)
    [Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
    [Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
    [Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
    [AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
    [Quark Oddities (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
    [Black_dogs's Modding Library (BML) (by black_dog20)](https://www.curseforge.com/minecraft/mc-mods/bml)
    [Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
    [Torchmaster (by xalcon)](https://www.curseforge.com/minecraft/mc-mods/torchmaster)
    [Advancement Book (by ParkerMc01)](https://www.curseforge.com/minecraft/mc-mods/advancement-book)
    [Architectury API (Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-forge)
    [Paintings ++ (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/paintings)
    [It's Just Lights (by purogu12)](https://www.curseforge.com/minecraft/mc-mods/its-just-lights)
    [Public Gui Announcement (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/public-gui-announcement)
    [Mantle (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/mantle)
    [Refined Pipes (by raoulvdberge)](https://www.curseforge.com/minecraft/mc-mods/refined-pipes)
    [Extended Lights (by Polyvalord)](https://www.curseforge.com/minecraft/mc-mods/extended-lights-mod)
    [MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
    [Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
    [Skinned Lanterns (Forge) (by nuxthefox)](https://www.curseforge.com/minecraft/mc-mods/skinned-lanterns)
    [Puzzles Lib [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
    [Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
    [Advanced Chimneys (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys)
    [Simple Kiln (by The_seVen_Twitch)](https://www.curseforge.com/minecraft/mc-mods/simple-kiln)
    [Name Pain (by naqaden)](https://www.curseforge.com/minecraft/mc-mods/name-pain)
    [Macaw's Paintings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
    [ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
    [Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
    [Display Case (by ChappiePie)](https://www.curseforge.com/minecraft/mc-mods/displaycase)
    [FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
    [Doggy Talents (by percivalalb)](https://www.curseforge.com/minecraft/mc-mods/doggy-talents)
    [Selene Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
    [Mod Name Tooltip (by mezz)](https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip)
    [Advancement Frames (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/advancement-frames)
    [Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
    [Beyond Earth (by mrscauthd)](https://www.curseforge.com/minecraft/mc-mods/beyond-earth)
    [FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
    [FPS Monitor (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/fps-monitor)
    [More Villagers (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/more-villagers)
    [AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
    [EnderChests (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/enderchests)
    [Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
    [Memory Usage Screen [Forge/Fabric] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/memory-usage-screen)
    [Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
    [Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
    [Distant Horizons: A Level of Detail mod (by James_Seibel)](https://www.curseforge.com/minecraft/mc-mods/distant-horizons)
    [Portable Mobs (by Dremoline)](https://www.curseforge.com/minecraft/mc-mods/portable-mobs)
    [Cloth Config API (Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge)
    [GUI Followers (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/gui-followers)
    [Entity Culling Fabric/Forge (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
    [Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements)
    [Dark Mode Everywhere (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/dark-mode-everywhere)
    [Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
    [SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
    [Functional Storage (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/functional-storage)
    [Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
    [Magitek Mechs (by DigiDigi_)](https://www.curseforge.com/minecraft/mc-mods/magitek-mechs)
    [Iceberg (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
    [FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
    [Just Player Heads (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/just-player-heads)
    [YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
    [Zetter — Painting Mod (by dantaeusb)](https://www.curseforge.com/minecraft/mc-mods/zetter)
    [Applied Energistics 2 (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
    [ShetiPhianCore (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore)
    [Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
    [Buddycards (by wildcard_gamer)](https://www.curseforge.com/minecraft/mc-mods/buddycards)
    [Wireless Chargers (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/wireless-chargers)
    [Mystical Agriculture (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture)
    [Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
    [Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
    [Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
    [Trofers (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/trofers)
    [Patina Pipeworks (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/patina-pipeworks)
    [Observable (by tasgon)](https://www.curseforge.com/minecraft/mc-mods/observable)
    [Valhelsia Structures (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures)
    [Server Tab Info (by black_dog20)](https://www.curseforge.com/minecraft/mc-mods/server-tab-info)
    [Mysterious Mountain Lib (by sz0999312)](https://www.curseforge.com/minecraft/mc-mods/mysterious-mountain-lib)
    [YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
    [Neon Craft 2 Mod (by Polyvalord)](https://www.curseforge.com/minecraft/mc-mods/neon-craft-2-mod)
    [Snuffles (by schnappdragon)](https://www.curseforge.com/minecraft/mc-mods/snuffles)
    [Titanium (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/titanium)
    [Exploration+ (by Buecher_wurm)](https://www.curseforge.com/minecraft/mc-mods/explorations)
    [Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
    [Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
    [ItemZoom (by mezz)](https://www.curseforge.com/minecraft/mc-mods/itemzoom)
    [Customized Dungeon Loot (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/customized-dungeon-loot)
    [Just Enough Keg (by marblegatekeeper)](https://www.curseforge.com/minecraft/mc-mods/just-enough-keg)
    [Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
    [Balanced Flight (Angel Ring) (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/balanced-flight)
    [GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
    [Tumbleweed (by bconv)](https://www.curseforge.com/minecraft/mc-mods/tumbleweed)
    [World Stripper (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/world-stripper)
    [Actually Compatible (by starmun)](https://www.curseforge.com/minecraft/mc-mods/actually-compatible)
    [Villager Names (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
    [GUI Clock (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/gui-clock)
    [Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
    [Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
    [Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
    [Compact Help Command (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/compact-help-command)
    [Pop! (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/bubbles)
    [Drip Sounds (Forge) (by PieKing1215)](https://www.curseforge.com/minecraft/mc-mods/waterdripsound)
    [SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
    [Pick Up Notifier [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
    [Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
    [NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
    [Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
    [Just Enough Drugz (by Jon1471)](https://www.curseforge.com/minecraft/mc-mods/just-enough-drugz)
    [Game Menu Remove GFARB [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/game-menu-remove-gfarb)
    [Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
    [Tinkers Construct (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct)
    [More Dragon Eggs (by Darkere)](https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs)
    [FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
    [Drink Beer (Forge) (by Lekavar)](https://www.curseforge.com/minecraft/mc-mods/drink-beer-forge)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment] 2022-03-13 06:38
Search pinned issues next time, they are pinned for a reason. Duplicate of #4734

**Closed as completed by KnightMiner** 2022-03-13 06:38 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
