### ISSUE TITLE
Seared Furnace/Tinker Tank Controllers

### ISSUE THREAD

**Issue by AaronFW** [SlimeKnights/TinkersConstruct#3290] opened 2017-12-21 11:31 UTC
For some unknown reason, I could not find a recipe for the Seared Furnace Controllers or Tinker Tank Controllers anywhere in Tinker's construct 12.2-2.7.4.34. I also could not find any information regarding the recipes on the web. I perceive this as an issue with the Materials and You Book since the book itself mentions the Seared Furnace and Tinker's Tank but does not give a description regarding how the controllers are created.

Additionally, I could not find any information on the web regarding whether there was a recipe, or any of my other questions so I wanted to post a question here for the next person who runs into my issue. My solution ended up being changing the game mode to Creative Mode and finding the Controllers in the Creative Inventory.

Is there some recipe for creating them? If so, can we add them to Materials and You? If there isn't a recipe, can we add some description regarding how they are supposed to be obtained? If they are being phased out, can we remove them from Materials and You? 

Seriously, there appears to be very little about the construction of the Controllers that I was unsure whether or not they were still a part of the mod.

**Comment by KnightMiner** [comment] 2017-12-21 13:27
Are you playing a mod pack? The controllers have had recipes since they were added, so there is a chance your pack removed the recipes. Try reproducing with just Tinkers Construct

**Comment by AaronFW** [comment] 2017-12-21 17:31
No, I am just playing Vanilla with a few mods installed (Tinker's; Waystone; Inventory Tweaks; Pam's Harvest craft; Gravestones). 

The issue I'm having is that I don't know what items are used in the recipe to make the objects and for some reason, I cannot find this information anywhere. 

Ah ha! I finally discovered it. This is what I was looking for:

<img width="251" alt="screen shot 2017-12-21 at 12 28 08 pm" src="https://user-images.githubusercontent.com/8921523/34267396-a841752c-e64a-11e7-974b-72a60d2813dc.png">
<img width="250" alt="screen shot 2017-12-21 at 12 27 51 pm" src="https://user-images.githubusercontent.com/8921523/34267397-a871be26-e64a-11e7-8df5-63084da5c527.png">

For some reason, I could not find these "recipes" explained anywhere. So I wanted to post them and, in regards to this issue, request that the recipes be added to the Tinker's book.

**Comment by KnightMiner** [comment] 2017-12-21 18:39
We currently don't keep recipes in our book in favor of the recipe book or JEI (though the former is weird as to when recipes show). If it's not showing in either that would be an issue, but it sounds like you just did not know the recipes, so I'll close this.

**Closed by KnightMiner** 2017-12-21 18:39 UTC
