### ISSUE TITLE
I cant hit/touch any Tinkers Construct blocks!

### ISSUE THREAD

**Issue by TommyXPhi** [SlimeKnights/TinkersConstruct#2312] opened 2016-08-12 16:52 UTC
Every time I Hit a Tinkers Construct Block it crashes!

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 8/12/16 12:43 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:38)
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:25)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:114)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2685)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1765)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:38)
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:25)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:114)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2685)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1765)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TommyXPhi'/321, l='MpServer', x=-28.97, y=63.00, z=264.48]]
	Chunk stats: MultiplayerChunkCache: 361, 361
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-4,64,252), Chunk: (at 12,4,12 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 346177 game time, 9574 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 84 total; [EntityWolf['Wolf'/135, l='MpServer', x=10.90, y=75.00, z=184.48], EntityZombie['Zombie'/137, l='MpServer', x=13.50, y=25.00, z=215.50], EntityHuman['Laraine'/138, l='MpServer', x=7.30, y=64.00, z=255.70], EntityHuman['Corina'/139, l='MpServer', x=10.30, y=64.00, z=254.51], EntityHuman['Sarah'/140, l='MpServer', x=9.66, y=64.00, z=267.50], EntityHuman['Wilbur'/141, l='MpServer', x=1.50, y=65.00, z=256.79], EntityHuman['Jack'/142, l='MpServer', x=8.05, y=63.00, z=276.83], EntityHorse['Horse'/143, l='MpServer', x=1.90, y=66.00, z=319.41], EntitySkeleton['Skeleton'/149, l='MpServer', x=17.50, y=44.00, z=197.50], EntityZombie['Zombie'/151, l='MpServer', x=28.51, y=35.00, z=265.20], EntityHuman['Richard'/152, l='MpServer', x=18.04, y=63.00, z=270.59], EntityHuman['Farah'/153, l='MpServer', x=17.50, y=64.00, z=264.71], EntityHorse['Horse'/155, l='MpServer', x=18.12, y=63.00, z=279.88], EntityHorse['Horse'/156, l='MpServer', x=16.16, y=65.00, z=299.11], EntityHorse['Horse'/157, l='MpServer', x=18.57, y=65.00, z=300.38], EntityHorse['Horse'/158, l='MpServer', x=27.98, y=64.00, z=303.06], EntityHorse['Horse'/159, l='MpServer', x=23.72, y=65.00, z=332.41], EntityHorse['Horse'/160, l='MpServer', x=25.13, y=65.00, z=329.98], EntitySkeleton['Skeleton'/166, l='MpServer', x=36.50, y=16.00, z=240.50], EntityHorse['Horse'/167, l='MpServer', x=30.10, y=65.00, z=305.06], EntitySkeleton['Skeleton'/40, l='MpServer', x=-101.25, y=39.00, z=229.55], EntityCreeper['Creeper'/168, l='MpServer', x=40.50, y=40.00, z=322.50], EntityBat['Bat'/41, l='MpServer', x=-97.27, y=37.10, z=245.55], EntityHorse['Horse'/169, l='MpServer', x=49.95, y=66.00, z=316.67], EntitySkeleton['Skeleton'/43, l='MpServer', x=-96.50, y=25.00, z=263.50], EntitySkeleton['Skeleton'/44, l='MpServer', x=-99.27, y=43.00, z=259.50], EntityBat['Bat'/45, l='MpServer', x=-97.80, y=47.47, z=269.44], EntityBat['Bat'/47, l='MpServer', x=-98.67, y=48.54, z=274.99], EntitySpider['Spider'/48, l='MpServer', x=-100.30, y=53.00, z=285.00], EntityBat['Bat'/50, l='MpServer', x=-81.88, y=49.57, z=188.47], EntityCreeper['Creeper'/51, l='MpServer', x=-91.50, y=49.00, z=198.50], EntityCreeper['Creeper'/52, l='MpServer', x=-87.50, y=31.00, z=209.50], EntityHorse['Horse'/53, l='MpServer', x=-94.07, y=63.00, z=273.87], EntityCreeper['Creeper'/54, l='MpServer', x=-91.50, y=53.00, z=329.50], EntityCreeper['Creeper'/55, l='MpServer', x=-79.50, y=30.00, z=214.50], EntityCreeper['Creeper'/56, l='MpServer', x=-74.50, y=30.00, z=216.50], EntityZombie['entity.Zombie.name'/184, l='MpServer', x=48.50, y=17.00, z=290.50], EntitySquid['Squid'/57, l='MpServer', x=-69.56, y=57.00, z=242.43], EntityCreeper['Creeper'/58, l='MpServer', x=-79.50, y=15.00, z=273.50], EntityHorse['Horse'/59, l='MpServer', x=-72.40, y=62.56, z=273.58], EntityHorse['Horse'/187, l='MpServer', x=44.17, y=65.08, z=319.95], EntitySkeleton['Skeleton'/60, l='MpServer', x=-80.23, y=13.00, z=314.51], EntityHorse['Horse'/189, l='MpServer', x=49.99, y=66.00, z=318.25], EntitySpider['Spider'/64, l='MpServer', x=-53.50, y=36.00, z=192.50], EntityCreeper['Creeper'/65, l='MpServer', x=-59.50, y=34.00, z=215.50], EntityPlayerSP['TommyXPhi'/321, l='MpServer', x=-28.97, y=63.00, z=264.48], EntityHorse['Horse'/66, l='MpServer', x=-60.97, y=67.00, z=224.99], EntitySquid['Squid'/67, l='MpServer', x=-47.05, y=62.04, z=298.71], EntityBat['Bat'/70, l='MpServer', x=-40.02, y=33.46, z=192.23], EntityEnderman['Enderman'/71, l='MpServer', x=-36.55, y=41.00, z=203.60], EntityBat['Bat'/72, l='MpServer', x=-24.47, y=61.20, z=202.72], EntitySkeleton['Skeleton'/73, l='MpServer', x=-39.50, y=43.00, z=211.50], EntityZombie['Zombie'/74, l='MpServer', x=-40.78, y=33.00, z=209.81], EntityCreeper['Creeper'/75, l='MpServer', x=-41.60, y=33.00, z=208.70], EntityZombie['Zombie'/76, l='MpServer', x=-37.73, y=35.00, z=218.46], EntityHorse['Horse'/77, l='MpServer', x=-41.95, y=69.00, z=218.90], EntityHorse['Horse'/78, l='MpServer', x=-39.82, y=67.00, z=223.95], EntityHorse['Horse'/79, l='MpServer', x=-43.13, y=63.00, z=236.07], EntityZombie['Zombie'/90, l='MpServer', x=-18.50, y=13.00, z=202.50], EntityWolf['Wolf'/92, l='MpServer', x=-17.52, y=69.00, z=193.63], EntitySheep['Sheep'/93, l='MpServer', x=-33.62, y=66.00, z=215.22], EntityHorse['Horse'/94, l='MpServer', x=-16.67, y=69.00, z=219.95], EntityHorse['Horse'/95, l='MpServer', x=-18.25, y=66.00, z=213.38], EntityHuman['Gerardo'/96, l='MpServer', x=-16.65, y=64.00, z=252.52], EntityHuman['Nolan'/97, l='MpServer', x=-19.19, y=63.00, z=256.29], EntityHuman['Norene'/98, l='MpServer', x=-22.30, y=63.00, z=258.30], EntityHorse['Neil'/99, l='MpServer', x=-16.10, y=63.00, z=257.28], EntityHuman['Dusty'/100, l='MpServer', x=-21.70, y=64.00, z=267.30], EntityHorse['Horse'/101, l='MpServer', x=-31.91, y=63.00, z=290.98], EntityWolf['Wolf'/112, l='MpServer', x=-14.70, y=66.00, z=196.55], EntityHorse['Horse'/113, l='MpServer', x=-5.23, y=64.00, z=205.01], EntityWolf['Wolf'/114, l='MpServer', x=-4.40, y=64.00, z=218.46], EntityWolf['Wolf'/115, l='MpServer', x=-5.50, y=68.00, z=218.28], EntityHuman['Chi'/116, l='MpServer', x=-3.22, y=63.00, z=252.70], EntityHuman['Lara'/117, l='MpServer', x=-11.51, y=64.00, z=252.71], EntityHuman['Ezequiel'/118, l='MpServer', x=-3.50, y=63.00, z=263.73], EntityHuman['Maisie'/119, l='MpServer', x=-3.66, y=63.00, z=266.96], EntityHuman['Jannet'/120, l='MpServer', x=-2.51, y=63.00, z=277.28], EntityHuman['Efrain'/121, l='MpServer', x=0.76, y=64.00, z=252.50], EntityHuman['Magaret'/122, l='MpServer', x=-14.71, y=64.00, z=259.51], EntityHuman['Aleisha'/123, l='MpServer', x=-12.25, y=63.00, z=257.50], EntityHorse['Horse'/124, l='MpServer', x=-18.74, y=63.00, z=291.97], EntityHorse['Horse'/125, l='MpServer', x=-1.05, y=65.00, z=309.76], EntityCreeper['Creeper'/126, l='MpServer', x=-0.40, y=41.00, z=337.83]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 508312568 bytes (484 MB) / 1004691456 bytes (958 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.1.2043 Optifine OptiFine_1.10.2_HD_U_C2 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2043.jar) 
	UCHIJAAAA	Forge{12.18.1.2043} [Minecraft Forge] (forge-1.10.2-12.18.1.2043.jar) 
	UCHIJAAAA	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.2} [RadixCore] (RadixCore-1.10.2-2.1.2-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.0} [Minecraft Comes Alive] (MCA-1.10.2-5.2.0-universal.jar) 
	UCHIJAAAA	morefood{1.17} [More Foods] (more-foods-1.10.2-2011-1.17.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.4.0.jenkins312} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jenkins312.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 2000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2043
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 2000 GL version 3.1.0 - Build 9.17.10.4229, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1.0 - Build 9.17.10.4229
	OpenGlRenderer: Intel(R) HD Graphics 2000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by ElKay99** [comment] 2016-08-12 17:11
I am having exactly the same problem (was about open a new issue), using latest Tinkers' Construct, Mantle and Forge. Cannot left click Tinkers' blocks such as crafting station, tool station, casting table etc. because of this crash. I've been having to use a block breaker!

**Comment by Khazadir** [comment] 2016-08-12 18:06
My wife is having the same problem.

She and I play together on a private server setup.  I am hosting the server on my machine.  I don't have this problem, and she does.

Whenever a Casting Basin (and probably any TC block) is struck and she is within 2 chunks, she crashes out with the error given above (same for at least the first part).

I do not have this problem.

We have noticed that if she is within two chunks of me

**Comment by ArukaAlter** [comment] 2016-08-12 18:10
Update Forge.

**Comment by LovelyFlare** [comment] 2016-08-12 20:15
Duplicate of #2279 which is caused by forge.  Make sure it's version 2046+

**Comment by Khazadir** [comment] 2016-08-13 05:42
Fixed the issue for us.  Thank you!

**Closed** 2016-08-13 05:54 UTC
Labels: duplicate
