### ISSUE TITLE
Osmium duping in Smeltery

### ISSUE THREAD

**Issue by NotezSK** [SlimeKnights/TinkersConstruct#4350] opened 2021-04-13 06:52 UTC
After putting Osmium in my smeltery, everything else I added turned into osmium going into the casting basin. It turned my molten glass and cobalt into osmium even after the osmium was drained from the smeltery.

**Comment by KnightMiner** [comment] 2021-04-13 06:53
Duplicate of #4283. There is a reason that issue is pinned. Remove performant.

**Closed as completed by KnightMiner** 2021-04-13 06:53 UTC
Labels: Duplicate, Performance Enhancers/Optifine
