### ISSUE TITLE
Wrong yields for Byproducts shown in JEI (1.18.2)

### ISSUE THREAD

**Issue by Gitcrafter** [SlimeKnights/TinkersConstruct#5018] opened 2022-11-06 13:22 UTC
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

For the Foundry I have set the Oreyield to 3 Ingots/Gems and the Byproductyield to 1 Ingot/Gem and that is working as it should, but in JEI it only very few ores with the correct yield wich are the Copper Ore(Regular/Deepslate), Raw Copper and Block of Raw Copper and all JAOPCA added Recipes, with all other ores, raw metals and blocks of raw metals showing a 3x the Byproductyield, despite giving the correct yield on melting, the Issue persist, when testing only with Mantle, Tinkers Construct and JEI

### Crash Report

no crash involved

### Other mods

Mantle, Tinkers Construct, JEI (10.2.1.283)

Reproducing with only Tinker is not possible, since JEI is required to show the Recipes

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment] 2022-11-06 14:11
It's not clear to me what the issue is here, can you provide screenshots of some example affected recipes? Is the correct value shown when you try crafting it? Sounds to me like a misunderstanding of the ore rate config 

There is absolutely no reason copper would work while others would not, however copper does have less byproduct than the average ore, thus suggesting misunderstanding.

This does sound a little like a bug that was fixed in 3.5.1, its literally impossible for the byproduct rate to affect just JEI after that version as the byproduct rate is only considered during JSON parsing.

**Comment by Gitcrafter** [comment] 2022-11-06 15:23
when melting the ore in the foundry it produces the correct amounts based on the config and after checking again in fact Raw Copper is the only ore showing the correct Recipe
Here an Example of the incorrectly shown Recipes with Raw Iron:
JEI shows me melting 1 Raw Iron in the Foundry gives 3 Ingots of Molten Iron + 3 Ingots of Molten Nickel,
but when actually melting the Raw Iron in the Foundry it gives 3 Ingots of Molten Iron + 1 Ingot of Molten Nickel

![2022-11-06_16 06 06](https://user-images.githubusercontent.com/81863925/200178861-b3c09970-12b6-4eff-9546-7b894b3c1592.png)
![2022-11-06_16 06 07](https://user-images.githubusercontent.com/81863925/200178863-70d2b154-f0e6-4617-9e8c-56641215a429.png)
![2022-11-06_16 07 34](https://user-images.githubusercontent.com/81863925/200178867-5d9abf91-e100-45f3-9ca4-5d36de975c08.png)
![2022-11-06_16 07 37](https://user-images.githubusercontent.com/81863925/200178860-7b0ecb9c-1b63-4001-87d9-bfda73253e27.png)

**Comment by KnightMiner** [comment] 2022-11-06 19:11
Can you provide a screenshot of the mod list from the main menu, or a screenshot of your mods folder?

Also, provide your tinkers config file.

**Comment by Gitcrafter** [comment] 2022-11-06 21:10
#Everything to do with gameplay
[gameplay]
	#Set this to false to disable new players spawning with the Tinkers' Book.
	shouldSpawnWithTinkersBook = true
	#If non-empty, only this material will be shown on tools in creative and JEI (or the first valid material if this is invalid for the tool).
	#If empty, all materials will show
	showOnlyToolMaterial = ""
	#If non-empty, only material will be shown on parts in creative and JEI (or the first valid material if this is invalid for the part).
	#If empty, all materials will show
	showOnlyPartMaterial = ""
	#If true, tables such as the part builder and tinker station will show all variants. If false shows only a variant with a default texture.
	showAllTableVariants = true
	#If true, anvils will show all metal variants. If false, shows only a variant with the default texture
	showAllAnvilVariants = true

	#Tweaks to vanilla damage sources to better work with armor
	[gameplay.damageTweaks]
		#Makes withering damage count as magic
		wither = true
		#Makes dragons breath count as magic
		dragon_breath = true
		#Makes falling blocks count as projectile
		falling_block = false
		#Makes lightning count as fire damage
		lightning = true

#Options related to recipes, limited options as a datapack allows most recipes to be modified
[recipes]
	#Add a recipe that allows you to craft a piece of flint using 3 gravel
	addGravelToFlintRecipe = false
	#Makes the recipe to alloy netherite in the smeltery only cost 2 gold per netherite ingot. If false uses the vanilla rate of 4 gold per ingot. Disable if there are crafting duplications.
	cheaperNetheriteAlloy = true
	#Makes wither skeletons drop necrotic bones
	witherBoneDrop = true
	#Allows converting wither bones to regular bones
	witherBoneConversion = true
	#Slimeballs not being usable in vanilla recipes that require slimeballs. Config option exists to disable easily in case this fix is redundant to another mod
	slimeRecipeFix = true
	#Fixes clear glass not being usable in vanilla recipes that require glass. Config option exists to disable easily in case this fix is redundant to another mod
	glassRecipeFix = true

	[recipes.ore_rates]

		#Ore rates when melting in the melter
		[recipes.ore_rates.melter]
			#Number of nuggets produced per metal ore unit melted. 9 nuggets would give 1 ingot
			#Range: 1 ~ 45
			nuggetsPerMetal = 27
			#Number of gem shards produced per gem ore unit melted. 4 gem shards would give 1 gem
			#Range: 1 ~ 20
			shardsPerGem = 12

		#Ore rates when melting in the smeltery
		[recipes.ore_rates.smeltery]
			#Number of nuggets produced per metal ore unit melted. 9 nuggets would give 1 ingot
			#Range: 1 ~ 45
			nuggetsPerMetal = 27
			#Number of gem shards produced per gem ore unit melted. 4 gem shards would give 1 gem
			#Range: 1 ~ 20
			shardsPerGem = 12

		#Ore rates when melting in the foundry
		[recipes.ore_rates.foundry]
			#Number of nuggets produced per metal ore unit melted. 9 nuggets would give 1 ingot
			#Range: 1 ~ 45
			nuggetsPerMetal = 27
			#Number of gem shards produced per gem ore unit melted. 4 gem shards would give 1 gem
			#Range: 1 ~ 20
			shardsPerGem = 12

		#Byprouct rates when melting in the foundry
		[recipes.ore_rates.foundry_byproduct]
			#Number of nuggets produced per metal ore unit melted. 9 nuggets would give 1 ingot
			#Range: 1 ~ 45
			nuggetsPerMetal = 9
			#Number of gem shards produced per gem ore unit melted. 4 gem shards would give 1 gem
			#Range: 1 ~ 20
			shardsPerGem = 4

	#Entity head drops when killed by a charged creeper
	[recipes.heads]
		blaze = true
		enderman = true
		stray = true
		husk = true
		drowned = true
		spider = true
		cave_spider = true
		piglin = true
		piglin_brute = true
		zombified_piglin = true

#Options related to loot table injections. Note some of the changes are done via global loot managers, these only control injecting loot into loot pools
#If your modpack makes extensive loot table changes, many of these may be automatically disabled. You can also manually set up tables for more control.
[loot]
	#Adds slimy saplings and seeds into various loot chests. Helps for worlds without slime islands
	slimy_loot = true
	#Weight of blazing blood in the piglin bartering tables. Set to 0 to disable
	#Range: 0 ~ 100
	barter_blazing_blood = 20
	#Weight of tinker tools in the vanilla spawn bonus chest, randomly replacing the vanilla axe or shovel. Tool will have a random tier 1 head and binding, plus a wooden handle. Set to 0 to disable.
	#For comparison, vanilla wooden axes and pickaxes have a weight of 3, and stone axes/pickaxes have a weight of 1
	#Range: 0 ~ 25
	tinker_tool_bonus_chest = 2
	#If true, ender dragons will drop scales when damaged by explosions
	drop_dragon_Scales = true

#Everything to do with world generation
[worldgen]
	#Generate Cobalt
	generateCobalt = true
	#Approx Ores per Chunk
	veinCountCobalt = 8

	#Options related to slime geodes
	[worldgen.geodes]
		#If true, earthslime geodes generate deep in the world as another way to get slime
		earth = true
		#If true, skyslime geodes generate above amethyst as another way to get skyslime
		sky = true
		#If true, ichor geodes generate high in the nether. Strongly encouraged to keep enabled even if you disable the other geodes, as ichor crystals have some unique recipes and the fallbacks kinda suck for gameplay.
		ichor = true
		#If true, enderslime geodes generate as additional islands in the end
		ender = true

#Features to use in debugging gameplay and mechanics, generally should not be enabled in packs
[debug]
	#If true, forces integration materials to be enabled, even if the relevant metal is missing. Useful for testing material balance.
	#Does not provide recipes for any of them, they will only be available to cheat in creative.
	forceIntegrationMaterials = false

**Comment by Gitcrafter** [comment] 2022-11-06 21:15
![grafik](https://user-images.githubusercontent.com/81863925/200195387-04087237-a608-41ea-ac0e-94f854a8ee7b.png)
![grafik](https://user-images.githubusercontent.com/81863925/200195488-3b28285c-f52a-43f9-9cb3-03897e20af98.png)
![grafik](https://user-images.githubusercontent.com/81863925/200195515-f109d318-91fd-4125-a14e-70f5520880e6.png)

**Comment by KnightMiner** [comment] 2022-11-06 21:35
Did you manage to reproduce with fewer mods? If you reproduced with just Tinkers and JEI, show me that mod list instead of a list of 100+ mods.

Also, let me reiterate, you describing that copper is correct and no others are makes no sense. Please, try melting copper ore to verify that you see the same value in JEI as you get when melting. Copper ore normally has 1/3 of the byproduct of other ores, the rate is a multiplier, not an absolute value

**Comment by KnightMiner** [comment] 2022-11-06 23:09
Did some digging into this myself, the problem fortunately was visible from your config file without me needing to dive into your mod list. You boosted regular ores to 300% their regular output, and JEI is using that rate to boost byproducts displayed, it should only use that rate to boost the primary output for the foundry.

The thing that threw me off was you insisting that copper was correct. I strongly suspect that copper fits the same trend as the rest of the ores, you just misunderstood that copper ore has 1/3 of the byproduct.

**Comment by Gitcrafter** [comment] 2022-11-07 10:49
Of course you are right with the copper ore, I forgot the increased yield of copper ore compared to the other ores and while confirming this, I found another unrelated issue:
when melting things in the Foundry, that have byproducts and there is not enough free space for the full amount of the byproduct, the amount of byproduct, that doesn´t fit in the Foundry, gets deleted

**Comment by KnightMiner** [comment] 2022-11-07 13:56
1. Unrelated issues should be on their own ticket
2. That is intentional. It's a byproduct, it's your job to ensure there is space

**Comment by Gitcrafter** [comment] 2022-11-07 20:01
well ensuring that there is enough free space is very difficult without comparator support

**Comment by KnightMiner** [comment] 2022-11-25 05:45
Fixed in [3.5.3.63](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.3.63)

**Closed as completed by KnightMiner** 2022-11-25 05:45 UTC
Labels: Bug, Resolved, Confirmed, 1.18
