### ISSUE TITLE
casting table cause server lag?

### ISSUE THREAD

**Issue by user38898892** [SlimeKnights/TinkersConstruct#3901] opened 2019-07-16 11:34 UTC
**Issue description:**
My server has a low tps. Here's the sampler report:
https://i.imgur.com/DeICpxk.png
So I wonder if it is caused by the casting table?
 
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* Mantle: 1.12-1.3.3.49
* Tinkers Construct: 1.12.2-2.12.0.135
Sponge:1.12.2-2838-7.1.7-RC3777

**Comment by KnightMiner** [comment] 2019-08-07 16:59
The casting table alone is unlikely to cause lag unless you are attempting to add fluid to it, so see if you have any active casting tables being filled or emptied radidly, and even that's minimal unless you have hundreds of them. I will look into this when I have some free to verify that's the only case.

**Comment by bonii-xx** [comment] 2019-09-18 17:10
Might also be that the list of casting recipes is absurdly long.

**Comment by KnightMiner** [comment] 2019-10-13 21:03
On additional research, this appears to be a duplicate of #3817. Something about getListFrom and ItemCombination.matches are not efficient, but its hard to tell why as in dev neither are significant. I will double check the two methods and see if there is anything we can make more efficient, but since its the same I will handle it on the other issue.

**Closed by KnightMiner** 2019-10-13 21:03 UTC
