### ISSUE TITLE
Game Crashes while starting

### ISSUE THREAD

**Issue by P33333333333dulski** [SlimeKnights/TinkersConstruct#4517] opened 2021-06-06 14:55 UTC
Game crashes while starting

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2855
* Mantle: Mantle-1.12-1.2.5
* Tinkers Construct: TConstruct-1.12.2-2.12.0.183

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  RandomPatches (randompatches-1.12.2-1.17.0.0.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  OTGCorePlugin (OTG-Core.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LevelUpCore (levelup2-1.5.8.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
  FutureMC (future-mc-1.12.2-0.2.6.1.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.14.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/6/21 4:20 PM
Description: Initializing game

java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo
	at lucraft.mods.lucraftcore.LCConfig$Materials.<init>(LCConfig.java:108)
	at lucraft.mods.lucraftcore.LCConfig.<clinit>(LCConfig.java:36)
	at lucraft.mods.lucraftcore.addonpacks.AddonPackHandler.getAddonPacksDir(AddonPackHandler.java:61)
	at lucraft.mods.lucraftcore.core.LCClientHooks.insertAddonPackResourcePacks(LCClientHooks.java:37)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:789)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.library.client.MaterialRenderInfo
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at lucraft.mods.lucraftcore.LCConfig$Materials.<init>(LCConfig.java:108)
	at lucraft.mods.lucraftcore.LCConfig.<clinit>(LCConfig.java:36)
	at lucraft.mods.lucraftcore.addonpacks.AddonPackHandler.getAddonPacksDir(AddonPackHandler.java:61)
	at lucraft.mods.lucraftcore.core.LCClientHooks.insertAddonPackResourcePacks(LCClientHooks.java:37)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:789)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by PrincessOfEvil** [comment] 2021-06-06 14:56
Lucraft issue. Duplicate of #4441.

**Closed as completed by PrincessOfEvil** 2021-06-06 14:56 UTC
Labels: Duplicate, Mod interaction, 1.12
