### ISSUE TITLE
TConstruct-1.16.5-3.0.3.152: when collecting molten blaze the seared drain stops working

### ISSUE THREAD

**Issue by Howsyomamanem** [SlimeKnights/TinkersConstruct#4544] opened 2021-06-20 04:35 UTC
It works for a bit, then it seems to "forget" that it can be interacted with like a block that contains fluid.  I don't know how better to describe the issue.

I'm using the TC faucet, and can't even get fluid to come out.  I've also tried mekanism pipes. I've tried breaking and replacing the controller, the tank, the drain and the faucet several times.  

Here's a screen shot of the setup: http://puu.sh/HQitQ/f462693b68.jpg

see how the mekanism pipe on the bottom doesn't "connect" to the drain.  It did for a bit, but now it won't.  If I right-click the faucet, nothing happens.  That also worked initially but not now.  The smeltery is fully formed and I can interact w/ the controller just fine.

**Comment by Howsyomamanem** [comment] 2021-06-20 04:51
Update:  I restarted my server and it's working again.  I'll let you know if it stops again.  Thanks.

**Comment by ShinyPorygon** [comment] 2021-06-20 09:01
Please properly fill out the report you ignored

**Comment by Howsyomamanem** [comment] 2021-06-20 20:37
I didn't "ignore" anything.   There was no "report" to fill out just a free-form textarea to populate.  Maybe instead of assuming the worst... you might investigate if you implemented your "report" properly?  Just sayin'.

**Comment by ShinyPorygon** [comment] 2021-06-20 21:05
When you opened the issue there was a pre made text for you that you would have had to purposely delete. There is not enough information here to fully debug your issue.

Edit: they all work fine I just tried it. And you are also on a way old version of tinkers anyway

**Comment by KnightMiner** [comment] 2021-06-21 02:33
You likely ran into a github bug due to clicking "New Issue" before you logged in, I have been looking for a way to deal with that.

Since we cannot do anything about that issue, I suggest you click new issue again to get the issue template, and add the requested information to this issue. Also, as Shiny said, update to the latest version. You said you cannot reproduce this anymore anyways, though, so honestly not sure there is anything I can do if you cannot reproduce it without more info about what caused it the first time.

**Comment by KnightMiner** [comment] 2021-08-20 06:35
Reading this description again, sounds like this is the same bug fixed by 71e1bcd. So will close this once that is released.

**Comment by KnightMiner** [comment] 2021-08-26 18:55
Fixed in 3.1.2.265

**Closed as completed by KnightMiner** 2021-08-26 18:55 UTC
Labels: Not enough information, Resolved, 1.16
