### ISSUE TITLE
[1.10.2] java.lang.RuntimeException

### ISSUE THREAD

**Issue by Xamxas** [SlimeKnights/TinkersConstruct#2465] opened 2016-10-09 03:24 UTC
Hello I started having trouble with minecraft a while ago but after much head banging on what the hell the crash report means I saw this line that I think caused the crash.

java.lang.RuntimeException: Could not load material from tconstruct:materials/vine.json

Then then some more incomprehensible stuff. I think this is what my game is saying caused the crash. If it helps here is the crash report.

http://pastebin.com/iTHdvGf5

If I am completely wrong then I apolagize in advance, I have no idea how to read a crash report.

**Comment by KnightMiner** [comment] 2016-10-09 03:47
Duplicate of #2436.

**Closed** 2016-10-09 08:47 UTC
Labels: duplicate
