### ISSUE TITLE
Gear cast is no where to be seen

### ISSUE THREAD

**Issue by MasterSloth1** [SlimeKnights/TinkersConstruct#4898] opened 2022-06-07 23:26 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.35

### Mantle Version

Mantle-1.16.5-1.6.157

### Tinkers' Construct Version

Tconstruct-1.16.5-3.3.2.335

### Describe your issue

if you create a new instance of minecraft with only 
Jei 
Mantle
Tconstruct
then you search jei for gear cast you will see its not there, but if you look at a recipe that uses the gear cast you can see the item and how to get it

### Other mods

Jei version jei-1.16.5-7.7.1.152

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment] 2022-06-07 23:27
Gear cast doesn't appear without a mod that adds gears

**Comment by MasterSloth1** [comment] 2022-06-07 23:39
this only happens on server not single player ive also added another mod that provides gears to the game
EmendatusEnigmatica version - EmendatusEnigmatica-1.2.15-build.7+mc1.16.5.jar

**Comment by KnightMiner** [comment] 2022-06-07 23:45
Emendantus Enigmatica for some weird reason does not work with any of tinkers. We have no idea why but the mod is closed source stopping us from putting too much effort into it.

Try with any other mod that adds gears. If the behavior is the same we can reopen. If not, this is a duplicate of Emendantus Enigmatica does something weird with tags.

**Comment by MasterSloth1** [comment] 2022-06-07 23:56
so ive added the thermal suit
Thermal Cultivation - thermal_cultivation-1.16.5-1.5.0.4.jar
Thermal Expansion - thermal_expansion-1.16.5-1.5.0.7.jar
Thermal Foundation - thermal_foundation-1.16.5-1.5.0.14.jar
Thermal Innovation - thermal_innovation-1.16.5-1.5.0.4.jar
Thermal Locomotion - thermal_locomotion-1.16.5-1.5.0.4.jar
and the same issue appears the gear cast from @tconstruct is missing in jei but when you look at the recipes for a gear from thermal you can see the gear cast there

**Comment by KnightMiner** [comment] 2022-06-07 23:56
Do you still have Emendantus Enigmatica installed? If so test without it, just Tinkers and Thermal.

**Comment by MasterSloth1** [comment] 2022-06-07 23:58
yip i removed EE and it still happens
![image](https://user-images.githubusercontent.com/34207969/172502984-0083ca0c-7f2d-41a0-82dd-fafaed03d96a.png)

**Comment by ShinyPorygon** [comment] 2022-06-08 00:10
![image](https://user-images.githubusercontent.com/35193007/172504484-0868229d-1f33-4886-bbcd-e6fdbeff934d.png)
Unable to reproduce with thermal and tinkers

**Comment by MasterSloth1** [comment] 2022-06-08 00:10
are you on a server?

**Comment by KnightMiner** [comment] 2022-06-08 00:16
If it only happens on servers, this is likely due to how broken tag loading was on 1.16. It has changed twice since 1.16.5. I suspect even if Shiny can reproduce it there is not much we can do as I am already using the proper system, it means for some reason on a server your tags are never syncing to the client.

Can you reproduce this on 1.18 at all?

**Comment by MasterSloth1** [comment] 2022-06-08 00:24
i will try and reproduce this on 1.18, i myself only play 1.16

**Comment by ShinyPorygon** [comment] 2022-06-08 00:30
1.16 is mostly unsupported at this point so if it's on 1.18 it's worth fixing

**Comment by MasterSloth1** [comment] 2022-06-08 00:41
yea i cant reproduce this on 1.18, so does this mean 1.16 wont get fixed/cant get fixed?

**Comment by KnightMiner** [comment] 2022-06-08 00:48
Considering I have no idea why it would even be broken, it is unlikely to be fixed

**Comment by KnightMiner** [comment] 2024-09-23 03:17
I am going to go ahead and close this given we never could reproduce the issue.

**Closed as completed by KnightMiner** 2024-09-23 03:17 UTC
Labels: Bug, Can't reproduce, 1.16

**Comment by Kurizek27** [comment] 2025-03-06 23:43
> Gear cast doesn't appear without a mod that adds gears

I have industrial foregoing (adds iron gold and diamond gears), jei shows cast when searching trough recipes for gear but i cant make it and when i search for all molds, the gear one is missing.

**Comment by Kurizek27** [comment] 2025-03-06 23:44
> If it only happens on servers, this is likely due to how broken tag loading was on 1.16. It has changed twice since 1.16.5. I suspect even if Shiny can reproduce it there is not much we can do as I am already using the proper system, it means for some reason on a server your tags are never syncing to the client.
> 
> Can you reproduce this on 1.18 at all?

1.19.2 still not working

**Comment by KnightMiner** [comment] 2025-03-07 03:49
Industrial Foregoing does not tag their gears as `forge:gears`, I only see tags for specific materials such as `forge:gears/iron`. Their bug, not ours. See InnovativeOnlineIndustries/Industrial-Foregoing#1504 (which was never fixed for earlier verisons than 1.21).

You can fix it with a datapack. Note using KubeJS will reportably not work for this as their tags are registered at the wrong time.
