### ISSUE TITLE
Fluids do not render with fabulous graphics

### ISSUE THREAD

**Issue by EvergreenSystems** [SlimeKnights/TinkersConstruct#4745] opened 2022-02-08 20:30 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.59

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.0.34

### Describe your issue

Fluids interacting with tinkers things (foundry, faucets, tanks, etc) do not render when graphics is set to fabulous. This is not limited to fluids that are _added_ by tinkers, the same effect is seen with vanilla lava and water. Fluids render as expected on the other two graphics settings.

Attached picture: the tank has lava in it, as does the smelter and seared channel/faucet. 
![2022-02-08_14 24 45](https://user-images.githubusercontent.com/23658767/153070263-e0b0ce33-bfe7-420b-8ea1-3ccd50c8762d.png)

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Check if you are not using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you have look at FAQ to see if your issue is answered
- [ ] Check if you did not read all of the above checkboxes and just checked all the boxes

**Comment by EvergreenSystems** [comment] 2022-02-09 19:35
Oddly enough cooling cast blocks render, but the fluid itself doesn't 
![2022-02-09_13 33 55](https://user-images.githubusercontent.com/23658767/153276776-35b18c6c-d0ea-4960-98b1-4fac776f3827.png)

**Comment by KnightMiner** [comment] 2022-02-14 05:28
Confirmed this issue, though may take a bit to figure out exactly what is causing it. I have a suspicion but I won't be able to test it for awhile.

**Comment by ChiefArug** [comment] 2022-03-01 09:05
I get this too, but discovered that while standing in certain positions (and different positions for different window sizes... for some odd reason) it does render. (screenshots of the window sizes on [SlimeKnights discord](https://discord.com/channels/381483562576379907/395801350731989003/948134596158046209))


https://user-images.githubusercontent.com/73862885/156138341-79d55804-4a92-4586-97e0-cbb2032ebcfe.mp4


It also happens with the mob grinding utils tanks, incase that helps narrow down the cause.

**Comment by KnightMiner** [comment] 2022-03-15 03:53
Fixed in Tinkers Construct 3.4.2.60 and Mantle 1.8.37

**Closed as completed by KnightMiner** 2022-03-15 03:53 UTC
Labels: Bug, Resolved, Confirmed, 1.18
