### ISSUE TITLE
Broken gui in Tinker's Station 

### ISSUE THREAD

**Issue by Kostiantyn322** [SlimeKnights/TinkersConstruct#4730] opened 2022-01-28 22:06 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Describe your issue

Tinker's station doesn't show a left tool selection panel & doesn't show boxes for part's
Screenshot: [https://imgur.com/a/XO2GsaQ](URL)

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment] 2022-01-28 23:19
Are you sure you reproduced with only Tinkers' Construct? Screenshots show that you somehow broken datapack loading, which never happens with just the mod.

Please provide a full mod list, and your game log, then test with no other mod installed. Also confirm if you are on a server or not.

**Comment by WarMind666** [comment] 2022-02-24 17:17
Having a similar issue.  I am on a server that I run, and I did run Optifine on my client, but never ran it on the server itself.  I have since removed Optifine from my client.  I have other players on my server that are experiencing the same issue, and they have never run Optifine.   The part builder will not populate the parts templates when a blank pattern and wooden planks are placed into it.  
Tinker's Construct version: 3.3.3.332
Mantle Version: 1.16.5-1.6.157
Forge for 1.16.5: 36.2.26
Also using Tinker's Construct addon mods:
Materialis:  1.16.5-2.5.0
TCon Planner: 1.16.5 - 1.1.1
Tinker's Delight: 1.16 - 1.8
Tinker Rapier: 1.1.4-1.16.5

Tested in Single Player, with/without the addons, and it worked perfectly.  Is there a way to rebuild the datapack?  Wasn't sure which log file you needed, so I provided both latest and debug.  The issue only started when I updated the mod on my server a few days ago.
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/8134431/debug.log)
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/8134433/latest.log)

**Comment by KnightMiner** [comment] 2022-02-24 17:59
You have a ton of erroring datapack content, including tool definition, vanilla tags, material stats, and alike. I cannot tell from the errors exactly what went wrong, simply that for some reason its not loading any datapack content from Tinkers Construct. The logs you game me have way more mods than you mentioned in your comment, so give me a smaller list of mods that lets me reproduce the error as there are a ton of datapack related errors from other mods that simply are broken recipes or tags, which are cluttering the log. There are other people having the mod work just fine on a server, its either one of your mods breaking datapack loading, or someone breaking loading of Tinkers Construct datapack content specifically causing it to get removed from the list of datapacks. 

You could try creating a new world on the server, and then getting me the log from the first time you load the new world, as that might include the error message I need. Ideally a more minimal log will help, create a fresh world on the server, start it up, log in to see the error, then shut it down and save the log.

**Comment by WarMind666** [comment] 2022-02-24 20:11
I think this issue is due to a corruption within my world on the server, because I created a new singleplayer instance with all of the associated mods, it worked like a champ

**Comment by KnightMiner** [comment] 2022-02-24 20:17
Like I said, the datapack corresponding to Tinkers Construct resources did not load. The only reason that happens in vanilla is if something errored so the game disabled the datapack, but that error only is logged when it actually disables the pack. Makes it really hard to find the cause. 

If you can get it to happen again (perhaps it only happens on a server), getting a server log as soon as possible after it happens will help debug this.

**Comment by KnightMiner** [comment] 2022-05-14 20:55
Going to close this as you no longer have the bug and without anyone having the issue we cannot really debug this.

**Closed as completed by KnightMiner** 2022-05-14 20:55 UTC
Labels: Bug, Not enough information, 1.16
