### ISSUE TITLE
Tools and Tool parts missing from Creative Inventory Search

### ISSUE THREAD

**Issue by Stick-2357** [SlimeKnights/TinkersConstruct#4314] opened 2021-04-06 17:40 UTC
**Issue description:**
Searching for sword (or any other tinkers tool) in the creative menu does not show the respective tinker's tool

**If crashed, link to crash report (use a site such as pastebin):**
N/A

**Versions:**
* Minecraft: 1.16.5
* Forge:  36.0.42
* Mantle: 1.6.79
* Tinkers Construct:  3.0.2.78

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Tinker's only

**Comment by PrincessOfEvil** [comment] 2021-04-06 18:41
Duplicate of #4301.

**Comment by KnightMiner** [comment] 2021-04-06 18:42
No, different issue. For more context, creative inventory loads on game start. Material list load on world load. JEI also loads on world load, by calling getSubItems as expected, which is why it works except in the case of #4301. I want to leave this open to remind me to argue with the search tab some time. Our dedicated tabs should work

**Comment by PrincessOfEvil** [comment] 2021-04-06 18:43
Right, my bad. It was reported already, though, I think.

**Comment by KnightMiner** [comment] 2021-04-25 00:56
Looks like fixing this involves messing with the search tree for vanilla, a complex datastructure that I dont' feel confortable messing with. Its either too hard or impossible for me to want to put in the effort.

**Comment by KnightMiner** [comment] 2022-01-11 18:53
In recent versions tools were given a way to initialize their data and now they show in in the search tab. Tool parts never will due to how Mojang indexes the search tab.

**Closed as completed by KnightMiner** 2022-01-11 18:53 UTC
Labels: Bug, Won't Fix, Can't Fix, 1.16
