### ISSUE TITLE
Illuminati effect white screen bug.

### ISSUE THREAD

**Issue by Aarhunt** [SlimeKnights/TinkersConstruct#4170] opened 2020-08-07 13:45 UTC
**Issue description: Whenever I have a pickaxe with a Lumium tool rod (giving the Illuminati and Glowing effects) in my hand, and my friend is in my sight (has the glow effect from Illuminati) my screen turns completely white. To fix it, I have to look away of my friend, wait until my screen isn't white anymore and swap out my pickaxe for something else. Sometimes, it just doesn't fix and I have to restart my game. **

If crashed, link to crash report (use a site such as pastebin):

**Versions: **

Minecraft: 1.12.2
Forge: 14.23.5.2584
Mantle: 1.3.3.55
Tinkers Construct: 2.13.0.183

Can it be reproduced with just Tinkers Construct? If not, list the other mods required to reproduce the issue.
Thermal foundation is needed to reproduce the issue, as that mod has the Lumium required to make the pickaxe.

**Comment by KnightMiner** [comment] 2020-08-07 14:34
Duplicate of #4169. This is not a Tinkers Construct error, it's an add-on error. We do not add lumium as a tool material

**Closed as completed by KnightMiner** 2020-08-07 14:34 UTC
Labels: Mod interaction
