### ISSUE TITLE
CraftingTable MP-Sync bug

### ISSUE THREAD

**Issue by yaroslav4167** [SlimeKnights/TinkersConstruct#3757] opened 2019-02-09 18:21 UTC
**Issue description:**
If 2 players use craftingTable - result slot don't synced :c
Reproduce: [https://youtu.be/cV0O8n70V8Q](https://youtu.be/cV0O8n70V8Q)
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2811
* Mantle: 1.3.3.39
* Tinkers Construct: 1.12.2-2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Can only be reproduced with TConstruct.

**Comment by KnightMiner** [comment] 2019-03-22 01:26
Duplicate of #3714.

**Closed by KnightMiner** 2019-03-22 01:26 UTC
