### ISSUE TITLE
1.16.5 Liquid iron turns to copper when ported into ingot cast or Basin (RESOLVED)

### ISSUE THREAD

**Issue by Steel-Strider** [SlimeKnights/TinkersConstruct#4353] opened 2021-04-14 00:07 UTC
Issue description:
I smelted iron ore in my smeltery but whenever i try to take it out of the smeltery, it turns to copper. it also does this when the liquid iron is taken out of a tank.

Video showing the bug in action:
![Iron to copper 1](https://user-images.githubusercontent.com/65756845/114635394-7d2cdc80-9c79-11eb-99b7-dfc9c5b49d03.png)
![iron to copper 2](https://user-images.githubusercontent.com/65756845/114635398-7ef6a000-9c79-11eb-8079-2ce0bc659cc2.png)

If crashed, link to crash report (use a site such as pastebin):

Versions:

Minecraft: 1.16.5
Forge: 36.1.1
Mantle: 1.6.92
Tinkers Construct: 3.0.2.96
Confirm below that this issue is not covered on the roadmap or "Whats New?"
Not on Either

Can it be reproduced with just Tinkers Construct? If not, list the other mods required to reproduce the issue.
No, ive isolated TC and i even tried adding mods one by one, but i can't even recreate this effect on a singleplayer world with all the mods that this error originally occured with.
![image](https://user-images.githubusercontent.com/65756845/114635242-2a532500-9c79-11eb-947d-e8724029127c.png)
![image](https://user-images.githubusercontent.com/65756845/114635268-38a14100-9c79-11eb-8207-48a4df7b5eb0.png)
![image](https://user-images.githubusercontent.com/65756845/114635300-4a82e400-9c79-11eb-8cb9-cc3c96803b0f.png)
![image](https://user-images.githubusercontent.com/65756845/114635371-700fed80-9c79-11eb-96ce-408867a0edd5.png)
![image](https://user-images.githubusercontent.com/65756845/114635381-7900bf00-9c79-11eb-99cf-79a3fafcc018.png)

this issue was fixed after a server restart; filing here for documentation purposes

**Comment by moon-st0ne** [comment] 2021-04-14 00:11
[this would do it](https://i.imgur.com/igMZC6l.png)

**Comment by mDiyo** [comment] 2021-04-14 00:12
Performant's recipe caching causes casting tables to get stuck globally on the first recipe used. Remove performant or disable the caching function.

**Comment by KnightMiner** [comment] 2021-04-14 00:12
Duplicate of #4283. And failure to use our issue template.

**Closed as completed by KnightMiner** 2021-04-14 00:12 UTC
Labels: Duplicate, Invalid, 1.16
