### ISSUE TITLE
Crash with Latest Tinker's Release

### ISSUE THREAD

**Issue by SacrificialFlame** [SlimeKnights/TinkersConstruct#3808] opened 2019-03-30 21:42 UTC
**Issue description:**
as soon as I start up my custom pack, Tinkers crashes
**If crashed, link to crash report (use a site such as pastebin):**
https://paste.dimdev.org/yejihifavo.mccrash
**Versions:** 
* Minecraft: 1.12.2
* Forge: 14.23.5.2808
* Mantle: 1.12-1.3.3.42
* Tinkers Construct: 1.12.2-2.12.0.133

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment] 2019-03-30 22:02
Duplicate of #3807.

**Closed by KnightMiner** 2019-03-30 22:02 UTC
