### ISSUE TITLE
Tinkers Construct is crashing my game on launch/ how to fix?

### ISSUE THREAD

**Issue by awakings** [SlimeKnights/TinkersConstruct#4506] opened 2021-06-01 11:30 UTC
When I launch minecraft with the Tinkers Construct mod it will crash and say this
Error: java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.12.0.135

**Comment by KnightMiner** [comment] 2021-06-01 15:07
Duplicate of #4441, not our bug.

**Closed as completed by KnightMiner** 2021-06-01 15:07 UTC
Labels: Duplicate, 1.12
