### ISSUE TITLE
Resonant Ender (fixed)

### ISSUE THREAD

**Issue by mchetvorkata** [SlimeKnights/TinkersConstruct#2841] opened 2017-04-12 23:31 UTC
The texture of the resonant ender from Thermal Foundation shows up like this: http://prntscr.com/evrg43

Edit: when you try to pour it into a bucket it doesn't show the flowing animation and doesn't fill up the bucket

**Comment by ArukaAlter** [comment] 2017-04-13 01:11
Is it reproduceable with only Tinkers' in the instance?

**Comment by KnightMiner** [comment] 2017-04-13 04:02
Good chance the error is on TE's side or is a conflict between that and Ender IO's version of the fluid. Try to minimize the mods need to reproduce it, and try the fluid in a few other modded machines to verify it is not just a Tinkers error.

**Comment by bonii-xx** [comment] 2017-04-13 06:18
Looks like the fluid is not correctly defined/registered.

**Comment by mchetvorkata** [comment] 2017-04-13 16:59
The error is not on TE's side its for the whole pack.. there are 2 fluids from Thermal Expansion.. both are Resonant ender howver one has no texture the other work perfectly... for some reason it uses the one that has no texture isntad the other one ;/

**Comment by mchetvorkata** [comment] 2017-04-13 19:07
i don't know how but i got it fixed.. i was messing around with the versions of the mods and ftb utilities and it works now lol

**Comment by KnightMiner** [comment] 2017-04-13 22:52
Sounds like it was never on Tinkers side to begin with, so I'm closing this.

**Closed by KnightMiner** 2017-04-13 22:52 UTC
