### ISSUE TITLE
Crash when rendering plate armor

### ISSUE THREAD

**Issue by LilMudDuck** [SlimeKnights/TinkersConstruct#4771] opened 2022-02-19 00:52 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.66

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

whenever I put a piece of plate armor onto my character, it crashes the game and now I am unable to open my inventory to remove it from my character.

The Error code:

The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class slimeknights.tconstruct.tools.client.PlateArmorModel cannot be cast to class net.minecraft.client.model.HumanoidModel (slimeknights.tconstruct.tools.client.PlateArmorModel is in module tconstruct@3.4.0.34 of loader 'TRANSFORMER' @fb0a08c; net.minecraft.client.model.HumanoidModel is in module minecraft@1.18.1 of loader 'TRANSFORMER' @fb0a08c)
Exit Code: -1

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-19 00:53
Duplicate of #4734 Remove Optifine.

**Closed as completed by ShinyPorygon** 2022-02-19 00:53 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
