### ISSUE TITLE
Mekanism render in Crafting Station

### ISSUE THREAD

**Issue by Magi1053** [SlimeKnights/TinkersConstruct#3155] opened 2017-09-13 16:30 UTC
```
Thread: Client thread
Stacktrace:
    at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:720)
    at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
    at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:170)
    at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:141)
 
-- Ingredient being rendered --
Details:
    Ingredient Mod: Mekanism
    Ingredient Info: 1xtile.MachineBlock3@1 mekanism:MachineBlock3 nbt:{mekData:{}}
Stacktrace:
    at mezz.jei.gui.ingredients.GuiIngredientFast.createRenderIngredientException(GuiIngredientFast.java:370)
    at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:99)
    at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:156)
    at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
    at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1873_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
    at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
    at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at Reflector.callVoid(Reflector.java:529)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1417)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
-- Screen render details --
Details:
    Screen name: slimeknights.tconstruct.tools.common.client.GuiCraftingStation
    Mouse location: Scaled: (240, 132). Absolute: (720, 398)
    Screen size: Scaled: (480, 265). Absolute: (1440, 795). Scale factor of 3
```
Item trying to craft is a MekanismGenerators Advanced Solar Generator in TinkersConstruct Crafting Station
![image](https://user-images.githubusercontent.com/1045179/30388461-70c33f54-9875-11e7-9729-8c02e9dce7e2.png)

**Comment by KnightMiner** [comment] 2017-09-13 18:56
Duplicate of #2776 and many others.

**Closed by KnightMiner** 2017-09-13 18:56 UTC
