### ISSUE TITLE
[1.12] Tools and stencils not rendering with optifine installed

### ISSUE THREAD

**Issue by ElementLiga** [SlimeKnights/TinkersConstruct#3090] opened 2017-08-06 23:50 UTC
Textures and items for tinkers construct straight up dont render and become invisible, they still work though. I sifted through my mods and found out it was optifine causing the problem, but i dont know what.
The optifine version im using is 1.12 HD ultra C4
TC Version: 1.12-2.7.2.15
mantle version: 1.12-1.2.1.18
i can replicate on my client and provide screenshots if needed

**Comment by KnightMiner** [comment] 2017-08-06 23:58
Duplicate of #3008.

**Closed by KnightMiner** 2017-08-06 23:58 UTC
