### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by DishyCorn23** [SlimeKnights/TinkersConstruct#3073] opened 2017-08-02 23:11 UTC
![2017-08-03_09 10 18](https://user-images.githubusercontent.com/30673360/28898916-9f64f4c0-782b-11e7-99ee-043631095b0f.png)

**Comment by KnightMiner** [comment] 2017-08-02 23:43
Duplicate of #3008.

**Closed by KnightMiner** 2017-08-02 23:43 UTC
