### ISSUE TITLE
crashes in the 1.12.2 pack. 

### ISSUE THREAD

**Issue by rednaxman** [SlimeKnights/TinkersConstruct#4000] opened 2020-01-04 22:34 UTC
**Issue description: Tinkers construct has crashed my game, not sure what to do.**

**If crashed, link to crash report (use a site such as pastebin): https://paste.dimdev.org/yosokogibu.mccrash**

**Versions:**
* Minecraft: 1.12.2
* Tinkers Construct: 1.12.2

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

not sure, as havent been able to reproduce it in single player world, however havent been able get access to a multiplayer world where i can reproduce it. other mods are from the 1.12.2 technic pack. ive provided all the info i know, and im sorry for bothering everyone.

**Comment by bonii-xx** [comment] 2020-01-05 11:20
Don't worry, you're not bothering anyone ;)

It looks like a rendering crash from the AOE toolbreak overlay (the one that shows you which blocks will be broken by a hammer etc.). From the crash there is no way that this was caused by simply Tinikers. Our code isn't able to produce such a crash, as far as I can see with the data.

It's most likely either some other mod who does things with rendering or, and this is what my bet is on, a race condition during some asynchronous rendering operation. If it simply was another mod modifying rendering it'd crash every time.

I doubt there's any chance of catching/fixing this, without it happening more often, and even then it's probably out of Tinkers' control. Gonna close this for now since there's nothing we can do.
Reopen if it happens again.

**Closed as completed by bonii-xx** 2020-01-05 11:20 UTC
Labels: Can't reproduce
