### ISSUE TITLE
Flashing pixel between 2 textures on axe

### ISSUE THREAD

**Issue by rockett1** [SlimeKnights/TinkersConstruct#3694] opened 2018-12-06 09:31 UTC
**Issue description:**
When moving this annoying square flashes on an axe. This mp4 shows what i'm trying to explain: https://i.gyazo.com/8a6368bf488f3f968eeeeb7d856eb0f3.mp4
It's where the rod joins the axe head at the top and the 2 textures keep overlapping whats visible to the user.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.39
* Tinkers Construct: 2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Just tinkers

**Comment by YaibaToKen** [comment] 2018-12-06 09:58
I could be wrong but... I think that's a problem of z-fighting between the two textures due to both trying to occupy the same surface.

**Comment by SweetSugarSugar** [comment] 2018-12-22 08:04
Sort of a duplicate of #2099

As Yaiba said, issue is z-fighting.

**Comment by KnightMiner** [comment] 2019-01-02 01:33
Yea, unfortunately vanilla rendering goes back and forth about whether overlapping quads on items cause Z fighting. On vanilla items its typically not an issue as most items are single layer, but some multi-layer items have had this issue on and off.

I know with our items specifically, sometimes the transforms are a bit difficult to maintain things lining up, so this will likely be difficult to fix again.

**Comment by KnightMiner** [comment] 2021-06-15 17:42
1.16 seems to fix this in most cases. Still a couple left to catch, but going to close this as this issue is targeted to 1.12

**Closed by KnightMiner** 2021-06-15 17:42 UTC
Labels: 1.12, Bug, Can't Fix
