### ISSUE TITLE
Performance issue on tconstruct.library.utils.ListUtil.getListFrom()

### ISSUE THREAD

**Issue by runescapejon** [SlimeKnights/TinkersConstruct#3817] opened 2019-04-08 02:01 UTC
**Issue description:**
I am having a bit of performance issue. I was wondering if this can fix?
![8bff182bdd919d9c4de3b6c664496b00](https://user-images.githubusercontent.com/10858509/55694134-9c088200-5980-11e9-8c0a-82a2f63e09a0.png)

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:  1.12.2
* Forge:  14.23.5.2815
* Mantle: 1.12-1.3.3.49
* Tinkers Construct:  1.12.2-2.12.0.135.jar

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment] 2019-04-08 02:47
What do you have sitting in that smeltery? Looks like its constantly trying to melt items without being able to do so. I will look into list utils to see if a more efficient way to make the list exists though.

**Comment by runescapejon** [comment] 2019-04-08 03:37
I'm not sure because at the time when the server was lagging i had few players online at the time and didn't see what they was doing.

**Comment by bonii-xx** [comment] 2019-04-09 16:51
The more important question is: how big was the smeltery.

**Comment by runescapejon** [comment] 2019-04-09 18:48
at the time of the performance degrading the highest was 8x8

**Comment by bonii-xx** [comment] 2019-04-10 16:55
And how high?

**Comment by runescapejon** [comment] 2019-04-10 16:56
oh i meant 8 blocks length and 8 blocks high

**Comment by KnightMiner** [comment] 2021-06-15 17:35
This is fixed on 1.16 as the logic behind melting has been rewritten and greatly optimized. Unlikely to change on 1.12 as I could not find any way to prevent performance issues there, I am still convinced the problem is not the method but the fact the method is being run so much.

**Closed by KnightMiner** 2021-06-15 17:35 UTC
Labels: 1.12
