### ISSUE TITLE
Using JEI move items results in scattered items in the crafting grid

### ISSUE THREAD

**Issue by starryfae** [SlimeKnights/TinkersConstruct#5232] opened 2024-05-30 04:54 UTC
### Minecraft Version

1.19.2

### Forge Version

43.3.13

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39.jar

### Describe your issue

Using the "move items" feature in JEI with tinker's recipes causes them to scatter the items on the grid.
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/73800917/e0cc02cf-117c-4d0b-984e-aaaebb84fc02)

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/73800917/1c257233-fee4-480f-82d1-5c920f2b6eee)

Tested with just JEI (jei-1.19.2-forge-11.6.0.1019.jar) and Tinker's Construct

### Other mods

jei-1.19.2-forge-11.6.0.1019.jar

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment] 2024-05-30 14:11
Need more information as I have not been experiencing this. Can you give screenshots of the full UI so I can see the sort of side inventory you have along with the tabs?

Also, do what the issue template says and tet reproducing with just tinkers and JEI. I could see other mods (notably REI) causing this

**Comment by starryfae** [comment] 2024-05-30 16:24
Sure thing. I've also attached debug.log and latest.log to show loaded mods. I'm absolutely not using any other mod to test this. I could potentially provide a video as well.

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/73800917/c4c380c7-b582-4922-a49e-0fbaca8a8ad8)


https://github.com/SlimeKnights/TinkersConstruct/assets/73800917/4a856c2c-45ac-49ef-9c23-9748b6662002

[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/15502897/debug.log)
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/15502898/latest.log)


Edit: Tested on both Curseforge and Prismlauncher and replicated the issue on both

Edit 2: Behavior happens on both vanilla crafting table and Tinker's crafting station

**Comment by KnightMiner** [comment] 2024-05-30 17:34
> Edit 2: Behavior happens on both vanilla crafting table and Tinker's crafting station

With all recipes or just this specific recipe?

> Also, do what the issue template says and try reproducing with just tinkers and JEI.

**Comment by starryfae** [comment] 2024-05-30 17:44
> > Also, do what the issue template says and try reproducing with just tinkers and JEI.

I'm not sure why you've quoted this again?

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/73800917/badecfb9-804f-450e-a2bc-b392ea4cb81d)


> > With all recipes or just this specific recipe?

So far, the crafting station recipe, and the tinker station recipe.

**Comment by KnightMiner** [comment] 2024-05-30 18:13
> So far, the crafting station recipe, and the tinker station recipe.

Does it happen with the tinkers anvil recipe and the seared drain/seared chute recipe (the one using blocks, not brick items). If so that narrows down the problem.

**Comment by starryfae** [comment] 2024-05-30 19:23
Behavior happens for Tinker's Anvil recipe,

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/73800917/22aa66fe-9d14-46cf-be06-71069a5850b5)

Seared Drain:

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/73800917/bc566b19-8a96-40eb-a4c5-3435019572d8)

Seared chute: 

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/73800917/19f38bc8-2739-4483-8512-08dcfb4535b8)

**Comment by starryfae** [comment] 2024-05-30 19:46
It's consistently putting items in the same (incorrect) place every time

**Comment by KnightMiner** [comment] 2024-09-15 06:20
I don't believe this issue is actually a Tinkers issue but a JEI one. Those recipes are normal recipe extensions in JEI, and they display correctly in JEI, so its a JEI bug if the transfer for that does not work (as JEI controls their transfer)

Please crosspost the issue to JEI's issue tracker.

**Comment by mezz** [comment] 2024-09-17 03:01
I tried it out and this looks like a JEI bug on 1.19.2.
These recipes use Mantle's `ShapedRetexturedRecipe`, which creates a focus link between one of the inputs and the output. The creation of the recipe link seems to cause JEI to incorrectly change the order of the slots. I'll look into a solution.

**Comment by mezz** [comment] 2024-09-18 02:43
I have pushed a fix for this in JEI for 1.19.2
![2024-09-18_11 42 38](https://github.com/user-attachments/assets/83888f6d-c110-47f5-ae74-4e4b1c611a83)
![2024-09-18_11 42 47](https://github.com/user-attachments/assets/bd87ce60-86e8-41c0-8228-0c8705cf84a7)

**Comment by mezz** [comment] 2024-09-18 02:57
I have pushed a fix for this in 1.20.1 and 1.21.1 as well.

**Comment by KnightMiner** [comment] 2024-09-18 05:09
Thanks for looking into this. Since its fixed in JEI I'll close this issue.

**Closed as completed by KnightMiner** 2024-09-18 05:09 UTC
Labels: Bug, Resolved, Mod interaction, Other mod, 1.19
