### ISSUE TITLE
No knockback on players

### ISSUE THREAD

**Issue by Wiral2** [SlimeKnights/TinkersConstruct#3923] opened 2019-08-11 05:38 UTC
Basically the problem I'm having is that all weapons from Tinker construct have no knockback on players, but seem to work normally on mobs. Is there a fix for this? I've tested with only Mantle and Tinker Construct and the problem still presists.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2837
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

**Comment by KnightMiner** [comment] 2019-08-11 22:23
Duplicate of #3480

**Closed by KnightMiner** 2019-08-11 22:23 UTC

**Comment by Wiral2** [comment] 2019-08-12 06:30
Was there ever a fix?

**Comment by KnightMiner** [comment] 2019-08-12 11:45
It's the same root cause. The previous issues was fixed but the fix is not yet released.

**Comment by Wiral2** [comment] 2019-08-18 23:07
Is there an estimated date for the next update and it will it be for 1.12.2?
