### ISSUE TITLE
lost textures

### ISSUE THREAD

**Issue by thatguyyouknow** [SlimeKnights/TinkersConstruct#3047] opened 2017-07-26 15:53 UTC
a bunch of the textures were lost when i downloaded the mod

**Comment by KnightMiner** [comment] 2017-07-26 16:09
You failed to provide any information such as screenshots or mod versions, but given the recent trends I would assume you are using 1.12 with Optifine, making this the eighth duplicate of #3008. Update Optifine and learn to properly report issues

**Closed by KnightMiner** 2017-07-26 16:09 UTC
