### ISSUE TITLE
everytime i try to create a world it crashes at the end, mid "saving world"

### ISSUE THREAD

**Issue by WorldNommer** [SlimeKnights/TinkersConstruct#4638] opened 2021-10-07 04:09 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

The game crashed whilst unexpected error
Error: java.lang.AbstractMethodError: Method slimeknights/tconstruct/library/recipe/casting/ItemCastingRecipe$Basin.getType()Lnet/minecraft/item/crafting/IRecipeType; is abstract
Exit Code: -1

### Reproduced with only Tinkers' Construct?

No

### Other mods required

botania, curios, jei, journeyman and patchouli 

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment] 2021-10-07 04:26
Duplicate of #4631, update Tinkers to fix.

**Closed as completed by KnightMiner** 2021-10-07 04:26 UTC
Labels: Duplicate, 1.16, Update
