### ISSUE TITLE
Duplication bug using Crafting Station

### ISSUE THREAD

**Issue by runescapejon** [SlimeKnights/TinkersConstruct#3784] opened 2019-03-09 20:43 UTC
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2814
* Mantle: 1.12-1.3.3.42
* Tinkers Construct:  1.12.2-2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
My issue is a duplication bug using just the Crafting Station you can dupe any craftable items. You would need to step up a server *(on my testing server i was only using forge not sponge)* and place down a crafting station 1 player right click the station and setup the recipe in the crafting station while the player 2 then right click the station. Next player 2 recreate at least one of the item in the crafting box. Then both players can take out items out of the output crafting station. Here a demonstration GIF: https://gyazo.com/98048f21770b58ecb1199d4a8b6bfc65

**Comment by KnightMiner** [comment] 2019-03-09 20:47
Duplicate of #3714, though I will say the GIF is a helpful addition, would you mind commenting that link on the other issue?

**Closed by KnightMiner** 2019-03-09 20:47 UTC
