### ISSUE TITLE
Crash when using tinkers weapons in mob farm.

### ISSUE THREAD

**Issue by Sulferix** [SlimeKnights/TinkersConstruct#3783] opened 2019-03-09 18:41 UTC
incredibly annoying crash. only happens when im using my ender io powered spawner mob farm for tool leveling.
https://pastebin.com/aBw4yZW2

**Versions:**
* Minecraft: 1.12.2
* Forge: 2768
* Mantle: 
Mantle-1.12-1.3.3.39
* Tinkers Construct: 
TConstruct-1.12.2-2.12.0.115

other mods required to my knowledge, havent tested with vanilla mod farms.
EDIT:
cuplrit has been discovered. crash is a particle effect conflict with the mod DynamicSurroundings, specific to the nether. simply use tinkers tools in the nether to attack mobs. eventually the game will randomly crash. 

SPECIAL THANKS TO Z-TUNIC FOR PUTTING IN THE TIME TO PINPOINT THE ISSUE

**Comment by KnightMiner** [comment] 2019-03-09 18:59
Reproduce this with fewer mods, you have at least 30 core mods and the crash is specifically caused by something breaking the skylight getter

**Comment by Sulferix** [comment] 2019-03-10 03:40
i only get crashes in the nether at my mob farm specifically. i can train mobs all day anywhere else. i think its just doing many things at once and thats causing it....

**Comment by KnightMiner** [comment] 2019-03-10 04:16
What is holding the sword in your mob farm? If the crash is only happening there, its possible some way they are calling the sword methods is the cause

**Comment by Sulferix** [comment] 2019-03-10 09:46
its a manual farm, so no different than going out and killing mobs normally except the increased volume in a small area....

**Comment by KnightMiner** [comment] 2019-03-10 14:30
If that's the case, the only thing left that we can do is figure out which mod causes it. Unless you can figure out which mod causes this there is nothing we can do.

**Comment by bonii-xx** [comment] 2019-03-15 14:56
Considering it does this when spawning particles I'd start with the clientside mods.

**Comment by Z-Tunic** [comment] 2019-04-16 07:02
An update... I narrowed it down to these mods here crash after crash.

Minecraft: 1.12.2
Forge: 14.23.5.2824

Mods: 4
DynamicSurroundings-1.12.2-3.5.4.3
Mantle-1.12-1.3.3.49
OreLib-1.12.2-3.5.2.2
TConstruct-1.12.2-2.12.0.135

Crash Report:
https://pastebin.com/8RneByWZ

This was tough to pin down since the crash is random and sometimes it may not even occur at all. What happens is that while attacking a mob in the nether with a Tinker's Tool, the game may crash and it's a type of crash that randomly occurs so this was quite a task to pin down what mods were causing the problem.

For attempting to figure out the crash... I've made a redstone clock with a command block '/effect @e[type=!player] minecraft:instant_damage 1 10' so it gives entities the instant_damage potion effect besides the player. This heals undead mobs so the mobs that I kill are a bunch of zombie pigmen in a 3x3 block pit while using a Tinker's Scythe due to it's AOE. I made the scythe unbreakable just so I don't have to stop & repair the scythe thanks to Tinker's Tool Leveling's creative modifiers and it carries over if Tinker's Tool Leveling was removed.

I gave myself a high level Haste effect to bypass the attack cooldown and to not starve I gave myself a high level Saturation effect . What I had on my scythe exactly is all Cobalt Parts, Fiery, Diamond, Emerald, Haste, Necrotic, Unbreakable, and Sharp. Once everything was set, I went ahead and begun slaughtering the zombie pigmen.

Since the scythe has AOE range, you can score a bunch of hits on them while the command block heals them and if DynamicSurroundings is installed... critical hit words will appear. Now in due time while may take a while... the game will crash and you'll get what's shown in the crash report.

What really puzzles me is that it points towards 'Tinker's Construct' with the 'ParticleEffect crash in the report. I'll open an issue on DynamicSurrounding's side to see if anything comes up.

**Comment by bonii-xx** [comment] 2019-04-28 19:17
I wonder if there's a conflict between dynamic surrounding spawning particles and TiC spawning its own. Needs debugging into MC itself I guess.
Also that's one hell of a bug report, gj 👍

**Comment by Z-Tunic** [comment] 2019-06-10 06:38
Just checking up on how this issue is doing. And yea... the crash kept occurring so I had to try a way to 'force-crash' it and then narrow down the mods being used after getting a suitable setup. Otherwise I would have to rely on it crashing randomly while attacking mobs in the nether with the tools.

**Comment by Sulferix** [comment] 2019-06-15 21:19
wow great work narrowing it down. sorry i couldnt do the testing myself, i just dont have the time or the patience. great work

**Comment by Z-Tunic** [comment] 2019-06-26 23:56
I see that there's a new release, is this bug fixed by any chance or is it on Dynamic Surroundings side?

**Comment by Z-Tunic** [comment] 2019-10-06 00:37
The Dev of Dynamic Surroundings responded to the report about the crash.

*"Not Dynamic Surroundings. For what it is worth I sometimes got this crash with my own particles and had to add defensive code."*

So... is it a vanilla bug then? In a private pack with quite a number of mods added, I've removed DS just to see if I would get the same crash to occur and it never occurred.

**Comment by bonii-xx** [comment] 2019-10-14 18:38
Quite possible. From the crashlogs and the stuff I know we do to spawn mobs I'm not aware of any other cause than coremods or forge/vanilla bugs. Which we can't determine because it's not reproducible/debuggable :(

**Comment by Z-Tunic** [comment] 2019-10-14 20:22
I wonder if this could be of any help, even though it's a theory. From what the DS Dev said after mentioning the defensive code...

*"I never root caused it. In my experiences for some reason the extended data for a chunk was not initialized, almost always at startup. My theory is that it is some sort of race condition between client side operational code and when the chunk data is fully available on the client. I am not sure how Tinker's does it's particle effects, but for Dynamic Surroundings they are triggered purely client side. (Sometimes server side code sends a message to the client to spawn particles.)"*

Not sure if that will help with finding it.

**Comment by bonii-xx** [comment] 2019-10-15 18:44
Yes, we're doing the same. Particles are clientside. I wonder if it's possible to check for that race condition... to prevent it. Hrm.

**Comment by zane49er2** [comment] 2019-10-20 23:35
I am having this crash when the mob in question is armoured, and I use a piercing weapon with modifiers. It is not required that I am in the nether, or even that I have dynamic surroundings installed. There are other coremods though. If possible, could TConstruct add configs for particles? Turning off the particles seems like a potential fix.

**Comment by KnightMiner** [comment] 2019-10-21 01:22
@zane49er2 the crash you are describing sounds very different, can you provide a crash log to verify its the same issue?

**Comment by zane49er2** [comment] 2019-10-23 21:01
https://pastebin.com/DLsK7Swe is the version without dynamic surroundings. There are others but I have to look through them. This pack is very chaotic and recently was changed drastically, so testing things in its current state is near impossible, unfortunately...

This log is more different from the ones I've seen connected to this issue, actually. The other ones I've read have had world or unknown errors, this one says entity...

**Comment by bonii-xx** [comment] 2019-10-24 07:32
Yup, that's a different crash. I've seen it before too.. think there should be an issue around somewhere with the same crash.

**Comment by SonicX8000** [comment] 2019-11-07 01:25
For a work around until it can be fixed... by any chance there could be a config option to disable the damage particles that tinker's uses aka the fiery hearts from the fiery modifier, chain-like hearts when using bolts/rapiers, cactus hearts from the spiky trait, blood hearts from the sharp trait, electric hearts from the voltaic trait?

While it's not the best option but until the cause can be found... can't really attack mobs in the nether since it's a gamble whether or not the game crashes. Then again would it still crash even with those particles disabled? Hmm...

**Comment by SonicX8000** [comment] 2020-02-27 17:25
Well... got back to messing with this again and... there's a way around this crash. To quote my post on DS side a few days ago...

> Got back to testing this... I think I MAY of found the source of the crashing although I'm still testing this out currently in a test world so this post may change. Anyway...
> 
> Minecraft: 1.12.2
> Forge: 14.23.5.2847
> 
> Mods: 5
> DynamicSurroundings-1.12.2-3.6.0.2
> jei_1.12.2-4.15.0.291
> Mantle-1.12-1.3.3.55
> OreLib-1.12.2-3.6.0.1
> TConstruct-1.12.2-2.13.0.171
> 
> If you set this config option under the 'Profiles' section to 'true' in 'config/dsurround/dsurround.cfg'...
> 
>     # Disable weather effects in the Nether
>     B:"No Nether Weather"=true
> 
> ...no crash seems to occur when using Tinker Tools that spawn custom particles in the Nether. Been using a Tinker's Scythe with the 'Fiery' modifier in the Nether on some Zombie Pigman and that modifier spawns a custom fiery heart particle when damaging a mob. 30+ Minutes so far and no crash yet.
> 
> Now I'm going to set it back to 'false' and do another test. Crashed in about 20 seconds... reloaded, crashed in about 5 seconds, reloaded... crashed in about 1 minute and 22 seconds... reload, crashed in about 6 seconds.
> 
> Setting it back to 'true'... did another go... 20 Minutes in... no crash. Decided to stop at that point since that was quite a number of left-clicks being done with scything up the Zombie Pigman.
> 
> The only thing that I know of for that option is that it spawns red dust particles in the nether if the weather is rainy/thunder. Netherack Blocks also emit smoky particles when it's rain/thunder. Is it possible that something related to that option is conflicting? Or is Tinkers' Custom particles not liking what that option does to the Nether or something?
> 
> That's the only option that was changed. Everything else were the default options.

-----

Still so far... no crashes. I've been using a Rapier in the Nether which uses chain-like hearts for it's damage particles. Bolts as well since those also use chain-like hearts for the damage particles. No Nether Weather is still set to 'true'.

Should it possibility occur. I'll update this post about it.

**Comment by bonii-xx** [comment] 2020-02-27 18:24
Have a ❤️

**Comment by r4m0n** [comment] 2020-03-15 19:00
Tried "No Nether Weather", seems to help a bit, but it still occasionally crashes. [Here's a dump if it helps](https://paste.dimdev.org/ucupojofiq.mccrash), but there's probably too many mods to find anything useful.

I'd suggest adding some defensive code to the mod like DS did, it's just skipping the particles if it would get that null-ref.

**Comment by bonii-xx** [comment] 2020-03-16 10:23
Where?

**Comment by r4m0n** [comment] 2020-03-16 11:35
Where what?

Where I was? Nether. Had a couple crashes like that before coming here and finding this possible workaround, pretty much one after the other. Then tried the fix and it seemed to work, but I had a crash after a few kills (10~20). Didn't save the log, so I tried again. This time it worked longer, but when I was wrapping things up and getting ready to get back to the overworld, it crashed again, with the log above. All crashes were with my portal nearby, if that counts for anything.

**Comment by SonicX8000** [comment] 2020-03-16 11:57
@r4m0n
That's strange. I have quite a number of mods added and I haven't encountered a crash with that config option changed for Dynamic Surroundings although there are some mods you have installed that I don't have installed.

If you can, could you try to see if you can get the crash to occur again but without Dynamic Surroundings installed? If you cannot test that currently... mind DMing me your 'mods' folder so I can try testing, if possible?

**Comment by r4m0n** [comment] 2020-03-16 12:01
I'm using [this modpack](https://www.curseforge.com/minecraft/modpacks/minecraft-eternal). I can give it a try without DS, but the crash is rare enough it might just not trigger that frequently. I'm using a crossbow with a bolt loaded with sharpness, so particle effects happen pretty frequently.

**Comment by bonii-xx** [comment] 2020-03-16 12:01
> Where what?

Where should we put the defensive code/null checks to prevent the issue from happening. Or rather, what is the thing that needs to be checked at this point?

**Comment by bonii-xx** [comment] 2020-03-16 12:06
> Where I was? Nether. Had a couple crashes like that before coming here and finding this possible workaround, pretty much one after the other. Then tried the fix and it seemed to work, but I had a crash after a few kills (10~20). Didn't save the log, so I tried again. This time it worked longer, but when I was wrapping things up and getting ready to get back to the overworld, it crashed again, with the log above. All crashes were with my portal nearby, if that counts for anything.

The crash shows that it has to do with the sunlight present in the world (which the nether has none.. hence the crash). The portal does spawn a lot of particles too, I wonder if there's some maximum # of particles that affects this..

**Comment by r4m0n** [comment] 2020-03-16 12:06
> > Where what?
> 
> Where should we put the defensive code/null checks to prevent the issue from happening. Or rather, what is the thing that needs to be checked at this point?

Where to put the code is easier to say, I'd say [where it's crashing](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/shared/client/ParticleEffect.java#L74). Now, what to check would need some extra digging into MC's source. A quick, ugly solution would be to just add a try/catch around that line, and ignore any errors (I mean, we're rendering particles, nobody is going to die if one doesn't).

**Comment by bonii-xx** [comment] 2020-03-16 12:18
But it's crashing in vanilla, and I'm not going to coremod that. A try/catch might be a feasible solution, but just a symptomatic fix. The call itself is just a passthrough, the method is being called from within vanilla (it's just a particle). Vanilla itself quite literally has a check that's supposed to prevent this from happening. It also doesn't happen with only vanilla, the check clearly works there.

I'm not really fond of catching things that shouldn't happen in the first place.

**Comment by r4m0n** [comment] 2020-03-16 12:39
A few minutes (15?) running around my portal in the Nether with DS disabled didn't produce any crashes. Can't say for certain without more testing, but it does seems likely that DS is doing something that's facilitating this crash at least.

**Comment by SonicX8000** [comment] 2020-03-16 13:12
@r4m0n 
Can't seem to reproduce the crash. You sure "No Nether Weather" is set to 'true' in the DS config?

What I'm doing is using a scythe with the Traits 'Sharp', 'Prickly' & the modifier 'Fiery'. These spawn custom particles when you attack mobs with these. Rapiers/Bolts also spawn custom particles as well as the 'Shocking' Trait.

I've been using a command block to heal the Zombie Pigmen with the Instant Damage Potion that excludes the player as I attack them with the scythe. They are in a 2x2x2 pit so they can't escape and attack me. Since the scythe has a AOE attack range I can multi-hit mobs which in turn spawns those particles commonly.

The moment I changed "No Nether Weather" to 'false'... and doing the above again... it started to crash.

**Comment by KnightMiner** [comment] 2021-06-15 17:37
Going to close this as it looks like there is a solution to resolve the conflict, and a fix from our side requires a significant rewrite of the particles (too big to do for 1.12)

**Closed by KnightMiner** 2021-06-15 17:37 UTC
Labels: 1.12, 3rd party mod interaction, Not enough information
