### ISSUE TITLE
slimelyra makes minecraft crash

### ISSUE THREAD

**Issue by MrGeomancer** [SlimeKnights/TinkersConstruct#4806] opened 2022-03-20 14:56 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

Wearing slimelytras make crash. 
1 crash - i weared elytras 
2 crash i spawned with elytras on, open enventoey>crash
3 crash try to wear again

### Crash Report

https://dropmefiles.com/3BWCS

### Other mods

https://imgur.com/a/1Sq3fCD

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine, Other (specify under other mods)

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment] 2022-03-20 14:58
Duplicate of #4734 Remove optifine.

**Closed as completed by ShinyPorygon** 2022-03-20 14:58 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
