### ISSUE TITLE
Mending Moss modifier not working

### ISSUE THREAD

**Issue by raquelmaree** [SlimeKnights/TinkersConstruct#3554] opened 2018-06-23 03:49 UTC
Hi,
I've been at work and had my computer open with my partner and not once has my pickaxe gained durability with the mending moss. He wasn't sure if I needed to be in the sun for it to generate but it didn't. It's been in my hot bar the entire time so not sure why this is not working. 

I'm currently running tinkers construct through FTB Revelation and playing version 1.12.2 - 2.10.1.84.jar

Thanks!

**Comment by KnightMiner** [comment] 2018-06-23 04:01
Did you collect XP while holding it? It consumes XP to repair, as it said in the description when applying it.

**Comment by Elytrus** [comment] 2018-06-29 07:43
This is just a suggestion, but I feel that what this issue shows is that the Mending Moss modifier is not very intuitive in how it truly functions.

From what I've seen playing with it (in FTB Revelations) is that it 'stores' exp when you collect it (but only up to a certain point, at which point it stops storing exp) and uses it to slowly regenerate the tool's durability.

As opposed to the enchantment which just repairs the tool the instant you collect exp and does not allow you to actually gain levels until it's fully repaired

**Comment by bonii-xx** [comment] 2018-06-29 11:57
If you read the modifier description, it will tell you exactly that. You can check the stored XP in a tool station.

**Comment by TheQuadShot** [comment] 2018-06-30 00:47
Is this changed behaviour? I seem to remember that it was sunlight that "healed" the tool. ie Holding the tool while in the sun it would slowly mend said tool.

**Comment by TherminatorX** [comment] 2018-06-30 02:31
This is very much changed behavior

**Comment by TheSnowyChickens** [comment] 2018-07-01 01:57
Hello,
I have the same bug on a server.
![2018-07-01_03 55 22](https://user-images.githubusercontent.com/29357962/42130343-cca25f92-7ce2-11e8-9b01-60f52c2807f6.png)

**Comment by bonii-xx** [comment] 2018-07-01 13:36
Go ahead. Read the modifier page in the book and see if that solves your issue.

**Comment by TheSnowyChickens** [comment] 2018-07-01 15:02
![tinkers](https://user-images.githubusercontent.com/29357962/42135800-813fe77c-7d50-11e8-863b-9bcd83cf3548.png)

**Comment by bonii-xx** [comment] 2018-07-01 16:39
Does the EXP go down when you hold it in your hand for a while? Does it happen with tools made from only base TiC materials/without other mods?

**Comment by TheSnowyChickens** [comment] 2018-07-01 17:35
With a full stone pickaxe, mending moss work good.
![2018-07-01_19 30 52](https://user-images.githubusercontent.com/29357962/42137016-5815a7c8-7d65-11e8-9a20-f659b5885640.png)

And no, the xp dont go down, if I hold it in my hand. (Pickaxe with supremium/paper/redined obsidian)

The resources come from Mystical Agriculture and Hardcore Ore

**Comment by bonii-xx** [comment] 2018-07-02 16:50
Looks like on of their traits is interfering with it then.

**Comment by TheSnowyChickens** [comment] 2018-07-02 17:33
I think its Hardcore ore, but im not sure.

**Comment by bonii-xx** [comment] 2018-07-03 18:37
I find it especially weird because it seems to only happens when a specific material is present.. which implies that it's another trait doing stuff with the repair callback. I kinda doubt it's intended behaviour.

**Comment by KnightMiner** [comment] 2019-03-22 01:26
Any update on this issue @TheSnowyChickens? Did you find which material caused the issue, and contact the related mod author?

**Comment by TheSnowyChickens** [comment] 2019-03-22 13:08
I think we can't calculate with a fix from Hardcore ore, because the mod is dead.
(no updates since March, 5 2018 + no reaction on any issues on the curse issue tracker)

And I re-build the modpack in which I tested this, so I don't use Hardcore ore anymore. Sry

**Comment by bonii-xx** [comment] 2019-03-22 14:16
Thanks for the info, then we'll close this issue.

**Closed by bonii-xx** 2019-03-22 14:16 UTC
Labels: 3rd party mod interaction
