### ISSUE TITLE
[1.16.5] Glass in the smeltery outputs into wrong item

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#4303] opened 2021-04-04 14:25 UTC
**Issue description:**
Outputting glass into a basin from the smeltery cools into seared stone instead of clear glass. Additionally, panes in a casting table cool into blank gold casts.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.76

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Confirmed

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by PrincessOfEvil** [comment] 2021-04-04 14:28
Do you have Performant installed? If you do, it's causing this issue.

**Comment by KnightMiner** [comment] 2021-04-04 14:28
Duplicate of #4283, there is a reason I pinned the issue. Remove performant.

**Closed as completed by KnightMiner** 2021-04-04 14:28 UTC
Labels: Bug, Not enough information, Mod interaction, 1.16
