### ISSUE TITLE
Liquids won't show themselves when pouring into a casting table or anywhere else.

### ISSUE THREAD

**Issue by rollandcarasi** [SlimeKnights/TinkersConstruct#4769] opened 2022-02-18 20:46 UTC
### Minecraft Version

1.18.1

### Forge Version

37.0.95

### Mantle Version

1.18.1 1.8.31

### Tinkers' Construct Version

1.18.1-3.4.0.34

### Describe your issue

So when i press RMB on the canal to pour it out into a shape or something it wont show the animation nor in the Smeltery room.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

![image](https://user-images.githubusercontent.com/99193425/154758814-08f2789a-69b7-4829-86a9-fc47c8b8dd82.png)
![image](https://user-images.githubusercontent.com/99193425/154758838-ed26fa5f-e109-4dc0-afbf-576f4edcc62c.png)

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment] 2022-02-18 20:47
I suspect this is a duplicate of #4745. Please test to confirm.

**Comment by rollandcarasi** [comment] 2022-02-18 20:51
Yes, that is the exact same problem as i have.

**Comment by KnightMiner** [comment] 2022-02-18 21:10
In that case, closing as a duplicate. The workaround for now is to not use fabulous graphics.

**Closed as completed by KnightMiner** 2022-02-18 21:10 UTC
Labels: Bug, Duplicate, 1.18
