### ISSUE TITLE
The game crashes after putting on a character of any set of armor

### ISSUE THREAD

**Issue by Maximillian537** [SlimeKnights/TinkersConstruct#4793] opened 2022-03-07 18:34 UTC
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

When you try to insert an item of armor into the slots of the head, body, legs and shoes, the game crashes. The error was noticed in the sets of the Traveler, the Plate set, the Slime set (the exception is Pants: you can put them on the character and the game does not fly out and like slime shoes), the game also crashes after dressing the Slime Elitra.

### Crash Report

https://paste.ee/d/A4dlx

### Other mods

Optifine HD U H4 version 1.0.0

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Optifine

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment] 2022-03-07 18:37
Duplicate of #4734 

Please search the issue tracker as it would save time and prevent duplicate issues. 

Remove optifine

**Closed as completed by ShinyPorygon** 2022-03-07 18:37 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18

**Comment by KnightMiner** [comment] 2022-03-07 18:41
Also, for the future if you answer "yes" to tried reproducing with just Tinkers, answer whether the issue still happens with just tinkers as part of "other mods"
