### ISSUE TITLE
Tinkers Hammer Glitch

### ISSUE THREAD

**Issue by FR057F1R3** [SlimeKnights/TinkersConstruct#4513] opened 2021-06-04 18:51 UTC
**All blocks vanish with nothing but void visible when using the hammer -Only while trying to break blocks, all blocks reappear after you either break the blocks or stop mining-, disabled shaders and texture pack to be sure those were not the cause. :**

**Did not cause a crash:**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.0
* Mantle: 1.6.88
* Tinkers Construct: 1.16.5-3.0.2.78

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.
This issue is replicated with just Tinkers and Mantle.**

Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by ShinyPorygon** [comment] 2021-06-04 18:52
Did you remove optifine as well

**Comment by PrincessOfEvil** [comment] 2021-06-04 18:54
Looks like a duplicate of #4316 to me.

**Comment by KnightMiner** [comment] 2021-06-15 16:53
Closing for lack of information, going to assume its an optifine bug

**Closed as completed by KnightMiner** 2021-06-15 16:53 UTC
Labels: Bug, Performance Enhancers/Optifine, Not enough information, 1.16
