### ISSUE TITLE
[1.12.2] Dupe

### ISSUE THREAD

**Issue by LoopRich161** [SlimeKnights/TinkersConstruct#4188] opened 2020-09-06 12:46 UTC
**Issue description:** https://youtu.be/L2WdvM9foPQ?t=24
Thus, you can dupe any object that is being laid out / assembled.

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2 - 14.23.5.2854
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.13.0.183.jar
--

**Comment by TherminatorX** [comment] 2020-09-06 14:15
Versions are faked, this bug has been patched for years. Hoppers are no longer able to extract from Crafting Stations.

**Comment by KnightMiner** [comment] 2020-09-06 18:27
Yeah, I have been unable to reproduce this bug for years. Where are you downloading your mod? Anywhere besides CurseForge is the wrong place as we only make the curseforge builds

**Comment by BartolomeoDR** [comment] 2020-09-10 11:57
This bug can reproduce on SpongeForge.    =)

**Comment by KnightMiner** [comment] 2020-09-10 14:17
Why is spongeforge changing the extraction behavior of tile entities? Make an issue with them and tell them use the Forge system for the hopper extraction, there is a reason we coded it to not allow extraction.

**Comment by KnightMiner** [comment] 2021-06-15 17:12
Closing as we are done with 1.12 support, and this is an issue with SpongeForge in any case. If you still have this issue, yell at SpongeForge more for bypassing Forge systems.

**Closed as completed by KnightMiner** 2021-06-15 17:12 UTC
Labels: Custom Server, Can't reproduce, Can't Fix, 1.12
