### ISSUE TITLE
Books crash on certain pages when smeltery module is disabled

### ISSUE THREAD

**Issue by adudney** [SlimeKnights/TinkersConstruct#1293] opened 2015-01-02 05:51 UTC
Materials and You V1: (Around page 9)
http://pastebin.com/3SvQSrsW

Mighty Smelting: (Around page 13)
http://pastebin.com/EKGxm8zg

Materials and You V2 does not crash luckily, so that one is completely usable.
This also has a side effect of making the modifiers for armor completely unknown, as those pages can't be navigated to.

Modlist:
Forge 10.13.2.1277
CodeChickenCore-1.7.10-1.0.4.29-universal
Mantle-1.7.10-0.3.2
NotEnoughItems-1.7.10-1.0.4.83-universal
TConstruct-1.7.10-1.8.1
Baubles-1.7.10-1.0.1.10
CodeChickenLib-1.7.10-1.1.1.110-universal
ForgeMultipart-1.7.10-1.1.1.320-universal
MrTJPCore-1.7.10-1.0.3.5-universal

**Comment by bonii-xx** [comment] 2015-01-02 08:48
Disabling the smeltery is only rudimentary supported because of @asiekierka, Books are static and can't adapt to active modules, best disable them when you deactivate that.
Wont be fixed for this version.

**Closed by bonii-xx** 2015-01-02 08:48 UTC

**Comment by adudney** [comment] 2015-01-02 19:24
Although the modifier book already handles ThermalExpansion being unloaded, and displays dirt blocks instead, perhaps something similar could be applied here? I know it'll make the book look silly, but hey, at least it wouldn't crash.

**Comment by bonii-xx** [comment] 2015-01-02 19:49
That's default behaviour. The problems are caused by missing items and information because it doesn't get added by the smeltery module.
