### ISSUE TITLE
Untextured tools

### ISSUE THREAD

**Issue by orrinpants** [SlimeKnights/TinkersConstruct#4595] opened 2021-08-10 17:14 UTC
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.115

### Tinkers' Construct Version

3.1.1.252

### Describe your issue

With Optifine shaders on, all TConstruct tools are untextured.
By the way, I am using Slidur's Shaders.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Other required mods:

- Optifine

Unrelated mods:

- Quark
- Create
- JEI

Unrelated library mods:

- Flywheel
- AutoRegLib

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by PrincessOfEvil** [comment] 2021-08-10 17:15
Duplicate of #4316.

**Comment by orrinpants** [comment] 2021-08-10 17:16
Not really a duplicate.

**Closed as completed by PrincessOfEvil** 2021-08-10 17:15 UTC
Labels: Performance Enhancers/Optifine, 1.16

**Comment by PrincessOfEvil** [comment] 2021-08-10 17:17
You use a mod that breaks stuff and expect it to not? That is exactly a duplicate.

**Comment by mDiyo** [comment] 2021-08-10 17:54
OptiFine is not supported.

**Comment by orrinpants** [comment] 2021-08-13 19:23
The other post was a helpful answer though, so I removed shaders, because if you just use Optifine without shaders it's fine and if I removed Optifine it would probably be like 10fps, so I'm using Optifine to get 60 fps.

**Comment by KnightMiner** [comment] 2021-08-13 19:56
Optifine will break tinkers. Never report issues with tinkers while optifine is installed. If you need performance, try [one of these performance mods](https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88) which does not delete huge chunks of forge code. Even with those, don't report issues until you test without performance mods.
