### ISSUE TITLE
Stackup! mod

### ISSUE THREAD

**Issue by Sephiroth91** [SlimeKnights/TinkersConstruct#3899] opened 2019-07-15 18:58 UTC
Hello,

 I use the mod stackup, with the mod I can increase the limit of the stacks.  Everything works fine with all other mods, but if I put items into the crafting station of tinker. The station reduce the stack to 64 and delete the other items.  Is it possible to fix it ?

https://www.curseforge.com/minecraft/mc-mods/stackup

Minecraft: 1.12.2
Forge: 27811
Mantle: 1.12-1.3.3.55
Tinker: 1.12.2-2.12.0.157

**Comment by KnightMiner** [comment] 2019-07-15 19:02
Duplicate of #3727.

**Closed by KnightMiner** 2019-07-15 19:02 UTC
