### ISSUE TITLE
Game Crashes when i put on TC armor

### ISSUE THREAD

**Issue by IvorAmlug** [SlimeKnights/TinkersConstruct#4766] opened 2022-02-18 17:28 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.76

### Mantle Version

1.18.1-1.8.31

### Tinkers' Construct Version

1.18.1-3.4.1.46

### Describe your issue

So when ever i put on  TC armor my game crashes. 
Now my world is also broken since it crashs when i rejoin.
Also seems like neither the forge nor the Optifine version change a thing.
Also did a lil thing an see if this was an always precent thing in tc.
So i got back to 1.16.5 and tried the same thing there where all worked.
I know optifine and mods is a thing but i still wanted to post it here for the record.
And also in the tiny hope that u may find a fix.

### Crash Report

https://pastebin.com/hdL6acnE

### Reproduced with only Tinkers' Construct?

No

### Other mods required

preview_OptiFine_1.18.1_HD_U_H5_pre5

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [X] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-18 17:38
Duplicate of #4734 Optifine is a trash mod. Remove it. That is the only fix as they literally delete forge code.

**Closed as completed by ShinyPorygon** 2022-02-18 17:38 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18

**Comment by KnightMiner** [comment] 2022-02-18 17:43
You think people would be willing to take 5 seconds to look at pinned issues when we literally tell you to do it in the issue template. But alas, its easier to make duplicate #7 of this issue rather than taking effort to do the steps we ask.
