### ISSUE TITLE
Crafting Station Mod Interaction Bug

### ISSUE THREAD

**Issue by Cazadorsniper** [SlimeKnights/TinkersConstruct#3700] opened 2018-12-15 20:16 UTC
**Issue description:**
It looks like some type of interaction with the crafting station is interrupting the crafting of almost anything that needs dyes, like lapis blocks, bone blocks, and even the dye cluster in Mystical Agriculture.

Does show in TConstruct and AE2 crafting station/terminal after closing the GUI then re-entering the GUI.
Vanilla workbench shows the recipes fine as long as Fast workbench isn't installed.

I'm unsure what is causing this so maybe you all might have a better idea.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 2796
* Mantle: 1.12-1.3.3.39
* Tinkers Construct: 1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Can be reproduced with Tinkers Construct and The Erebus.

Trying to find this issue I made a test modpack with these mods:
Crafting Tweaks
FastWorkbench
Foamfix
Journeymap
JEI
Mantle
The Erebus
Tinkers Construct

**Comment by KnightMiner** [comment] 2018-12-15 21:58
Sounds like a mod added a broken customer recipe that only breaks with crafting recipe caches. When you say it can be reproduced with Erebus and tinkers do you mean with only those two? Does it happen with just erebus and AE2 or just Erebus and FastWorkbench?

**Comment by Cazadorsniper** [comment] 2018-12-15 22:35
Happens with Erebus and Tinkers, I tested this before adding FastWorkbench.
Happens with Erebus and FastWorkbench without tinkers.
Happens with Erebus and AE2 without tinkers.
All mods work fine by themselves.
Already mention this to Vadis here: https://github.com/vadis365/TheErebus/issues/665

**Comment by vadis365** [comment] 2018-12-15 23:13
o7 KM ;)

I'm only registering some coloured blocks as ore dictionary aliases for dyes in an Item registry event.
Don't know how this could be affecting things on a massive cluster**** basis though
https://github.com/vadis365/TheErebus/blob/mc1.12/src/main/java/erebus/recipes/RecipeHandler.java#L165

**Comment by vadis365** [comment] 2018-12-15 23:34
Found a broken recipe that uses dyes - that 'may' be an issue will find out.

**Comment by KnightMiner** [comment] 2018-12-15 23:35
That could be it. Its overall hard to tell what as the Erebus code for registration is a bit out there. In any case whatever it is seems to be breaking three different crafting methods, so something is up.

@Cazadorsniper can you post a copy of your game log? Specifically when trying to craft a recipe. Hopefully that will shed some light on the issue

**Comment by vadis365** [comment] 2018-12-15 23:37
>the Erebus code for registration is a bit out there
hahahahaha - yes.
I only found one recipe instance of a null stack for a dye related issue.

**Comment by vadis365** [comment] 2018-12-15 23:41
kay sent Caz a new version - he says it works!
Thanks @KnightMiner for you insight and help.

**Comment by KnightMiner** [comment] 2018-12-15 23:56
Cool, in that case I'll close this as an Erebus issue.

**Closed by KnightMiner** 2018-12-15 23:56 UTC
Labels: 3rd party mod interaction
