### ISSUE TITLE
Text in the Materials and You are troncated with OptiFine

### ISSUE THREAD

**Issue by ExDomino** [SlimeKnights/TinkersConstruct#3629] opened 2018-08-30 19:27 UTC
**Issue description:**

The text in the "Materials and You" are troncated.
A picture is better: https://image.noelshack.com/fichiers/2018/35/4/1535656630-2018-08-30-15-16-28.png
All Gui Scale, tested Small, Normal and Large as well as Auto in the screenshot.

**If crashed, link to crash report (use a site such as pastebin):** No crashlog since there is no crash.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2758
* Mantle: 1.3.2.24
* Tinkers Construct: 2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
OptiFine HD U E2 seems to be the source of this bug.
Without OptiFine the page is fine, but without OptiFine the game lags.
I don't know how to issue a bug to OptiFine though.

**Comment by SweetSugarSugar** [comment] 2018-08-30 22:05
Duplicate of #2987 and has been reported many times.  The issue is on their end.

**Comment by KnightMiner** [comment] 2018-08-31 00:31
If it only happens with Optifine, Optifine is the problem. They break stuff they have no right breaking without saying what they change.

**Closed by KnightMiner** 2018-08-31 00:31 UTC

**Comment by ExDomino** [comment] 2018-08-31 01:09
Without Optifine you cannot play because the game lags!

**Comment by KnightMiner** [comment] 2018-08-31 11:52
Consider using a different performance enhancing mod that does not break mods randomly. Better FPS is an option

Otherwise, report this issue to Optifine so they can fix it.
