### ISSUE TITLE
Damage display bug

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [SlimeKnights/TinkersConstruct#2718] opened 2017-01-11 08:06 UTC
![uc 20170111160206](https://cloud.githubusercontent.com/assets/20567492/21840317/ce2f0ebc-d817-11e6-9ede-71e383ee8a74.png)
![uc 20170111161038](https://cloud.githubusercontent.com/assets/20567492/21840442/87e0636a-d818-11e6-8f0a-57cb1c08ac3c.png)

**Comment by KnightMiner** [comment] 2017-10-22 21:00
Sorry for the late response. Can you please try and reproduce with just Tinkers Construct? From what I can tell, one of those tooltips is not added by vanilla or TiC as we never added a DPS one.

**Comment by LoveFireAmi** [comment] 2017-10-25 07:27
No, the DPS is not in vanilla but the attack damage part is.

**Comment by KnightMiner** [comment] 2019-09-21 20:53
Closing as this issue is pretty ancient and I cannot reproduce it. If someone can give an exact tool material+modifier combination to make it in the latest version then we can look into this again.

**Closed by KnightMiner** 2019-09-21 20:53 UTC
Labels: 3rd party mod interaction
