### ISSUE TITLE
help cant craft stuff for the smeltery or iron armour

### ISSUE THREAD

**Issue by IsuckAtEverythingYT** [SlimeKnights/TinkersConstruct#4537] opened 2021-06-17 19:37 UTC
**Issue description:**
so when i try to craft the stuff for the smeltery in the crafting station i get this message(see picture below)

![CIsoaFT](https://user-images.githubusercontent.com/67279216/122461896-37abc900-cfb4-11eb-87ac-0eb16622c90a.png)
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:
* 1.16.5
* Forge: 
* 36.1.30
* Mantle: 
* 1.6.109
* Tinkers Construct: 
* 3.0.4.197

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
yes it can
Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by KnightMiner** [comment] 2021-06-17 19:40
Are you sure about your Tinkers build number? That error message says you are on 2.0.3.194.

**Comment by IsuckAtEverythingYT** [comment] 2021-06-17 19:41
> Are you sure about your Tinkers build number? That error message says you are on 2.0.3.194.

i miss clicked its 3.0.4.197

**Comment by KnightMiner** [comment] 2021-06-17 19:43
Hold F3+C for about 15 seconds, it should generate a crash report. Upload said report here or link it.

**Comment by IsuckAtEverythingYT** [comment] 2021-06-17 19:52
> Hold F3+C for about 15 seconds, it should generate a crash report. Upload said report here or link it.

[
[crash-2021-06-17_21.52.15-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/6672877/crash-2021-06-17_21.52.15-client.txt)
](url)

**Comment by KnightMiner** [comment] 2021-06-17 19:55
According to the crash report, you are on 3.0.4.194:

> TConstruct-1.16.5-3.0.4.194.jar                   |Tinkers' Construct            |tconstruct                    |3.0.4.194

This makes this a duplicate of #4533. Update to build 3.0.4.197 properly. You might have both jars in your mods folder or something similar.

**Closed as completed by KnightMiner** 2021-06-17 19:55 UTC
Labels: Bug, Duplicate, 1.16, Update
