### ISSUE TITLE
Fluids Tag

### ISSUE THREAD

**Issue by RaiXgame** [SlimeKnights/TinkersConstruct#4461] opened 2021-05-12 21:04 UTC
**Is your idea related to a problem? Please describe.**
Kind of. Forge doesn’t allow custom fluids, meaning that the TiC 3’s fluids won’t behave normally when placed.
**Describe the solution you'd like**
I don’t know how they did that, but in Create (another mod) they tag as “water” their fluids.
I suppose that this may not be possible in your end, or maybe you don’t want it because you don’t the watery fluids (like enderslime) to act like water in the interactions with lava or other mods that decompose water.
Also, their fluids move as slow as lava (at least in the overworld) and when you submerge in them you have the air bubbles and you can swim, but the visibility is reduced as if you were on lava.
Again, I don’t know if this is either possible or desirable in TiC 3 (and how it’s done),but you might not know about this.

If you decide to implement this, maybe you could also investigate how to tag other fluids as lava to finish implementing all the molten fluids (I don’t have any proof of this working, just an idea).

**Describe alternatives you've considered**
Including all the watery fluids in the “water” blocktag of Minecraft through a data pack, it won’t work as good, but it will allow for swimming and drowning inside the fluid.

**Additional context**
In Create, both liquid honey and molten chocolate behave as water in every sense except when extending (work as lava in the overworld) and the visibility inside them, which is very reduced.
I cannot put screenshots of it right now, if really needed I can put them tomorrow.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.16
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.144
* (Am I also supposed add the Create version? I so: v0.3.1c)

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
Not that I have seen.

**Comment by KnightMiner** [comment] 2021-05-12 21:42
Duplicate of #4295

**Closed as completed by KnightMiner** 2021-05-12 21:42 UTC
Labels: Duplicate, Enhancement, 1.16
