### ISSUE TITLE
[1.12.2] Crash when placing tool in tool station for upgrading

### ISSUE THREAD

**Issue by 1gn153n515** [SlimeKnights/TinkersConstruct#3501] opened 2018-05-23 18:44 UTC
I wanted to add a slime binding to my pickaxe but when I tried to place it into the grid the game crashed
[crash-2018-05-23_20.39.48-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/2032421/crash-2018-05-23_20.39.48-client.txt)

**Comment by YaibaToKen** [comment] 2018-05-23 18:49
Remove TAIGA, it's adding a broken modifier causing the game to crash

**Comment by KnightMiner** [comment] 2018-05-23 18:51
Duplicate of #3372, TAIGA's fault.

**Closed by KnightMiner** 2018-05-23 18:51 UTC
Labels: duplicate
