### ISSUE TITLE
Wetting modifier doesnt work at all

### ISSUE THREAD

**Issue by Zen9890** [SlimeKnights/TinkersConstruct#5189] opened 2024-03-03 13:22 UTC
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Mantle Version

1.9.50

### Tinkers' Construct Version

3.7.1.155

### Describe your issue

While taking damage from zombies/falling pants with wetting refuse to use fluid in them, though rarely wetting actually triggers properly

### Other mods

Tinkers things, json things, tinkers construct, mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment] 2024-03-03 15:39
Wetting does not trigger every time, it's chance based. Higher levels make it more common to trigger.

**Comment by KnightMiner** [comment] 2024-03-04 04:04
I am going to go ahead and close this as works as intended. If you are not finding it is chance based as intended, feel free to request a reopen.

**Closed as not planned by KnightMiner** 2024-03-04 04:04 UTC
Labels: Bug, Works as Intended, 1.18
