### ISSUE TITLE
ALOT OF CASTS AND TOOLS ARE INVISIBLE (VERSION 1.12)

### ISSUE THREAD

**Issue by ProphetDoesMusic** [SlimeKnights/TinkersConstruct#3027] opened 2017-07-21 23:04 UTC
PLEASE FIX I CANT SEE MY BELOVED HAMMER

**Comment by billybricker** [comment] 2017-07-21 23:18
![2017-07-21_17 14 53](https://user-images.githubusercontent.com/26291936/28485666-422a01ee-6e38-11e7-8f1a-b3cd9b1797ec.png)
![2017-07-21_17 14 55](https://user-images.githubusercontent.com/26291936/28485662-4221bc78-6e38-11e7-9b5f-4f46159b27da.png)
![2017-07-21_17 14 59](https://user-images.githubusercontent.com/26291936/28485664-42232432-6e38-11e7-95d5-d49fea1dd493.png)
![2017-07-21_17 15 01](https://user-images.githubusercontent.com/26291936/28485661-4220818c-6e38-11e7-883b-b9a76505e83a.png)
![2017-07-21_17 15 03](https://user-images.githubusercontent.com/26291936/28485663-42229026-6e38-11e7-842d-8c04e5950285.png)
![2017-07-21_17 15 05](https://user-images.githubusercontent.com/26291936/28485665-42239836-6e38-11e7-915a-0a14bd4a3ac0.png)

The textures are working fine. I'm guessing Optifine is breaking them. See #3008

**Comment by TheSnowyChickens** [comment] 2017-07-22 01:01
Yep , its a Optifine bug.
They add on Thursday a new pre-release version ,but this bug they dont fix. :(

**Comment by KnightMiner** [comment] 2017-07-22 01:20
I am closing this as a likely duplicate of #3008. @ProphetDoesMusic: if you can verify this happens without Optifine then post additional information including mod versions and game logs.

**Closed by KnightMiner** 2017-07-22 01:20 UTC
