### ISSUE TITLE
Tinker's Construct is Incompatible with JEI and Twilight Forest together.

### ISSUE THREAD

**Issue by BlackAvarice311** [SlimeKnights/TinkersConstruct#5211] opened 2024-04-08 01:31 UTC
### Minecraft Version

1.19.2

### Forge Version

43.3.9

### Mantle Version

1.10.23

### Tinkers' Construct Version

3.8.0.14

### Describe your issue

When loading Tinkers Construct, Twilight Forest, and Just Enough Items together, the game will always freeze and become not responding when opening the inventory in creative or survival mode. When any two combination of mods are present, the issue does not happen. When all three are present, the issue happens 100% of the time. 

### Crash Report

N/A due to Minecraft not crashing, but instead freezing. 

### Other mods

Mantle - 1.10.23
TConstruct - 3.8.0.14
Just Enough Items - 11.6.0.1019
Twilight Forest - 4.2.1518

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment] 2024-04-08 01:36
Duplicate of #5203

**Closed as not planned** 2024-04-08 03:58 UTC
Labels: Bug, Duplicate, 1.19
