### ISSUE TITLE
Forge Freezes when Loading Tinker's

### ISSUE THREAD

**Issue by gans4728** [SlimeKnights/TinkersConstruct#3709] opened 2018-12-31 23:04 UTC
**Issue description:**
When loading Forge for my modpack, forge freezes when it displays that it is constructing Tinker's Construct. No crash report is created as I have to manually quit for it to close.
**If crashed, link to crash report (use a site such as pastebin):**
Link to log, not a crash report: https://pastebin.com/3bK2RbuS
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2796
* Mantle: 1.12-1.3.3.39
* Tinkers Construct: 1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Error only happens with Tinker's

**Comment by KnightMiner** [comment] 2018-12-31 23:45
I have never seen this issue personally. Can you give a copy of your log from when you tested with just Tinkers? That should be a lot cleaner to figure out what is going on

**Comment by gans4728** [comment] 2019-01-01 05:06
https://pastebin.com/aVw5NS8t
I've had this issue in the past, but the only way I could get it to stop was to remove it from my pack. But then I've also played the same pack without having the issue. It really makes no sense.

**Comment by KnightMiner** [comment] 2019-01-01 06:57
Huh, that is very odd. The log just stops after OS details. Unfortunately there is nothing in there which helps me figure out why its happening, I just used that same version of the mod earlier today and it loaded fine.

Since I am not really sure the cause, I guess lets try a couple random things:
* First, want to try running the recommended Forge build instead of the latest? Possible something broke in Forge that we are one of the few mods using
* Second, can you verify you are downloading the mods from CurseForge? Other download sites are not controlled by us, so there is a chance the file is not real
* Last, if neither of the other two are the problem you could try updating Java, you are about 100 builds behind the version I am using, though I doubt that would be the cause, at this point I'm mostly throwing out random ideas.

**Comment by gans4728** [comment] 2019-01-01 07:57
1. I tried the recommend version of forge of 2768 as well as a couple later versions and still nothing.
2. I'm doing all of this out of the Twitch launcher, so I would hope I'm getting the right files.
3. I updated to the latest version of Java 8 (191) and still nothing.
Yeah this is really weird and it may just be a system issue, but I think this has happened to me before on a different computer. Do you think not having enough storage space on the computer could affect it? Either way, I appreciate the help!

**Comment by gans4728** [comment] 2019-01-01 21:09
So I tried it with Mantle and Natura: same freeze. I tried with just Mantle: same freeze. I tried it with no mods: same freeze. I tried regular Minecraft version 1.13: managed to get to the home screen, but froze when I tried to join a world. Clearly something's either wrong with my Minecraft or just my computer in general. I got no clue.

**Comment by KnightMiner** [comment] 2019-01-02 01:08
If its happening with no mods, I guess there is not much more we can do for you here. You are probably better off asking on [the Minecraft forms](https://www.minecraftforum.net/forums) or [the Forge forms](http://www.minecraftforge.net/forum/). Happening in 1.13 normal makes the former seem like the better option.

I'll close this issue as you just confirmed its an issue with more than Tinkers

**Closed by KnightMiner** 2019-01-02 01:08 UTC
