### ISSUE TITLE
Crashes when modifying tool in tool forge or tool station

### ISSUE THREAD

**Issue by GLGShadow** [SlimeKnights/TinkersConstruct#3633] opened 2018-09-01 17:52 UTC
Whenever I attempt to place a tool into the center slot of a tool station or tool forge, my game crashes

Crash report: https://paste.dimdev.org/uwatofidij.mccrash

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2759
* Mantle: 1.3.2.24
* Tinkers Construct: 1.12.2-2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Tinkers Construct by itself does not create the crash, so other mods are necessary.

**Comment by KnightMiner** [comment] 2018-09-01 17:58
You did not finish the last question which asks which mods, but this is a duplicate of #3631.

**Closed by KnightMiner** 2018-09-01 17:58 UTC
