### ISSUE TITLE
Slime Islands / Config File problem

### ISSUE THREAD

**Issue by EmergentCapulin** [SlimeKnights/TinkersConstruct#3455] opened 2018-04-13 22:26 UTC
Just wanted to ask a question about the functionality of the Config file - as... I may be doing something wrong and I just don't realize it.  Every time I set restrictions for the slime islands (about 20 dimensions) the file always nullifies any changes I make and reverts the dimensions black list to simply -1 and 1.  Is there some other setting I need to turn on / off before doing this?  Or is this Tconstruct making a new .cfg file every time I restart the world?  

Cheers, and thanks for the mod / continued support.

Capulin

**Comment by EmergentCapulin** [comment] 2018-04-13 22:39
Oh, I forgot to mention.  I'm currently using using version: TConstruct-1.12.2-2.9.1.65

The following is how I've set up the list - and every time I restart the server it reverts to simply -1  1.

    # Prevents generation of slime islands in the listed dimensions
    I:slimeIslandBlacklist <  
        -9999
        -11325
        -127
        -28
        -29
        -30
        -31
        -50
        -51
        -52
        -53
        -54
        -55
        -56
        -57
        -58
        -59
        -2
        1
        2
        4
        7
        20
        33
        43
        53
        66
        73
        74
        84
        144
        684
        685
        686
        687
        688
        5000
        5001
        5002
        5003
        5004
        5005
        5006
        5007
        5008
        5009
        5010
        11150
        28885
     >

**Comment by KnightMiner** [comment] 2018-04-14 04:11
It's all Forge code responsible for reading the file and resetting invalid values, so not sure what is going on. Do you know of it is the length or a specific number? Try filling with all one number or with just high numbers.

**Comment by EmergentCapulin** [comment] 2018-04-14 06:35
I can try it tomorrow when I get a break from daddy duty.  That said, this is a similar list I use in other mod configs to restrict creatures spawning in other dimensions.  (Specifically Ice and Fire dragon spawning.  Forge doesn't seem to have an issue with that list and doesn't revert that file.  Could it be that there might be a difference in expectations between mob spawning and this?  Anyway, please don't take it as pointing fingers, as I truly don't mean it that way - merely brainstorming and giving information based on what I've observed (and trying to help narrow down what might be going wrong.)

**Comment by KnightMiner** [comment] 2018-04-14 15:39
All the config does is parse the array using the Forge method, so unless the other mods are not using the Forge method there is no difference

**Comment by KnightMiner** [comment] 2018-05-09 18:45
Any update? Were you able to discover exactly what is causing the parsing to break?

**Comment by KnightMiner** [comment] 2018-07-03 19:05
Since you have been unable to reproduce consistently and no other reports have been made, I am closing this. Feel free to leave a comment if it starts happening again consistently.

**Closed by KnightMiner** 2018-07-03 19:05 UTC
