### ISSUE TITLE
Game crashes when creating Slimewood on a server

### ISSUE THREAD

**Issue by Thundershark1** [SlimeKnights/TinkersConstruct#4418] opened 2021-04-29 13:08 UTC
When creating a slimewood item, the minecraft client freezes then crashes

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/H8xZ4tff

**Versions:**
* Minecraft: 1.16.5
* Forge: 1.16.5-forge-36.1.4
* Mantle: 1.16.5-1.6.92
* Tinkers Construct: 1.16.5-3.0.2.96

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I have not seen this pop up in any recent reports for 1.16.5

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue
Modpack that the server runs: https://drive.google.com/file/d/1qaB7BspKJnpJZXhrz2xUjZO4m_K-Sx7g/view?usp=sharing

**Comment by PrincessOfEvil** [comment] 2021-04-29 13:11
Duplicate of #4316.

**Closed as completed by PrincessOfEvil** 2021-04-29 13:11 UTC
Labels: Duplicate, Performance Enhancers/Optifine, 1.16
