### ISSUE TITLE
Crafting Station - Preview Grid Graphical Glitch

### ISSUE THREAD

**Issue by Naddox** [SlimeKnights/TinkersConstruct#2157] opened 2016-06-08 08:38 UTC
Found this in version 1.9.4-2.3.1..jenkins229

If you put a vanilla chest in the crafting station, the preview gives you a box with no textures. Haven't found any other items currently, just the chest.

http://i.imgur.com/CYWS8I3.png

**Comment by AlterAkima** [comment] 2016-06-08 12:29
Mojang's fault.

**Comment by KnightMiner** [comment] 2016-06-08 12:52
Duplicate of #2111. The issue is some items display using the `builtin/entity` method, which requires data that is assigned to that item on display (thus not available when we ask for its original model)

**Closed** 2016-06-08 19:06 UTC
Labels: duplicate
