### ISSUE TITLE
Traveler's Leggings on Armor Stand Causes the Game to Crash (Rendering Entity in World)

### ISSUE THREAD

**Issue by Coraline77447** [SlimeKnights/TinkersConstruct#4784] opened 2022-02-27 05:32 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.18.1-1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

When I put the Traveler's Leggings on an Armor Stand that has armor on it already the game instantly went to "Saving World" screen like as if I was saving and quitting when I wasn't done playing yet (now I am for the time being cause of this issue...), which means the game crashed... 
I wasn't put all the way back to the launcher thanks to NotEnoughCrashes, I tried to log back onto the world and instantly the same thing happened again...
Now I can't rejoin the world until the issue is resolved and I'm unwilling to load one of my backups cause I've made so much progress from the last backup that was made at the beginning of my play session earlier today..
I just got what I'd needed to make Scorched Stone tool parts which took me two weeks at least IRL cause of me doing other things instead of going to the nether to get soul sand and magma cream until today when I went to the nether for the third time to get the magma cream... 
The first time I went in there I grabbed a stack of soul sand and some gravel but didn't get the magma cream from the magma cubes since I'd thought that I was still able to obtain magma cream from smelting down magma blocks in the smeltery but yall took that away in one of the versions of TiC3, the second time I went in there I wanted to go back home to get some building blocks...

### Crash Report

https://pastebin.com/fhygsg3W

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [ ] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-27 07:53
Duplicate of #4734 Check the pinned issues next time like you said you did. Remove optifine

**Closed as completed by ShinyPorygon** 2022-02-27 07:53 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18

**Comment by Coraline77447** [comment] 2022-03-01 03:57
Well, sorry for making a dup report even tho the cause of my crash was with different armor and putting it on an armor stand, meaning a different scenario than what happened with the person who reported #4734..

I read most of their report and seems like they were having similar issues and apparently it's caused by none other than OptFine aka FartFine as I like to call it nowadays and you should know exactly why I gave OptiFine that nickname for several reasons...

So for me to fix my mistake that I'd made by putting those leggings on an armor stand is to launch my game without optifine and take those leggings off of the armor stand that I put them on, log out of the game entirly, then load back in with optifine and will never put any of the armor from Tinkers' Construct 3 back on any armor stands.
I probably wont be wearing any of the armor sets on my character, also won't allow any entity to wear any of the armor to avoid any issues with optifine while I continue to use optifine.. 
(So I'll just recycle my Traveler's Leggings with Coral Recycler mod to get my resources back from those leggings...)

Since I need that shitty mod for that 5% in "performance boost" and for some reason my game apparently likes/loves optifine more than any other performance mods out there..
Since my game lags more with Magnesium installed than with OptiFine, I've tried other performance mods that are originally for fabric but have forge ports and they caused my game to crash...

One last thing, I was exited to be able to make armor in tinkers (even tho I'd prefer the method to make armor from Construct's Armory) which the plate armor may be better than both diamond and netherite armor combined but now I'm disappointed that I can't make any of the armor sets cause I still need to use OptiFine..
Since I primarily use it for it's dynamic lighting and any resource packs that requires optifine and partially for it's zoom feature (replaced by the spyglass) as well as it's "performance improvements" nowadays... 
(even tho I can use a dynamic lighting mod that I can't remember it's name right off the bat that's as smooth as OptiFine's dynamic lighting without any lag/performance loss)

**Comment by KnightMiner** [comment] 2022-03-01 04:37
Your rant there confuses me, so let me clarify some details:

* If the armor is crashing on the player, it is believable to assume it crashes on armor stands as well
* Its is not Tinkers Constructs fault that the armor crashes, it is optifines fault. They are deleting forge code for their performance hacks. Yell at them for ruining your excitement.
* Tinkers Construct cannot fix this bug, Optifine has to fix it on their side
* This bug was reported to Optifine nearly a month ago, they don't seem to care

It sucks that you cannot run the game without optifine, and its great that you acknowledge optifine is a terrible mod. The fact remains that we cannot fix this bug without deleting tinkers construct features, and its stupid that we have to delete features for compatibility with a mod that does not care about its users. Thus, we do not support optifine. Ask optifine to support Tinkers Construct if you need the mod so much.
