### ISSUE TITLE
Smelting not working properly

### ISSUE THREAD

**Issue by Skullmonkeys44** [SlimeKnights/TinkersConstruct#3223] opened 2017-11-03 13:11 UTC
Can someone explain to me how the hell the new version of tinkers works ??? i have no recipes and smelting ores does not works /!\ EXCEPT for vanilla ores
soo i used both oven and tinkers smelter and nothing happen when i try to melt : copper, salpeter, sulfur, silver, tin. "this item cannot be melt"
no recipes found and the book does not talk about a weird way to do it or not. sooo..??
version is 1.12 - 2.7.3.30 from the modpack Medival Reborn (on technic launcher)

Nota Bene : i used an old version of tinkers annnnnnd i just added the ores to the smeltery like any gold or iron and it smelt it. soo is the new version bugged ? (from the modpack HEXXIT)

EDIT : to be clear i smelted an iron door into ingot. and gold ingot into a gold ingot stencil. the tinker smelter works. only thoses ores seems to be just normal non usable items. weird
EDIT 2 : and recipes says i can smelt armor into liquid metal but when i try, same problem "this item cannot be melt"

**Comment by luckyu19** [comment] 2017-11-04 18:34
Let me just straighten this just a tad bit.

Paragraph 1:
No recipe? Get JEI. You have modded ores and they don't smelt?
Reproduce the issue with the latest version of TiC (1.12 - 2.7.3.34) and whatever mod that adds the ores ONLY.

Paragraph 2:
If you checked JEI stating the item can be melted in the smeltery and you can't, kindly reproduce the issue with the latest version of TiC (1.12 - 2.7.3.34) and whatever mod that adds the ores, and post a screenshot regarding the issue.

Paragraph 3:
If a recipe is not found for smelting x item, then they cannot be smelted in the smeltery.
Consult the pack maker and see if it's intended behaviour.

Paragraph 4:
TiC2 (1.8+) and TiC (1.7.10 and below) are different in many aspects. The features are as intended by the devs.

Paragraph 5:
*shrug* Can't tell you what's wrong if you can't tell me what mod added the new ores.

Paragraph 6:
Is the armor at full durability?

**Comment by Skullmonkeys44** [comment] 2017-11-04 19:43
i'm not hte mod maker so eff if i know how it was intended to be.
all i know is the book saying you CAN smelt thoses ores.
and the 1.7 version was jsut to compare. i'm not dumb 1.7 is different from 1.12 oh really now ?
like i said modpack is Medival Reborn. i hate to repeat myself

i'm no codder, no modder, so if the TC isn't the one that include ores but works with then i have no idea how the hell this is working.

all i know is HEXXIT smelting TC was on point for 1.7
Medival Reborn TC 1.12 smelting is broken (and when i say no recipe, i mean i clicked on the NEI items listed and for all the ores listed no recipes appeared such as smelting or else)

**Comment by luckyu19** [comment] 2017-11-05 03:54
I created an instance with only Tinker's Construct, Dark Roleplay Medieval and JEI, what I found was DRM doesn't even add a ingot smelting recipe, i.e. you can't use them at all as it is WIP.
Everything is working as intended on TC end of things, but without the crucial information about smelting output, TiC can't smelt the ores in the smeltery.
This is not an TiC issue, but a DRM issue. Kindly refer this issue to mod devs (though the answer you'll likely be getting is it is WIP, will be updated soon).

**Comment by Skullmonkeys44** [comment] 2017-11-05 11:03
Understandable, have a great day.

**Comment by KnightMiner** [comment] 2017-11-05 16:19
Closing as a DRM issue. Note that they just need to oredict their items and it will work in the smeltery.

**Closed by KnightMiner** 2017-11-05 16:19 UTC
