### ISSUE TITLE
Crashing on pressing launch

### ISSUE THREAD

**Issue by Ectoniqua** [SlimeKnights/TinkersConstruct#4525] opened 2021-06-09 06:38 UTC
**Issue description:**
Whenever I'm launching, it just crashes, it doesn't load or anything, just crash

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/tBfYRdbv
**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-forge-14.23.5.2855
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
GalacticraftCore-1.12.2-4.0.2.280
Galacticraft-Planets-1.12.2-4.0.2.280
GalacticraftTweaker-1.12.2-1.0.3
HeroesExpansion-1.12.2-1.3.5
Hwyla-1.8.26-B41_1.12.2
InfinityStonesMod-1.3
inventorypets-1.12-2.0.13
jei_1.12.2-4.16.1.301
JustEnoughCalculation-1.12.2-3.2.6
JustEnoughIDs-1.0.3-55
JustEnoughResources-1.12.2-0.9.2.60
LucraftCore-1.12.2-2.4.14
Mantle-1.12-1.3.3.55
NotEnoughIDs-1.5.4.4
OptiFine_1.12.2_HD_U_G5
SpeedsterHeroes-1.12.2-2.2.1
TConstruct-1.12.2-2.13.0.183
Wawla-1.12.2-2.6.275

**Comment by PrincessOfEvil** [comment] 2021-06-09 06:39
Duplicate of #4441.

**Closed as completed by PrincessOfEvil** 2021-06-09 06:39 UTC
Labels: Duplicate, Mod interaction, 1.12
