### ISSUE TITLE
Tinker's/ Chisel Loadup crash.

### ISSUE THREAD

**Issue by border999** [SlimeKnights/TinkersConstruct#3226] opened 2017-11-05 04:36 UTC
TConstruct-1.12-2.7.4.34
Forge 1.12.2 - 14.23.0.2529
https://pastebin.com/g8VmVg1P
Any ideas? For some reason Chisel is throwing a curve ball into things.

**Comment by Drullkus** [comment] 2017-11-09 04:20
That doesn't look like a chisel crash to me

**Comment by Drullkus** [comment] 2017-11-09 04:20
That doesn't look like a chisel crash to me... @tterrag1098?

**Comment by tterrag1098** [comment] 2017-11-09 04:46
You're missing ctm

**Comment by KnightMiner** [comment] 2017-11-09 05:23
Closing per @tterrag1098. Reproduce with CTM installed if you want a reopen.

**Closed by KnightMiner** 2017-11-09 05:23 UTC

**Comment by border999** [comment] 2017-11-10 04:13
Issue did not occur with CTM installed. With that settled, you might want to  put some form of disclaimer on your curse page about having CTM installed when using chisel and tinkers together.

**Comment by KnightMiner** [comment] 2017-11-10 06:38
This has nothing to do with Tinkers. Rather, chisel requires CTM, but due to the way Forge handles mod loading the exception is not always accurate if other mods are installed with Chisel.

**Comment by tterrag1098** [comment] 2017-11-10 08:15
In 1.12 forge (thanks to https://github.com/MinecraftForge/MinecraftForge/pull/4403) it is now possible to have client-only dependencies, which i will be adding to chisel for CTM ASAP. But since that doesn't exist on 1.10/1.11 I have to use a somewhat hacky system that doesn't quite work the same as normal dependencies.

**Comment by border999** [comment] 2017-11-11 01:16
good to know, carry on.
