### ISSUE TITLE
[1.16.5] Item dupe bug

### ISSUE THREAD

**Issue by omoflop** [SlimeKnights/TinkersConstruct#4284] opened 2021-04-01 23:29 UTC
**Issue description:** It seems that item entities thrown into the smeltery don't get properly deleted, causing players to be able to duplicate items.

**Versions:** 
* Minecraft: 1.16.5
* Forge: 36.1.3
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.73

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
There's no sign of this on both the roadmap and what's new.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes, you can reproduce this with just Tinkers Construct.

Here is the bug in action:

https://user-images.githubusercontent.com/29988852/113363989-3e0c9c00-9307-11eb-8e7c-9ab24c408ce3.mp4

**Comment by xVodkaX** [comment] 2021-04-02 21:19
> 
> 
> **Issue description:** It seems that item entities thrown into the smeltery don't get properly deleted, causing players to be able to duplicate items.
> 
> **Versions:**
> 
>     * Minecraft: 1.16.5
> 
>     * Forge: 36.1.3
> 
>     * Mantle: 1.6.79
> 
>     * Tinkers Construct: 3.0.2.73
> 
> 
> **Confirm below that this issue is not covered on the roadmap or "Whats New?"**
> There's no sign of this on both the roadmap and what's new.
> 
> **Can it be reproduced with _just_ Tinkers Construct? If not, list the other mods _required_ to reproduce the issue.**
> Yes, you can reproduce this with just Tinkers Construct.
> 
> Here is the bug in action:
> 2021-04-01_16-08-38.mp4

Confirmed dupe item

**Comment by KnightMiner** [comment] 2021-04-03 21:25
Fixed in 3.0.2.76

**Closed as completed by KnightMiner** 2021-04-03 21:25 UTC
Labels: Bug, Resolved, 1.16, Confirmed
