### ISSUE TITLE
Bug Visual Tinkers Furnace

### ISSUE THREAD

**Issue by Kofola45cz** [SlimeKnights/TinkersConstruct#3215] opened 2017-10-28 15:53 UTC
The error is shown only when something melts or something is in the oven.
The oven is inside size 7x7 y: 15
The problem is also with a furnace of size 5x5 y: 15 (inside).
Besides, when it's over chunk it will cut off the visual tinkers furnace.
Bug is on the server, even after restart there remains to the point where it is not tinkers furnace empty.
when the bug shows so close to the furnace tinkers, so I have smaller lags.
I am sorry for my bad English.
Version:
TConstruct-1.7.10-1.8.8
Mantle-1.7.10-0.3.2b
![2017-10-27_19 08 47](https://user-images.githubusercontent.com/22054484/32136028-a6f14a7e-bc08-11e7-9518-4de1f6b5ce4e.png)
![2017-10-27_19 08 55](https://user-images.githubusercontent.com/22054484/32136033-b048a202-bc08-11e7-9955-2d8af487205b.png)
![2017-10-27_19 09 49](https://user-images.githubusercontent.com/22054484/32136034-b39f48f2-bc08-11e7-93fc-c1379a7c1a6d.png)

**Comment by LoveFireAmi** [comment] 2017-10-29 05:57
1.7.10 is no longer supported.  Also, I would try reproducing the bug without OptiFine.

**Comment by Kofola45cz** [comment] 2017-10-29 10:08
ok, I did not know, I would try without Optifine.

**Comment by KnightMiner** [comment] 2017-10-29 15:28
Closing since 1.7 is no .onger suported, and it does not happen in the latest versions.

**Closed by KnightMiner** 2017-10-29 15:28 UTC
