### ISSUE TITLE
Steel Sharp trait causing Thorns damage when hitting Guardian with spike out from bleeding

### ISSUE THREAD

**Issue by PokeMaserJ** [SlimeKnights/TinkersConstruct#3704] opened 2018-12-29 03:13 UTC
**Issue description:**
The Player takes what I assume is Thorns damage from the Guardian's Spikes when they are hit with a tool with a Steel Head, IE a Steel Sword Blade from the Guardian taking Bleeding damage from said tool
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.52782
* Mantle: Mantle-1.12-1.3.3.39
* Tinkers Construct: TConstruct-1.12.2-2.11.0.106

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

**Comment by KnightMiner** [comment] 2019-09-21 21:39
This one is a bit difficult to fix. Guardians will deal damage back if the attack is not magical (splash potion), caused by another entity (so not cactus), and not an explosion. I want to avoid marking bleeding as an explosion, and we need the entity for the damage to count as a player kill. Marking it as magic is an option, but not great as magic may be interpreted differently by other mods.

A more hacky solution would be to make the player not the immediate damage source, but that could cause issues with mods assuming no immediate source means no indirect source.

**Comment by KnightMiner** [comment] 2022-01-31 19:41
Closing as 1.16 got a beta release making 1.12 end of support. Best fix is probably marking steel damage as magic, but its not super ideal. I'll put a note to double check this on 1.16, I think marking it projectile would fix it there.

**Closed by KnightMiner** 2022-01-31 19:41 UTC
Labels: Bug, 1.12
