### ISSUE TITLE
I don't know how to explain this, maybe rendering errors?

### ISSUE THREAD

**Issue by Lion4K** [SlimeKnights/TinkersConstruct#4617] opened 2021-09-05 00:41 UTC
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2855

### Mantle Version

Mantle-1.12-1.3.3.55.jar

### Tinkers' Construct Version

TConstruct-1.12.2-2.13.0.183.jar

### Describe your issue

The fluids present in the smeltery renders intermittently, sometimes renders, sometimes not, sometimes only if I look up, others if I look down.

I took some screenshots standing in the same spot and looking at different angles to try and replicate the issue.
https://imgur.com/a/iyi6a8B

Also, it didn't crashed the game, but here's the log anyway.
https://pastebin.com/Y5eu0hDy 

### Reproduced with only Tinkers' Construct?

Yes

**Comment by ShinyPorygon** [comment] 2021-09-05 00:45
Well A. You clearly didn't reproduce it with only tinkers construct with the provided screenshots and B. Optifine is not supported. The words "rendering error" + optifine being installed = optifine is causing this

**Comment by Lion4K** [comment] 2021-09-05 00:47
Yeah It had Optifine, I thought it was OK to have it.
I'll try again without it

**Comment by ShinyPorygon** [comment] 2021-09-05 00:47
No mod supports optifine...

**Comment by Lion4K** [comment] 2021-09-05 00:48
> No mod supports optifine...

what do you mean? I never had any issues before, not even with TC

**Comment by ShinyPorygon** [comment] 2021-09-05 00:49
I mean no mod will support optifine, ever. It's horrible, worse on 1.16 to the point where it corrupts everything, and it causes bugs mod devs can't fix. So it's not supported. Reproduce without it, then again this somewhat seems like normal behavior from what I remember.

**Comment by Lion4K** [comment] 2021-09-05 00:52
https://imgur.com/a/ShWCCrK

Without optifine

[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/7110706/latest.log)

**Comment by ShinyPorygon** [comment] 2021-09-05 00:55
Yeah I'd almost mark this as usual behavior because I remember doing this, just awkward rendering. Doubt it will ever be fixed due to 1.12 having very limited support if any. I'll let Knight decide rather or not to close it.

**Comment by Lion4K** [comment] 2021-09-05 00:58
> Yeah I'd almost mark this as usual behavior because I remember doing this, just awkward rendering. Doubt it will ever be fixed due to 1.12 having very limited support if any. I'll let Knight decide rather or not to close it.

Oh so this is not present on the 1.16 branch ?

**Comment by KnightMiner** [comment] 2021-09-05 04:55
I have never seen this issue on 1.12. I assume you have a mod messing with rendering. You claim it still happens without optifine, but do you have any other performance mods?

And yes, there are no problems on 1.16. Which I will point out is the exact same code with the addition of a patch for vanilla 1.13+ TESR culling.

**Comment by Lion4K** [comment] 2021-09-06 18:04
> I have never seen this issue on 1.12. I assume you have a mod messing with rendering. You claim it still happens without optifine, but do you have any other performance mods?

No I literally tested with just TC and Mantle, and it still happened.

Is there anything I can provide to help debuggin this?

**Comment by KnightMiner** [comment] 2021-09-06 19:36
As stated earlier, 1.12 is unlikely to get another build. You reported this years after we released the last build. The debug help I was giving was to help you resolve the issue. If it's true it's a big with tinkers, your choices are basically ignore it or update to 1.16 at this point.

**Comment by Lion4K** [comment] 2021-09-06 23:43
> As stated earlier, 1.12 is unlikely to get another build. You reported this years after we released the last build. The debug help I was giving was to help you resolve the issue. If it's true it's a bug with tinkers, your choices are basically ignore it or update to 1.16 at this point.

I see. I thought it was still being maintened since the issue tracker still have option to report bugs for it.
No worries thou, it's not game breaking or anything.

Thanks anyway.

**Comment by KnightMiner** [comment] 2021-09-07 00:53
I said unlikely, not definitely not. There is still a chance of another build, but it will likely be simple fixes. In either case, I don't want to fully drop 1.12 support until 1.16 is at least a beta release.

**Comment by KnightMiner** [comment] 2022-01-31 19:10
Closing as 1.16 got a beta released and we are done with 1.12. I don't think this issue will be a simple fix, so not adding it to the "known fixes" milestone.

**Closed by KnightMiner** 2022-01-31 19:10 UTC
Labels: Bug, 1.12, Unreviewed
