### ISSUE TITLE
[1.16.5] Quark Chest Helper Buttons Invade Crafting Station GUI

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#4558] opened 2021-07-04 18:22 UTC
When using the crafting station with a chest next to it and you have quark installed the chest helper buttons from quark end up in the middle of the stations crafting GUI making it annoying to use.

Screenshot:

https://www.dropbox.com/s/xz9qlrkivtwtcgu/2021-07-04_13.15.08.png?dl=0

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.31
* Mantle: 1.6.109
* Tinkers Construct: 3.0.4.197

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes

**Comment by KnightMiner** [comment] 2021-07-04 18:49
Your answer for the last question is not true, as you said in the title Quark is needed. I don't want you to answer yes, I want you to answer honestly.

In any case, this is an issue on Quarks's side, as they add the buttons. If they make an assumption that is not true for our UIs, its on the quark dev to let us know what the problem is, as I cannot guess how they place the buttons. I can say ours is not the only UI I have seen them weirdly placed in. So basically, report this to Quark, get a response for how this is supposed to be fixed.

**Comment by MokahTGS** [comment] 2021-07-05 03:42
Probably answering incorrectly not dishonestly...there is a difference.  I will post this in Quarks git hub then.

**Comment by KnightMiner** [comment] 2021-07-05 03:52
Leave open until we get an answer from quark, makes this issue easier to search.

**Comment by FynnWaelsing** [comment] 2021-08-31 00:46
Here's (a clarified version of) my comment on the issue posted in the Quark Github:

"There's a way to disable the Quark buttons in all of the Tinker's Construct GUIs. In the Quark config there's an option to print to your log the classnames of any GUI screens you open. After you've done that, you can paste the classname of the screen into the blacklist for those buttons in the Quark config"

Vazkii closed the issue afterwards, so clearly he sees this as the intended solution for this GUI conflict

**Comment by KnightMiner** [comment] 2021-08-31 00:49
That is a bit disappointing, I would have rather he added proper support to ensure it did not break the station or added an opt-out rather than just blacklisting. Right now this means every modpack with the two mods together has to blacklist it.

Anyways, since there is nothing we can do on our side that I know, and Vazkii seems to consider blacklisting as the proper solution, going to close this.

**Closed as completed by KnightMiner** 2021-08-31 00:49 UTC
Labels: Bug, Can't Fix, Mod interaction, 1.16

**Comment by FynnWaelsing** [comment] 2021-08-31 01:38
Just to be clear, I'm not privy to Vazkii's thoughts on this matter. He may be amenable to such a solution, but that was how he reacted after my comment. Make of that what you will.

**Comment by JabSparrowtheoriginal** [comment] 2022-06-20 04:14
I have never altered a config file for a mod in minecraft before, how does one print to log the classnames for tinker's GUI screens??

**Comment by KnightMiner** [comment] 2022-06-20 04:19
This is the wrong place to ask. Its not my mod you are configuring, and modern mods should not be using class name blacklists, they should use registry IDs (which are far easier to find)

There are plenty of discords and subreddits devoted to modded minecraft, I suggest you ask on one of them. Consider asking on Vazkii's discord since that is the author of the mod you are trying to configure

**Comment by JabSparrowtheoriginal** [comment] 2022-06-20 04:35
I never implied that it was your mod, I was just asking how it is done. If you dont have the time or the desire to help just say that instead. No need to respond to this however, I won't be following this thread any longer, thanks for the tip of getting in touch with someone who is willing to help tho...toodles
