### ISSUE TITLE
Auto smelt embossment on hammer smelts double

### ISSUE THREAD

**Issue by mani00132** [SlimeKnights/TinkersConstruct#4566] opened 2021-07-13 07:19 UTC
So I had a hammer (cobalt head, 2 cobalt plates and ardite tough tool rod) and i have put an embossment on it with a firewood plate. but now when I mine ores/any smeltable blocks it gives me the item as if the block was smelted two times in a row. For example; Iron ore gives me refined iron ore from tech reborn, however the recipe for that is to smelt vanilla iron ingot. Any idea how to fix that? MC-Version: 1.12.2, newest available TiC version for 1.12.2

**Comment by Mrthomas20121** [comment] 2021-07-15 15:56
i tested using my tinkers addon minecraft instance(running more than just tinkers+tech reborn) and i was unable to reproduce it using the same materials. one of your installed mod must be messing with tinkers.

**Comment by KnightMiner** [comment] 2021-08-25 04:25
Closing as we cannot reproduce and the author provided no more information.

**Closed as completed by KnightMiner** 2021-08-25 04:25 UTC
Labels: Can't reproduce, 1.12
