### ISSUE TITLE
[1.12] Stencils don't display

### ISSUE THREAD

**Issue by cyberdjinn** [SlimeKnights/TinkersConstruct#3046] opened 2017-07-26 10:55 UTC
Minimal modpack, testing for 1.12 functionality and trying to craft in Tinkers is complicated by invisible stencils. No resource pack being used.

![stencil1](https://user-images.githubusercontent.com/30061080/28617659-954448c0-7244-11e7-8c85-d773903dc90e.jpg)
![stencil2](https://user-images.githubusercontent.com/30061080/28617660-9544ffa4-7244-11e7-9847-02479ab85df8.jpg)

**Comment by cyberdjinn** [comment] 2017-07-26 11:14
This is my mod list:
![mods](https://user-images.githubusercontent.com/30061080/28618336-6a05f64c-7247-11e7-995d-f7ba92c31333.jpg)

**Comment by KnightMiner** [comment] 2017-07-26 13:23
Congradulations, you are the seventh duplicate of #3008. Update Optifine

**Closed by KnightMiner** 2017-07-26 13:23 UTC
