### ISSUE TITLE
Hovering over Ichor Bottle crashes when Botania is installed

### ISSUE THREAD

**Issue by TheUnnamed44** [SlimeKnights/TinkersConstruct#5209] opened 2024-04-06 18:13 UTC
### Minecraft Version

1.19.2

### Forge Version

43.3.9

### Mantle Version

1.10.23

### Tinkers' Construct Version

3.8.0.14

### Describe your issue

When Botania and JEI are installed, searching for the Ichor Bottle and hovering over it crashes the game.

### Crash Report

https://pastebin.com/qewrcYXt

### Other mods

Botania-1.19.2-440-FORGE.jar
curios-forge-1.19.2-5.1.6.1.jar
jei-1.19.2-forge-11.6.0.1019.jar
Mantle-1.19.2-1.10.23.jar
Patchouli-1.19.2-77.jar
TConstruct-1.19.2-3.8.0.14.jar

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by Insane96** [comment] 2024-04-06 18:55
Duplicate of #5202

**Closed as completed** 2024-04-06 19:21 UTC
Labels: Bug, Duplicate, 1.19
