### ISSUE TITLE
Tool Station Crash

### ISSUE THREAD

**Issue by jackrtades** [SlimeKnights/TinkersConstruct#3510] opened 2018-05-27 19:51 UTC
Every time I put my pickaxe in the station it crashes.
https://openeye.openmods.info/crashes/e715edc93ed4367853455673225f475a

**Comment by KnightMiner** [comment] 2018-05-27 20:06
Duplicate of #3372, TAIGA's fault.

**Closed by KnightMiner** 2018-05-27 20:06 UTC
