### ISSUE TITLE
Compatibility Issue TiC grout recipe is not using  Forge ore dictionary.

### ISSUE THREAD

**Issue by Venedrex** [SlimeKnights/TinkersConstruct#3854] opened 2019-05-13 02:10 UTC
Grout does not accept mod gravels for use in recipe, most notably making construction of smeltery with Underground Biomes gravel impossible. 

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

Can be replicated with just TiC but is only an issue with other mods, specifically when normal gravel is no longer generated in a world, making smeltery construction impossible in survival.

**Comment by KnightMiner** [comment] 2019-08-07 17:15
Duplicate of #3884 which was fixed

**Closed by KnightMiner** 2019-08-07 17:15 UTC
Labels: 3rd party mod interaction, bug
