### ISSUE TITLE
Game crash when i will upgrade a tool

### ISSUE THREAD

**Issue by Blackout707** [SlimeKnights/TinkersConstruct#3398] opened 2018-02-25 15:38 UTC
When i put a iron pick or every other toll in the table to modify it, my game crashes (i have tinker mods installed) but it crashes every time. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  FMLPlugin (elulib-0.1.11.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 2/25/18 4:17 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at slimeknights.tconstruct.library.utils.ToolBuilder.tryModifyTool(ToolBuilder.java:183)
	at slimeknights.tconstruct.tools.common.inventory.ContainerToolStation.modifyTool(ContainerToolStation.java:275)
	at slimeknights.tconstruct.tools.common.inventory.ContainerToolStation.func_75130_a(ContainerToolStation.java:166)
	at slimeknights.tconstruct.tools.common.inventory.SlotToolStationIn.func_75218_e(SlotToolStationIn.java:32)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:71)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at slimeknights.mantle.inventory.ContainerMultiModule.func_184996_a(ContainerMultiModule.java:121)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_146286_b(GuiMultiModule.java:286)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at slimeknights.tconstruct.library.utils.ToolBuilder.tryModifyTool(ToolBuilder.java:183)
	at slimeknights.tconstruct.tools.common.inventory.ContainerToolStation.modifyTool(ContainerToolStation.java:275)
	at slimeknights.tconstruct.tools.common.inventory.ContainerToolStation.func_75130_a(ContainerToolStation.java:166)
	at slimeknights.tconstruct.tools.common.inventory.SlotToolStationIn.func_75218_e(SlotToolStationIn.java:32)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:71)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at slimeknights.mantle.inventory.ContainerMultiModule.func_184996_a(ContainerMultiModule.java:121)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_146286_b(GuiMultiModule.java:286)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: slimeknights.tconstruct.tools.common.client.GuiToolForge

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Blackout7707'/9134, l='MpServer', x=-148.50, y=71.00, z=332.50]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-152,64,333), Chunk: (at 8,4,13 in -10,20; contains blocks -160,0,320 to -145,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1851 game time, 1851 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 86 total; [EntityPlayerSP['Blackout7707'/9134, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9969, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unbekannt'/9971, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9972, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9973, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9974, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9975, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9976, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9977, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9978, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9979, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9980, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9981, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9982, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9983, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/10035, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityItem['item.tile.mushroom.glowshroom'/6179, l='MpServer', x=-176.84, y=15.00, z=273.33], EntityItem['item.tile.mushroom3'/6180, l='MpServer', x=-176.13, y=15.00, z=272.35], EntityItem['item.tile.mushroom.glowshroom'/6181, l='MpServer', x=-183.88, y=13.00, z=274.88], MoCEntityTiger['Tiger'/6210, l='MpServer', x=-159.99, y=84.00, z=264.01], MoCEntityTiger['Tiger'/6211, l='MpServer', x=-160.99, y=84.00, z=260.02], EntityItem['item.tile.mushroom.glowshroom'/6215, l='MpServer', x=-152.55, y=21.00, z=269.88], MoCEntityMole['Mole'/6216, l='MpServer', x=-156.16, y=69.00, z=316.97], MoCEntityRaccoon['Raccoon'/6221, l='MpServer', x=-146.49, y=67.00, z=366.36], MoCEntityRaccoon['Raccoon'/6222, l='MpServer', x=-142.50, y=72.00, z=358.06], EntitySheep['Schaf'/6225, l='MpServer', x=-140.80, y=77.00, z=350.44], EntitySheep['Schaf'/6229, l='MpServer', x=-144.77, y=76.00, z=350.48], EntitySheep['Schaf'/6230, l='MpServer', x=-150.15, y=75.00, z=340.45], EntitySheep['Schaf'/6231, l='MpServer', x=-145.53, y=76.00, z=338.26], EntityItem['item.tile.stone_formations.stone_formation'/6240, l='MpServer', x=-136.17, y=5.00, z=272.37], MoCEntityBoar['Boar'/6241, l='MpServer', x=-128.50, y=73.00, z=303.50], MoCEntityBoar['Boar'/6242, l='MpServer', x=-129.50, y=73.00, z=305.50], MoCEntityGoat['Goat'/6243, l='MpServer', x=-138.25, y=72.00, z=311.50], MoCEntityPanther['Panther'/6245, l='MpServer', x=-130.00, y=74.00, z=302.11], MoCEntityPanther['Panther'/6246, l='MpServer', x=-131.92, y=73.00, z=309.92], MoCEntityEnt['Ent'/6265, l='MpServer', x=-110.50, y=69.00, z=338.50], MoCEntityEnt['Ent'/6266, l='MpServer', x=-110.50, y=69.00, z=338.50], MoCEntityPanther['Panther'/6304, l='MpServer', x=-79.93, y=69.00, z=277.97], MoCEntityPanther['Panther'/6305, l='MpServer', x=-77.18, y=69.00, z=278.57], MoCEntityDuck['Duck'/6306, l='MpServer', x=-83.50, y=71.00, z=285.50], MoCEntityDuck['Duck'/6307, l='MpServer', x=-77.50, y=73.00, z=297.50], MoCEntityDuck['Duck'/6308, l='MpServer', x=-81.50, y=74.00, z=297.50], MoCEntityEnt['Ent'/6309, l='MpServer', x=-74.50, y=71.00, z=325.50], MoCEntityBoar['Boar'/6327, l='MpServer', x=-70.50, y=71.00, z=327.50], MoCEntityGoat['Goat'/6329, l='MpServer', x=-70.50, y=71.00, z=327.50], MoCEntityGoat['Goat'/6330, l='MpServer', x=-71.50, y=71.00, z=326.50], MoCEntityGoat['Goat'/6331, l='MpServer', x=-69.50, y=71.00, z=326.50], EntityMaug['Maug'/14753, l='MpServer', x=-112.04, y=42.00, z=377.18], EntityLatchedRenderer['unbekannt'/10746, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/10747, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityFrostweaver['Frostweaver'/14952, l='MpServer', x=-188.53, y=5.00, z=319.47], EntityItem['item.tile.dungeontactics:flower_bramble'/14972, l='MpServer', x=-111.62, y=42.00, z=374.92], EntitySkeleton['Skelett'/14979, l='MpServer', x=-104.50, y=23.00, z=319.50], EntityItem['item.tile.gravel'/15030, l='MpServer', x=-177.87, y=19.00, z=372.83], EntityItem['item.tile.gravel'/15230, l='MpServer', x=-165.56, y=53.00, z=361.88], EntityItem['item.tile.stone_formations.stone_formation'/15644, l='MpServer', x=-169.13, y=53.00, z=325.03], MoCEntityFirefly['Firefly'/15653, l='MpServer', x=-164.50, y=85.00, z=273.50], EntityItem['item.tile.stone_formations.stone_formation'/15683, l='MpServer', x=-126.66, y=12.00, z=344.27], EntityItem['item.item.seeds'/15746, l='MpServer', x=-101.93, y=67.00, z=373.13], EntityItem['item.item.natura.overworld_seeds.barley_seeds'/15759, l='MpServer', x=-100.37, y=67.00, z=377.02], EntityItem['item.tile.mushroom9'/15762, l='MpServer', x=-146.88, y=11.00, z=283.13], EntityItem['item.tile.mushroom.glowshroom'/15765, l='MpServer', x=-168.65, y=20.00, z=302.37], MoCEntityFirefly['Firefly'/15777, l='MpServer', x=-135.50, y=80.00, z=269.50], MoCEntityFirefly['Firefly'/15778, l='MpServer', x=-135.50, y=80.00, z=270.50], MoCEntityFirefly['Firefly'/15779, l='MpServer', x=-136.50, y=80.00, z=265.50], MoCEntityBee['Bee'/15832, l='MpServer', x=-147.54, y=74.00, z=306.49], EntityCreeper['Creeper'/15995, l='MpServer', x=-162.50, y=33.00, z=258.50], EntityMaug['Maug'/16034, l='MpServer', x=-86.50, y=19.00, z=420.50], EntityWarg['Warg'/16036, l='MpServer', x=-46.50, y=48.00, z=375.50], EntityCreeper['Creeper'/16057, l='MpServer', x=-84.50, y=26.00, z=252.50], EntityLatchedRenderer['unbekannt'/16066, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityFrostweaver['Frostweaver'/16085, l='MpServer', x=-80.57, y=38.00, z=407.47], EntityGrue['Grue'/16102, l='MpServer', x=-173.50, y=54.00, z=359.50], EntityChupacabra['Chupacabra'/16103, l='MpServer', x=-109.50, y=39.00, z=365.50], EntityDarkling['Darkling'/16104, l='MpServer', x=-181.77, y=64.53, z=351.23], EntityGrue['Grue'/16105, l='MpServer', x=-119.50, y=50.00, z=374.50], EntityGrue['Grue'/16106, l='MpServer', x=-177.49, y=64.64, z=347.85], EntityShade['Shade'/16107, l='MpServer', x=-105.52, y=39.00, z=362.48], EntityChupacabra['Chupacabra'/16109, l='MpServer', x=-104.51, y=48.00, z=349.49], EntityChupacabra['Chupacabra'/16110, l='MpServer', x=-117.52, y=49.00, z=308.48], EntityArix['Arix'/16128, l='MpServer', x=-127.50, y=59.00, z=317.50], EntityArix['Arix'/16129, l='MpServer', x=-127.50, y=59.00, z=318.50], EntityArix['Arix'/16130, l='MpServer', x=-126.50, y=58.00, z=319.50], EntityArix['Arix'/16132, l='MpServer', x=-124.50, y=59.00, z=319.50], EntityArix['Arix'/16133, l='MpServer', x=-127.50, y=59.00, z=324.50], EntityWendigo['Wendigo'/16149, l='MpServer', x=-123.50, y=57.00, z=317.50]]
	Retry entities: 17 total; [EntityLatchedRenderer['unbekannt'/9969, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unbekannt'/9971, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/10035, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9972, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9973, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9974, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9975, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9976, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9977, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9978, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/10746, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9979, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/10747, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9980, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9981, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9982, l='MpServer', x=-148.50, y=71.00, z=332.50], EntityLatchedRenderer['unbekannt'/9983, l='MpServer', x=-148.50, y=71.00, z=332.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1580828432 bytes (1507 MB) / 3043479552 bytes (2902 MB) up to 6335102976 bytes (6041 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.2.2619 Optifine OptiFine_1.12.2_HD_U_C9 70 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version              | Source                                        | Signature                                |
	|:--------- |:------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2               | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                 | 9.42                 | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99            | forge-1.12.2-14.23.2.2619.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.2.2619         | forge-1.12.2-14.23.2.2619.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | elucore             | 1.0                  | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | appliedenergistics2 | rv5-stable-8         | appliedenergistics2-rv5-stable-8.jar          | None                                     |
	| UCHIJAAAA | battletowers        | 1.6.1                | BattleTowers-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | baubles             | 1.5.2                | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAAAA | bibliocraft         | 2.4.3                | BiblioCraft-Mod-1.12.jar                      | None                                     |
	| UCHIJAAAA | biomesoplenty       | 7.0.1.2297           | BiomesOPlenty-1.12.2-7.0.1.2297-universal.jar | None                                     |
	| UCHIJAAAA | blockcraftery       | 0.1.3                | Blockcraftery-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | guideapi            | 1.12-2.1.4-57        | Guide-API-1.12-2.1.4-57.jar                   | None                                     |
	| UCHIJAAAA | bloodmagic          | 1.12.2-2.2.5-88      | BloodMagic-1.12.2-2.2.5-88.jar                | None                                     |
	| UCHIJAAAA | bookshelf           | 2.3.524              | Bookshelf-1.12.2-2.3.524.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | botania             | r1.10-353            | Botania-Mod-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | codechickenlib      | 3.1.5.331            | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux        | 2.0.1                | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | brandonscore        | 2.4.0                | BrandonsCore-1.12-2.4.0.152-universal.jar     | None                                     |
	| UCHIJAAAA | chameleon           | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCHIJAAAA | ctm                 | MC1.12-0.2.3.12      | CTM-MC1.12-0.2.3.12.jar                       | None                                     |
	| UCHIJAAAA | chisel              | MC1.12-0.1.1.27      | Chisel-MC1.12-0.1.1.27.jar                    | None                                     |
	| UCHIJAAAA | cofhcore            | 4.3.10               | CoFHCore-1.12.2-4.3.10.5-universal.jar        | None                                     |
	| UCHIJAAAA | cofhworld           | 1.1.1                | CoFHWorld-1.12.2-1.1.1.12-universal.jar       | None                                     |
	| UCHIJAAAA | customspawner       | 3.11.3               | Custom-Mob-Spawner-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAA | waila               | 1.8.23               | Hwyla-1.8.23-B38_1.12.jar                     | None                                     |
	| UCHIJAAAA | jei                 | 4.8.0.111            | jei_1.12.2-4.8.0.111.jar                      | None                                     |
	| UCHIJAAAA | darkutils           | 1.8.192              | DarkUtils-1.12.2-1.8.192.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | dungeontactics      | DT-0.14.2            | DungeonTactics-1.12.2-0.14.2.jar              | None                                     |
	| UCHIJAAAA | mantle              | 1.12-1.3.1.21        | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCHIJAAAA | tconstruct          | 1.12.2-2.9.1.65      | TConstruct-1.12.2-2.9.1.65.jar                | None                                     |
	| UCHIJAAAA | extrautils2         | 1.0                  | extrautils2-1.12-1.7.4.jar                    | None                                     |
	| UCHIJAAAA | foamfix             | 0.8.1-1.12           | FoamFixUnofficial-1.12-0.8.1-Lawful.jar       | None                                     |
	| UCHIJAAAA | gravestone          | 1.10.1               | gravestone-1.10.1.jar                         | None                                     |
	| UCHIJAAAA | ichunutil           | 7.1.4                | iChun-Util-Mod-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | ironchest           | 1.12.2-7.0.34.820    | ironchest-1.12.2-7.0.34.820.jar               | None                                     |
	| UCHIJAAAA | journeymap          | 1.12.2-5.5.2         | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAA | lycanitesmobs       | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | arcticmobs          | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | demonmobs           | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | desertmobs          | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | elementalmobs       | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | forestmobs          | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | freshwatermobs      | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | infernomobs         | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | junglemobs          | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | mountainmobs        | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | plainsmobs          | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | saltwatermobs       | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | shadowmobs          | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | swampmobs           | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar   | None                                     |
	| UCHIJAAAA | mjrlegendslib       | 1.12.2-1.0.9         | MJRLegendsLib-1.12.2-1.0.9.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | orespawn            | 3.2.0                | MMD-OreSpawn-Library-1.12.1.jar               | None                                     |
	| UCHIJAAAA | mocreatures         | 12.0.3               | Mo-Creatures-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | moartinkers         | 0.5.4                | moartinkers-0.5.4.jar                         | None                                     |
	| UCHIJAAAA | mores               | 1.3.6                | mores-1.3.6.jar                               | None                                     |
	| UCHIJAAAA | morph               | 7.1.2                | Morph-1.12.2.jar                              | None                                     |
	| UCHIJAAAA | natura              | 1.12.2-4.3.2.42      | natura-1.12.2-4.3.2.42.jar                    | None                                     |
	| UCHIJAAAA | twilightforest      | 3.0.0                | Twilight-Forest-Mod-1.12.2.jar                | None                                     |
	| UCHIJAAAA | plustic             | 6.3.6.2              | plustic-6.3.6.2.jar                           | None                                     |
	| UCHIJAAAA | roguelike           | 1.7.2                | Roguelike-Dungeons-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAA | simplecore          | 1.6.0.6              | simplecore-1.12.2-1.6.0.6.jar                 | None                                     |
	| UCHIJAAAA | storagedrawers      | 1.12-5.2.5           | StorageDrawers-1.12.2-5.3.4.jar               | None                                     |
	| UCHIJAAAA | subcommonlib        | 1.2.0.1              | SubLib-1.12.2.jar                             | None                                     |
	| UCHIJAAAA | taiga               | 1.3.0                | taiga-1.12.2-1.3.0.jar                        | None                                     |
	| UCHIJAAAA | techores            | 1.1                  | Tech+Ores+1.1+[1.12.2].jar                    | None                                     |
	| UCHIJAAAA | telepads            | 1.11.2-1.0.2.1       | TelePads-Mod-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | torohealthmod       | 1.12.2-11            | torohealth-1.12.2-11.jar                      | None                                     |
	| UCHIJAAAA | toroquest           | 1.12.2-5.2           | toroquest-1.12.2-5.2.jar                      | None                                     |
	| UCHIJAAAA | wawla               | 2.5.251              | Wawla-1.12.2-2.5.251.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | elulib              | 0.1.11               | elulib-0.1.11.jar                             | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FMLPlugin (elulib-0.1.11.jar)
  elucent.elulib.asm.ASMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4425' Renderer: 'Intel(R) HD Graphics 2500'
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2619
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 2500 GL version 4.0.0 - Build 10.18.10.4425, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 8
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4425
	OpenGlRenderer: Intel(R) HD Graphics 2500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by KnightMiner** [comment] 2018-02-25 15:49
Duplicate of #3372

**Closed by KnightMiner** 2018-02-25 15:49 UTC
