### ISSUE TITLE
JEI integration issues

### ISSUE THREAD

**Issue by SuperFluffyFoxxo** [SlimeKnights/TinkersConstruct#5075] opened 2023-01-30 08:05 UTC
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.2.92

### Describe your issue

At some point in play sessions, JEI's ability to show smeltery recipes and modification recipes seems to break and it doesn't get restored until Minecraft is restarted

### Other mods

JEI

### Tried reproducing with just Tinkers?

Tinkers + JEI

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by KnightMiner** [comment] 2023-01-30 08:31
I need a little more information than "at some point in play sessions", I have never experienced this myself. Please give me the full game log from a time you managed to reproduce the issue, ideally with as few mods as possible.

In addition, provide information about your environment, including whether you are on a server and the list of mods you reproduced the issue with (as I said, I have never experienced this and I tend to run about 50 mods, so I find it highly unlikely you reproduced this with only 2)

**Comment by LordSeabass** [comment] 2023-02-05 03:21
I have this same issue in servers

**Comment by KnightMiner** [comment] 2023-02-05 03:53
Again, I need actual info. I can do nothing unless you actually explain the problem

**Comment by FoxMcloud5655** [comment] 2023-02-06 22:33
Can confirm that this happens in my modpack, The Crafty Kettle 0.9.6.  I've extracted what I think is the relevant info from the `latest.log` file on my modpack:
```
[06Feb2023 11:44:15.837] [Render thread/ERROR] [mezz.jei.common.load.PluginCaller/]: Caught an error from mod plugin: class slimeknights.tconstruct.plugin.jei.JEIPlugin tconstruct:jei_plugin
java.lang.IllegalArgumentException: ingredients must not be empty.
	at mezz.jei.common.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:111) ~[jei-1.18.2-forge-10.2.1.1002.jar%23196!/:10.2.1.1002]
	at mezz.jei.common.ingredients.IngredientManager.removeIngredientsAtRuntime(IngredientManager.java:151) ~[jei-1.18.2-forge-10.2.1.1002.jar%23196!/:10.2.1.1002]
	at slimeknights.tconstruct.plugin.jei.JEIPlugin.onRuntimeAvailable(JEIPlugin.java:404) ~[TConstruct-1.18.2-3.6.2.92.jar%23313!/:1.18.2-3.6.2.92]
	at mezz.jei.common.startup.JeiStarter.lambda$start$0(JeiStarter.java:141) ~[jei-1.18.2-forge-10.2.1.1002.jar%23196!/:10.2.1.1002]
	at mezz.jei.common.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.18.2-forge-10.2.1.1002.jar%23196!/:10.2.1.1002]
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:141) ~[jei-1.18.2-forge-10.2.1.1002.jar%23196!/:10.2.1.1002]
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.18.2-forge-10.2.1.1002.jar%23196!/:10.2.1.1002]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.18.2-forge-10.2.1.1002.jar%23196!/:10.2.1.1002]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.18.2-forge-10.2.1.1002.jar%23196!/:10.2.1.1002]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1270) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

**Comment by FoxMcloud5655** [comment] 2023-02-06 22:35
There's also this warning here, but I am fairly certain it's a separate issue:
```
Unknown custom packet identifier: tconstruct:network
```

**Comment by KnightMiner** [comment] 2023-02-07 01:12
You log is a duplicate of #5074. Going to close this unless someone provides me a log showing a different issue.

**Closed as completed by KnightMiner** 2023-02-07 01:12 UTC
Labels: Bug, Duplicate, Needs Update, Not enough information, 1.18
