### ISSUE TITLE
[1.12.2] Mob spawn in seared multiblocks

### ISSUE THREAD

**Issue by TheSnowyChickens** [SlimeKnights/TinkersConstruct#3639] opened 2018-09-07 19:06 UTC
I searched for equal issues, but I couldn't find any.

**Issue description:**
Mobs can spawn inside Seared Tanks. (and in 1.10.2 (skyfactory3) they can spawn inside the smeltery)
![2018-09-07_21 02 36](https://user-images.githubusercontent.com/29357962/45238331-c65a6a00-b2e1-11e8-8e69-0433d97dddf0.png)
Its dark, but you can find a Creeper inside this tank. (its oil from Immersive)

**Versions:**
SevTech Ages 3.0.8
----------------- Edit, sry. :(
Forge: 2707
TC: 2.10.1.84
Mantle: 1.3.2.24
MC: 1.12.2

**Comment by SweetSugarSugar** [comment] 2018-09-08 05:53
1) 1.10.2 is no longer supported so that issue is irrelevant.
2) Since the release of SevTech Ages 3.0.8, Tinkers' Construct has had an update.  Also, please don't give pack version alone and erase all the other questions.  You haven't provided the Forge version, Tinkers' version, Forge version, Mantle version, etc. and haven't given much information to work with.
3) I'm pretty sure there was an issue fix for this already.

**Comment by TheSnowyChickens** [comment] 2018-09-08 13:05
Sry. :(
I added it.

**Comment by bonii-xx** [comment] 2018-09-17 18:14
more or less duplicate of #2638 
For smelteries and tanks you can provide light too.

**Closed by bonii-xx** 2018-09-17 18:14 UTC
