### ISSUE TITLE
Wearing cobalt armor crashes my game.

### ISSUE THREAD

**Issue by TheTraveller-g** [SlimeKnights/TinkersConstruct#4777] opened 2022-02-22 14:39 UTC
### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

here is the report
[crash-2022-02-22_17.25.01-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/8117485/crash-2022-02-22_17.25.01-client.txt)

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [x] Check if you are using performance enhancers, such as optifine
- [ ] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [ ] Check if you read FAQ to see if your issue is answered

**Comment by ShinyPorygon** [comment] 2022-02-22 14:40
Duplicate of #4734 Actually try reading the pinned issues next time since you said you don't. Remove optifine.

**Closed as completed by ShinyPorygon** 2022-02-22 14:40 UTC
Labels: Duplicate, Performance Enhancers/Optifine, Can't Fix, 1.18
