### ISSUE TITLE
[1.11.2] Crash when repairing tools

### ISSUE THREAD

**Issue by EmosewaGamer** [SlimeKnights/TinkersConstruct#2907] opened 2017-05-13 20:37 UTC
Simply when you trying to repair a tool in the Tool Station, a few players of my pack have gotten this crash: https://media-elerium.cursecdn.com/attachments/204/235/crash-2017-05-13_11.txt Seems to have something to do with the GUI.

**Comment by KnightMiner** [comment] 2017-05-13 22:38
Duplicate of #2903.

**Closed by KnightMiner** 2017-05-13 22:38 UTC
